import 'package:flutter/services.dart';

import 'package:plot/style/plot_colors.dart';
import 'package:plot/style/plot_icon_sizes.dart';
import 'package:plot/util/platform.dart';
import 'package:plot/util/shortcut.dart';
import 'package:plot/widget/widget.dart';

/// Title row inside the compose surface. Always-editable single-line
/// FTextField with the shared [ComposeFieldRow] chrome and ghost styling.
///
/// Placeholder behavior matches the surrounding select-style rows:
/// - empty + unfocused + unhovered → sparkles + "Auto-title" (the thread
///   title is generated by the server when the user submits without one);
/// - hovered or focused → "Set title" prompt;
/// - any value present → no placeholder.
///
/// The row also picks up the same hover/focus background highlight as the
/// other compose rows so it doesn't look inert next to them.
class TitleComposeField extends StatefulWidget {
  const TitleComposeField({
    super.key,
    required this.title,
    required this.onChanged,
    this.onTabForward,
  });

  /// Current draft title (null when unset).
  final String? title;

  /// Persist a new value. Pass `null` to clear.
  final Future<void> Function(String? next) onChanged;

  /// Called when the user presses Tab (no Shift) inside the field. Page
  /// wires this to focus the note editor so the compose-surface flow
  /// continues into the body. Shift-Tab is left to the default focus
  /// traversal so the user lands on the previous compose field.
  final VoidCallback? onTabForward;

  @override
  State<TitleComposeField> createState() => TitleComposeFieldState();
}

class TitleComposeFieldState extends State<TitleComposeField> {
  late final TextEditingController _controller;
  late final FocusNode _focusNode;
  bool _hovered = false;
  bool _focused = false;
  bool _empty = true;

  @override
  void initState() {
    super.initState();
    _controller = TextEditingController(text: widget.title ?? '');
    _empty = _controller.text.isEmpty;
    _focusNode = FocusNode();
    _controller.addListener(_onControllerChanged);
    _focusNode.addListener(_onFocusChanged);
  }

  void _onControllerChanged() {
    final emptyNow = _controller.text.isEmpty;
    if (emptyNow != _empty) {
      setState(() => _empty = emptyNow);
    }
    _commit(_controller.text);
  }

  void _onFocusChanged() {
    final focusedNow = _focusNode.hasFocus;
    if (focusedNow != _focused) setState(() => _focused = focusedNow);
  }

  @override
  void didUpdateWidget(TitleComposeField oldWidget) {
    super.didUpdateWidget(oldWidget);
    // External title changes (e.g. clear after submit) only update the
    // controller when the field isn't focused, to avoid clobbering an
    // in-progress edit.
    if (!_focusNode.hasFocus && (widget.title ?? '') != _controller.text) {
      _controller.text = widget.title ?? '';
    }
  }

  @override
  void dispose() {
    _focusNode.removeListener(_onFocusChanged);
    _controller.removeListener(_onControllerChanged);
    _focusNode.dispose();
    _controller.dispose();
    super.dispose();
  }

  /// Request focus on the title input. Used by the ⌘⇧H shortcut.
  void focus() => _focusNode.requestFocus();

  Future<void> _commit(String value) async {
    final trimmed = value.trim();
    final next = trimmed.isEmpty ? null : trimmed;
    if (next != widget.title) {
      await widget.onChanged(next);
    }
  }

  @override
  Widget build(BuildContext context) {
    final theme = context.theme;
    final highlighted = _hovered || _focused;
    // Interpolate alpha only — keeping the same RGB on both ends avoids a
    // brief flash of a darker color mid-transition (the Color.lerp from
    // pure black-transparent to editableBackground passes through dim
    // semi-transparent black, which reads as a darker pulse in dark mode).
    final background = highlighted
        ? theme.plotColors.editableBackground
        : theme.plotColors.editableBackground.withValues(alpha: 0);

    return MouseRegion(
      onEnter: (_) => setState(() => _hovered = true),
      onExit: (_) => setState(() => _hovered = false),
      child: AnimatedContainer(
        duration: const Duration(milliseconds: 80),
        decoration: BoxDecoration(
          color: background,
          borderRadius: BorderRadius.circular(6),
        ),
        child: ComposeFieldRow(
          tooltip: 'Title',
          shortcut: platformSingleActivator(
            LogicalKeyboardKey.keyH,
            shift: true,
          ),
          onTapField: focus,
          child: Focus(
            // Intercept Tab/Shift-Tab BEFORE the FTextField sees it.
            // FTextField inside Stack swallows backward traversal unless we
            // forward Shift-Tab explicitly to the previous focus node.
            canRequestFocus: false,
            skipTraversal: true,
            onKeyEvent: _handleTabKey,
            child: Stack(
              alignment: AlignmentDirectional.centerStart,
              children: [
                // Bottom layer: the placeholder. Rendered behind the
                // transparent FTextField so the field's cursor stays
                // visible when focused and the placeholder text remains
                // readable beneath it.
                if (_empty)
                  IgnorePointer(
                    child: Padding(
                      padding: EdgeInsets.symmetric(
                        vertical: isMobilePlatform() ? 10 : 6,
                      ),
                      child: _buildPlaceholder(theme),
                    ),
                  ),
                FTextField(
                  control: .managed(controller: _controller),
                  focusNode: _focusNode,
                  hint: '',
                  textInputAction: TextInputAction.next,
                  onSubmit: _commit,
                  style: ghostFieldStyle(context),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }

  /// The placeholder shown when the title is empty. Sparkles + "Auto-title"
  /// at rest or on hover; "Set title" only when the field is focused. Both
  /// use the veryMuted color so they read as the same level of de-emphasis.
  Widget _buildPlaceholder(FThemeData theme) {
    final color = theme.plotColors.veryMuted;
    final textStyle = theme.typography.md.copyWith(color: color);
    if (_focused) {
      return Text('Set title', style: textStyle);
    }
    return Row(
      mainAxisSize: MainAxisSize.min,
      children: [
        ComposeLeadingIcon(
          child: Icon(
            PlotIcon.sparkles,
            size: theme.iconSizes.leading,
            color: color,
          ),
        ),
        const SizedBox(width: composeIconGap),
        Text('Auto-title', style: textStyle),
      ],
    );
  }

  KeyEventResult _handleTabKey(FocusNode node, KeyEvent event) {
    if (event is! KeyDownEvent) return KeyEventResult.ignored;
    if (event.logicalKey != LogicalKeyboardKey.tab) {
      return KeyEventResult.ignored;
    }
    if (HardwareKeyboard.instance.isShiftPressed) {
      // Walk traversal backward to the previous compose row (contacts).
      // FTextField inside Stack consumes Shift-Tab on its own otherwise.
      node.previousFocus();
      return KeyEventResult.handled;
    }
    final cb = widget.onTabForward;
    if (cb == null) return KeyEventResult.ignored;
    cb();
    return KeyEventResult.handled;
  }
}
