packages:
  - apps/*
  - workers/*
  - libs/*
onlyBuiltDependencies:
  - "@sentry/cli"
  - bufferutil
  - es5-ext
  - esbuild
  - fast-folder-size
  - nx
  - sharp
  - supabase
  - utf-8-validate
  - workerd
