packages:
  - apps/*
  - workers/*
  - libs/*
  - twists/*
  - public/twister
  - public/sources/*
  - public/twists/*

onlyBuiltDependencies:
  - '@posthog/cli'
  - bufferutil
  - es5-ext
  - esbuild
  - fast-folder-size
  - nx
  - sharp
  - utf-8-validate
  - workerd

patchedDependencies:
  pg-cloudflare@1.3.0: patches/pg-cloudflare@1.3.0.patch
