packages:
  - apps/*
  - workers/*
  - libs/*
  - twists/*
  - public/twister
  - public/tools/*
  - public/twists/*

onlyBuiltDependencies:
  - "@posthog/cli"
  - bufferutil
  - es5-ext
  - esbuild
  - fast-folder-size
  - nx
  - sharp
  - utf-8-validate
  - workerd
