name = "plot-event-sync"
main = "src/index.ts"
compatibility_date = "2024-11-18"
upload_source_maps = true

[[queues.consumers]]
  queue = "plot-event-queue"
  max_batch_size = 100
  max_batch_timeout = 3
  max_retries = 3

[placement]
  mode = "smart"

[ai]
  binding = "ai"
