name = "calendar-webhook"
main = "src/index.ts"
compatibility_date = "2024-11-18"
compatibility_flags = ["nodejs_compat"]
upload_source_maps = true

[env.development]
[env.development.define]
  ENV = '"development"'
  RELEASE = '"dev"'
  PACKAGE = '"calendar-webhook"'

[env.production]
[env.production.define]
  ENV = '"production"'
  RELEASE = '"prod"'
  PACKAGE = '"calendar-webhook"'

[env.production.triggers]
  # every 5 minutes
  crons = ["*/5 * * * *"]

[[queues.producers]]
  queue = "sync"
  binding = "SYNC_QUEUE"


[dev]
  port = 8785

[observability.logs]
  enabled = true
