targets:
  $default:
    builders:
      drift_dev:
        options:
          store_date_time_values_as_text: true
          use_sql_column_name_as_json_key: true
          sql:
            dialect: sqlite
            options:
              modules:
                - json1
        generate_for:
          include:
            - "lib/store/**"
