targets:
  $default:
    builders:
      go_router_builder:
        generate_for:
          include:
            - 'lib/router.dart'
      drift_dev:
        options:
          store_date_time_values_as_text: true
          use_sql_column_name_as_json_key: true
        generate_for:
          include:
            - 'lib/store/**'
