// libs/db/scripts/onboarding/gen-onboarding.ts
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { execSync } from "node:child_process";
import { parseModel } from "./parse.ts";
import { compileSnapshot, diffSnapshots, type Snapshot } from "./snapshot.ts";
import { emitGlobalReconcile } from "./emit-global.ts";
import { emitSchedulesRegion, emitTodosRegion, emitWelcomeUserRegion, replaceRegion } from "./emit-functions.ts";

const __dirname = dirname(fileURLToPath(import.meta.url));
const DB_ROOT = resolve(__dirname, "../..");           // libs/db
const ONBOARDING_DIR = join(DB_ROOT, "onboarding");
const SNAPSHOT_PATH = join(ONBOARDING_DIR, ".snapshot.json");
const MIGRATIONS_DIR = join(DB_ROOT, "migrations");
const SCHED_FILE = join(DB_ROOT, "schema/95-triggers/25-onboarding_schedules.sql");
const TODOS_FILE = join(DB_ROOT, "schema/95-triggers/26-onboarding_todos.sql");
const ACTIVATE_FILE = join(DB_ROOT, "schema/60-functions/activate_invited_user.sql");

const isCheck = process.argv.includes("--check");

function loadSnapshot(): Snapshot | null {
  if (!existsSync(SNAPSHOT_PATH)) return null;
  return JSON.parse(readFileSync(SNAPSHOT_PATH, "utf-8")) as Snapshot;
}

/** Timestamp for the migration filename. */
function timestamp(): string {
  const d = new Date();
  const p = (n: number) => String(n).padStart(2, "0");
  return `${d.getFullYear()}${p(d.getMonth() + 1)}${p(d.getDate())}${p(d.getHours())}${p(d.getMinutes())}${p(d.getSeconds())}`;
}

/** Extract a full `CREATE OR REPLACE FUNCTION ... $$;` (or `$function$;`) block from a schema file. */
function extractFunction(fileContents: string): string {
  const start = fileContents.indexOf("CREATE OR REPLACE FUNCTION");
  if (start === -1) throw new Error("no CREATE OR REPLACE FUNCTION found in schema file");
  const tail = fileContents.slice(start);
  const m = /\$(function|)\$;\s*$/m.exec(tail);
  if (!m) throw new Error("could not find function terminator");
  return tail.slice(0, m.index + m[0].length).trimEnd();
}

function migrationSlug(diff: ReturnType<typeof diffSnapshots>): string {
  if (diff.threadsArchived.length) return "archive_threads";
  if (diff.threadsUpserted.length) return "update_threads";
  if (diff.notesUpserted.length || diff.notesArchived.length) return "update_notes";
  if (diff.perUserChanged) return "update_welcome_user";
  return "update_state";
}

function main(): void {
  const model = parseModel(ONBOARDING_DIR);
  const next = compileSnapshot(model);
  const prev = loadSnapshot();
  const diff = diffSnapshots(prev, next);

  if (!diff.hasChanges) {
    console.log("✅ onboarding up to date — no migration needed");
    return;
  }

  if (isCheck) {
    console.error("❌ onboarding markdown changed but no migration generated. Run `pnpm gen-onboarding` and commit.");
    console.error(JSON.stringify(diff, null, 2));
    process.exit(1);
  }

  // 1. Global content reconcile (all users).
  let sql = "-- AUTO-GENERATED by pnpm gen-onboarding from libs/db/onboarding/*. Do not edit by hand.\n\n";
  if (diff.threadsUpserted.length || diff.notesUpserted.length || diff.threadsArchived.length || diff.notesArchived.length) {
    sql += emitGlobalReconcile(model, {
      archivedThreadKeys: diff.threadsArchived,
      archivedNoteKeys: diff.notesArchived,
    });
  }

  // 2 + 3. Regenerated functions (new users only). Rewrite schema files AND
  //        emit CREATE OR REPLACE so the deployed DB updates.
  if (diff.globalStateChanged || diff.threadsArchived.length || diff.threadsUpserted.length) {
    const schedFile = replaceRegion(readFileSync(SCHED_FILE, "utf-8"), "schedules", emitSchedulesRegion(model.global));
    writeFileSync(SCHED_FILE, schedFile);
    const todosFile = replaceRegion(readFileSync(TODOS_FILE, "utf-8"), "todos", emitTodosRegion(model.global));
    writeFileSync(TODOS_FILE, todosFile);
    sql += "\n-- Regenerated per-user-state functions (new signups only).\n";
    sql += extractFunction(schedFile) + "\n";
    sql += extractFunction(todosFile) + "\n";
  }
  if (diff.perUserChanged) {
    const activateFile = replaceRegion(readFileSync(ACTIVATE_FILE, "utf-8"), "welcome-user", emitWelcomeUserRegion(model.perUser[0]));
    writeFileSync(ACTIVATE_FILE, activateFile);
    sql += extractFunction(activateFile) + "\n";
  }

  // Write the migration + update snapshot + rehash.
  const slug = migrationSlug(diff);
  const file = join(MIGRATIONS_DIR, `${timestamp()}_onboarding_${slug}.sql`);
  writeFileSync(file, sql);
  writeFileSync(SNAPSHOT_PATH, JSON.stringify(next, null, 2) + "\n");
  execSync(`atlas migrate hash --dir file://migrations`, { cwd: DB_ROOT, stdio: "inherit" });

  console.log(`✅ wrote ${file}`);
  console.log(`   threads: +${diff.threadsUpserted.length} / archived ${diff.threadsArchived.length}`);
  console.log(`   notes:   +${diff.notesUpserted.length} / archived ${diff.notesArchived.length}`);
  console.log(`   per-user changed: ${diff.perUserChanged}, global-state changed: ${diff.globalStateChanged}`);
}

main();
