-- user.priority_actor is retired.
--
-- Contact/actor visibility is now user-level, driven by user_contact rows.
-- The user.actor view queries user_contact + contact + twist_instance directly.
-- The priority_actor view was a no-op in the per-user priority model (every
-- contact was projected onto every priority with depth=0).
--
-- This file is kept as a placeholder so Atlas doesn't recreate the view.
-- The DROP is handled via migration.
