CREATE TABLE "public"."waitlist" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" timestamp with time zone DEFAULT now(),
    "email" text NOT NULL
);

ALTER TABLE "public"."waitlist" ENABLE ROW LEVEL SECURITY;

CREATE UNIQUE INDEX waitlist_email_key ON public.waitlist USING btree (email);

CREATE UNIQUE INDEX waitlist_pkey ON public.waitlist USING btree (id);

ALTER TABLE "public"."waitlist"
    ADD CONSTRAINT "waitlist_pkey" PRIMARY KEY USING INDEX "waitlist_pkey";

ALTER TABLE "public"."waitlist"
    ADD CONSTRAINT "waitlist_email_key" UNIQUE USING INDEX "waitlist_email_key";

