DROP POLICY "Users can view their own labels" ON "public"."event_label_override";

ALTER TABLE "public"."event_label_override"
    DROP CONSTRAINT "event_label_event_id_fkey";

ALTER TABLE "public"."event_label_override"
    DROP CONSTRAINT "event_label_label_id_fkey";

DROP FUNCTION IF EXISTS "public"."invitee" (event_x2);

DROP VIEW IF EXISTS "public"."event_x2" CASCADE;

DROP VIEW IF EXISTS "public"."expenditure_monthly" CASCADE;

DROP VIEW IF EXISTS "public"."expenditure_rolling";

DROP VIEW IF EXISTS "public"."expenditure";

DROP VIEW IF EXISTS "public"."event_label";

DROP FUNCTION IF EXISTS "public"."event_label_matches" (e event_x);

ALTER TABLE "public"."event_label_override"
    DROP CONSTRAINT "event_label_pkey";

DROP INDEX IF EXISTS "public"."event_label_event_id_series_label_id_key";

DROP INDEX IF EXISTS "public"."event_label_pkey";

DROP TABLE "public"."event_label_override";

CREATE TABLE "public"."event_label" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" timestamp with time zone DEFAULT now(),
    "event_id" bigint,
    "series" text,
    "label_id" bigint NOT NULL,
    "priority" smallint NOT NULL DEFAULT '100' ::smallint,
    "negate" boolean NOT NULL DEFAULT FALSE
);

ALTER TABLE "public"."event_label" ENABLE ROW LEVEL SECURITY;

CREATE INDEX event_label_event_id_idx ON public.event_label USING btree (event_id);

CREATE UNIQUE INDEX event_label_event_id_series_label_id_key ON public.event_label USING btree (event_id, series, label_id) NULLS NOT DISTINCT;

CREATE UNIQUE INDEX event_label_pkey ON public.event_label USING btree (id);

ALTER TABLE "public"."event_label"
    ADD CONSTRAINT "event_label_pkey" PRIMARY KEY USING INDEX "event_label_pkey";

ALTER TABLE "public"."event_label"
    ADD CONSTRAINT "event_label_event_id_fkey" FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE NOT valid;

ALTER TABLE "public"."event_label" validate CONSTRAINT "event_label_event_id_fkey";

ALTER TABLE "public"."event_label"
    ADD CONSTRAINT "event_label_label_id_fkey" FOREIGN KEY (label_id) REFERENCES label (id) ON DELETE CASCADE NOT valid;

ALTER TABLE "public"."event_label" validate CONSTRAINT "event_label_label_id_fkey";

SET check_function_bodies = OFF;

CREATE OR REPLACE FUNCTION public.event_label_ids (e event_x)
    RETURNS bigint[]
    LANGUAGE plpgsql
    STABLE
    AS $function$
DECLARE
    result bigint[] = '{}'::bigint[];
BEGIN
    IF e.type <> 'meeting' THEN
        RETURN result;
    END IF;
    IF e.initiated = TRUE THEN
        result := result || 1;
    END IF;
    result := result || CASE WHEN e.invitee_count = 2 THEN
        2
    WHEN e.invitee_count <= 4 THEN
        3
    WHEN e.invitee_count <= 7 THEN
        4
    WHEN e.invitee_count <= 15 THEN
        5
    WHEN e.invitee_count <= 30 THEN
        6
    ELSE
        7
    END;
    IF e.internal = 'internal'::event_internal THEN
        result := result || 8;
    END IF;
    IF e.internal = 'external'::event_internal THEN
        result := result || 9;
    END IF;
    result := result || CASE WHEN e.minutes <= 20 THEN
        10
    WHEN e.minutes < 40 THEN
        11
    WHEN e.minutes < 50 THEN
        12
    WHEN e.minutes < 75 THEN
        13
    WHEN e.minutes < 101 THEN
        14
    WHEN e.minutes < 131 THEN
        15
    WHEN e.minutes < 161 THEN
        16
    WHEN e.minutes <= 180 THEN
        17
    WHEN e.minutes <= 300 THEN
        18
    WHEN e.minutes <= 420 THEN
        19
    ELSE
        20
    END;
    IF e.series IS NOT NULL THEN
        result := result || 21;
    END IF;
    IF e.created_at IS NOT NULL AND EXTRACT(EPOCH FROM (LOWER(e.at) - e.created_at)) < 18 * 60 * 60 THEN
        result := result || 22;
    END IF;
    IF e.minutes < 30 OR (MOD(e.minutes, 30) >= 10 AND MOD(e.minutes, 30) <= 15) THEN
        result := result || 23;
    END IF;
    IF e.initiated = TRUE THEN
        result := result || 24;
    END IF;
    RETURN result;
END;
$function$;

CREATE OR REPLACE FUNCTION public.update_event_labels ()
    RETURNS TRIGGER
    LANGUAGE plpgsql
    AS $function$
DECLARE
    label_ids bigint[];
BEGIN
    SELECT
        event_label_ids (e) INTO label_ids
    FROM
        event_x e
    WHERE
        id = NEW.id;
    DELETE FROM event_label
    WHERE event_id = NEW.id;
    INSERT INTO event_label (event_id, label_id)
    SELECT
        NEW.id,
        unnest(label_ids);
    RETURN NEW;
END;
$function$;

CREATE OR REPLACE VIEW "public"."event_x" AS
SELECT
    u.id AS user_id,
    min(e.id) AS id,
    e.name,
    CASE WHEN (EXTRACT(epoch FROM (upper(e.at) - lower(e.at))) >= (((60 * 60) * 23))::numeric) THEN
        tstzrange(timezone(u.timezone, timezone('UTC'::text, lower(e.at))), timezone(u.timezone, timezone('UTC'::text, upper(e.at))), '[)'::text)
    ELSE
        e.at
    END AS at,
    min(e.calendar_id) AS calendar_id,
    min(e.provider_id) AS provider_id,
    min(e.series) AS series,
    min(e.created_at) AS created_at,
    min(e.status) AS status,
    min(e.provider_link) AS provider_link,
    min(e.summary) AS summary,
    min(e.description) AS description,
    min(e.visibility) AS visibility,
    min(e.availability) AS availability,
    min(e.conferencing_url) AS conferencing_url,
    min(e.organizer) AS organizer,
    COALESCE(min(i.response) FILTER (WHERE (ct.contact_user_id = u.id)), 'tentative'::event_response) AS response,
    calc_attendance (min(er.attendance), min(i.response) FILTER (WHERE (ct.contact_user_id = u.id)), (count(DISTINCT i.contact_id))::integer, lower(e.at)) AS attendance,
    (round((EXTRACT(epoch FROM (upper(e.at) - lower(e.at))) / (60)::numeric)))::integer AS minutes,
    (count(DISTINCT i.contact_id) FILTER (WHERE (i.response = 'accepted'::event_response)))::integer AS attendee_count,
(count(DISTINCT i.contact_id))::integer AS invitee_count,
COALESCE(bool_or(er.ready), FALSE) AS ready,
COALESCE(bool_or(er.reviewed), FALSE) AS reviewed,
CASE WHEN (EXTRACT(epoch FROM (upper(e.at) - lower(e.at))) >= (((60 * 60) * 23))::numeric) THEN
    (timezone(u.timezone, timezone('UTC'::text, lower(e.at))))::date
ELSE
    ((lower(e.at) AT TIME ZONE u.timezone))::date
END AS day,
COALESCE((u.id = min(ct.contact_user_id) FILTER (WHERE (ct.id = e.organizer))), FALSE) AS initiated,
(EXTRACT(epoch FROM (upper(e.at) - lower(e.at))) >= (((60 * 60) * 23))::numeric) AS all_day,
calc_event_type (e.at, min(e.availability), COALESCE(min(i.response) FILTER (WHERE (ct.contact_user_id = u.id)), 'tentative'::event_response), (count(DISTINCT i.contact_id))::integer) AS type,
calc_internal (min(ct.domain_id) FILTER (WHERE (ct.contact_user_id = u.id)), array_agg(DISTINCT ct.domain_id)) AS internal,
CASE WHEN (count(el.label_id) > 0) THEN
    array_agg(DISTINCT el.label_id) FILTER (WHERE (el.label_id IS NOT NULL))
ELSE
    ARRAY[]::bigint[]
END AS labels
FROM (((((((event e
                            JOIN calendar c ON (e.calendar_id = c.id))
                        JOIN account a ON (c.account_id = a.id))
                    JOIN "user" u ON (a.user_id = u.id))
                LEFT JOIN response er ON (((u.id = er.user_id)
                            AND (e.provider_id = er.provider_id))))
            JOIN invitee i ON (e.id = i.event_id))
        JOIN contact ct ON (i.contact_id = ct.id))
    LEFT JOIN event_label el ON (e.id = el.event_id))
GROUP BY
    u.id,
    e.name,
    e.at;

CREATE OR REPLACE VIEW "public"."expenditure" AS
SELECT
    e.user_id,
    e.day,
    el.label_id,
    e.attendance,
    (count(*))::integer AS event_count,
    (sum(e.minutes))::integer AS minutes,
    (count(*) FILTER (WHERE (e.initiated
            AND (el.label_id <> 24))))::integer AS org_event_count,
(sum(e.minutes * e.invitee_count) FILTER (WHERE (e.initiated
        AND (el.label_id <> 24))))::integer AS org_minutes
FROM (event_x e
    JOIN event_label el ON (e.id = el.event_id))
WHERE (e.status <> 'cancelled'::event_status)
GROUP BY
    e.user_id,
    e.day,
    el.label_id,
    e.attendance;

CREATE OR REPLACE VIEW "public"."expenditure_monthly" AS
SELECT
    e.user_id,
    (date_trunc('month'::text, (e.day)::timestamp with time zone))::date AS month,
    e.label_id,
    e.attendance,
    sum(e.event_count) AS event_count,
    sum(e.minutes) AS minutes,
    sum(e.org_event_count) AS org_event_count,
    sum(e.org_minutes) AS org_minutes
FROM
    expenditure e
GROUP BY
    e.user_id,
    ((date_trunc('month'::text, (e.day)::timestamp with time zone))::date),
    e.label_id,
    e.attendance;

CREATE OR REPLACE VIEW "public"."expenditure_rolling" AS
SELECT
    COALESCE(expenditure.user_id, expenditure_expiries.user_id) AS user_id,
    COALESCE(expenditure.day, expenditure_expiries.day) AS day,
    COALESCE(expenditure.label_id, expenditure_expiries.label_id) AS label_id,
    COALESCE(expenditure.attendance, expenditure_expiries.attendance) AS attendance,
    sum(COALESCE(expenditure.event_count, 0)) OVER w AS event_count,
    sum(COALESCE(expenditure.minutes, 0)) OVER w AS minutes,
    sum(COALESCE(expenditure.org_event_count, 0)) OVER w AS org_event_count,
    sum(COALESCE(expenditure.org_minutes, 0)) OVER w AS org_minutes
FROM (expenditure
    FULL JOIN (
        SELECT
            expenditure_1.user_id, (expenditure_1.day + '28 days'::interval)::date AS day,
            expenditure_1.label_id,
            expenditure_1.attendance
        FROM
            expenditure expenditure_1) expenditure_expiries ON (((expenditure.user_id = expenditure_expiries.user_id)
                    AND (expenditure.day = expenditure_expiries.day)
                    AND (expenditure.label_id = expenditure_expiries.label_id)
                    AND (expenditure.attendance = expenditure_expiries.attendance))))
WINDOW w AS (PARTITION BY COALESCE(expenditure.user_id, expenditure_expiries.user_id),
    COALESCE(expenditure.label_id, expenditure_expiries.label_id),
    COALESCE(expenditure.attendance, expenditure_expiries.attendance)
ORDER BY
    COALESCE(expenditure.day, expenditure_expiries.day)
    RANGE BETWEEN '27 days'::interval PRECEDING AND CURRENT ROW)
ORDER BY
    COALESCE(expenditure.day, expenditure_expiries.day);

CREATE OR REPLACE FUNCTION public.label (expenditure_monthly)
    RETURNS SETOF label ROWS 1
    LANGUAGE sql
    STABLE
    AS $function$
    SELECT
        *
    FROM
        label
    WHERE
        id = $1.label_id
$function$;

CREATE POLICY "Users can view their own labels" ON "public"."event_label" AS permissive
    FOR ALL TO authenticated
        USING ((event_id IN (
            SELECT
                event.id
            FROM
                event)));

CREATE TRIGGER event_update_trigger
    AFTER UPDATE ON public.event
    FOR EACH ROW
    EXECUTE FUNCTION update_event_labels ();

ALTER VIEW gap SET (security_invoker = TRUE);

ALTER VIEW gap_monthly SET (security_invoker = TRUE);

ALTER VIEW gap_daily SET (security_invoker = TRUE);

ALTER VIEW "public"."invitation_admin" SET (security_invoker = FALSE);

ALTER VIEW "public"."event_x" SET (security_invoker = TRUE);

ALTER VIEW "public"."waitlist_admin" SET (security_invoker = FALSE);

ALTER VIEW expenditure SET (security_invoker = TRUE);

ALTER VIEW expenditure_monthly SET (security_invoker = TRUE);

ALTER VIEW expenditure_rolling SET (security_invoker = TRUE);

ALTER VIEW "public"."sync_admin" SET (security_invoker = FALSE);

