CREATE TABLE "public"."response" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" timestamp with time zone DEFAULT now(),
    "user_id" bigint NOT NULL,
    "provider_id" text NOT NULL,
    "response" event_response NOT NULL
);

ALTER TABLE "public"."response" ENABLE ROW LEVEL SECURITY;

CREATE UNIQUE INDEX response_pkey ON public.response USING btree (id);

CREATE UNIQUE INDEX response_user_id_provider_id_key ON public.response USING btree (user_id, provider_id);

ALTER TABLE "public"."response"
    ADD CONSTRAINT "response_pkey" PRIMARY KEY USING INDEX "response_pkey";

ALTER TABLE "public"."response"
    ADD CONSTRAINT "response_user_id_fkey" FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT valid;

ALTER TABLE "public"."response" validate CONSTRAINT "response_user_id_fkey";

ALTER TABLE "public"."response"
    ADD CONSTRAINT "response_user_id_provider_id_key" UNIQUE USING INDEX "response_user_id_provider_id_key";

SET check_function_bodies = OFF;

CREATE OR REPLACE FUNCTION public.org_stats (user_id bigint, during tstzrange)
    RETURNS TABLE (
        label_id bigint,
        name text,
        description text,
        response event_response,
        event_count integer,
        minutes integer)
    LANGUAGE plpgsql
    AS $function$
BEGIN
    RETURN query
    SELECT
        l.id AS label_id,
        l.name AS name,
        l.description AS description,
        e.response,
        count(*)::integer AS event_count,
        sum((e.minutes + 15) * e.invitee_count)::integer AS minutes
    FROM
        event_x e
        JOIN contact c ON c.id = e.organizer
        JOIN event_label le ON le.event_id = e.id
        JOIN label l ON le.label_id = l.id
    WHERE
        e.user_id = org_stats.user_id
        AND e.at && during
        AND c.contact_user_id = e.user_id
        AND e.status != 'cancelled'
        AND l.name != 'initiated'
    GROUP BY
        l.id,
        e.status,
        e.response;
END
$function$;

CREATE OR REPLACE VIEW "public"."event_x" WITH (security_invoker = TRUE) AS
SELECT
    u.id AS user_id,
    min(e.id) AS id,
    e.name,
    CASE WHEN (EXTRACT(epoch FROM (upper(e.at) - lower(e.at))) >= (((60 * 60) * 23))::numeric) THEN
        tstzrange(timezone(u.timezone, timezone('UTC'::text, lower(e.at))), timezone(u.timezone, timezone('UTC'::text, upper(e.at))), '[)'::text)
    ELSE
        e.at
    END AS at,
    min(e.calendar_id) AS calendar_id,
    min(e.provider_id) AS provider_id,
    min(e.series) AS series,
    min(e.created_at) AS created_at,
    min(e.status) AS status,
    min(e.provider_link) AS provider_link,
    min(e.summary) AS summary,
    min(e.description) AS description,
    min(e.visibility) AS visibility,
    min(e.availability) AS availability,
    min(e.conferencing_url) AS conferencing_url,
    min(e.organizer) AS organizer,
    COALESCE(min(er.response), min(i.response) FILTER (WHERE (ct.contact_user_id = u.id))) AS response,
    (round((EXTRACT(epoch FROM (upper(e.at) - lower(e.at))) / (60)::numeric)))::integer AS minutes,
    count(DISTINCT i.contact_id) FILTER (WHERE (i.response = 'accepted'::event_response)) AS attendee_count,
count(DISTINCT i.contact_id) AS invitee_count
FROM ((((((event e
                        JOIN calendar c ON (e.calendar_id = c.id))
                    JOIN account a ON (c.account_id = a.id))
                JOIN "user" u ON (a.user_id = u.id))
            LEFT JOIN response er ON (((u.id = er.user_id)
                        AND (e.provider_id = er.provider_id))))
        JOIN invitee i ON (e.id = i.event_id))
    JOIN contact ct ON (i.contact_id = ct.id))
GROUP BY
    u.id,
    e.name,
    e.at;

CREATE POLICY "Users can view their own responses" ON "public"."response" AS permissive
    FOR SELECT TO authenticated
        USING (is_user_account (auth.uid (), user_id));

