CREATE SCHEMA IF NOT EXISTS "extensions";

CREATE TYPE "public"."provider" AS enum (
    'google',
    'outlook'
);

CREATE TABLE "public"."account" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    "auth_user_id" uuid NOT NULL,
    "user_id" bigint NOT NULL,
    "credentials" jsonb,
    "provider" provider NOT NULL,
    "organization_id" bigint,
    "email" text
);

ALTER TABLE "public"."account" ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."calendar" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    "account_id" bigint NOT NULL,
    "provider_id" text NOT NULL,
    "starts_at" timestamp with time zone,
    "ends_at" timestamp with time zone,
    "next_token" text,
    "more" boolean,
    "watch_id" text,
    "watch_secret" text,
    "watch_expires_at" timestamp with time zone
);

ALTER TABLE "public"."calendar" ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."domain" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" timestamp with time zone DEFAULT now(),
    "domain" text NOT NULL,
    "organization_id" bigint
);

ALTER TABLE "public"."domain" ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."organization" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    "name" text NOT NULL
);

ALTER TABLE "public"."organization" ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."user" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    "email" text NOT NULL,
    "name" text NOT NULL,
    "timezone" text,
    "avatar_url" text
);

ALTER TABLE "public"."user" ENABLE ROW LEVEL SECURITY;

CREATE UNIQUE INDEX account_pkey ON public.account USING btree (id);

CREATE UNIQUE INDEX calendar_pkey ON public.calendar USING btree (id);

CREATE UNIQUE INDEX domain_pkey ON public.domain USING btree (id);

CREATE UNIQUE INDEX organization_pkey ON public.organization USING btree (id);

CREATE UNIQUE INDEX user_pkey ON public."user" USING btree (id);

CREATE UNIQUE INDEX user_email_key ON public."user" USING btree (email);

CREATE UNIQUE INDEX account_auth_user_id_key ON public."account" USING btree (auth_user_id);

ALTER TABLE "public"."account"
    ADD CONSTRAINT "account_pkey" PRIMARY KEY USING INDEX "account_pkey";

ALTER TABLE "public"."calendar"
    ADD CONSTRAINT "calendar_pkey" PRIMARY KEY USING INDEX "calendar_pkey";

ALTER TABLE "public"."domain"
    ADD CONSTRAINT "domain_pkey" PRIMARY KEY USING INDEX "domain_pkey";

ALTER TABLE "public"."organization"
    ADD CONSTRAINT "organization_pkey" PRIMARY KEY USING INDEX "organization_pkey";

ALTER TABLE "public"."user"
    ADD CONSTRAINT "user_pkey" PRIMARY KEY USING INDEX "user_pkey";

ALTER TABLE "public"."account"
    ADD CONSTRAINT "account_auth_user_id_fkey" FOREIGN KEY (auth_user_id) REFERENCES auth.users (id) ON DELETE CASCADE NOT valid;

ALTER TABLE "public"."account" validate CONSTRAINT "account_auth_user_id_fkey";

ALTER TABLE "public"."account"
    ADD CONSTRAINT "account_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES organization (id) ON DELETE SET NULL NOT valid;

ALTER TABLE "public"."account" validate CONSTRAINT "account_organization_id_fkey";

ALTER TABLE "public"."account"
    ADD CONSTRAINT "account_user_id_fkey" FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT valid;

ALTER TABLE "public"."account" validate CONSTRAINT "account_user_id_fkey";

ALTER TABLE "public"."calendar"
    ADD CONSTRAINT "calendar_account_id_fkey" FOREIGN KEY (account_id) REFERENCES account (id) ON DELETE CASCADE NOT valid;

ALTER TABLE "public"."calendar" validate CONSTRAINT "calendar_account_id_fkey";

SET check_function_bodies = OFF;

CREATE OR REPLACE FUNCTION public.get_or_create_organization_id (email text)
    RETURNS bigint
    LANGUAGE plpgsql
    AS $function$
DECLARE
    domain_name text := lower(regexp_replace(split_part(email, '@', 2), '\s+', '', 'g'));
    org_id bigint;
BEGIN
    SELECT
        organization_id INTO org_id
    FROM
        DOMAIN
    WHERE
        DOMAIN = domain_name;
    IF FOUND THEN
        RETURN org_id;
    ELSE
        INSERT INTO organization (name)
            VALUES (domain_name)
        RETURNING
            id INTO org_id;
        INSERT INTO DOMAIN (organization_id, DOMAIN)
            VALUES (org_id, domain_name);
        RETURN org_id;
    END IF;
END;
$function$;

CREATE OR REPLACE FUNCTION public.link_account_to_organization ()
    RETURNS TRIGGER
    LANGUAGE plpgsql
    SECURITY DEFINER
    SET search_path TO 'public'
    AS $function$
BEGIN
    IF NEW.email IS NULL THEN
        RETURN NEW;
    END IF;
    UPDATE
        public.account
    SET
        organization_id = (
            SELECT
                public.get_or_create_organization_id (NEW.email))
    WHERE
        id = NEW.id;
    RETURN NEW;
END;
$function$;

CREATE POLICY "Users can read their accounts" ON "public"."account" AS permissive
    FOR SELECT TO authenticated
        USING ((auth.uid () IN (
            SELECT
                account_1.auth_user_id
            FROM
                account account_1
            WHERE (account_1.user_id = (
                SELECT
                    account_2.user_id
                FROM
                    account account_2
                WHERE (account_2.auth_user_id = auth.uid ()))))));

CREATE POLICY "Users can read themselves" ON "public"."user" AS permissive
    FOR SELECT TO authenticated
        USING ((auth.uid () IN (
            SELECT
                account.auth_user_id
            FROM
                account
            WHERE (account.user_id = "user".id))));

CREATE TRIGGER on_account_created
    AFTER INSERT ON public.account
    FOR EACH ROW
    EXECUTE FUNCTION link_account_to_organization ();

