CREATE EXTENSION IF NOT EXISTS "btree_gist" WITH SCHEMA "extensions";

CREATE EXTENSION IF NOT EXISTS "ltree" WITH SCHEMA "extensions";

CREATE TYPE "public"."goal_type" AS enum (
    'meeting',
    'focus'
);

CREATE TYPE "public"."meeting_size" AS enum (
    '1:1',
    'Small',
    'Medium',
    'Large',
    'XL',
    'XXL'
);

DROP POLICY "Users can view their own labels" ON "public"."event_label";

DROP POLICY "Everyone can view global labels" ON "public"."label";

DROP POLICY "Users can edit their own responses" ON "public"."response";

DROP POLICY "Users can view their own targets" ON "public"."target";

ALTER TABLE "public"."event_label"
    DROP CONSTRAINT "event_label_event_id_fkey";

ALTER TABLE "public"."event_label"
    DROP CONSTRAINT "event_label_label_id_fkey";

ALTER TABLE "public"."label"
    DROP CONSTRAINT "label_user_id_fkey";

ALTER TABLE "public"."label"
    DROP CONSTRAINT "label_user_id_name_unique";

ALTER TABLE "public"."response"
    DROP CONSTRAINT "response_user_id_fkey";

ALTER TABLE "public"."response"
    DROP CONSTRAINT "response_user_id_provider_id_key";

ALTER TABLE "public"."target"
    DROP CONSTRAINT "target_label_id_fkey";

ALTER TABLE "public"."target"
    DROP CONSTRAINT "target_user_id_fkey";

DROP FUNCTION IF EXISTS "public"."event_label_ids" (e event_x);

DROP VIEW IF EXISTS "public"."event_x" CASCADE;

DROP VIEW IF EXISTS "public"."expenditure_monthly";

DROP VIEW IF EXISTS "public"."expenditure_rolling";

DROP VIEW IF EXISTS "public"."gap_daily";

DROP VIEW IF EXISTS "public"."gap_monthly";

DROP VIEW IF EXISTS "public"."prep_monthly";

DROP VIEW IF EXISTS "public"."sync_admin";

DROP VIEW IF EXISTS "public"."waitlist_admin";

DROP VIEW IF EXISTS "public"."expenditure";

DROP VIEW IF EXISTS "public"."gap";

DROP FUNCTION IF EXISTS "public"."label" (expenditure_monthly);

DROP FUNCTION IF EXISTS "public"."update_all_event_labels" ();

DROP FUNCTION IF EXISTS "public"."update_labels" (_event_ids bigint[]);

ALTER TABLE "public"."event_label"
    DROP CONSTRAINT "event_label_pkey";

ALTER TABLE "public"."label"
    DROP CONSTRAINT "label_pkey";

ALTER TABLE "public"."response"
    DROP CONSTRAINT "response_pkey";

ALTER TABLE "public"."target"
    DROP CONSTRAINT "target_pkey";

DROP INDEX IF EXISTS "public"."event_label_event_id_idx";

DROP INDEX IF EXISTS "public"."event_label_event_id_series_label_id_key";

DROP INDEX IF EXISTS "public"."event_label_pkey";

DROP INDEX IF EXISTS "public"."label_pkey";

DROP INDEX IF EXISTS "public"."label_user_id_name_unique";

DROP INDEX IF EXISTS "public"."response_pkey";

DROP INDEX IF EXISTS "public"."response_user_id_provider_id_key";

DROP INDEX IF EXISTS "public"."target_pkey";

DROP TABLE "public"."event_label";

DROP TABLE "public"."label";

DROP TABLE "public"."response";

DROP TABLE "public"."target";

CREATE TABLE "public"."category" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" timestamp with time zone DEFAULT now(),
    "user_id" bigint NOT NULL,
    "path" ltree NOT NULL,
    "name" text NOT NULL
);

ALTER TABLE "public"."category" ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."event_overlay" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" timestamp with time zone DEFAULT now(),
    "user_id" bigint NOT NULL,
    "provider_id" text NOT NULL,
    "ready" timestamp with time zone,
    "reviewed" timestamp with time zone,
    "attendance" event_attendance,
    "category_id" bigint
);

ALTER TABLE "public"."event_overlay" ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."goal" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" timestamp with time zone DEFAULT now(),
    "user_id" bigint NOT NULL,
    "category_id" bigint NOT NULL,
    "at" daterange,
    "type" goal_type NOT NULL,
    "weekly_minutes" integer NOT NULL,
    "minimize" boolean NOT NULL DEFAULT TRUE
);

ALTER TABLE "public"."goal" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."calendar"
    ADD COLUMN "category_id" bigint;

CREATE INDEX category_path_idx ON public.category USING gist (user_id, path);

CREATE UNIQUE INDEX category_pkey ON public.category USING btree (id);

CREATE UNIQUE INDEX event_overlay_pkey ON public.event_overlay USING btree (id);

CREATE UNIQUE INDEX event_overlay_user_id_provider_id_key ON public.event_overlay USING btree (user_id, provider_id);

CREATE UNIQUE INDEX goal_pkey ON public.goal USING btree (id);

CREATE INDEX goal_user_id_idx ON public.goal USING btree (user_id);

ALTER TABLE "public"."category"
    ADD CONSTRAINT "category_pkey" PRIMARY KEY USING INDEX "category_pkey";

ALTER TABLE "public"."event_overlay"
    ADD CONSTRAINT "event_overlay_pkey" PRIMARY KEY USING INDEX "event_overlay_pkey";

ALTER TABLE "public"."goal"
    ADD CONSTRAINT "goal_pkey" PRIMARY KEY USING INDEX "goal_pkey";

ALTER TABLE "public"."calendar"
    ADD CONSTRAINT "calendar_category_id_fkey" FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE SET NULL NOT valid;

ALTER TABLE "public"."calendar" validate CONSTRAINT "calendar_category_id_fkey";

ALTER TABLE "public"."category"
    ADD CONSTRAINT "category_user_id_fkey" FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT valid;

ALTER TABLE "public"."category" validate CONSTRAINT "category_user_id_fkey";

ALTER TABLE "public"."event_overlay"
    ADD CONSTRAINT "event_overlay_category_id_fkey" FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE SET NULL NOT valid;

ALTER TABLE "public"."event_overlay" validate CONSTRAINT "event_overlay_category_id_fkey";

ALTER TABLE "public"."event_overlay"
    ADD CONSTRAINT "event_overlay_user_id_fkey" FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT valid;

ALTER TABLE "public"."event_overlay" validate CONSTRAINT "event_overlay_user_id_fkey";

ALTER TABLE "public"."event_overlay"
    ADD CONSTRAINT "event_overlay_user_id_provider_id_key" UNIQUE USING INDEX "event_overlay_user_id_provider_id_key";

ALTER TABLE "public"."goal"
    ADD CONSTRAINT "goal_category_id_fkey" FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE CASCADE NOT valid;

ALTER TABLE "public"."goal" validate CONSTRAINT "goal_category_id_fkey";

ALTER TABLE "public"."goal"
    ADD CONSTRAINT "goal_user_id_fkey" FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT valid;

ALTER TABLE "public"."goal" validate CONSTRAINT "goal_user_id_fkey";

SET check_function_bodies = OFF;

CREATE OR REPLACE FUNCTION public.calc_all_day (at tstzrange)
    RETURNS boolean
    LANGUAGE plpgsql
    STABLE
    AS $function$
DECLARE
    minutes integer = calc_minutes (at);
BEGIN
    RETURN minutes >= 60 * 23;
END;
$function$;

CREATE OR REPLACE FUNCTION public.calc_meeting_size (invitee_count integer)
    RETURNS text
    LANGUAGE plpgsql
    STABLE
    AS $function$
BEGIN
    RETURN CASE WHEN invitee_count = 2 THEN
        '1:1'
    WHEN invitee_count <= 4 THEN
        'Small'
    WHEN invitee_count <= 7 THEN
        'Medium'
    WHEN invitee_count <= 15 THEN
        'Large'
    WHEN invitee_count <= 30 THEN
        'XL'
    ELSE
        'XXL'
    END;
END;
$function$;

CREATE OR REPLACE FUNCTION public.calc_minutes (at tstzrange)
    RETURNS integer
    LANGUAGE plpgsql
    STABLE
    AS $function$
BEGIN
    RETURN (round((EXTRACT(epoch FROM (upper(at) - lower(at))) / (60)::numeric)))::integer;
END;
$function$;

CREATE OR REPLACE FUNCTION public.calc_notice (created_at timestamp with time zone, at tstzrange)
    RETURNS integer
    LANGUAGE plpgsql
    STABLE
    AS $function$
BEGIN
    RETURN CASE WHEN created_at IS NULL THEN
        NULL
    WHEN created_at > LOWER(at) THEN
        0
    ELSE
        EXTRACT(EPOCH FROM (LOWER(at) - created_at))::integer
    END;
END;
$function$;

CREATE OR REPLACE FUNCTION public.calc_rounded_length (at tstzrange)
    RETURNS integer
    LANGUAGE plpgsql
    STABLE
    AS $function$
DECLARE
    minutes integer = calc_minutes (at);
BEGIN
    RETURN CASE WHEN minutes <= 20 THEN
        15
    WHEN minutes < 40 THEN
        30
    WHEN minutes < 50 THEN
        45
    WHEN minutes < 75 THEN
        60
    WHEN minutes < 101 THEN
        90
    WHEN minutes < 131 THEN
        120
    WHEN minutes < 161 THEN
        150
    WHEN minutes <= 180 THEN
        180
    WHEN minutes <= 300 THEN
        240
    WHEN minutes <= 420 THEN
        360
    ELSE
        480
    END;
END;
$function$;

CREATE OR REPLACE FUNCTION public.calc_speedy (at tstzrange)
    RETURNS boolean
    LANGUAGE plpgsql
    STABLE
    AS $function$
DECLARE
    minutes integer = calc_minutes (at);
BEGIN
    RETURN minutes < 30
        OR (MOD(minutes, 30) >= 10
            AND MOD(minutes, 30) <= 15);
END;
$function$;

CREATE OR REPLACE FUNCTION public.goal_type_equal (gtype goal_type, etype event_type)
    RETURNS boolean
    LANGUAGE plpgsql
    AS $function$
BEGIN
    RETURN CASE WHEN gtype = 'meeting' THEN
        etype = 'meeting'
    WHEN gtype = 'focus' THEN
        etype = 'task'
    ELSE
        FALSE
    END;
END;
$function$;

CREATE OR REPLACE VIEW "public"."goal_weekly" AS
SELECT
    (w.week)::date AS week,
    g.user_id,
    c.id AS category_id,
    text2ltree (min(ltree2text (c.path))) AS category_path,
    g.type,
    sum(g.weekly_minutes) AS weekly_minutes
FROM ((generate_series(((date_trunc('week'::text, (CURRENT_DATE - '1 year'::interval)))::date)::timestamp with time zone, ((CURRENT_DATE + '1 year'::interval)::date)::timestamp with time zone, '7 days'::interval) w (week)
        JOIN goal g ON (((w.week)::date <@ g.at)))
    JOIN category c ON (((g.user_id = c.user_id)
                AND (g.category_id = c.id))))
GROUP BY
    g.user_id,
    w.week,
    c.id,
    g.type;

CREATE OR REPLACE FUNCTION public.insight_category (user_id bigint, category_path ltree, at daterange)
    RETURNS TABLE (
        type event_type,
        attendance event_attendance,
        name text,
        value text,
        count integer,
        minutes integer)
    LANGUAGE plpgsql
    AS $function$
BEGIN
    RETURN QUERY
    SELECT
        insight.type,
        insight.attendance,
        insight.name,
        insight.value,
        SUM(insight.count)::integer AS count,
        SUM(insight.minutes)::integer AS minutes
    FROM
        insight
    WHERE
        insight.user_id = insight_category.user_id
        AND insight_category.category_path @> insight.category_path
        AND insight_category.at @> insight.day
    GROUP BY
        insight.type,
        insight.attendance,
        insight.name,
        insight.value;
END;
$function$;

CREATE OR REPLACE FUNCTION public.calc_event_type (at tstzrange, availability event_availability, response event_response, has_invitees boolean)
    RETURNS event_type
    LANGUAGE plpgsql
    AS $function$
BEGIN
    RETURN CASE WHEN calc_all_day (at) THEN
        'note'::event_type
    WHEN has_invitees
        AND (availability = 'busy'
            OR response = 'declined') THEN
        'meeting'::event_type
    ELSE
        'task'::event_type
    END;
END;
$function$;

CREATE OR REPLACE VIEW "public"."event_x" AS
SELECT
    u.id AS user_id,
    min(e.id) AS id,
    e.name,
    CASE WHEN calc_all_day (e.at) THEN
        tstzrange(timezone(COALESCE(u.timezone, 'America/New_York'::text), timezone('UTC'::text, lower(e.at))), timezone(COALESCE(u.timezone, 'America/New_York'::text), timezone('UTC'::text, upper(e.at))), '[)'::text)
    ELSE
        e.at
    END AS at,
    min(e.calendar_id) AS calendar_id,
    min(e.provider_id) AS provider_id,
    min(e.series) AS series,
    min(e.created_at) AS created_at,
    min(e.status) AS status,
    min(e.provider_link) AS provider_link,
    min(e.summary) AS summary,
    min(e.description) AS description,
    min(e.visibility) AS visibility,
    min(e.availability) AS availability,
    min(e.conferencing_url) AS conferencing_url,
    min(e.organizer_email) AS organizer_email,
    COALESCE(min(i.response) FILTER (WHERE (ct.contact_user_id = u.id)), 'tentative'::event_response) AS response,
    calc_attendance (min(eo.attendance), min(i.response) FILTER (WHERE (ct.contact_user_id = u.id)), (count(DISTINCT i.email))::integer, lower(e.at), ((count(DISTINCT i.email) < 2)
    AND COALESCE((u.id = min(ct.contact_user_id) FILTER (WHERE (ct.email = e.organizer_email))), FALSE)
AND (min(e.series) IS NULL))) AS attendance,
    calc_minutes (e.at) AS minutes,
    (count(DISTINCT i.email) FILTER (WHERE (i.response = 'accepted'::event_response)))::integer AS attendee_count,
(count(DISTINCT i.email))::integer AS invitee_count,
min(eo.ready) AS ready,
CASE WHEN (min(upper(e.at)) < u.activated_at) THEN
    upper(e.at)
ELSE
    min(eo.reviewed)
END AS reviewed,
CASE WHEN (EXTRACT(epoch FROM (upper(e.at) - lower(e.at))) >= (((60 * 60) * 23))::numeric) THEN
    (timezone(COALESCE(u.timezone, 'America/New_York'::text), timezone('UTC'::text, lower(e.at))))::date
ELSE
    ((lower(e.at) AT TIME ZONE COALESCE(u.timezone, 'America/New_York'::text)))::date
END AS day,
COALESCE((u.id = min(ct.contact_user_id) FILTER (WHERE (ct.email = e.organizer_email))), FALSE) AS initiated,
calc_all_day (e.at) AS all_day,
calc_event_type (e.at, min(e.availability), COALESCE(min(i.response) FILTER (WHERE (ct.contact_user_id = u.id)), 'tentative'::event_response), (((count(DISTINCT i.email))::integer > 1)
    OR bool_or(e.invitees_hidden))) AS type,
calc_internal ((count(DISTINCT i.email))::integer, min(ct.domain_id) FILTER (WHERE (ct.contact_user_id = u.id)), array_agg(DISTINCT ct.domain_id)) AS internal,
bool_or(e.invitees_hidden) AS invitees_hidden,
min(cg.id) AS category_id,
text2ltree (min(ltree2text (cg.path))) AS category_path,
(min(e.series) IS NOT NULL) AS recurring,
calc_notice (min(e.created_at), e.at) AS notice,
calc_speedy (e.at) AS speedy,
calc_rounded_length (e.at) AS rounded_length,
calc_meeting_size ((count(DISTINCT i.email))::integer) AS size
FROM (((((((event e
                            JOIN calendar c ON (e.calendar_id = c.id))
                        JOIN account a ON (c.account_id = a.id))
                    JOIN "user" u ON (a.user_id = u.id))
                LEFT JOIN event_overlay eo ON (((u.id = eo.user_id)
                            AND (e.provider_id = eo.provider_id))))
            LEFT JOIN category cg ON (((u.id = cg.user_id)
                        AND (COALESCE(eo.category_id, c.category_id) = cg.id))))
        JOIN invitee i ON (e.id = i.event_id))
    JOIN contact ct ON (((ct.user_id = u.id)
                AND (i.email = ct.email))))
WHERE (c.enabled = TRUE)
GROUP BY
    u.id,
    e.name,
    e.at;

CREATE OR REPLACE VIEW "public"."gap" AS
SELECT
    gap.user_id,
    gap.day,
    (gap.at * tstzrange(((gap.day + work_day_start ()) AT TIME ZONE COALESCE("user".timezone, 'America/New_York'::text)), ((gap.day + work_day_end ()) AT TIME ZONE COALESCE("user".timezone, 'America/New_York'::text)), '[]'::text)) AS at,
    extract_minutes ((gap.at * tstzrange(((gap.day + work_day_start ()) AT TIME ZONE COALESCE("user".timezone, 'America/New_York'::text)), ((gap.day + work_day_end ()) AT TIME ZONE COALESCE("user".timezone, 'America/New_York'::text)), '[]'::text))) AS minutes
FROM ((
        SELECT
            e.user_id,
            e.day,
            CASE WHEN ((EXTRACT(isodow FROM e.day) <= (5)::numeric)
                AND (max(upper(e.at)) OVER start_window < lower(e.at))) THEN
                tstzrange(max(upper(e.at)) OVER start_window, lower(e.at), '[)'::text)
            ELSE
                NULL::tstzrange
            END AS at
        FROM (
            SELECT
                event_x.user_id,
                event_x.day,
                event_x.at
            FROM
                event_x
            WHERE ((event_x.type = 'meeting'::event_type)
                AND (event_x.status <> 'cancelled'::event_status)
                AND (event_x.response = 'accepted'::event_response))
        UNION
        SELECT DISTINCT
            user_1.id,
            days.day,
            tstzrange(((days.day + '1 day'::interval) AT TIME ZONE COALESCE(user_1.timezone, 'America/New_York'::text)), ((days.day + '1 day'::interval) AT TIME ZONE COALESCE(user_1.timezone, 'America/New_York'::text)), '[]'::text) AS at
        FROM ("user" user_1
        CROSS JOIN (
            SELECT
                (generate_series(((min(lower(event.at)))::date)::timestamp with time zone, ((max(upper(event.at)))::date)::timestamp with time zone, '1 day'::interval))::date AS day
            FROM
                event) days)) e
WINDOW start_window AS (PARTITION BY e.user_id ORDER BY (lower(e.at)),
    (upper(e.at))
    ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING)) gap
JOIN "user" ON (gap.user_id = "user".id))
WHERE (gap.at IS NOT NULL);

CREATE OR REPLACE VIEW "public"."gap_daily" AS
SELECT
    gap.user_id,
    gap.day,
    sum(gap.minutes) AS total,
    sum(gap.minutes) FILTER (WHERE (gap.minutes >= 60)) AS focus
FROM
    gap
GROUP BY
    gap.user_id,
    gap.day;

CREATE OR REPLACE VIEW "public"."gap_monthly" AS
SELECT
    gap.user_id,
    (date_trunc('month'::text, (gap.day)::timestamp with time zone))::date AS month,
    sum(gap.minutes) AS total,
    sum(gap.minutes) FILTER (WHERE (gap.minutes >= 60)) AS focus
FROM
    gap
GROUP BY
    gap.user_id,
    ((date_trunc('month'::text, (gap.day)::timestamp with time zone))::date);

CREATE OR REPLACE VIEW "public"."prep_monthly" AS
SELECT
    e.user_id,
    (date_trunc('month'::text, (e.day)::timestamp with time zone))::date AS month,
    count(*) FILTER (WHERE (lower(e.at) < CURRENT_TIMESTAMP)) AS past_count,
count(*) FILTER (WHERE ((lower(e.at) < CURRENT_TIMESTAMP)
AND (e.ready < lower(e.at)))) AS past_ready_count,
count(*) FILTER (WHERE ((upper(e.at) < CURRENT_TIMESTAMP)
AND (e.reviewed < (upper(e.at) + '2 days'::interval)))) AS past_reviewed_count,
round((avg(EXTRACT(epoch FROM (COALESCE(e.reviewed, CURRENT_TIMESTAMP) - upper(e.at)))) FILTER (WHERE (upper(e.at) < CURRENT_TIMESTAMP)) / (60)::numeric)) AS review_time
FROM
    event_x e
WHERE (e.type = 'meeting'::event_type)
GROUP BY
    e.user_id,
    ((date_trunc('month'::text, (e.day)::timestamp with time zone))::date);

CREATE OR REPLACE VIEW "public"."sync_admin" AS
SELECT
    min(a.email) AS email,
    min(a.id) AS account_id,
    min(a.provider) AS provider,
    c.provider_id AS calendar_provider_id,
    c.created_at AS first_synced_at,
    c.full_sync_at,
    c.synced_at,
    c.sync_error AS error,
    CASE WHEN ((c.full_sync_at IS NULL)
        OR (c.sync_error IS NOT NULL)) THEN
        NULL::numeric
    ELSE
        round(EXTRACT(epoch FROM (COALESCE(c.full_sync_at, now()) - c.full_sync_started_at)))
    END AS sync_seconds,
    count(e.id) AS event_count
FROM ((account a
    LEFT JOIN calendar c ON (c.account_id = a.id))
    LEFT JOIN event e ON (e.calendar_id = c.id))
GROUP BY
    c.id;

CREATE OR REPLACE VIEW "public"."waitlist_admin" AS
SELECT
    min(u.id) AS id,
    min(u.created_at) AS created_at,
    min(u.email) AS email,
    CASE WHEN (min(c.sync_error) IS NOT NULL) THEN
        'sync_error'::text
    WHEN (min(u.activated_at) IS NOT NULL) THEN
        'active'::text
    WHEN (count(*) FILTER (WHERE ((a.credentials -> 'refresh_token'::text) IS NOT NULL)) > 0) THEN
        'synced'::text
    ELSE
        'waitlisted'::text
    END AS status,
    array_agg(DISTINCT a.email) FILTER (WHERE (a.email IS NOT NULL)) AS sync_accounts,
array_agg(c.sync_error) FILTER (WHERE (c.sync_error IS NOT NULL)) AS sync_error,
array_agg(DISTINCT a.provider) FILTER (WHERE (a.provider IS NOT NULL)) AS provider,
u.invitation,
count(e.id) AS event_count
FROM ((("user" u
        LEFT JOIN account a ON (((u.id = a.user_id)
                    AND (a.credentials IS NOT NULL))))
    LEFT JOIN calendar c ON (c.account_id = a.id))
    LEFT JOIN event e ON (e.calendar_id = c.id))
GROUP BY
    u.id;

CREATE OR REPLACE VIEW "public"."insight" AS
SELECT
    e.user_id,
    e.day,
    e.category_id,
    text2ltree (min(ltree2text (e.category_path))) AS category_path,
    e.type,
    e.attendance,
    nv.name,
    nv.value,
    (count(*))::integer AS count,
    (sum(e.minutes))::integer AS minutes
FROM (event_x e
    CROSS JOIN LATERAL (
        VALUES ('Total'::text, NULL::text),
            ('Length'::text, (e.rounded_length)::text),
            ('Size'::text, e.size),
            ('Organizer'::text, CASE WHEN e.initiated THEN
                    'You'::text
                ELSE
                    e.organizer_email
                END),
            ('External'::text, CASE WHEN (e.internal = 'internal'::event_internal) THEN
                    'Interal'::text
                WHEN (e.internal = 'external'::event_internal) THEN
                    'External'::text
                ELSE
                    NULL::text
                END),
            ('Recurring'::text, CASE WHEN e.recurring THEN
                    'Recurring'::text
                ELSE
                    'Ad hoc'::text
                END),
            ('Notice'::text, CASE WHEN (e.notice < 12) THEN
                    '< 12 hours'::text
                WHEN (e.notice < 24) THEN
                    '< 24 hours'::text
                WHEN (e.notice < (24 * 7)) THEN
                    '< week'::text
                ELSE
                    '> week'::text
                END)) nv (name, value))
WHERE (e.status <> 'cancelled'::event_status)
GROUP BY
    e.user_id,
    e.day,
    e.category_id,
    e.type,
    e.attendance,
    nv.name,
    nv.value;

CREATE OR REPLACE VIEW "public"."insight_monthly" AS
SELECT
    insight.user_id,
    (date_trunc('month'::text, (insight.day)::timestamp with time zone))::date AS month,
    insight.type,
    insight.category_id,
    text2ltree (min(ltree2text (insight.category_path))) AS category_path,
    insight.attendance,
    insight.name,
    insight.value,
    sum(insight.count) AS count,
    sum(insight.minutes) AS minutes
FROM
    insight
GROUP BY
    insight.user_id,
    ((date_trunc('month'::text, (insight.day)::timestamp with time zone))::date),
    insight.type,
    insight.category_id,
    insight.attendance,
    insight.name,
    insight.value;

CREATE OR REPLACE VIEW "public"."category_total_weekly" AS
SELECT
    insight.user_id,
    (date_trunc('week'::text, (insight.day)::timestamp with time zone))::date AS week,
    insight.category_id,
    text2ltree (min(ltree2text (insight.category_path))) AS category_path,
    insight.type,
    sum(insight.count) FILTER (WHERE (insight.attendance = 'attend'::event_attendance)) AS count,
sum(insight.minutes) FILTER (WHERE (insight.attendance = 'attend'::event_attendance)) AS minutes,
sum(insight.count) FILTER (WHERE (insight.attendance IS NULL)) AS pending_count,
sum(insight.minutes) FILTER (WHERE (insight.attendance IS NULL)) AS pending_minutes
FROM
    insight
WHERE (insight.name = 'Total'::text)
GROUP BY
    insight.user_id,
    (date_trunc('week'::text, (insight.day)::timestamp with time zone)),
    insight.category_id,
    insight.type;

CREATE OR REPLACE VIEW "public"."balance" AS
SELECT
    g.user_id,
    g.week,
    g.category_id,
    g.category_path,
    g.type,
    sum((g.weekly_minutes - COALESCE(i.minutes, (0)::bigint))) OVER w AS minutes,
    sum(i.pending_minutes) OVER w AS pending_minutes
FROM (goal_weekly g
    LEFT JOIN category_total_weekly i ON (((g.user_id = i.user_id)
                AND (g.week = i.week)
                AND (g.category_path <@ i.category_path)
                AND goal_type_equal (g.type, i.type))))
WINDOW w AS (PARTITION BY g.user_id, g.category_id, g.type ORDER BY g.week RANGE BETWEEN '21 days'::interval PRECEDING AND CURRENT ROW);

CREATE POLICY "Users can read/write their categories" ON "public"."category" AS permissive
    FOR ALL TO authenticated
        USING (is_user_account (auth.uid (), user_id));

CREATE POLICY "Users can edit their own event overlays" ON "public"."event_overlay" AS permissive
    FOR ALL TO authenticated
        USING (is_user_account (auth.uid (), user_id));

CREATE POLICY "Users can view their own goals" ON "public"."goal" AS permissive
    FOR ALL TO authenticated
        USING (is_user_account (auth.uid (), user_id));

ALTER VIEW gap SET (security_invoker = TRUE);

ALTER VIEW gap_monthly SET (security_invoker = TRUE);

ALTER VIEW gap_daily SET (security_invoker = TRUE);

ALTER VIEW insight SET (security_invoker = TRUE);

ALTER VIEW insight_monthly SET (security_invoker = TRUE);

ALTER VIEW category_total_weekly SET (security_invoker = TRUE);

ALTER VIEW goal_weekly SET (security_invoker = TRUE);

ALTER VIEW balance SET (security_invoker = TRUE);

ALTER VIEW "public"."invitation_admin" SET (security_invoker = FALSE);

ALTER VIEW "public"."event_x" SET (security_invoker = TRUE);

ALTER VIEW "public"."waitlist_admin" SET (security_invoker = FALSE);

ALTER VIEW prep_monthly SET (security_invoker = TRUE);

ALTER VIEW "public"."sync_admin" SET (security_invoker = FALSE);

REVOKE ALL ON waitlist_admin FROM PUBLIC;

GRANT SELECT ON waitlist_admin TO internal_admin;

REVOKE ALL ON sync_admin FROM PUBLIC;

GRANT SELECT ON sync_admin TO internal_admin;

