CREATE TABLE "public"."event_label" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" timestamp with time zone DEFAULT now(),
    "event_id" bigint,
    "series" text,
    "label_id" bigint NOT NULL,
    "priority" smallint NOT NULL DEFAULT '100' ::smallint,
    "negate" boolean NOT NULL DEFAULT FALSE
);

ALTER TABLE "public"."event_label" ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."label" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" timestamp with time zone DEFAULT now(),
    "user_id" bigint,
    "name" text NOT NULL
);

ALTER TABLE "public"."label" ENABLE ROW LEVEL SECURITY;

CREATE UNIQUE INDEX event_label_event_id_series_label_id_key ON public.event_label USING btree (event_id, series, label_id) NULLS NOT DISTINCT;

CREATE UNIQUE INDEX event_label_pkey ON public.event_label USING btree (id);

CREATE UNIQUE INDEX label_pkey ON public.label USING btree (id);

ALTER TABLE "public"."event_label"
    ADD CONSTRAINT "event_label_pkey" PRIMARY KEY USING INDEX "event_label_pkey";

ALTER TABLE "public"."label"
    ADD CONSTRAINT "label_pkey" PRIMARY KEY USING INDEX "label_pkey";

ALTER TABLE "public"."event_label"
    ADD CONSTRAINT "event_label_event_id_fkey" FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE NOT valid;

ALTER TABLE "public"."event_label" validate CONSTRAINT "event_label_event_id_fkey";

ALTER TABLE "public"."event_label"
    ADD CONSTRAINT "event_label_label_id_fkey" FOREIGN KEY (label_id) REFERENCES label (id) ON DELETE CASCADE NOT valid;

ALTER TABLE "public"."event_label" validate CONSTRAINT "event_label_label_id_fkey";

ALTER TABLE "public"."label"
    ADD CONSTRAINT "label_user_id_fkey" FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT valid;

ALTER TABLE "public"."label" validate CONSTRAINT "label_user_id_fkey";

SET check_function_bodies = OFF;

CREATE OR REPLACE VIEW "public"."event_x" AS
SELECT
    u.id AS user_id,
    e.id,
    e.created_at,
    e.calendar_id,
    e.provider_id,
    e.series,
    e.name,
    e.status,
    e.at,
    e.attended,
    e.provider_link,
    e.summary,
    e.description,
    e.visibility,
    e.availability,
    e.conferencing_url,
    e.organizer,
    e.sequence
FROM (((event e
            JOIN calendar c ON (e.calendar_id = c.id))
        JOIN account a ON (c.account_id = a.id))
    JOIN "user" u ON (a.user_id = u.id));

DROP FUNCTION public.upsert_event;

CREATE FUNCTION public.upsert_event (_calendar_id bigint, _raw_event raw_event, _event event, _organizer event_contact, _invitees event_invitee[])
    RETURNS bigint
    LANGUAGE plpgsql
    AS $function$
DECLARE
    _user_id bigint;
    _new_event record;
    _contact_id bigint;
    _invitee event_invitee;
    _organizer_id bigint DEFAULT 343;
BEGIN
    -- get _user_id
    SELECT
        a.user_id INTO _user_id
    FROM
        account a
        JOIN calendar c ON a.id = c.account_id
    WHERE
        c.id = _calendar_id;
    -- create or update raw event
    INSERT INTO public.raw_event (calendar_id, provider_id, event, "sequence")
        VALUES (_raw_event.calendar_id, _raw_event.provider_id, _raw_event.event, _raw_event.sequence)
    ON CONFLICT (calendar_id, provider_id)
        DO UPDATE SET event = EXCLUDED.event, "sequence" = EXCLUDED.sequence;
    -- get (or create) organizer contact
    IF _organizer.email IS NOT NULL THEN
        INSERT INTO public.contact (email, name, user_id)
            VALUES (_organizer.email, _organizer.name, _user_id)
        ON CONFLICT (user_id, email)
            DO UPDATE SET
                name = COALESCE(contact.name, EXCLUDED.name)
            RETURNING
                id INTO _organizer_id;
    END IF;
    -- create or update event
    INSERT INTO public.event (calendar_id, provider_id, series, name, status, at, attended, provider_link, summary, description, visibility, availability, conferencing_url, organizer)
        VALUES (_event.calendar_id, _event.provider_id, _event.series, _event.name, _event.status, _event.at, _event.attended, _event.provider_link, _event.summary, _event.description, _event.visibility, _event.availability, _event.conferencing_url, _organizer_id)
    ON CONFLICT (calendar_id, provider_id)
        DO UPDATE SET
            "sequence" = EXCLUDED.sequence + 1, series = EXCLUDED.series, name = EXCLUDED.name, status = EXCLUDED.status, at = EXCLUDED.at, attended = EXCLUDED.attended, provider_link = EXCLUDED.provider_link, summary = EXCLUDED.summary, description = EXCLUDED.description, visibility = EXCLUDED.visibility, availability = EXCLUDED.availability, conferencing_url = EXCLUDED.conferencing_url, organizer = EXCLUDED.organizer
        RETURNING
            id, "sequence" INTO _new_event;
    -- create or update contacts and invitees
    FOREACH _invitee IN ARRAY _invitees LOOP
        INSERT INTO public.contact (email, name, user_id)
            VALUES ((_invitee).contact.email, (_invitee).contact.name, _user_id)
        ON CONFLICT (user_id, email)
            DO UPDATE SET
                name = COALESCE(contact.name, EXCLUDED.name)
            RETURNING
                id INTO _contact_id;
        INSERT INTO public.invitee (event_id, contact_id, response, "sequence", is_optional)
            VALUES (_new_event.id, _contact_id, _invitee.response, _new_event.sequence, _invitee.is_optional)
        ON CONFLICT (event_id, contact_id)
            DO UPDATE SET
                response = EXCLUDED.response, "sequence" = EXCLUDED.sequence, is_optional = EXCLUDED.is_optional;
    END LOOP;
    -- delete any now missing invitees
    DELETE FROM invitee i
    WHERE i.event_id = _new_event.id
        AND "sequence" < _new_event.sequence;
    RETURN _new_event.id;
END;
$function$;

