CREATE TYPE "public"."event_availability" AS enum (
    'busy',
    'away',
    'focus',
    'free'
);

CREATE TYPE "public"."event_response" AS enum (
    'accepted',
    'declined',
    'tentative'
);

CREATE TYPE "public"."event_status" AS enum (
    'confirmed',
    'cancelled',
    'tentative'
);

CREATE TYPE "public"."event_visibility" AS enum (
    'normal',
    'private',
    'confidential',
    'public',
    'personal'
);

CREATE TYPE "public"."location_type" AS enum (
    'room',
    'address',
    'other'
);

ALTER TABLE "public"."raw_event"
    DROP CONSTRAINT "raw_event_provider_id_key";

DROP INDEX IF EXISTS "public"."raw_event_provider_id_key";

CREATE TABLE "public"."contact" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    "user_id" bigint NOT NULL,
    "email" text,
    "name" text,
    "organization_id" bigint,
    "contact_user_id" bigint
);

ALTER TABLE "public"."contact" ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."event" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    "calendar_id" bigint NOT NULL,
    "provider_id" text NOT NULL,
    "series" text,
    "name" text,
    "status" event_status NOT NULL DEFAULT 'confirmed' ::event_status,
    "at" tstzrange NOT NULL,
    "attended" tstzrange,
    "provider_link" text,
    "summary" text,
    "description" text,
    "response" event_response,
    "visibility" event_visibility NOT NULL DEFAULT 'normal' ::event_visibility,
    "availability" event_availability NOT NULL DEFAULT 'busy' ::event_availability,
    "conferencing_url" text,
    "organizer" bigint,
    "sequence" integer NOT NULL DEFAULT 1
);

ALTER TABLE "public"."event" ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."invitee" (
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    "event_id" bigint NOT NULL,
    "contact_id" bigint NOT NULL,
    "response" event_response,
    "sequence" integer NOT NULL DEFAULT 1,
    "is_optional" boolean NOT NULL DEFAULT FALSE
);

ALTER TABLE "public"."invitee" ENABLE ROW LEVEL SECURITY;

CREATE UNIQUE INDEX contact_pkey ON public.contact USING btree (id);

CREATE UNIQUE INDEX contact_user_id_email_key ON public.contact USING btree (user_id, email);

CREATE UNIQUE INDEX event_calendar_id_provider_id_key ON public.event USING btree (calendar_id, provider_id);

CREATE UNIQUE INDEX event_pkey ON public.event USING btree (id);

CREATE UNIQUE INDEX invitee_pkey ON public.invitee USING btree (event_id, contact_id);

CREATE UNIQUE INDEX raw_event_calendar_id_provider_id_key ON public.raw_event USING btree (calendar_id, provider_id);

ALTER TABLE "public"."contact"
    ADD CONSTRAINT "contact_pkey" PRIMARY KEY USING INDEX "contact_pkey";

ALTER TABLE "public"."event"
    ADD CONSTRAINT "event_pkey" PRIMARY KEY USING INDEX "event_pkey";

ALTER TABLE "public"."invitee"
    ADD CONSTRAINT "invitee_pkey" PRIMARY KEY USING INDEX "invitee_pkey";

ALTER TABLE "public"."contact"
    ADD CONSTRAINT "contact_contact_user_id_fkey" FOREIGN KEY (contact_user_id) REFERENCES "user" (id) ON DELETE SET NULL NOT valid;

ALTER TABLE "public"."contact" validate CONSTRAINT "contact_contact_user_id_fkey";

ALTER TABLE "public"."contact"
    ADD CONSTRAINT "contact_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES organization (id) ON DELETE SET NULL NOT valid;

ALTER TABLE "public"."contact" validate CONSTRAINT "contact_organization_id_fkey";

ALTER TABLE "public"."contact"
    ADD CONSTRAINT "contact_user_id_email_key" UNIQUE USING INDEX "contact_user_id_email_key";

ALTER TABLE "public"."contact"
    ADD CONSTRAINT "contact_user_id_fkey" FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT valid;

ALTER TABLE "public"."contact" validate CONSTRAINT "contact_user_id_fkey";

ALTER TABLE "public"."event"
    ADD CONSTRAINT "event_calendar_id_fkey" FOREIGN KEY (calendar_id) REFERENCES calendar (id) ON DELETE CASCADE NOT valid;

ALTER TABLE "public"."event" validate CONSTRAINT "event_calendar_id_fkey";

ALTER TABLE "public"."event"
    ADD CONSTRAINT "event_calendar_id_provider_id_key" UNIQUE USING INDEX "event_calendar_id_provider_id_key";

ALTER TABLE "public"."event"
    ADD CONSTRAINT "event_organizer_fkey" FOREIGN KEY (organizer) REFERENCES contact (id) ON DELETE SET NULL NOT valid;

ALTER TABLE "public"."event" validate CONSTRAINT "event_organizer_fkey";

ALTER TABLE "public"."invitee"
    ADD CONSTRAINT "invitee_contact_id_fkey" FOREIGN KEY (contact_id) REFERENCES contact (id) ON DELETE CASCADE NOT valid;

ALTER TABLE "public"."invitee" validate CONSTRAINT "invitee_contact_id_fkey";

ALTER TABLE "public"."invitee"
    ADD CONSTRAINT "invitee_event_id_fkey" FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE NOT valid;

ALTER TABLE "public"."invitee" validate CONSTRAINT "invitee_event_id_fkey";

ALTER TABLE "public"."raw_event"
    ADD CONSTRAINT "raw_event_calendar_id_provider_id_key" UNIQUE USING INDEX "raw_event_calendar_id_provider_id_key";

SET check_function_bodies = OFF;

CREATE TYPE "public"."invitee_contact" AS (
    "email" text,
    "name" text,
    "response" event_response,
    "is_organizer" boolean,
    "is_optional" boolean
);

CREATE OR REPLACE FUNCTION public.link_contact_to_organization ()
    RETURNS TRIGGER
    LANGUAGE plpgsql
    SECURITY DEFINER
    SET search_path TO 'public'
    AS $function$
BEGIN
    IF NEW.email IS NOT NULL THEN
        NEW.organization_id = (
            SELECT
                public.get_or_create_organization_id (NEW.email));
    END IF;
    RETURN NEW;
END
$function$;

CREATE OR REPLACE FUNCTION public.upsert_event (_calendar_id bigint, _raw_event raw_event, _event event, _invitees invitee_contact[])
    RETURNS void
    LANGUAGE plpgsql
    AS $function$
DECLARE
    _user_id bigint;
    _new_event record;
    _contact_id bigint;
    _invitee invitee_contact;
    _organizer_id bigint;
BEGIN
    SELECT
        a.user_id INTO _user_id
    FROM
        account a
        JOIN calendar c ON a.id = c.account_id
    WHERE
        c.id = _calendar_id;
    INSERT INTO public.raw_event (calendar_id, provider_id, event, SEQUENCE)
VALUES (_raw_event.calendar_id,
    _raw_event.provider_id,
    _raw_event.event,
    _raw_event.sequence)
ON CONFLICT (calendar_id,
    provider_id)
    DO UPDATE SET event = EXCLUDED.event, SEQUENCE =
        EXCLUDED.sequence;
    INSERT INTO public.event (calendar_id, provider_id, series, name, status, at, attended, provider_link, summary, description, response, visibility, availability, conferencing_url, organizer)
        VALUES (_event.calendar_id, _event.provider_id, _event.series, _event.name, _event.status, _event.at, _event.attended, _event.provider_link, _event.summary, _event.description, _event.response, _event.visibility, _event.availability, _event.conferencing_url, _event.organizer)
    ON CONFLICT (calendar_id, provider_id)
        DO UPDATE SET SEQUENCE =
            EXCLUDED.sequence + 1, series = EXCLUDED.series, name = EXCLUDED.name, status = EXCLUDED.status, at = EXCLUDED.at, attended = EXCLUDED.attended, provider_link = EXCLUDED.provider_link, summary = EXCLUDED.summary, description = EXCLUDED.description, response = EXCLUDED.response, visibility = EXCLUDED.visibility, availability = EXCLUDED.availability, conferencing_url = EXCLUDED.conferencing_url, organizer = EXCLUDED.organizer
        RETURNING
            id, SEQUENCE INTO
                _new_event;
    FOREACH _invitee IN ARRAY _invitees LOOP
        INSERT INTO public.contact (email, name, user_id)
            VALUES (_invitee.email, _invitee.name, _user_id)
        ON CONFLICT (user_id, email)
            DO UPDATE SET
                name = COALESCE(public.contact.name, EXCLUDED.name)
            RETURNING
                id INTO _contact_id;
        IF _invitee.is_organizer THEN
            _organizer_id = _contact_id;
        END IF;
        INSERT INTO public.invitee (event_id, contact_id, response, SEQUENCE)
    VALUES (_new_event.id,
        _contact_id,
        _invitee.response,
        _new_event.sequence)
ON CONFLICT (event_id,
    contact_id)
    DO UPDATE SET
        response = EXCLUDED.response,
        SEQUENCE =
            EXCLUDED.sequence;
    END LOOP;
    DELETE FROM invitee i
    WHERE i.event_id = _new_event.id
        AND i.contact_id = _contact_id
        AND SEQUENCE <
            _new_event.sequence;
END;
$function$;

CREATE TRIGGER on_contact_created
    BEFORE INSERT ON public.contact
    FOR EACH ROW
    EXECUTE FUNCTION link_contact_to_organization ();

