CREATE TABLE "public"."tag" (
    "id" bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    "user_id" uuid NOT NULL,
    "note_id" bigint,
    "emoji" text NOT NULL
);

ALTER TABLE "public"."tag" ENABLE ROW LEVEL SECURITY;

ALTER TABLE "public"."context"
    DROP COLUMN "pinned";

ALTER TABLE "public"."context"
    ALTER COLUMN "order" SET NOT NULL;

ALTER TABLE "public"."note"
    ADD COLUMN "order" text NOT NULL;

ALTER TABLE "public"."note"
    ADD COLUMN "private" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "public"."note"
    ADD COLUMN "root" boolean NOT NULL DEFAULT TRUE;

ALTER TABLE "public"."note"
    ADD COLUMN "topic_id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL;

CREATE UNIQUE INDEX note_order_root ON public.note USING btree (context_id, "order")
WHERE (root = TRUE);

CREATE UNIQUE INDEX note_order_topic ON public.note USING btree (context_id, topic_id, "order")
WHERE (root = FALSE);

CREATE UNIQUE INDEX note_topic_root ON public.note USING btree (context_id, topic_id)
WHERE (root = TRUE);

CREATE UNIQUE INDEX tag_pkey ON public.tag USING btree (id);

CREATE UNIQUE INDEX tag_user_id_note_id_emoji_key ON public.tag USING btree (user_id, note_id, emoji);

ALTER TABLE "public"."tag"
    ADD CONSTRAINT "tag_pkey" PRIMARY KEY USING INDEX "tag_pkey";

ALTER TABLE "public"."tag"
    ADD CONSTRAINT "tag_note_id_fkey" FOREIGN KEY (note_id) REFERENCES note (id) ON DELETE CASCADE NOT valid;

ALTER TABLE "public"."tag" validate CONSTRAINT "tag_note_id_fkey";

ALTER TABLE "public"."tag"
    ADD CONSTRAINT "tag_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users (id) ON DELETE CASCADE NOT valid;

ALTER TABLE "public"."tag" validate CONSTRAINT "tag_user_id_fkey";

ALTER TABLE "public"."tag"
    ADD CONSTRAINT "tag_user_id_note_id_emoji_key" UNIQUE USING INDEX "tag_user_id_note_id_emoji_key";

SET check_function_bodies = OFF;

CREATE OR REPLACE VIEW "public"."note_x" AS
SELECT
    note.id,
    note.created_at,
    note.modified_at,
    note.user_id,
    note.context_id,
    note.topic_id,
    note.body,
    note."order",
    note.root,
    note.private,
    context.path AS context_path,
    jsonb_object_agg(tag_users.emoji, tag_users.user_ids) AS tags
FROM ((note
    LEFT JOIN context ON (note.context_id = context.id))
    LEFT JOIN (
        SELECT
            tag.note_id,
            tag.emoji,
            jsonb_agg(tag.user_id) AS user_ids
        FROM
            tag
        GROUP BY
            tag.note_id,
            tag.emoji) tag_users ON (note.id = tag_users.note_id))
GROUP BY
    note.id,
    context.path;

CREATE OR REPLACE FUNCTION public.update_topic_root (note_id bigint)
    RETURNS void
    LANGUAGE plpgsql
    AS $function$
DECLARE
    _root_order text;
    _context_id bigint;
    _topic_id bigint;
BEGIN
    -- Start a transaction block
    BEGIN
        -- Find the context_id and topic_id for the given ID
        SELECT
            context_id,
            topic_id INTO _context_id,
            _topic_id
        FROM
            "public"."note"
        WHERE
            id = note_id;
        -- Find the previous root and capture the order value
        SELECT
            "order" INTO _root_order
        FROM
            "public"."note"
        WHERE (context_id IS NOT DISTINCT FROM _context_id)
            AND topic_id = _topic_id
            AND root = TRUE
        FOR UPDATE;
        -- Update previous root record to set root = false and order = '!'
        UPDATE
            "public"."note"
        SET
            root = FALSE,
            "order" = '!'
        WHERE (context_id IS NOT DISTINCT FROM _context_id)
            AND topic_id = _topic_id
            AND root = TRUE;
        -- Update the row for the given id to set root = true and order previous order
        UPDATE
            "public"."note"
        SET
            root = TRUE,
            "order" = _root_order
        WHERE
            id = note_id;
    EXCEPTION
        WHEN OTHERS THEN
            -- Rollback the transaction if any exception occurs
            RAISE;
    END;
END;

$function$;

ALTER VIEW note_x SET (security_invoker = TRUE);

