import { type Tag } from "./tag";
import { type Callback } from "./tools/callbacks";
import { type JSONValue } from "./utils/types";
import { Uuid } from "./utils/uuid";

export { Tag } from "./tag";
export { Uuid } from "./utils/uuid";
export { type JSONValue } from "./utils/types";

/**
 * @fileoverview
 * Core Plot entity types for working with activities, notes, priorities, and contacts.
 *
 * ## Type Pattern: Null vs Undefined Semantics
 *
 * Plot entity types use a consistent pattern to distinguish between missing, unset, and explicitly cleared values:
 *
 * ### Entity Types (Activity, Priority, Note, Actor)
 * - **Required fields**: No `?`, cannot be `undefined`
 *   - Example: `id: Uuid`, `type: ActivityType`
 * - **Nullable fields**: Use `| null` to allow explicit clearing
 *   - Example: `assignee: ActorId | null`, `done: Date | null`
 *   - `null` = field is explicitly unset/cleared
 *   - Non-null value = field has a value
 * - **Optional nullable fields**: Use `?` with `| null` for permission-based access
 *   - Example: `email?: string | null`, `name?: string | null`
 *   - `undefined` = field not included (e.g., no permission to access)
 *   - `null` = field included but not set
 *   - Value = field has a value
 *
 * ### New* Types (NewActivity, NewNote, NewPriority)
 * Used for creating or updating entities. Support partial updates by distinguishing omitted vs cleared fields:
 * - **Required fields**: Must be provided (no `?`)
 *   - Example: `type: ActivityType` in NewActivity
 * - **Optional fields**: Use `?` to make them optional
 *   - Example: `title?: string`, `author?: NewActor`
 *   - `undefined` (omitted) = don't set/update this field
 *   - Provided value = set/update this field
 * - **Optional nullable fields**: Use `?` with `| null` to support clearing
 *   - Example: `assignee?: NewActor | null`
 *   - `undefined` (omitted) = don't change assignee
 *   - `null` = clear the assignee
 *   - NewActor = set/update the assignee
 *
 * This pattern allows API consumers to:
 * 1. Omit fields they don't want to change (undefined)
 * 2. Explicitly clear fields by setting to null
 * 3. Set or update fields by providing values
 *
 * @example
 * ```typescript
 * // Creating a new activity
 * const newActivity: NewActivity = {
 *   type: ActivityType.Action,  // Required
 *   title: "Review PR",          // Optional, provided
 *   assignee: null,              // Optional nullable, explicitly clearing
 *   // priority is omitted (undefined), will auto-select or use default
 * };
 *
 * // Updating an activity - only change what's specified
 * const update: ActivityUpdate = {
 *   id: activityId,
 *   done: new Date(),       // Mark as done
 *   assignee: null,         // Clear assignee
 *   // title is omitted, won't be changed
 * };
 * ```
 */

/**
 * Represents a unique user, contact, or twist in Plot.
 *
 * ActorIds are used throughout Plot for:
 * - Activity authors and assignees
 * - Tag creators (actor_id in activity_tag/note_tag)
 * - Mentions in activities and notes
 * - Any entity that can perform actions in Plot
 */
export type ActorId = string & { readonly __brand: "ActorId" };

/**
 * Theme colors for priorities.
 */
export enum ThemeColor {
  /** Catalyst - Green */
  Catalyst = 0,
  /** Call to Adventure - Blue */
  CallToAdventure = 1,
  /** Rising Action - Purple */
  RisingAction = 2,
  /** Momentum - Pink-Purple */
  Momentum = 3,
  /** Turning Point - Pink */
  TurningPoint = 4,
  /** Breakthrough - Orange */
  Breakthrough = 5,
  /** Climax - Olive */
  Climax = 6,
  /** Resolution - Blue-Gray */
  Resolution = 7,
}

/**
 * Represents a priority context within Plot.
 *
 * Priorities are similar to projects in other apps. All Activity is in a Priority.
 * Priorities can be nested.
 */
export type Priority = {
  /** Unique identifier for the priority */
  id: Uuid;
  /** Human-readable title for the priority */
  title: string;
  /** Whether this priority has been archived */
  archived: boolean;
  /**
   * Optional key for referencing this priority.
   * Keys are unique per priority tree (a user's personal priorities or the root of a shared priority).
   */
  key: string | null;
  /** Optional theme color for the priority (0-7). If not set, inherits from parent or defaults to 7 (Resolution). */
  color: ThemeColor | null;
};

/**
 * Type for creating new priorities.
 *
 * Supports multiple creation patterns:
 * - Provide a specific UUID for the priority
 * - Provide a key for upsert within the user's priorities
 * - Omit both to auto-generate a new UUID
 *
 * Optionally specify a parent priority by ID or key for hierarchical structures.
 */
export type NewPriority = Pick<Priority, "title"> &
  Partial<Omit<Priority, "id" | "title">> &
  (
    | {
        /**
         * Unique identifier for the priority, generated by Uuid.Generate().
         * Specifying an ID allows tools to track and upsert priorities.
         */
        id: Uuid;
      }
    | {
        /**
         * Unique key for the priority within the user's priorities.
         * Can be used to upsert without knowing the UUID.
         * For example, "@plot" identifies the Plot priority.
         */
        key: string;
      }
    | {
        /* Neither id nor key is required. An id will be generated and returned. */
      }
  ) & {
    /** Add the new priority as the child of another priority */
    parent?: { id: Uuid } | { key: string };
  };

/**
 * Type for updating existing priorities.
 * Must provide either id or key to identify the priority to update.
 */
export type PriorityUpdate = ({ id: Uuid } | { key: string }) &
  Partial<Pick<Priority, "title" | "archived">>;

/**
 * Enumeration of supported activity types in Plot.
 *
 * Each activity type has different behaviors and rendering characteristics
 * within the Plot application.
 */
export enum ActivityType {
  /** A note or piece of information without actionable requirements */
  Note,
  /** An actionable item that can be completed */
  Action,
  /** A scheduled occurrence with start and optional end time */
  Event,
}

/**
 * Kinds of activities. Used only for visual categorization (icon).
 */
export enum ActivityKind {
  document = "document", // any external document or item in an external system
  messages = "messages", // emails and chat threads
  meeting = "meeting", // in-person meeting
  videoconference = "videoconference",
  phone = "phone",
  focus = "focus",
  meal = "meal",
  exercise = "exercise",
  family = "family",
  travel = "travel",
  social = "social",
  entertainment = "entertainment",
}

/**
 * Enumeration of supported activity link types.
 *
 * Different link types have different behaviors when clicked by users
 * and may require different rendering approaches.
 */
export enum ActivityLinkType {
  /** External web links that open in browser */
  external = "external",
  /** Authentication flows for connecting services */
  auth = "auth",
  /** Callback links that trigger twist methods when clicked */
  callback = "callback",
  /** Video conferencing links with provider-specific handling */
  conferencing = "conferencing",
  /** File attachment links stored in R2 */
  file = "file",
}

/**
 * Video conferencing providers for conferencing links.
 *
 * Used to identify the conferencing platform and provide
 * provider-specific UI elements (titles, icons, etc.).
 */
export enum ConferencingProvider {
  /** Google Meet */
  googleMeet = "googleMeet",
  /** Zoom */
  zoom = "zoom",
  /** Microsoft Teams */
  microsoftTeams = "microsoftTeams",
  /** Cisco Webex */
  webex = "webex",
  /** Other or unknown conferencing provider */
  other = "other",
}

/**
 * Represents a clickable link attached to an activity.
 *
 * Activity links are rendered as buttons that enable user interaction with activities.
 * Different link types have specific behaviors and required fields for proper functionality.
 *
 * @example
 * ```typescript
 * // External link - opens URL in browser
 * const externalLink: ActivityLink = {
 *   type: ActivityLinkType.external,
 *   title: "Open in Google Calendar",
 *   url: "https://calendar.google.com/event/123",
 * };
 *
 * // Conferencing link - opens video conference with provider info
 * const conferencingLink: ActivityLink = {
 *   type: ActivityLinkType.conferencing,
 *   url: "https://meet.google.com/abc-defg-hij",
 *   provider: ConferencingProvider.googleMeet,
 * };
 *
 * // Integrations link - initiates OAuth flow
 * const authLink: ActivityLink = {
 *   type: ActivityLinkType.auth,
 *   title: "Continue with Google",
 *   provider: AuthProvider.Google,
 *   scopes: ["https://www.googleapis.com/auth/calendar.readonly"],
 *   callback: "callback-token-for-auth-completion"
 * };
 *
 * // Callback link - triggers a twist method
 * const callbackLink: ActivityLink = {
 *   type: ActivityLinkType.callback,
 *   title: "📅 Primary Calendar",
 *   token: "callback-token-here"
 * };
 * ```
 */
export type ActivityLink =
  | {
      /** External web link that opens in browser */
      type: ActivityLinkType.external;
      /** Display text for the link button */
      title: string;
      /** URL to open when clicked */
      url: string;
    }
  | {
      /** Video conferencing link with provider-specific handling */
      type: ActivityLinkType.conferencing;
      /** URL to join the conference */
      url: string;
      /** Conferencing provider for UI customization */
      provider: ConferencingProvider;
    }
  | {
      /** Authentication link that initiates an OAuth flow */
      type: ActivityLinkType.auth;
      /** Display text for the auth button */
      title: string;
      /** OAuth provider (e.g., "google", "microsoft") */
      provider: string;
      /** Array of OAuth scopes to request */
      scopes: string[];
      /** Callback token for auth completion notification */
      callback: Callback;
    }
  | {
      /** Callback link that triggers a twist method when clicked */
      type: ActivityLinkType.callback;
      /** Display text for the callback button */
      title: string;
      /** Token identifying the callback to execute */
      callback: Callback;
    }
  | {
      /** File attachment link stored in R2 */
      type: ActivityLinkType.file;
      /** Unique identifier for the stored file */
      fileId: string;
      /** Original filename */
      fileName: string;
      /** File size in bytes */
      fileSize: number;
      /** MIME type of the file */
      mimeType: string;
    };

/**
 * Represents metadata about an activity, typically from an external system.
 *
 * Activity metadata enables storing additional information about activities,
 * which is useful for synchronization, linking back to external systems,
 * and storing tool-specific data.
 *
 * Must be valid JSON data (strings, numbers, booleans, null, objects, arrays).
 * Functions and other non-JSON values are not supported.
 *
 * @example
 * ```typescript
 * // Calendar event metadata
 * await plot.createActivity({
 *   type: ActivityType.Event,
 *   title: "Team Meeting",
 *   start: new Date("2024-01-15T10:00:00Z"),
 *   meta: {
 *     calendarId: "primary",
 *     htmlLink: "https://calendar.google.com/event/abc123",
 *     conferenceData: { ... }
 *   }
 * });
 *
 * // Project issue metadata
 * await plot.createActivity({
 *   type: ActivityType.Action,
 *   title: "Fix login bug",
 *   meta: {
 *     projectId: "TEAM",
 *     issueNumber: 123,
 *     url: "https://linear.app/team/issue/TEAM-123"
 *   }
 * });
 * ```
 */
export type ActivityMeta = {
  /** Source-specific properties and metadata */
  [key: string]: JSONValue;
};

/**
 * Tags on an item, along with the actors who added each tag.
 */
export type Tags = { [K in Tag]?: ActorId[] };

/**
 * A set of tags to add to an item, along with the actors adding each tag.
 */
export type NewTags = { [K in Tag]?: NewActor[] };

/**
 * Common fields shared by both Activity and Note entities.
 */
export type ActivityCommon = {
  /** Unique identifier for the activity */
  id: Uuid;
  /**
   * When this activity was originally created in its source system.
   *
   * For activities created in Plot, this is when the user created it.
   * For activities synced from external systems (GitHub issues, emails, calendar events),
   * this is the original creation time in that system.
   *
   * Defaults to the current time when creating new activities.
   */
  created: Date;
  /** Information about who created the activity */
  author: Actor;
  /** Whether this activity is private (only visible to author) */
  private: boolean;
  /** Whether this activity has been archived */
  archived: boolean;
  /** Tags attached to this activity. Maps tag ID to array of actor IDs who added that tag. */
  tags: Tags;
  /** Array of actor IDs (users, contacts, or twists) mentioned in this activity via @-mentions */
  mentions: ActorId[];
};

export type Activity = ActivityCommon & {
  /**
   * Globally unique, stable identifier for the item in an external system.
   * MUST use immutable system-generated IDs, not human-readable slugs or titles.
   *
   * Recommended format: `${domain}:${type}:${id}`
   *
   * Examples:
   *   - `linear:issue:549dd8bd-2bc9-43d1-95d5-4b4af0c5af1b` (Linear issue by UUID)
   *   - `jira:10001:issue:12345` (Jira issue by numeric ID with cloud ID)
   *   - `gmail:thread:18d4e5f2a3b1c9d7` (Gmail thread by system ID)
   *
   * ⚠️ AVOID: URLs with mutable components like team names or issue keys
   *   - Bad: `https://linear.app/team/issue/TEAM-123/title` (team and title can change)
   *   - Bad: `jira:issue:PROJECT-42` (issue key can change)
   *
   * When set, uniquely identifies the activity within a priority tree for upsert operations.
   */
  source: string | null;
  /** The display title/summary of the activity */
  title: string;
  /** The type of activity (Note, Task, or Event) */
  type: ActivityType;
  /** Optional kind for additional categorization within the activity */
  kind: ActivityKind | null;
  /**
   * The actor assigned to this activity.
   *
   * **For actions (tasks):**
   * - If not provided (undefined), defaults to the user who installed the twist (twist owner)
   * - To create an **unassigned action**, explicitly set `assignee: null`
   * - For synced tasks from external systems, typically set `assignee: null` for unassigned items
   *
   * **For notes and events:** Assignee is optional and typically null.
   *
   * @example
   * ```typescript
   * // Create action assigned to twist owner (default behavior)
   * const task: NewActivity = {
   *   type: ActivityType.Action,
   *   title: "Follow up on email"
   *   // assignee omitted → defaults to twist owner
   * };
   *
   * // Create UNASSIGNED action (for backlog items)
   * const backlogTask: NewActivity = {
   *   type: ActivityType.Action,
   *   title: "Review PR #123",
   *   assignee: null  // Explicitly set to null
   * };
   *
   * // Create action with explicit assignee
   * const assignedTask: NewActivity = {
   *   type: ActivityType.Action,
   *   title: "Deploy to production",
   *   assignee: {
   *     id: userId as ActorId,
   *     type: ActorType.User,
   *     name: "Alice"
   *   }
   * };
   * ```
   */
  assignee: Actor | null;
  /** Timestamp when the activity was marked as complete. Null if not completed. */
  done: Date | null;
  /**
   * Start time of a scheduled activity. Notes are not typically scheduled unless they're about specific times.
   * For recurring events, this represents the start of the first occurrence.
   * Can be a Date object for timed events or a date string in "YYYY-MM-DD" format for all-day events.
   *
   * **Activity Scheduling States** (for Actions):
   * - **Do Now** (current/actionable): When creating an Action, omitting `start` defaults to current time
   * - **Do Later** (future scheduled): Set `start` to a future Date or date string
   * - **Do Someday** (unscheduled backlog): Explicitly set `start: null`
   *
   * **Important for synced tasks**: When syncing unassigned backlog items from external systems,
   * set BOTH `start: null` AND `assignee: null` to create unscheduled, unassigned actions.
   *
   * @example
   * ```typescript
   * // "Do Now" - assigned to twist owner, actionable immediately
   * await this.tools.plot.createActivity({
   *   type: ActivityType.Action,
   *   title: "Urgent task"
   *   // start omitted → defaults to now
   *   // assignee omitted → defaults to twist owner
   * });
   *
   * // "Do Later" - scheduled for a specific time
   * await this.tools.plot.createActivity({
   *   type: ActivityType.Action,
   *   title: "Future task",
   *   start: new Date("2025-02-01")
   * });
   *
   * // "Do Someday" - unassigned backlog item (common for synced tasks)
   * await this.tools.plot.createActivity({
   *   type: ActivityType.Action,
   *   title: "Backlog task",
   *   start: null,      // Explicitly unscheduled
   *   assignee: null    // Explicitly unassigned
   * });
   * ```
   */
  start: Date | string | null;
  /**
   * End time of a scheduled activity. Notes are not typically scheduled unless they're about specific times.
   * For recurring events, this represents the end of the first occurrence.
   * Can be a Date object for timed events or a date string in "YYYY-MM-DD" format for all-day events.
   * Null for tasks or activities without defined end times.
   */
  end: Date | string | null;
  /**
   * For recurring activities, the last occurrence date (inclusive).
   * Can be a Date object, date string in "YYYY-MM-DD" format, or null if recurring indefinitely.
   * When both recurrenceCount and recurrenceUntil are provided, recurrenceCount takes precedence.
   */
  recurrenceUntil: Date | string | null;
  /**
   * For recurring activities, the number of occurrences to generate.
   * Takes precedence over recurrenceUntil if both are provided.
   * Null for non-recurring activities or indefinite recurrence.
   */
  recurrenceCount: number | null;
  /** The priority context this activity belongs to */
  priority: Priority;
  /** Recurrence rule in RFC 5545 RRULE format (e.g., "FREQ=WEEKLY;BYDAY=MO,WE,FR") */
  recurrenceRule: string | null;
  /** Array of dates to exclude from the recurrence pattern */
  recurrenceExdates: Date[] | null;
  /** Metadata about the activity, typically from an external system that created it */
  meta: ActivityMeta | null;
};

export type ActivityWithNotes = Activity & {
  notes: Note[];
};

export type NewActivityWithNotes = NewActivity & {
  notes: Omit<NewNote, "activity">[];
};

/**
 * Represents a specific instance of a recurring activity.
 * All field values are computed by merging the recurring activity's
 * defaults with any occurrence-specific overrides.
 */
export type ActivityOccurrence = {
  /**
   * Original date/datetime of this occurrence.
   * Use start for the occurrence's current start time.
   * Format: Date object or "YYYY-MM-DD" for all-day events.
   */
  occurrence: Date | string;

  /**
   * The recurring activity of which this is an occurrence.
   */
  activity: Activity;

  /**
   * Effective values for this occurrence (series defaults + overrides).
   * These are the actual values that apply to this specific instance.
   */
  start: Date | string;
  end: Date | string | null;
  done: Date | null;
  title: string;
  /**
   * Meta is merged, with the occurrence's meta taking precedence.
   */
  meta: ActivityMeta | null;

  /**
   * Tags for this occurrence (merged with the recurring tags).
   */
  tags: Tags;

  /**
   * True if the occurrence is archived.
   */
  archived: boolean;
};

/**
 * Type for creating or updating activity occurrences.
 *
 * Follows the same pattern as Activity/NewActivity:
 * - Required fields: `occurrence` (key) and `start` (for scheduling)
 * - Optional fields: All others from ActivityOccurrence
 * - Additional fields: `twistTags` for add/remove, `unread` for notification control
 *
 * @example
 * ```typescript
 * const activity: NewActivity = {
 *   type: ActivityType.Event,
 *   recurrenceRule: "FREQ=WEEKLY;BYDAY=MO",
 *   occurrences: [
 *     {
 *       occurrence: new Date("2025-01-27T14:00:00Z"),
 *       start: new Date("2025-01-27T14:00:00Z"),
 *       tags: { [Tag.Skip]: [user] }
 *     }
 *   ]
 * };
 * ```
 */
export type NewActivityOccurrence = Pick<
  ActivityOccurrence,
  "occurrence" | "start"
> &
  Partial<
    Omit<ActivityOccurrence, "occurrence" | "start" | "activity" | "tags">
  > & {
    /**
     * Tags specific to this occurrence.
     * These replace any recurrence-level tags for this occurrence.
     */
    tags?: NewTags;

    /**
     * Add or remove the twist's tags on this occurrence.
     * Maps tag ID to boolean: true = add tag, false = remove tag.
     */
    twistTags?: Partial<Record<Tag, boolean>>;

    /**
     * Whether this occurrence should be marked as unread for users.
     * - undefined/omitted (default): Occurrence is unread for users, except auto-marked
     *   as read for the author if they are the twist owner (user)
     * - true: Occurrence is explicitly unread for ALL users (use sparingly)
     * - false: Occurrence is marked as read for all users
     *
     * For the default behavior, omit this field entirely.
     * Use false for initial sync to avoid marking historical items as unread.
     */
    unread?: boolean;
  };

/**
 * Inline type for creating/updating occurrences within NewActivity/ActivityUpdate.
 * Used to specify occurrence-specific overrides when creating or updating a recurring activity.
 */
export type ActivityOccurrenceUpdate = Pick<
  NewActivityOccurrence,
  "occurrence"
> &
  Partial<Omit<NewActivityOccurrence, "occurrence" | "activity">>;

/**
 * Configuration for automatic priority selection based on activity similarity.
 *
 * Maps activity fields to scoring weights or required exact matches:
 * - Number value: Maximum score for similarity matching on this field
 * - `true` value: Required exact match - activities must match exactly or be excluded
 *
 * Scoring rules:
 * - content: Uses vector similarity on activity embedding (cosine similarity)
 * - type: Exact match on ActivityType
 * - mentions: Percentage of existing activity's mentions that appear in new activity
 * - meta.field: Exact match on top-level meta fields (e.g., "meta.sourceId")
 *
 * When content is `true`, applies a strong similarity threshold to ensure only close matches.
 * Default (when neither priority nor pickPriority specified): `{content: true}`
 *
 * @example
 * ```typescript
 * // Require exact content match with strong similarity
 * pickPriority: { content: true }
 *
 * // Score based on content (max 100 points) and require exact type match
 * pickPriority: { content: 100, type: true }
 *
 * // Match on meta and score content
 * pickPriority: { "meta.projectId": true, content: 50 }
 * ```
 */
export type PickPriorityConfig = {
  content?: number | true;
  type?: number | true;
  mentions?: number | true;
  [key: `meta.${string}`]: number | true;
};

/**
 * Type for creating new activities.
 *
 * Requires only the activity type, with all other fields optional.
 * The author will be automatically assigned by the Plot system based on
 * the current execution context. The ID can be optionally provided by
 * tools for tracking and update detection purposes.
 *
 * **Important: Defaults for Actions**
 *
 * When creating an Activity of type `Action`:
 * - **`start` omitted** → Defaults to current time (now) → "Do Now"
 * - **`assignee` omitted** → Defaults to twist owner → Assigned action
 *
 * To create unassigned backlog items (common for synced tasks), you MUST explicitly set BOTH:
 * - `start: null` → "Do Someday" (unscheduled)
 * - `assignee: null` → Unassigned
 *
 * **Scheduling States**:
 * - **"Do Now"** (actionable today): Omit `start` or set to current time
 * - **"Do Later"** (scheduled): Set `start` to a future Date
 * - **"Do Someday"** (backlog): Set `start: null`
 *
 * Priority can be specified in three ways:
 * 1. Explicit priority: `priority: { id: "..." }` - Use specific priority (disables pickPriority)
 * 2. Pick priority config: `pickPriority: { ... }` - Auto-select based on similarity
 * 3. Neither: Defaults to `pickPriority: { content: true }` for automatic matching
 *
 * @example
 * ```typescript
 * // "Do Now" - Assigned to twist owner, actionable immediately
 * const urgentTask: NewActivity = {
 *   type: ActivityType.Action,
 *   title: "Review pull request"
 *   // start omitted → defaults to now
 *   // assignee omitted → defaults to twist owner
 * };
 *
 * // "Do Someday" - UNASSIGNED backlog item (for synced tasks)
 * const backlogTask: NewActivity = {
 *   type: ActivityType.Action,
 *   title: "Refactor user service",
 *   start: null,      // Must explicitly set to null
 *   assignee: null    // Must explicitly set to null
 * };
 *
 * // "Do Later" - Scheduled for specific date
 * const futureTask: NewActivity = {
 *   type: ActivityType.Action,
 *   title: "Prepare Q1 review",
 *   start: new Date("2025-03-15")
 * };
 *
 * // Note (typically unscheduled)
 * const note: NewActivity = {
 *   type: ActivityType.Note,
 *   title: "Meeting notes",
 *   content: "Discussed Q4 roadmap...",
 *   start: null  // Notes typically don't have scheduled times
 * };
 *
 * // Event (always has explicit start/end times)
 * const event: NewActivity = {
 *   type: ActivityType.Event,
 *   title: "Team standup",
 *   start: new Date("2025-01-15T10:00:00"),
 *   end: new Date("2025-01-15T10:30:00")
 * };
 * ```
 */
export type NewActivity = Pick<Activity, "type"> &
  Partial<
    Omit<
      Activity,
      | "author"
      | "assignee"
      | "type"
      | "priority"
      | "tags"
      | "mentions"
      | "id"
      | "source"
    >
  > &
  (
    | {
        /**
         * Unique identifier for the activity, generated by Uuid.Generate().
         * Specifying an ID allows tools to track and upsert activities.
         */
        id: Uuid;
      }
    | {
        /**
         * Canonical URL for the item in an external system.
         * For example, https://acme.atlassian.net/browse/PROJ-42 could represent a Jira issue.
         * When set, it uniquely identifies the activity within a priority tree. This performs
         * an upsert.
         */
        source: string;
      }
    | {
        /* Neither id nor source is required. An id will be generated and returned. */
      }
  ) &
  (
    | {
        /** Explicit priority (required when specified) - disables automatic priority matching */
        priority: Pick<Priority, "id">;
      }
    | {
        /** Configuration for automatic priority selection based on similarity */
        pickPriority?: PickPriorityConfig;
      }
  ) & {
    /**
     * The person that created the item. By default, it will be the twist itself.
     */
    author?: NewActor;

    /**
     * The person that assigned to the item.
     */
    assignee?: NewActor | null;

    /**
     * All tags to set on the new activity.
     */
    tags?: NewTags;

    /**
     * Whether the activity should be marked as unread for users.
     * - undefined/omitted (default): Activity is unread for users, except auto-marked
     *   as read for the author if they are the twist owner (user)
     * - true: Activity is explicitly unread for ALL users (use sparingly)
     * - false: Activity is marked as read for all users in the priority at creation time
     *
     * For the default behavior, omit this field entirely.
     * Use false for initial sync to avoid marking historical items as unread.
     */
    unread?: boolean;

    /**
     * Whether the activity is archived.
     * - true: Archive the activity
     * - false: Unarchive the activity
     * - undefined (default): Preserve current archive state
     *
     * Best practice: Set to false during initial syncs to ensure activities
     * are unarchived. Omit during incremental syncs to preserve user's choice.
     */
    archived?: boolean;

    /**
     * Optional preview content for the activity. Can be Markdown formatted.
     * The preview will be automatically generated from this content (truncated to 100 chars).
     *
     * - string: Use this content for preview generation
     * - null: Explicitly disable preview (no preview will be shown)
     * - undefined (default): Fall back to legacy behavior (generate from first note with content)
     *
     * This field is write-only and won't be returned when reading activities.
     */
    preview?: string | null;

    /**
     * Create or update specific occurrences of a recurring activity.
     * Each entry specifies overrides for a specific occurrence.
     *
     * When occurrence matches the recurrence rule but only tags are specified,
     * the occurrence is created with just tags in activity_tag.occurrence (no activity_exception).
     *
     * When any other field is specified, creates/updates an activity_exception row.
     *
     * @example
     * ```typescript
     * // Create recurring event with per-occurrence RSVPs
     * const meeting: NewActivity = {
     *   type: ActivityType.Event,
     *   recurrenceRule: "FREQ=WEEKLY;BYDAY=MO",
     *   start: new Date("2025-01-20T14:00:00Z"),
     *   duration: 1800000, // 30 minutes
     *   occurrences: [
     *     {
     *       occurrence: new Date("2025-01-27T14:00:00Z"),
     *       tags: { [Tag.Skip]: [{ email: "user@example.com" }] }
     *     },
     *     {
     *       occurrence: new Date("2025-02-03T14:00:00Z"),
     *       start: new Date("2025-02-03T15:00:00Z"), // Reschedule this one
     *       tags: { [Tag.Attend]: [{ email: "user@example.com" }] }
     *     }
     *   ]
     * };
     * ```
     */
    occurrences?: NewActivityOccurrence[];

    /**
     * Dates to add to the recurrence exclusion list.
     * These are merged with existing exdates. Use this for incremental updates
     * (e.g., cancelling a single occurrence) instead of replacing the full list.
     */
    addRecurrenceExdates?: Date[];

    /**
     * Dates to remove from the recurrence exclusion list.
     * Use this to "uncancel" a previously excluded occurrence.
     */
    removeRecurrenceExdates?: Date[];
  };

export type ActivityUpdate = (
  | {
      /**
       * Unique identifier for the activity.
       */
      id: Uuid;
    }
  | {
      /**
       * Canonical URL for the item in an external system.
       */
      source: string;
    }
) &
  Partial<
    Pick<
      Activity,
      | "type"
      | "kind"
      | "start"
      | "end"
      | "done"
      | "title"
      | "assignee"
      | "private"
      | "archived"
      | "meta"
      | "recurrenceRule"
      | "recurrenceExdates"
      | "recurrenceUntil"
      | "recurrenceCount"
    >
  > & {
    /**
     * Tags to change on the activity. Use an empty array of NewActor to remove a tag.
     * Use twistTags to add/remove the twist from tags to avoid clearing other actors' tags.
     */
    tags?: NewTags;

    /**
     * Add or remove the twist's tags.
     * Maps tag ID to boolean: true = add tag, false = remove tag.
     * This is allowed on all activities the twist has access to.
     */
    twistTags?: Partial<Record<Tag, boolean>>;

    /**
     * Optional preview content for the activity. Can be Markdown formatted.
     * The preview will be automatically generated from this content (truncated to 100 chars).
     *
     * - string: Use this content for preview generation
     * - null: Explicitly disable preview (no preview will be shown)
     * - undefined (omitted): Preserve current preview value
     *
     * This field is write-only and won't be returned when reading activities.
     */
    preview?: string | null;

    /**
     * Create or update specific occurrences of this recurring activity.
     * Each entry specifies overrides for a specific occurrence.
     *
     * Setting a field to null reverts it to the series default.
     * Omitting a field leaves it unchanged.
     *
     * @example
     * ```typescript
     * // Update RSVPs for specific occurrences
     * await plot.updateActivity({
     *   id: meetingId,
     *   occurrences: [
     *     {
     *       occurrence: new Date("2025-01-27T14:00:00Z"),
     *       tags: { [Tag.Skip]: [user] }
     *     },
     *     {
     *       occurrence: new Date("2025-02-03T14:00:00Z"),
     *       tags: { [Tag.Attend]: [user] }
     *     },
     *     {
     *       occurrence: new Date("2025-02-10T14:00:00Z"),
     *       archived: true  // Cancel this occurrence
     *     }
     *   ]
     * });
     * ```
     */
    occurrences?: (NewActivityOccurrence | ActivityOccurrenceUpdate)[];

    /**
     * Dates to add to the recurrence exclusion list.
     * These are merged with existing exdates. Use this for incremental updates
     * (e.g., cancelling a single occurrence) instead of replacing the full list.
     */
    addRecurrenceExdates?: Date[];

    /**
     * Dates to remove from the recurrence exclusion list.
     * Use this to "uncancel" a previously excluded occurrence.
     */
    removeRecurrenceExdates?: Date[];
  };

/**
 * Represents a note within an activity.
 *
 * Notes contain the detailed content (note text, links) associated with an activity.
 * They are always ordered by creation time within their parent activity.
 */
export type Note = ActivityCommon & {
  /**
   * Globally unique, stable identifier for the note within its activity.
   * Can be used to upsert without knowing the id.
   *
   * Use one of these patterns:
   *   - Hardcoded semantic keys for fixed note types: "description", "cancellation"
   *   - External service IDs for dynamic collections: `comment:${immutableId}`
   *
   * Examples:
   *   - `"description"` (for a Jira issue's description note)
   *   - `"comment:12345"` (for a specific comment by ID)
   *   - `"gmail:msg:18d4e5f2a3b1c9d7"` (for a Gmail message within a thread)
   *
   * ⚠️ Ensure IDs are immutable - avoid human-readable slugs or titles.
   */
  key: string | null;
  /** The parent activity this note belongs to */
  activity: Activity;
  /** Primary content for the note (markdown) */
  content: string | null;
  /** Array of interactive links attached to the note */
  links: Array<ActivityLink> | null;
};

/**
 * Type for creating new notes.
 *
 * Requires the activity reference, with all other fields optional.
 * Can provide id, key, or neither for note identification:
 * - id: Provide a specific UUID for the note
 * - key: Provide an external identifier for upsert within the activity
 * - neither: A new note with auto-generated UUID will be created
 */
export type NewNote = Partial<
  Omit<Note, "author" | "activity" | "tags" | "mentions" | "id" | "key">
> &
  ({ id: Uuid } | { key: string } | {}) & {
    /** Reference to the parent activity (required) */
    activity:
      | Pick<Activity, "id">
      | {
          source: string;
        };

    /**
     * The person that created the item, or leave undefined to use the twist as author.
     */
    author?: NewActor;

    /**
     * Format of the note content. Determines how the note is processed:
     * - 'text': Plain text that will be converted to markdown (auto-links URLs, preserves line breaks)
     * - 'markdown': Already in markdown format (default, no conversion)
     * - 'html': HTML content that will be converted to markdown
     */
    contentType?: ContentType;

    /**
     * Tags to change on the activity. Use an empty array of NewActor to remove a tag.
     * Use twistTags to add/remove the twist from tags to avoid clearing other actors' tags.
     */
    tags?: NewTags;

    /**
     * Change the mentions on the note.
     */
    mentions?: NewActor[];

    /**
     * Whether the note should mark the parent activity as unread for users.
     * - undefined/omitted (default): Activity is unread for users, except auto-marked
     *   as read for the author if they are the twist owner (user)
     * - true: Activity is explicitly unread for ALL users (use sparingly)
     * - false: Activity is marked as read for all users in the priority at note creation time
     *
     * For the default behavior, omit this field entirely.
     * Use false for initial sync to avoid marking historical items as unread.
     */
    unread?: boolean;
  };

/**
 * Type for updating existing notes.
 * Must provide either id or key to identify the note to update.
 */
export type NoteUpdate = ({ id: Uuid; key?: string } | { key: string }) &
  Partial<Pick<Note, "private" | "archived" | "content" | "links">> & {
    /**
     * Format of the note content. Determines how the note is processed:
     * - 'text': Plain text that will be converted to markdown (auto-links URLs, preserves line breaks)
     * - 'markdown': Already in markdown format (default, no conversion)
     * - 'html': HTML content that will be converted to markdown
     */
    contentType?: ContentType;

    /**
     * Tags to change on the note. Use an empty array of NewActor to remove a tag.
     * Use twistTags to add/remove the twist from tags to avoid clearing other actors' tags.
     */
    tags?: NewTags;

    /**
     * Add or remove the twist's tags.
     * Maps tag ID to boolean: true = add tag, false = remove tag.
     * This is allowed on all notes the twist has access to.
     */
    twistTags?: Partial<Record<Tag, boolean>>;

    /**
     * Change the mentions on the note.
     */
    mentions?: NewActor[];
  };

/**
 * Represents an actor in Plot - a user, contact, or twist.
 *
 * Actors can be associated with activities as authors, assignees, or mentions.
 * The email field is only included when ContactAccess.Read permission is granted.
 *
 * @example
 * ```typescript
 * const actor: Actor = {
 *   id: "f0ffd5f8-1635-4b13-9532-35f97446db90" as ActorId,
 *   type: ActorType.Contact,
 *   email: "john.doe@example.com",  // Only if ContactAccess.Read
 *   name: "John Doe"
 * };
 * ```
 */
export type Actor = {
  /** Unique identifier for the actor */
  id: ActorId;
  /** Type of actor (User, Contact, or Twist) */
  type: ActorType;
  /**
   * Email address (only included with ContactAccess.Read permission).
   * - `undefined`: No permission to read email
   * - `null`: Permission granted but email not set
   * - `string`: Email address
   */
  email?: string | null;
  /**
   * Display name.
   * - `undefined`: Not included due to permissions
   * - `null`: Not set
   * - `string`: Display name
   */
  name?: string | null;
};

/**
 * An existing or new contact.
 */
export type NewActor =
  | {
      /** Unique identifier for the actor */
      id: ActorId;
    }
  | NewContact;

/**
 * Enumeration of author types that can create activities.
 *
 * The author type affects how activities are displayed and processed
 * within the Plot system.
 */
export enum ActorType {
  /** Activities created by human users */
  User,
  /** Activities created by external contacts */
  Contact,
  /** Activities created by automated twists */
  Twist,
}

/**
 * Represents contact information for creating a new contact.
 *
 * Contacts are used throughout Plot for representing people associated
 * with activities, such as event attendees or task assignees.
 *
 * @example
 * ```typescript
 * const newContact: NewContact = {
 *   email: "john.doe@example.com",
 *   name: "John Doe",
 *   avatar: "https://avatar.example.com/john.jpg"
 * };
 * ```
 */
export type NewContact = {
  /** Email address of the contact (required) */
  email: string;
  /** Optional display name for the contact */
  name?: string;
  /** Optional avatar image URL for the contact */
  avatar?: string;
};

export type ContentType = "text" | "markdown" | "html";
