// GENERATED FILE — do not edit by hand.
// Source: https://unicode.org/Public/emoji/15.1/emoji-test.txt
// Regenerate via scripts/gen_emoji_data.py (see commit history).
//
// Emits two constants used by reaction_picker.dart:
//  - kUnicodeEmojiCategories: ordered category -> list of emoji.
//  - kUnicodeEmojiLabels:     emoji -> search keywords (CLDR name words).
//
// Skin-tone variants and the "Component" group are intentionally
// excluded from the picker — they swamp the grid without adding much.

const Map<String, List<String>> kUnicodeEmojiCategories = {
  'Smileys & Emotion': [
    '😀', '😃', '😄', '😁', '😆', '😅', '🤣', '😂', '🙂', '🙃',
    '🫠', '😉', '😊', '😇', '🥰', '😍', '🤩', '😘', '😗', '☺️',
    '😚', '😙', '🥲', '😋', '😛', '😜', '🤪', '😝', '🤑', '🤗',
    '🤭', '🫢', '🫣', '🤫', '🤔', '🫡', '🤐', '🤨', '😐', '😑',
    '😶', '🫥', '😶‍🌫️', '😏', '😒', '🙄', '😬', '😮‍💨', '🤥', '🫨',
    '🙂‍↔️', '🙂‍↕️', '😌', '😔', '😪', '🤤', '😴', '😷', '🤒', '🤕',
    '🤢', '🤮', '🤧', '🥵', '🥶', '🥴', '😵', '😵‍💫', '🤯', '🤠',
    '🥳', '🥸', '😎', '🤓', '🧐', '😕', '🫤', '😟', '🙁', '☹️',
    '😮', '😯', '😲', '😳', '🥺', '🥹', '😦', '😧', '😨', '😰',
    '😥', '😢', '😭', '😱', '😖', '😣', '😞', '😓', '😩', '😫',
    '🥱', '😤', '😡', '😠', '🤬', '😈', '👿', '💀', '☠️', '💩',
    '🤡', '👹', '👺', '👻', '👽', '👾', '🤖', '😺', '😸', '😹',
    '😻', '😼', '😽', '🙀', '😿', '😾', '🙈', '🙉', '🙊', '💌',
    '💘', '💝', '💖', '💗', '💓', '💞', '💕', '💟', '❣️', '💔',
    '❤️‍🔥', '❤️‍🩹', '❤️', '🩷', '🧡', '💛', '💚', '💙', '🩵', '💜',
    '🤎', '🖤', '🩶', '🤍', '💋', '💯', '💢', '💥', '💫', '💦',
    '💨', '🕳️', '💬', '👁️‍🗨️', '🗨️', '🗯️', '💭', '💤',
  ],
  'People & Body': [
    '👋', '🤚', '🖐️', '✋', '🖖', '🫱', '🫲', '🫳', '🫴', '🫷',
    '🫸', '👌', '🤌', '🤏', '✌️', '🤞', '🫰', '🤟', '🤘', '🤙',
    '👈', '👉', '👆', '🖕', '👇', '☝️', '🫵', '👍', '👎', '✊',
    '👊', '🤛', '🤜', '👏', '🙌', '🫶', '👐', '🤲', '🤝', '🙏',
    '✍️', '💅', '🤳', '💪', '🦾', '🦿', '🦵', '🦶', '👂', '🦻',
    '👃', '🧠', '🫀', '🫁', '🦷', '🦴', '👀', '👁️', '👅', '👄',
    '🫦', '👶', '🧒', '👦', '👧', '🧑', '👱', '👨', '🧔', '🧔‍♂️',
    '🧔‍♀️', '👨‍🦰', '👨‍🦱', '👨‍🦳', '👨‍🦲', '👩', '👩‍🦰', '🧑‍🦰', '👩‍🦱', '🧑‍🦱',
    '👩‍🦳', '🧑‍🦳', '👩‍🦲', '🧑‍🦲', '👱‍♀️', '👱‍♂️', '🧓', '👴', '👵', '🙍',
    '🙍‍♂️', '🙍‍♀️', '🙎', '🙎‍♂️', '🙎‍♀️', '🙅', '🙅‍♂️', '🙅‍♀️', '🙆', '🙆‍♂️',
    '🙆‍♀️', '💁', '💁‍♂️', '💁‍♀️', '🙋', '🙋‍♂️', '🙋‍♀️', '🧏', '🧏‍♂️', '🧏‍♀️',
    '🙇', '🙇‍♂️', '🙇‍♀️', '🤦', '🤦‍♂️', '🤦‍♀️', '🤷', '🤷‍♂️', '🤷‍♀️', '🧑‍⚕️',
    '👨‍⚕️', '👩‍⚕️', '🧑‍🎓', '👨‍🎓', '👩‍🎓', '🧑‍🏫', '👨‍🏫', '👩‍🏫', '🧑‍⚖️', '👨‍⚖️',
    '👩‍⚖️', '🧑‍🌾', '👨‍🌾', '👩‍🌾', '🧑‍🍳', '👨‍🍳', '👩‍🍳', '🧑‍🔧', '👨‍🔧', '👩‍🔧',
    '🧑‍🏭', '👨‍🏭', '👩‍🏭', '🧑‍💼', '👨‍💼', '👩‍💼', '🧑‍🔬', '👨‍🔬', '👩‍🔬', '🧑‍💻',
    '👨‍💻', '👩‍💻', '🧑‍🎤', '👨‍🎤', '👩‍🎤', '🧑‍🎨', '👨‍🎨', '👩‍🎨', '🧑‍✈️', '👨‍✈️',
    '👩‍✈️', '🧑‍🚀', '👨‍🚀', '👩‍🚀', '🧑‍🚒', '👨‍🚒', '👩‍🚒', '👮', '👮‍♂️', '👮‍♀️',
    '🕵️', '🕵️‍♂️', '🕵️‍♀️', '💂', '💂‍♂️', '💂‍♀️', '🥷', '👷', '👷‍♂️', '👷‍♀️',
    '🫅', '🤴', '👸', '👳', '👳‍♂️', '👳‍♀️', '👲', '🧕', '🤵', '🤵‍♂️',
    '🤵‍♀️', '👰', '👰‍♂️', '👰‍♀️', '🤰', '🫃', '🫄', '🤱', '👩‍🍼', '👨‍🍼',
    '🧑‍🍼', '👼', '🎅', '🤶', '🧑‍🎄', '🦸', '🦸‍♂️', '🦸‍♀️', '🦹', '🦹‍♂️',
    '🦹‍♀️', '🧙', '🧙‍♂️', '🧙‍♀️', '🧚', '🧚‍♂️', '🧚‍♀️', '🧛', '🧛‍♂️', '🧛‍♀️',
    '🧜', '🧜‍♂️', '🧜‍♀️', '🧝', '🧝‍♂️', '🧝‍♀️', '🧞', '🧞‍♂️', '🧞‍♀️', '🧟',
    '🧟‍♂️', '🧟‍♀️', '🧌', '💆', '💆‍♂️', '💆‍♀️', '💇', '💇‍♂️', '💇‍♀️', '🚶',
    '🚶‍♂️', '🚶‍♀️', '🚶‍➡️', '🚶‍♀️‍➡️', '🚶‍♂️‍➡️', '🧍', '🧍‍♂️', '🧍‍♀️', '🧎', '🧎‍♂️',
    '🧎‍♀️', '🧎‍➡️', '🧎‍♀️‍➡️', '🧎‍♂️‍➡️', '🧑‍🦯', '🧑‍🦯‍➡️', '👨‍🦯', '👨‍🦯‍➡️', '👩‍🦯', '👩‍🦯‍➡️',
    '🧑‍🦼', '🧑‍🦼‍➡️', '👨‍🦼', '👨‍🦼‍➡️', '👩‍🦼', '👩‍🦼‍➡️', '🧑‍🦽', '🧑‍🦽‍➡️', '👨‍🦽', '👨‍🦽‍➡️',
    '👩‍🦽', '👩‍🦽‍➡️', '🏃', '🏃‍♂️', '🏃‍♀️', '🏃‍➡️', '🏃‍♀️‍➡️', '🏃‍♂️‍➡️', '💃', '🕺',
    '🕴️', '👯', '👯‍♂️', '👯‍♀️', '🧖', '🧖‍♂️', '🧖‍♀️', '🧗', '🧗‍♂️', '🧗‍♀️',
    '🤺', '🏇', '⛷️', '🏂', '🏌️', '🏌️‍♂️', '🏌️‍♀️', '🏄', '🏄‍♂️', '🏄‍♀️',
    '🚣', '🚣‍♂️', '🚣‍♀️', '🏊', '🏊‍♂️', '🏊‍♀️', '⛹️', '⛹️‍♂️', '⛹️‍♀️', '🏋️',
    '🏋️‍♂️', '🏋️‍♀️', '🚴', '🚴‍♂️', '🚴‍♀️', '🚵', '🚵‍♂️', '🚵‍♀️', '🤸', '🤸‍♂️',
    '🤸‍♀️', '🤼', '🤼‍♂️', '🤼‍♀️', '🤽', '🤽‍♂️', '🤽‍♀️', '🤾', '🤾‍♂️', '🤾‍♀️',
    '🤹', '🤹‍♂️', '🤹‍♀️', '🧘', '🧘‍♂️', '🧘‍♀️', '🛀', '🛌', '🧑‍🤝‍🧑', '👭',
    '👫', '👬', '💏', '👩‍❤️‍💋‍👨', '👨‍❤️‍💋‍👨', '👩‍❤️‍💋‍👩', '💑', '👩‍❤️‍👨', '👨‍❤️‍👨', '👩‍❤️‍👩',
    '👨‍👩‍👦', '👨‍👩‍👧', '👨‍👩‍👧‍👦', '👨‍👩‍👦‍👦', '👨‍👩‍👧‍👧', '👨‍👨‍👦', '👨‍👨‍👧', '👨‍👨‍👧‍👦', '👨‍👨‍👦‍👦', '👨‍👨‍👧‍👧',
    '👩‍👩‍👦', '👩‍👩‍👧', '👩‍👩‍👧‍👦', '👩‍👩‍👦‍👦', '👩‍👩‍👧‍👧', '👨‍👦', '👨‍👦‍👦', '👨‍👧', '👨‍👧‍👦', '👨‍👧‍👧',
    '👩‍👦', '👩‍👦‍👦', '👩‍👧', '👩‍👧‍👦', '👩‍👧‍👧', '🗣️', '👤', '👥', '🫂', '👪',
    '🧑‍🧑‍🧒', '🧑‍🧑‍🧒‍🧒', '🧑‍🧒', '🧑‍🧒‍🧒', '👣',
  ],
  'Animals & Nature': [
    '🐵', '🐒', '🦍', '🦧', '🐶', '🐕', '🦮', '🐕‍🦺', '🐩', '🐺',
    '🦊', '🦝', '🐱', '🐈', '🐈‍⬛', '🦁', '🐯', '🐅', '🐆', '🐴',
    '🫎', '🫏', '🐎', '🦄', '🦓', '🦌', '🦬', '🐮', '🐂', '🐃',
    '🐄', '🐷', '🐖', '🐗', '🐽', '🐏', '🐑', '🐐', '🐪', '🐫',
    '🦙', '🦒', '🐘', '🦣', '🦏', '🦛', '🐭', '🐁', '🐀', '🐹',
    '🐰', '🐇', '🐿️', '🦫', '🦔', '🦇', '🐻', '🐻‍❄️', '🐨', '🐼',
    '🦥', '🦦', '🦨', '🦘', '🦡', '🐾', '🦃', '🐔', '🐓', '🐣',
    '🐤', '🐥', '🐦', '🐧', '🕊️', '🦅', '🦆', '🦢', '🦉', '🦤',
    '🪶', '🦩', '🦚', '🦜', '🪽', '🐦‍⬛', '🪿', '🐦‍🔥', '🐸', '🐊',
    '🐢', '🦎', '🐍', '🐲', '🐉', '🦕', '🦖', '🐳', '🐋', '🐬',
    '🦭', '🐟', '🐠', '🐡', '🦈', '🐙', '🐚', '🪸', '🪼', '🐌',
    '🦋', '🐛', '🐜', '🐝', '🪲', '🐞', '🦗', '🪳', '🕷️', '🕸️',
    '🦂', '🦟', '🪰', '🪱', '🦠', '💐', '🌸', '💮', '🪷', '🏵️',
    '🌹', '🥀', '🌺', '🌻', '🌼', '🌷', '🪻', '🌱', '🪴', '🌲',
    '🌳', '🌴', '🌵', '🌾', '🌿', '☘️', '🍀', '🍁', '🍂', '🍃',
    '🪹', '🪺', '🍄',
  ],
  'Food & Drink': [
    '🍇', '🍈', '🍉', '🍊', '🍋', '🍋‍🟩', '🍌', '🍍', '🥭', '🍎',
    '🍏', '🍐', '🍑', '🍒', '🍓', '🫐', '🥝', '🍅', '🫒', '🥥',
    '🥑', '🍆', '🥔', '🥕', '🌽', '🌶️', '🫑', '🥒', '🥬', '🥦',
    '🧄', '🧅', '🥜', '🫘', '🌰', '🫚', '🫛', '🍄‍🟫', '🍞', '🥐',
    '🥖', '🫓', '🥨', '🥯', '🥞', '🧇', '🧀', '🍖', '🍗', '🥩',
    '🥓', '🍔', '🍟', '🍕', '🌭', '🥪', '🌮', '🌯', '🫔', '🥙',
    '🧆', '🥚', '🍳', '🥘', '🍲', '🫕', '🥣', '🥗', '🍿', '🧈',
    '🧂', '🥫', '🍱', '🍘', '🍙', '🍚', '🍛', '🍜', '🍝', '🍠',
    '🍢', '🍣', '🍤', '🍥', '🥮', '🍡', '🥟', '🥠', '🥡', '🦀',
    '🦞', '🦐', '🦑', '🦪', '🍦', '🍧', '🍨', '🍩', '🍪', '🎂',
    '🍰', '🧁', '🥧', '🍫', '🍬', '🍭', '🍮', '🍯', '🍼', '🥛',
    '☕', '🫖', '🍵', '🍶', '🍾', '🍷', '🍸', '🍹', '🍺', '🍻',
    '🥂', '🥃', '🫗', '🥤', '🧋', '🧃', '🧉', '🧊', '🥢', '🍽️',
    '🍴', '🥄', '🔪', '🫙', '🏺',
  ],
  'Travel & Places': [
    '🌍', '🌎', '🌏', '🌐', '🗺️', '🗾', '🧭', '🏔️', '⛰️', '🌋',
    '🗻', '🏕️', '🏖️', '🏜️', '🏝️', '🏞️', '🏟️', '🏛️', '🏗️', '🧱',
    '🪨', '🪵', '🛖', '🏘️', '🏚️', '🏠', '🏡', '🏢', '🏣', '🏤',
    '🏥', '🏦', '🏨', '🏩', '🏪', '🏫', '🏬', '🏭', '🏯', '🏰',
    '💒', '🗼', '🗽', '⛪', '🕌', '🛕', '🕍', '⛩️', '🕋', '⛲',
    '⛺', '🌁', '🌃', '🏙️', '🌄', '🌅', '🌆', '🌇', '🌉', '♨️',
    '🎠', '🛝', '🎡', '🎢', '💈', '🎪', '🚂', '🚃', '🚄', '🚅',
    '🚆', '🚇', '🚈', '🚉', '🚊', '🚝', '🚞', '🚋', '🚌', '🚍',
    '🚎', '🚐', '🚑', '🚒', '🚓', '🚔', '🚕', '🚖', '🚗', '🚘',
    '🚙', '🛻', '🚚', '🚛', '🚜', '🏎️', '🏍️', '🛵', '🦽', '🦼',
    '🛺', '🚲', '🛴', '🛹', '🛼', '🚏', '🛣️', '🛤️', '🛢️', '⛽',
    '🛞', '🚨', '🚥', '🚦', '🛑', '🚧', '⚓', '🛟', '⛵', '🛶',
    '🚤', '🛳️', '⛴️', '🛥️', '🚢', '✈️', '🛩️', '🛫', '🛬', '🪂',
    '💺', '🚁', '🚟', '🚠', '🚡', '🛰️', '🚀', '🛸', '🛎️', '🧳',
    '⌛', '⏳', '⌚', '⏰', '⏱️', '⏲️', '🕰️', '🕛', '🕧', '🕐',
    '🕜', '🕑', '🕝', '🕒', '🕞', '🕓', '🕟', '🕔', '🕠', '🕕',
    '🕡', '🕖', '🕢', '🕗', '🕣', '🕘', '🕤', '🕙', '🕥', '🕚',
    '🕦', '🌑', '🌒', '🌓', '🌔', '🌕', '🌖', '🌗', '🌘', '🌙',
    '🌚', '🌛', '🌜', '🌡️', '☀️', '🌝', '🌞', '🪐', '⭐', '🌟',
    '🌠', '🌌', '☁️', '⛅', '⛈️', '🌤️', '🌥️', '🌦️', '🌧️', '🌨️',
    '🌩️', '🌪️', '🌫️', '🌬️', '🌀', '🌈', '🌂', '☂️', '☔', '⛱️',
    '⚡', '❄️', '☃️', '⛄', '☄️', '🔥', '💧', '🌊',
  ],
  'Activities': [
    '🎃', '🎄', '🎆', '🎇', '🧨', '✨', '🎈', '🎉', '🎊', '🎋',
    '🎍', '🎎', '🎏', '🎐', '🎑', '🧧', '🎀', '🎁', '🎗️', '🎟️',
    '🎫', '🎖️', '🏆', '🏅', '🥇', '🥈', '🥉', '⚽', '⚾', '🥎',
    '🏀', '🏐', '🏈', '🏉', '🎾', '🥏', '🎳', '🏏', '🏑', '🏒',
    '🥍', '🏓', '🏸', '🥊', '🥋', '🥅', '⛳', '⛸️', '🎣', '🤿',
    '🎽', '🎿', '🛷', '🥌', '🎯', '🪀', '🪁', '🔫', '🎱', '🔮',
    '🪄', '🎮', '🕹️', '🎰', '🎲', '🧩', '🧸', '🪅', '🪩', '🪆',
    '♠️', '♥️', '♦️', '♣️', '♟️', '🃏', '🀄', '🎴', '🎭', '🖼️',
    '🎨', '🧵', '🪡', '🧶', '🪢',
  ],
  'Objects': [
    '👓', '🕶️', '🥽', '🥼', '🦺', '👔', '👕', '👖', '🧣', '🧤',
    '🧥', '🧦', '👗', '👘', '🥻', '🩱', '🩲', '🩳', '👙', '👚',
    '🪭', '👛', '👜', '👝', '🛍️', '🎒', '🩴', '👞', '👟', '🥾',
    '🥿', '👠', '👡', '🩰', '👢', '🪮', '👑', '👒', '🎩', '🎓',
    '🧢', '🪖', '⛑️', '📿', '💄', '💍', '💎', '🔇', '🔈', '🔉',
    '🔊', '📢', '📣', '📯', '🔔', '🔕', '🎼', '🎵', '🎶', '🎙️',
    '🎚️', '🎛️', '🎤', '🎧', '📻', '🎷', '🪗', '🎸', '🎹', '🎺',
    '🎻', '🪕', '🥁', '🪘', '🪇', '🪈', '📱', '📲', '☎️', '📞',
    '📟', '📠', '🔋', '🪫', '🔌', '💻', '🖥️', '🖨️', '⌨️', '🖱️',
    '🖲️', '💽', '💾', '💿', '📀', '🧮', '🎥', '🎞️', '📽️', '🎬',
    '📺', '📷', '📸', '📹', '📼', '🔍', '🔎', '🕯️', '💡', '🔦',
    '🏮', '🪔', '📔', '📕', '📖', '📗', '📘', '📙', '📚', '📓',
    '📒', '📃', '📜', '📄', '📰', '🗞️', '📑', '🔖', '🏷️', '💰',
    '🪙', '💴', '💵', '💶', '💷', '💸', '💳', '🧾', '💹', '✉️',
    '📧', '📨', '📩', '📤', '📥', '📦', '📫', '📪', '📬', '📭',
    '📮', '🗳️', '✏️', '✒️', '🖋️', '🖊️', '🖌️', '🖍️', '📝', '💼',
    '📁', '📂', '🗂️', '📅', '📆', '🗒️', '🗓️', '📇', '📈', '📉',
    '📊', '📋', '📌', '📍', '📎', '🖇️', '📏', '📐', '✂️', '🗃️',
    '🗄️', '🗑️', '🔒', '🔓', '🔏', '🔐', '🔑', '🗝️', '🔨', '🪓',
    '⛏️', '⚒️', '🛠️', '🗡️', '⚔️', '💣', '🪃', '🏹', '🛡️', '🪚',
    '🔧', '🪛', '🔩', '⚙️', '🗜️', '⚖️', '🦯', '🔗', '⛓️‍💥', '⛓️',
    '🪝', '🧰', '🧲', '🪜', '⚗️', '🧪', '🧫', '🧬', '🔬', '🔭',
    '📡', '💉', '🩸', '💊', '🩹', '🩼', '🩺', '🩻', '🚪', '🛗',
    '🪞', '🪟', '🛏️', '🛋️', '🪑', '🚽', '🪠', '🚿', '🛁', '🪤',
    '🪒', '🧴', '🧷', '🧹', '🧺', '🧻', '🪣', '🧼', '🫧', '🪥',
    '🧽', '🧯', '🛒', '🚬', '⚰️', '🪦', '⚱️', '🧿', '🪬', '🗿',
    '🪧', '🪪',
  ],
  'Symbols': [
    '🏧', '🚮', '🚰', '♿', '🚹', '🚺', '🚻', '🚼', '🚾', '🛂',
    '🛃', '🛄', '🛅', '⚠️', '🚸', '⛔', '🚫', '🚳', '🚭', '🚯',
    '🚱', '🚷', '📵', '🔞', '☢️', '☣️', '⬆️', '↗️', '➡️', '↘️',
    '⬇️', '↙️', '⬅️', '↖️', '↕️', '↔️', '↩️', '↪️', '⤴️', '⤵️',
    '🔃', '🔄', '🔙', '🔚', '🔛', '🔜', '🔝', '🛐', '⚛️', '🕉️',
    '✡️', '☸️', '☯️', '✝️', '☦️', '☪️', '☮️', '🕎', '🔯', '🪯',
    '♈', '♉', '♊', '♋', '♌', '♍', '♎', '♏', '♐', '♑',
    '♒', '♓', '⛎', '🔀', '🔁', '🔂', '▶️', '⏩', '⏭️', '⏯️',
    '◀️', '⏪', '⏮️', '🔼', '⏫', '🔽', '⏬', '⏸️', '⏹️', '⏺️',
    '⏏️', '🎦', '🔅', '🔆', '📶', '🛜', '📳', '📴', '♀️', '♂️',
    '⚧️', '✖️', '➕', '➖', '➗', '🟰', '♾️', '‼️', '⁉️', '❓',
    '❔', '❕', '❗', '〰️', '💱', '💲', '⚕️', '♻️', '⚜️', '🔱',
    '📛', '🔰', '⭕', '✅', '☑️', '✔️', '❌', '❎', '➰', '➿',
    '〽️', '✳️', '✴️', '❇️', '©️', '®️', '™️', '#️⃣', '*️⃣', '0️⃣',
    '1️⃣', '2️⃣', '3️⃣', '4️⃣', '5️⃣', '6️⃣', '7️⃣', '8️⃣', '9️⃣', '🔟',
    '🔠', '🔡', '🔢', '🔣', '🔤', '🅰️', '🆎', '🅱️', '🆑', '🆒',
    '🆓', 'ℹ️', '🆔', 'Ⓜ️', '🆕', '🆖', '🅾️', '🆗', '🅿️', '🆘',
    '🆙', '🆚', '🈁', '🈂️', '🈷️', '🈶', '🈯', '🉐', '🈹', '🈚',
    '🈲', '🉑', '🈸', '🈴', '🈳', '㊗️', '㊙️', '🈺', '🈵', '🔴',
    '🟠', '🟡', '🟢', '🔵', '🟣', '🟤', '⚫', '⚪', '🟥', '🟧',
    '🟨', '🟩', '🟦', '🟪', '🟫', '⬛', '⬜', '◼️', '◻️', '◾',
    '◽', '▪️', '▫️', '🔶', '🔷', '🔸', '🔹', '🔺', '🔻', '💠',
    '🔘', '🔳', '🔲',
  ],
  'Flags': [
    '🏁', '🚩', '🎌', '🏴', '🏳️', '🏳️‍🌈', '🏳️‍⚧️', '🏴‍☠️', '🇦🇨', '🇦🇩',
    '🇦🇪', '🇦🇫', '🇦🇬', '🇦🇮', '🇦🇱', '🇦🇲', '🇦🇴', '🇦🇶', '🇦🇷', '🇦🇸',
    '🇦🇹', '🇦🇺', '🇦🇼', '🇦🇽', '🇦🇿', '🇧🇦', '🇧🇧', '🇧🇩', '🇧🇪', '🇧🇫',
    '🇧🇬', '🇧🇭', '🇧🇮', '🇧🇯', '🇧🇱', '🇧🇲', '🇧🇳', '🇧🇴', '🇧🇶', '🇧🇷',
    '🇧🇸', '🇧🇹', '🇧🇻', '🇧🇼', '🇧🇾', '🇧🇿', '🇨🇦', '🇨🇨', '🇨🇩', '🇨🇫',
    '🇨🇬', '🇨🇭', '🇨🇮', '🇨🇰', '🇨🇱', '🇨🇲', '🇨🇳', '🇨🇴', '🇨🇵', '🇨🇷',
    '🇨🇺', '🇨🇻', '🇨🇼', '🇨🇽', '🇨🇾', '🇨🇿', '🇩🇪', '🇩🇬', '🇩🇯', '🇩🇰',
    '🇩🇲', '🇩🇴', '🇩🇿', '🇪🇦', '🇪🇨', '🇪🇪', '🇪🇬', '🇪🇭', '🇪🇷', '🇪🇸',
    '🇪🇹', '🇪🇺', '🇫🇮', '🇫🇯', '🇫🇰', '🇫🇲', '🇫🇴', '🇫🇷', '🇬🇦', '🇬🇧',
    '🇬🇩', '🇬🇪', '🇬🇫', '🇬🇬', '🇬🇭', '🇬🇮', '🇬🇱', '🇬🇲', '🇬🇳', '🇬🇵',
    '🇬🇶', '🇬🇷', '🇬🇸', '🇬🇹', '🇬🇺', '🇬🇼', '🇬🇾', '🇭🇰', '🇭🇲', '🇭🇳',
    '🇭🇷', '🇭🇹', '🇭🇺', '🇮🇨', '🇮🇩', '🇮🇪', '🇮🇱', '🇮🇲', '🇮🇳', '🇮🇴',
    '🇮🇶', '🇮🇷', '🇮🇸', '🇮🇹', '🇯🇪', '🇯🇲', '🇯🇴', '🇯🇵', '🇰🇪', '🇰🇬',
    '🇰🇭', '🇰🇮', '🇰🇲', '🇰🇳', '🇰🇵', '🇰🇷', '🇰🇼', '🇰🇾', '🇰🇿', '🇱🇦',
    '🇱🇧', '🇱🇨', '🇱🇮', '🇱🇰', '🇱🇷', '🇱🇸', '🇱🇹', '🇱🇺', '🇱🇻', '🇱🇾',
    '🇲🇦', '🇲🇨', '🇲🇩', '🇲🇪', '🇲🇫', '🇲🇬', '🇲🇭', '🇲🇰', '🇲🇱', '🇲🇲',
    '🇲🇳', '🇲🇴', '🇲🇵', '🇲🇶', '🇲🇷', '🇲🇸', '🇲🇹', '🇲🇺', '🇲🇻', '🇲🇼',
    '🇲🇽', '🇲🇾', '🇲🇿', '🇳🇦', '🇳🇨', '🇳🇪', '🇳🇫', '🇳🇬', '🇳🇮', '🇳🇱',
    '🇳🇴', '🇳🇵', '🇳🇷', '🇳🇺', '🇳🇿', '🇴🇲', '🇵🇦', '🇵🇪', '🇵🇫', '🇵🇬',
    '🇵🇭', '🇵🇰', '🇵🇱', '🇵🇲', '🇵🇳', '🇵🇷', '🇵🇸', '🇵🇹', '🇵🇼', '🇵🇾',
    '🇶🇦', '🇷🇪', '🇷🇴', '🇷🇸', '🇷🇺', '🇷🇼', '🇸🇦', '🇸🇧', '🇸🇨', '🇸🇩',
    '🇸🇪', '🇸🇬', '🇸🇭', '🇸🇮', '🇸🇯', '🇸🇰', '🇸🇱', '🇸🇲', '🇸🇳', '🇸🇴',
    '🇸🇷', '🇸🇸', '🇸🇹', '🇸🇻', '🇸🇽', '🇸🇾', '🇸🇿', '🇹🇦', '🇹🇨', '🇹🇩',
    '🇹🇫', '🇹🇬', '🇹🇭', '🇹🇯', '🇹🇰', '🇹🇱', '🇹🇲', '🇹🇳', '🇹🇴', '🇹🇷',
    '🇹🇹', '🇹🇻', '🇹🇼', '🇹🇿', '🇺🇦', '🇺🇬', '🇺🇲', '🇺🇳', '🇺🇸', '🇺🇾',
    '🇺🇿', '🇻🇦', '🇻🇨', '🇻🇪', '🇻🇬', '🇻🇮', '🇻🇳', '🇻🇺', '🇼🇫', '🇼🇸',
    '🇽🇰', '🇾🇪', '🇾🇹', '🇿🇦', '🇿🇲', '🇿🇼', '🏴󠁧󠁢󠁥󠁮󠁧󠁿', '🏴󠁧󠁢󠁳󠁣󠁴󠁿', '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
  ],
};

const Map<String, List<String>> kUnicodeEmojiLabels = {
  '😀': ['face', 'grinning', 'smiling'],
  '😃': ['big', 'eyes', 'face', 'grinning', 'smiling', 'with'],
  '😄': ['eyes', 'face', 'grinning', 'smiling', 'with'],
  '😁': ['beaming', 'eyes', 'face', 'smiling', 'with'],
  '😆': ['face', 'grinning', 'smiling', 'squinting'],
  '😅': ['face', 'grinning', 'smiling', 'sweat', 'with'],
  '🤣': ['face', 'floor', 'laughing', 'on', 'rolling', 'smiling', 'the'],
  '😂': ['face', 'joy', 'of', 'smiling', 'tears', 'with'],
  '🙂': ['face', 'slightly', 'smiling'],
  '🙃': ['down', 'face', 'smiling', 'upside'],
  '🫠': ['face', 'melting', 'smiling'],
  '😉': ['face', 'smiling', 'winking'],
  '😊': ['eyes', 'face', 'smiling', 'with'],
  '😇': ['face', 'halo', 'smiling', 'with'],
  '🥰': ['affection', 'face', 'hearts', 'smiling', 'with'],
  '😍': ['affection', 'eyes', 'face', 'heart', 'smiling', 'with'],
  '🤩': ['affection', 'face', 'star', 'struck'],
  '😘': ['a', 'affection', 'blowing', 'face', 'kiss'],
  '😗': ['affection', 'face', 'kissing'],
  '☺️': ['affection', 'face', 'smiling'],
  '😚': ['affection', 'closed', 'eyes', 'face', 'kissing', 'with'],
  '😙': ['affection', 'eyes', 'face', 'kissing', 'smiling', 'with'],
  '🥲': ['affection', 'face', 'smiling', 'tear', 'with'],
  '😋': ['face', 'food', 'savoring', 'tongue'],
  '😛': ['face', 'tongue', 'with'],
  '😜': ['face', 'tongue', 'winking', 'with'],
  '🤪': ['face', 'tongue', 'zany'],
  '😝': ['face', 'squinting', 'tongue', 'with'],
  '🤑': ['face', 'money', 'mouth', 'tongue'],
  '🤗': ['face', 'hand', 'hands', 'open', 'smiling', 'with'],
  '🤭': ['face', 'hand', 'mouth', 'over', 'with'],
  '🫢': ['and', 'eyes', 'face', 'hand', 'mouth', 'open', 'over', 'with'],
  '🫣': ['eye', 'face', 'hand', 'peeking', 'with'],
  '🤫': ['face', 'hand', 'shushing'],
  '🤔': ['face', 'hand', 'thinking'],
  '🫡': ['face', 'hand', 'saluting'],
  '🤐': ['face', 'mouth', 'neutral', 'skeptical', 'zipper'],
  '🤨': ['eyebrow', 'face', 'neutral', 'raised', 'skeptical', 'with'],
  '😐': ['face', 'neutral', 'skeptical'],
  '😑': ['expressionless', 'face', 'neutral', 'skeptical'],
  '😶': ['face', 'mouth', 'neutral', 'skeptical', 'without'],
  '🫥': ['dotted', 'face', 'line', 'neutral', 'skeptical'],
  '😶‍🌫️': ['clouds', 'face', 'in', 'neutral', 'skeptical'],
  '😏': ['face', 'neutral', 'skeptical', 'smirking'],
  '😒': ['face', 'neutral', 'skeptical', 'unamused'],
  '🙄': ['eyes', 'face', 'neutral', 'rolling', 'skeptical', 'with'],
  '😬': ['face', 'grimacing', 'neutral', 'skeptical'],
  '😮‍💨': ['exhaling', 'face', 'neutral', 'skeptical'],
  '🤥': ['face', 'lying', 'neutral', 'skeptical'],
  '🫨': ['face', 'neutral', 'shaking', 'skeptical'],
  '🙂‍↔️': ['face', 'head', 'horizontally', 'neutral', 'shaking', 'skeptical'],
  '🙂‍↕️': ['face', 'head', 'neutral', 'shaking', 'skeptical', 'vertically'],
  '😌': ['face', 'relieved', 'sleepy'],
  '😔': ['face', 'pensive', 'sleepy'],
  '😪': ['face', 'sleepy'],
  '🤤': ['drooling', 'face', 'sleepy'],
  '😴': ['face', 'sleeping', 'sleepy'],
  '😷': ['face', 'mask', 'medical', 'unwell', 'with'],
  '🤒': ['face', 'thermometer', 'unwell', 'with'],
  '🤕': ['bandage', 'face', 'head', 'unwell', 'with'],
  '🤢': ['face', 'nauseated', 'unwell'],
  '🤮': ['face', 'unwell', 'vomiting'],
  '🤧': ['face', 'sneezing', 'unwell'],
  '🥵': ['face', 'hot', 'unwell'],
  '🥶': ['cold', 'face', 'unwell'],
  '🥴': ['face', 'unwell', 'woozy'],
  '😵': ['crossed', 'eyes', 'face', 'out', 'unwell', 'with'],
  '😵‍💫': ['eyes', 'face', 'spiral', 'unwell', 'with'],
  '🤯': ['exploding', 'face', 'head', 'unwell'],
  '🤠': ['cowboy', 'face', 'hat'],
  '🥳': ['face', 'hat', 'partying'],
  '🥸': ['disguised', 'face', 'hat'],
  '😎': ['face', 'glasses', 'smiling', 'sunglasses', 'with'],
  '🤓': ['face', 'glasses', 'nerd'],
  '🧐': ['face', 'glasses', 'monocle', 'with'],
  '😕': ['concerned', 'confused', 'face'],
  '🫤': ['concerned', 'diagonal', 'face', 'mouth', 'with'],
  '😟': ['concerned', 'face', 'worried'],
  '🙁': ['concerned', 'face', 'frowning', 'slightly'],
  '☹️': ['concerned', 'face', 'frowning'],
  '😮': ['concerned', 'face', 'mouth', 'open', 'with'],
  '😯': ['concerned', 'face', 'hushed'],
  '😲': ['astonished', 'concerned', 'face'],
  '😳': ['concerned', 'face', 'flushed'],
  '🥺': ['concerned', 'face', 'pleading'],
  '🥹': ['back', 'concerned', 'face', 'holding', 'tears'],
  '😦': ['concerned', 'face', 'frowning', 'mouth', 'open', 'with'],
  '😧': ['anguished', 'concerned', 'face'],
  '😨': ['concerned', 'face', 'fearful'],
  '😰': ['anxious', 'concerned', 'face', 'sweat', 'with'],
  '😥': ['but', 'concerned', 'face', 'relieved', 'sad'],
  '😢': ['concerned', 'crying', 'face'],
  '😭': ['concerned', 'crying', 'face', 'loudly'],
  '😱': ['concerned', 'face', 'fear', 'in', 'screaming'],
  '😖': ['concerned', 'confounded', 'face'],
  '😣': ['concerned', 'face', 'persevering'],
  '😞': ['concerned', 'disappointed', 'face'],
  '😓': ['concerned', 'downcast', 'face', 'sweat', 'with'],
  '😩': ['concerned', 'face', 'weary'],
  '😫': ['concerned', 'face', 'tired'],
  '🥱': ['concerned', 'face', 'yawning'],
  '😤': ['face', 'from', 'negative', 'nose', 'steam', 'with'],
  '😡': ['enraged', 'face', 'negative'],
  '😠': ['angry', 'face', 'negative'],
  '🤬': ['face', 'mouth', 'negative', 'on', 'symbols', 'with'],
  '😈': ['face', 'horns', 'negative', 'smiling', 'with'],
  '👿': ['angry', 'face', 'horns', 'negative', 'with'],
  '💀': ['face', 'negative', 'skull'],
  '☠️': ['and', 'crossbones', 'face', 'negative', 'skull'],
  '💩': ['costume', 'face', 'of', 'pile', 'poo'],
  '🤡': ['clown', 'costume', 'face'],
  '👹': ['costume', 'face', 'ogre'],
  '👺': ['costume', 'face', 'goblin'],
  '👻': ['costume', 'face', 'ghost'],
  '👽': ['alien', 'costume', 'face'],
  '👾': ['alien', 'costume', 'face', 'monster'],
  '🤖': ['costume', 'face', 'robot'],
  '😺': ['cat', 'face', 'grinning'],
  '😸': ['cat', 'eyes', 'face', 'grinning', 'smiling', 'with'],
  '😹': ['cat', 'face', 'joy', 'of', 'tears', 'with'],
  '😻': ['cat', 'eyes', 'face', 'heart', 'smiling', 'with'],
  '😼': ['cat', 'face', 'smile', 'with', 'wry'],
  '😽': ['cat', 'face', 'kissing'],
  '🙀': ['cat', 'face', 'weary'],
  '😿': ['cat', 'crying', 'face'],
  '😾': ['cat', 'face', 'pouting'],
  '🙈': ['evil', 'face', 'monkey', 'no', 'see'],
  '🙉': ['evil', 'face', 'hear', 'monkey', 'no'],
  '🙊': ['evil', 'face', 'monkey', 'no', 'speak'],
  '💌': ['heart', 'letter', 'love'],
  '💘': ['arrow', 'heart', 'with'],
  '💝': ['heart', 'ribbon', 'with'],
  '💖': ['heart', 'sparkling'],
  '💗': ['growing', 'heart'],
  '💓': ['beating', 'heart'],
  '💞': ['heart', 'hearts', 'revolving'],
  '💕': ['heart', 'hearts', 'two'],
  '💟': ['decoration', 'heart'],
  '❣️': ['exclamation', 'heart'],
  '💔': ['broken', 'heart'],
  '❤️‍🔥': ['fire', 'heart', 'on'],
  '❤️‍🩹': ['heart', 'mending'],
  '❤️': ['heart', 'red'],
  '🩷': ['heart', 'pink'],
  '🧡': ['heart', 'orange'],
  '💛': ['heart', 'yellow'],
  '💚': ['green', 'heart'],
  '💙': ['blue', 'heart'],
  '🩵': ['blue', 'heart', 'light'],
  '💜': ['heart', 'purple'],
  '🤎': ['brown', 'heart'],
  '🖤': ['black', 'heart'],
  '🩶': ['grey', 'heart'],
  '🤍': ['heart', 'white'],
  '💋': ['emotion', 'kiss', 'mark'],
  '💯': ['emotion', 'hundred', 'points'],
  '💢': ['anger', 'emotion', 'symbol'],
  '💥': ['collision', 'emotion'],
  '💫': ['dizzy', 'emotion'],
  '💦': ['droplets', 'emotion', 'sweat'],
  '💨': ['away', 'dashing', 'emotion'],
  '🕳️': ['emotion', 'hole'],
  '💬': ['balloon', 'emotion', 'speech'],
  '👁️‍🗨️': ['bubble', 'emotion', 'eye', 'in', 'speech'],
  '🗨️': ['bubble', 'emotion', 'left', 'speech'],
  '🗯️': ['anger', 'bubble', 'emotion', 'right'],
  '💭': ['balloon', 'emotion', 'thought'],
  '💤': ['emotion', 'zzz'],
  '👋': ['fingers', 'hand', 'open', 'waving'],
  '🤚': ['back', 'fingers', 'hand', 'of', 'open', 'raised'],
  '🖐️': ['fingers', 'hand', 'open', 'splayed', 'with'],
  '✋': ['fingers', 'hand', 'open', 'raised'],
  '🖖': ['fingers', 'hand', 'open', 'salute', 'vulcan'],
  '🫱': ['fingers', 'hand', 'open', 'rightwards'],
  '🫲': ['fingers', 'hand', 'leftwards', 'open'],
  '🫳': ['down', 'fingers', 'hand', 'open', 'palm'],
  '🫴': ['fingers', 'hand', 'open', 'palm', 'up'],
  '🫷': ['fingers', 'hand', 'leftwards', 'open', 'pushing'],
  '🫸': ['fingers', 'hand', 'open', 'pushing', 'rightwards'],
  '👌': ['fingers', 'hand', 'ok', 'partial'],
  '🤌': ['fingers', 'hand', 'partial', 'pinched'],
  '🤏': ['fingers', 'hand', 'partial', 'pinching'],
  '✌️': ['fingers', 'hand', 'partial', 'victory'],
  '🤞': ['crossed', 'fingers', 'hand', 'partial'],
  '🫰': ['and', 'crossed', 'finger', 'fingers', 'hand', 'index', 'partial', 'thumb', 'with'],
  '🤟': ['fingers', 'gesture', 'hand', 'love', 'partial', 'you'],
  '🤘': ['fingers', 'hand', 'horns', 'of', 'partial', 'sign', 'the'],
  '🤙': ['call', 'fingers', 'hand', 'me', 'partial'],
  '👈': ['backhand', 'finger', 'hand', 'index', 'left', 'pointing', 'single'],
  '👉': ['backhand', 'finger', 'hand', 'index', 'pointing', 'right', 'single'],
  '👆': ['backhand', 'finger', 'hand', 'index', 'pointing', 'single', 'up'],
  '🖕': ['finger', 'hand', 'middle', 'single'],
  '👇': ['backhand', 'down', 'finger', 'hand', 'index', 'pointing', 'single'],
  '☝️': ['finger', 'hand', 'index', 'pointing', 'single', 'up'],
  '🫵': ['at', 'finger', 'hand', 'index', 'pointing', 'single', 'the', 'viewer'],
  '👍': ['closed', 'fingers', 'hand', 'thumbs', 'up'],
  '👎': ['closed', 'down', 'fingers', 'hand', 'thumbs'],
  '✊': ['closed', 'fingers', 'fist', 'hand', 'raised'],
  '👊': ['closed', 'fingers', 'fist', 'hand', 'oncoming'],
  '🤛': ['closed', 'facing', 'fingers', 'fist', 'hand', 'left'],
  '🤜': ['closed', 'facing', 'fingers', 'fist', 'hand', 'right'],
  '👏': ['clapping', 'hands'],
  '🙌': ['hands', 'raising'],
  '🫶': ['hands', 'heart'],
  '👐': ['hands', 'open'],
  '🤲': ['hands', 'palms', 'together', 'up'],
  '🤝': ['hands', 'handshake'],
  '🙏': ['folded', 'hands'],
  '✍️': ['hand', 'prop', 'writing'],
  '💅': ['hand', 'nail', 'polish', 'prop'],
  '🤳': ['hand', 'prop', 'selfie'],
  '💪': ['biceps', 'body', 'flexed', 'parts'],
  '🦾': ['arm', 'body', 'mechanical', 'parts'],
  '🦿': ['body', 'leg', 'mechanical', 'parts'],
  '🦵': ['body', 'leg', 'parts'],
  '🦶': ['body', 'foot', 'parts'],
  '👂': ['body', 'ear', 'parts'],
  '🦻': ['aid', 'body', 'ear', 'hearing', 'parts', 'with'],
  '👃': ['body', 'nose', 'parts'],
  '🧠': ['body', 'brain', 'parts'],
  '🫀': ['anatomical', 'body', 'heart', 'parts'],
  '🫁': ['body', 'lungs', 'parts'],
  '🦷': ['body', 'parts', 'tooth'],
  '🦴': ['body', 'bone', 'parts'],
  '👀': ['body', 'eyes', 'parts'],
  '👁️': ['body', 'eye', 'parts'],
  '👅': ['body', 'parts', 'tongue'],
  '👄': ['body', 'mouth', 'parts'],
  '🫦': ['biting', 'body', 'lip', 'parts'],
  '👶': ['baby', 'person'],
  '🧒': ['child', 'person'],
  '👦': ['boy', 'person'],
  '👧': ['girl', 'person'],
  '🧑': ['person'],
  '👱': ['blond', 'hair', 'person'],
  '👨': ['man', 'person'],
  '🧔': ['beard', 'person'],
  '🧔‍♂️': ['beard', 'man', 'person'],
  '🧔‍♀️': ['beard', 'person', 'woman'],
  '👨‍🦰': ['hair', 'man', 'person', 'red'],
  '👨‍🦱': ['curly', 'hair', 'man', 'person'],
  '👨‍🦳': ['hair', 'man', 'person', 'white'],
  '👨‍🦲': ['bald', 'man', 'person'],
  '👩': ['person', 'woman'],
  '👩‍🦰': ['hair', 'person', 'red', 'woman'],
  '🧑‍🦰': ['hair', 'person', 'red'],
  '👩‍🦱': ['curly', 'hair', 'person', 'woman'],
  '🧑‍🦱': ['curly', 'hair', 'person'],
  '👩‍🦳': ['hair', 'person', 'white', 'woman'],
  '🧑‍🦳': ['hair', 'person', 'white'],
  '👩‍🦲': ['bald', 'person', 'woman'],
  '🧑‍🦲': ['bald', 'person'],
  '👱‍♀️': ['blond', 'hair', 'person', 'woman'],
  '👱‍♂️': ['blond', 'hair', 'man', 'person'],
  '🧓': ['older', 'person'],
  '👴': ['man', 'old', 'person'],
  '👵': ['old', 'person', 'woman'],
  '🙍': ['frowning', 'gesture', 'person'],
  '🙍‍♂️': ['frowning', 'gesture', 'man', 'person'],
  '🙍‍♀️': ['frowning', 'gesture', 'person', 'woman'],
  '🙎': ['gesture', 'person', 'pouting'],
  '🙎‍♂️': ['gesture', 'man', 'person', 'pouting'],
  '🙎‍♀️': ['gesture', 'person', 'pouting', 'woman'],
  '🙅': ['gesture', 'gesturing', 'no', 'person'],
  '🙅‍♂️': ['gesture', 'gesturing', 'man', 'no', 'person'],
  '🙅‍♀️': ['gesture', 'gesturing', 'no', 'person', 'woman'],
  '🙆': ['gesture', 'gesturing', 'ok', 'person'],
  '🙆‍♂️': ['gesture', 'gesturing', 'man', 'ok', 'person'],
  '🙆‍♀️': ['gesture', 'gesturing', 'ok', 'person', 'woman'],
  '💁': ['gesture', 'hand', 'person', 'tipping'],
  '💁‍♂️': ['gesture', 'hand', 'man', 'person', 'tipping'],
  '💁‍♀️': ['gesture', 'hand', 'person', 'tipping', 'woman'],
  '🙋': ['gesture', 'hand', 'person', 'raising'],
  '🙋‍♂️': ['gesture', 'hand', 'man', 'person', 'raising'],
  '🙋‍♀️': ['gesture', 'hand', 'person', 'raising', 'woman'],
  '🧏': ['deaf', 'gesture', 'person'],
  '🧏‍♂️': ['deaf', 'gesture', 'man', 'person'],
  '🧏‍♀️': ['deaf', 'gesture', 'person', 'woman'],
  '🙇': ['bowing', 'gesture', 'person'],
  '🙇‍♂️': ['bowing', 'gesture', 'man', 'person'],
  '🙇‍♀️': ['bowing', 'gesture', 'person', 'woman'],
  '🤦': ['facepalming', 'gesture', 'person'],
  '🤦‍♂️': ['facepalming', 'gesture', 'man', 'person'],
  '🤦‍♀️': ['facepalming', 'gesture', 'person', 'woman'],
  '🤷': ['gesture', 'person', 'shrugging'],
  '🤷‍♂️': ['gesture', 'man', 'person', 'shrugging'],
  '🤷‍♀️': ['gesture', 'person', 'shrugging', 'woman'],
  '🧑‍⚕️': ['health', 'person', 'role', 'worker'],
  '👨‍⚕️': ['health', 'man', 'person', 'role', 'worker'],
  '👩‍⚕️': ['health', 'person', 'role', 'woman', 'worker'],
  '🧑‍🎓': ['person', 'role', 'student'],
  '👨‍🎓': ['man', 'person', 'role', 'student'],
  '👩‍🎓': ['person', 'role', 'student', 'woman'],
  '🧑‍🏫': ['person', 'role', 'teacher'],
  '👨‍🏫': ['man', 'person', 'role', 'teacher'],
  '👩‍🏫': ['person', 'role', 'teacher', 'woman'],
  '🧑‍⚖️': ['judge', 'person', 'role'],
  '👨‍⚖️': ['judge', 'man', 'person', 'role'],
  '👩‍⚖️': ['judge', 'person', 'role', 'woman'],
  '🧑‍🌾': ['farmer', 'person', 'role'],
  '👨‍🌾': ['farmer', 'man', 'person', 'role'],
  '👩‍🌾': ['farmer', 'person', 'role', 'woman'],
  '🧑‍🍳': ['cook', 'person', 'role'],
  '👨‍🍳': ['cook', 'man', 'person', 'role'],
  '👩‍🍳': ['cook', 'person', 'role', 'woman'],
  '🧑‍🔧': ['mechanic', 'person', 'role'],
  '👨‍🔧': ['man', 'mechanic', 'person', 'role'],
  '👩‍🔧': ['mechanic', 'person', 'role', 'woman'],
  '🧑‍🏭': ['factory', 'person', 'role', 'worker'],
  '👨‍🏭': ['factory', 'man', 'person', 'role', 'worker'],
  '👩‍🏭': ['factory', 'person', 'role', 'woman', 'worker'],
  '🧑‍💼': ['office', 'person', 'role', 'worker'],
  '👨‍💼': ['man', 'office', 'person', 'role', 'worker'],
  '👩‍💼': ['office', 'person', 'role', 'woman', 'worker'],
  '🧑‍🔬': ['person', 'role', 'scientist'],
  '👨‍🔬': ['man', 'person', 'role', 'scientist'],
  '👩‍🔬': ['person', 'role', 'scientist', 'woman'],
  '🧑‍💻': ['person', 'role', 'technologist'],
  '👨‍💻': ['man', 'person', 'role', 'technologist'],
  '👩‍💻': ['person', 'role', 'technologist', 'woman'],
  '🧑‍🎤': ['person', 'role', 'singer'],
  '👨‍🎤': ['man', 'person', 'role', 'singer'],
  '👩‍🎤': ['person', 'role', 'singer', 'woman'],
  '🧑‍🎨': ['artist', 'person', 'role'],
  '👨‍🎨': ['artist', 'man', 'person', 'role'],
  '👩‍🎨': ['artist', 'person', 'role', 'woman'],
  '🧑‍✈️': ['person', 'pilot', 'role'],
  '👨‍✈️': ['man', 'person', 'pilot', 'role'],
  '👩‍✈️': ['person', 'pilot', 'role', 'woman'],
  '🧑‍🚀': ['astronaut', 'person', 'role'],
  '👨‍🚀': ['astronaut', 'man', 'person', 'role'],
  '👩‍🚀': ['astronaut', 'person', 'role', 'woman'],
  '🧑‍🚒': ['firefighter', 'person', 'role'],
  '👨‍🚒': ['firefighter', 'man', 'person', 'role'],
  '👩‍🚒': ['firefighter', 'person', 'role', 'woman'],
  '👮': ['officer', 'person', 'police', 'role'],
  '👮‍♂️': ['man', 'officer', 'person', 'police', 'role'],
  '👮‍♀️': ['officer', 'person', 'police', 'role', 'woman'],
  '🕵️': ['detective', 'person', 'role'],
  '🕵️‍♂️': ['detective', 'man', 'person', 'role'],
  '🕵️‍♀️': ['detective', 'person', 'role', 'woman'],
  '💂': ['guard', 'person', 'role'],
  '💂‍♂️': ['guard', 'man', 'person', 'role'],
  '💂‍♀️': ['guard', 'person', 'role', 'woman'],
  '🥷': ['ninja', 'person', 'role'],
  '👷': ['construction', 'person', 'role', 'worker'],
  '👷‍♂️': ['construction', 'man', 'person', 'role', 'worker'],
  '👷‍♀️': ['construction', 'person', 'role', 'woman', 'worker'],
  '🫅': ['crown', 'person', 'role', 'with'],
  '🤴': ['person', 'prince', 'role'],
  '👸': ['person', 'princess', 'role'],
  '👳': ['person', 'role', 'turban', 'wearing'],
  '👳‍♂️': ['man', 'person', 'role', 'turban', 'wearing'],
  '👳‍♀️': ['person', 'role', 'turban', 'wearing', 'woman'],
  '👲': ['person', 'role', 'skullcap', 'with'],
  '🧕': ['headscarf', 'person', 'role', 'with', 'woman'],
  '🤵': ['in', 'person', 'role', 'tuxedo'],
  '🤵‍♂️': ['in', 'man', 'person', 'role', 'tuxedo'],
  '🤵‍♀️': ['in', 'person', 'role', 'tuxedo', 'woman'],
  '👰': ['person', 'role', 'veil', 'with'],
  '👰‍♂️': ['man', 'person', 'role', 'veil', 'with'],
  '👰‍♀️': ['person', 'role', 'veil', 'with', 'woman'],
  '🤰': ['person', 'pregnant', 'role', 'woman'],
  '🫃': ['man', 'person', 'pregnant', 'role'],
  '🫄': ['person', 'pregnant', 'role'],
  '🤱': ['breast', 'feeding', 'person', 'role'],
  '👩‍🍼': ['baby', 'feeding', 'person', 'role', 'woman'],
  '👨‍🍼': ['baby', 'feeding', 'man', 'person', 'role'],
  '🧑‍🍼': ['baby', 'feeding', 'person', 'role'],
  '👼': ['angel', 'baby', 'fantasy', 'person'],
  '🎅': ['claus', 'fantasy', 'person', 'santa'],
  '🤶': ['claus', 'fantasy', 'mrs', 'person'],
  '🧑‍🎄': ['claus', 'fantasy', 'mx', 'person'],
  '🦸': ['fantasy', 'person', 'superhero'],
  '🦸‍♂️': ['fantasy', 'man', 'person', 'superhero'],
  '🦸‍♀️': ['fantasy', 'person', 'superhero', 'woman'],
  '🦹': ['fantasy', 'person', 'supervillain'],
  '🦹‍♂️': ['fantasy', 'man', 'person', 'supervillain'],
  '🦹‍♀️': ['fantasy', 'person', 'supervillain', 'woman'],
  '🧙': ['fantasy', 'mage', 'person'],
  '🧙‍♂️': ['fantasy', 'mage', 'man', 'person'],
  '🧙‍♀️': ['fantasy', 'mage', 'person', 'woman'],
  '🧚': ['fairy', 'fantasy', 'person'],
  '🧚‍♂️': ['fairy', 'fantasy', 'man', 'person'],
  '🧚‍♀️': ['fairy', 'fantasy', 'person', 'woman'],
  '🧛': ['fantasy', 'person', 'vampire'],
  '🧛‍♂️': ['fantasy', 'man', 'person', 'vampire'],
  '🧛‍♀️': ['fantasy', 'person', 'vampire', 'woman'],
  '🧜': ['fantasy', 'merperson', 'person'],
  '🧜‍♂️': ['fantasy', 'merman', 'person'],
  '🧜‍♀️': ['fantasy', 'mermaid', 'person'],
  '🧝': ['elf', 'fantasy', 'person'],
  '🧝‍♂️': ['elf', 'fantasy', 'man', 'person'],
  '🧝‍♀️': ['elf', 'fantasy', 'person', 'woman'],
  '🧞': ['fantasy', 'genie', 'person'],
  '🧞‍♂️': ['fantasy', 'genie', 'man', 'person'],
  '🧞‍♀️': ['fantasy', 'genie', 'person', 'woman'],
  '🧟': ['fantasy', 'person', 'zombie'],
  '🧟‍♂️': ['fantasy', 'man', 'person', 'zombie'],
  '🧟‍♀️': ['fantasy', 'person', 'woman', 'zombie'],
  '🧌': ['fantasy', 'person', 'troll'],
  '💆': ['activity', 'getting', 'massage', 'person'],
  '💆‍♂️': ['activity', 'getting', 'man', 'massage', 'person'],
  '💆‍♀️': ['activity', 'getting', 'massage', 'person', 'woman'],
  '💇': ['activity', 'getting', 'haircut', 'person'],
  '💇‍♂️': ['activity', 'getting', 'haircut', 'man', 'person'],
  '💇‍♀️': ['activity', 'getting', 'haircut', 'person', 'woman'],
  '🚶': ['activity', 'person', 'walking'],
  '🚶‍♂️': ['activity', 'man', 'person', 'walking'],
  '🚶‍♀️': ['activity', 'person', 'walking', 'woman'],
  '🚶‍➡️': ['activity', 'facing', 'person', 'right', 'walking'],
  '🚶‍♀️‍➡️': ['activity', 'facing', 'person', 'right', 'walking', 'woman'],
  '🚶‍♂️‍➡️': ['activity', 'facing', 'man', 'person', 'right', 'walking'],
  '🧍': ['activity', 'person', 'standing'],
  '🧍‍♂️': ['activity', 'man', 'person', 'standing'],
  '🧍‍♀️': ['activity', 'person', 'standing', 'woman'],
  '🧎': ['activity', 'kneeling', 'person'],
  '🧎‍♂️': ['activity', 'kneeling', 'man', 'person'],
  '🧎‍♀️': ['activity', 'kneeling', 'person', 'woman'],
  '🧎‍➡️': ['activity', 'facing', 'kneeling', 'person', 'right'],
  '🧎‍♀️‍➡️': ['activity', 'facing', 'kneeling', 'person', 'right', 'woman'],
  '🧎‍♂️‍➡️': ['activity', 'facing', 'kneeling', 'man', 'person', 'right'],
  '🧑‍🦯': ['activity', 'cane', 'person', 'white', 'with'],
  '🧑‍🦯‍➡️': ['activity', 'cane', 'facing', 'person', 'right', 'white', 'with'],
  '👨‍🦯': ['activity', 'cane', 'man', 'person', 'white', 'with'],
  '👨‍🦯‍➡️': ['activity', 'cane', 'facing', 'man', 'person', 'right', 'white', 'with'],
  '👩‍🦯': ['activity', 'cane', 'person', 'white', 'with', 'woman'],
  '👩‍🦯‍➡️': ['activity', 'cane', 'facing', 'person', 'right', 'white', 'with', 'woman'],
  '🧑‍🦼': ['activity', 'in', 'motorized', 'person', 'wheelchair'],
  '🧑‍🦼‍➡️': ['activity', 'facing', 'in', 'motorized', 'person', 'right', 'wheelchair'],
  '👨‍🦼': ['activity', 'in', 'man', 'motorized', 'person', 'wheelchair'],
  '👨‍🦼‍➡️': ['activity', 'facing', 'in', 'man', 'motorized', 'person', 'right', 'wheelchair'],
  '👩‍🦼': ['activity', 'in', 'motorized', 'person', 'wheelchair', 'woman'],
  '👩‍🦼‍➡️': ['activity', 'facing', 'in', 'motorized', 'person', 'right', 'wheelchair', 'woman'],
  '🧑‍🦽': ['activity', 'in', 'manual', 'person', 'wheelchair'],
  '🧑‍🦽‍➡️': ['activity', 'facing', 'in', 'manual', 'person', 'right', 'wheelchair'],
  '👨‍🦽': ['activity', 'in', 'man', 'manual', 'person', 'wheelchair'],
  '👨‍🦽‍➡️': ['activity', 'facing', 'in', 'man', 'manual', 'person', 'right', 'wheelchair'],
  '👩‍🦽': ['activity', 'in', 'manual', 'person', 'wheelchair', 'woman'],
  '👩‍🦽‍➡️': ['activity', 'facing', 'in', 'manual', 'person', 'right', 'wheelchair', 'woman'],
  '🏃': ['activity', 'person', 'running'],
  '🏃‍♂️': ['activity', 'man', 'person', 'running'],
  '🏃‍♀️': ['activity', 'person', 'running', 'woman'],
  '🏃‍➡️': ['activity', 'facing', 'person', 'right', 'running'],
  '🏃‍♀️‍➡️': ['activity', 'facing', 'person', 'right', 'running', 'woman'],
  '🏃‍♂️‍➡️': ['activity', 'facing', 'man', 'person', 'right', 'running'],
  '💃': ['activity', 'dancing', 'person', 'woman'],
  '🕺': ['activity', 'dancing', 'man', 'person'],
  '🕴️': ['activity', 'in', 'levitating', 'person', 'suit'],
  '👯': ['activity', 'bunny', 'ears', 'people', 'person', 'with'],
  '👯‍♂️': ['activity', 'bunny', 'ears', 'men', 'person', 'with'],
  '👯‍♀️': ['activity', 'bunny', 'ears', 'person', 'with', 'women'],
  '🧖': ['activity', 'in', 'person', 'room', 'steamy'],
  '🧖‍♂️': ['activity', 'in', 'man', 'person', 'room', 'steamy'],
  '🧖‍♀️': ['activity', 'in', 'person', 'room', 'steamy', 'woman'],
  '🧗': ['activity', 'climbing', 'person'],
  '🧗‍♂️': ['activity', 'climbing', 'man', 'person'],
  '🧗‍♀️': ['activity', 'climbing', 'person', 'woman'],
  '🤺': ['fencing', 'person', 'sport'],
  '🏇': ['horse', 'person', 'racing', 'sport'],
  '⛷️': ['person', 'skier', 'sport'],
  '🏂': ['person', 'snowboarder', 'sport'],
  '🏌️': ['golfing', 'person', 'sport'],
  '🏌️‍♂️': ['golfing', 'man', 'person', 'sport'],
  '🏌️‍♀️': ['golfing', 'person', 'sport', 'woman'],
  '🏄': ['person', 'sport', 'surfing'],
  '🏄‍♂️': ['man', 'person', 'sport', 'surfing'],
  '🏄‍♀️': ['person', 'sport', 'surfing', 'woman'],
  '🚣': ['boat', 'person', 'rowing', 'sport'],
  '🚣‍♂️': ['boat', 'man', 'person', 'rowing', 'sport'],
  '🚣‍♀️': ['boat', 'person', 'rowing', 'sport', 'woman'],
  '🏊': ['person', 'sport', 'swimming'],
  '🏊‍♂️': ['man', 'person', 'sport', 'swimming'],
  '🏊‍♀️': ['person', 'sport', 'swimming', 'woman'],
  '⛹️': ['ball', 'bouncing', 'person', 'sport'],
  '⛹️‍♂️': ['ball', 'bouncing', 'man', 'person', 'sport'],
  '⛹️‍♀️': ['ball', 'bouncing', 'person', 'sport', 'woman'],
  '🏋️': ['lifting', 'person', 'sport', 'weights'],
  '🏋️‍♂️': ['lifting', 'man', 'person', 'sport', 'weights'],
  '🏋️‍♀️': ['lifting', 'person', 'sport', 'weights', 'woman'],
  '🚴': ['biking', 'person', 'sport'],
  '🚴‍♂️': ['biking', 'man', 'person', 'sport'],
  '🚴‍♀️': ['biking', 'person', 'sport', 'woman'],
  '🚵': ['biking', 'mountain', 'person', 'sport'],
  '🚵‍♂️': ['biking', 'man', 'mountain', 'person', 'sport'],
  '🚵‍♀️': ['biking', 'mountain', 'person', 'sport', 'woman'],
  '🤸': ['cartwheeling', 'person', 'sport'],
  '🤸‍♂️': ['cartwheeling', 'man', 'person', 'sport'],
  '🤸‍♀️': ['cartwheeling', 'person', 'sport', 'woman'],
  '🤼': ['people', 'person', 'sport', 'wrestling'],
  '🤼‍♂️': ['men', 'person', 'sport', 'wrestling'],
  '🤼‍♀️': ['person', 'sport', 'women', 'wrestling'],
  '🤽': ['person', 'playing', 'polo', 'sport', 'water'],
  '🤽‍♂️': ['man', 'person', 'playing', 'polo', 'sport', 'water'],
  '🤽‍♀️': ['person', 'playing', 'polo', 'sport', 'water', 'woman'],
  '🤾': ['handball', 'person', 'playing', 'sport'],
  '🤾‍♂️': ['handball', 'man', 'person', 'playing', 'sport'],
  '🤾‍♀️': ['handball', 'person', 'playing', 'sport', 'woman'],
  '🤹': ['juggling', 'person', 'sport'],
  '🤹‍♂️': ['juggling', 'man', 'person', 'sport'],
  '🤹‍♀️': ['juggling', 'person', 'sport', 'woman'],
  '🧘': ['in', 'lotus', 'person', 'position', 'resting'],
  '🧘‍♂️': ['in', 'lotus', 'man', 'person', 'position', 'resting'],
  '🧘‍♀️': ['in', 'lotus', 'person', 'position', 'resting', 'woman'],
  '🛀': ['bath', 'person', 'resting', 'taking'],
  '🛌': ['bed', 'in', 'person', 'resting'],
  '🧑‍🤝‍🧑': ['family', 'hands', 'holding', 'people'],
  '👭': ['family', 'hands', 'holding', 'women'],
  '👫': ['and', 'family', 'hands', 'holding', 'man', 'woman'],
  '👬': ['family', 'hands', 'holding', 'men'],
  '💏': ['family', 'kiss'],
  '👩‍❤️‍💋‍👨': ['family', 'kiss', 'man', 'woman'],
  '👨‍❤️‍💋‍👨': ['family', 'kiss', 'man'],
  '👩‍❤️‍💋‍👩': ['family', 'kiss', 'woman'],
  '💑': ['couple', 'family', 'heart', 'with'],
  '👩‍❤️‍👨': ['couple', 'family', 'heart', 'man', 'with', 'woman'],
  '👨‍❤️‍👨': ['couple', 'family', 'heart', 'man', 'with'],
  '👩‍❤️‍👩': ['couple', 'family', 'heart', 'with', 'woman'],
  '👨‍👩‍👦': ['boy', 'family', 'man', 'woman'],
  '👨‍👩‍👧': ['family', 'girl', 'man', 'woman'],
  '👨‍👩‍👧‍👦': ['boy', 'family', 'girl', 'man', 'woman'],
  '👨‍👩‍👦‍👦': ['boy', 'family', 'man', 'woman'],
  '👨‍👩‍👧‍👧': ['family', 'girl', 'man', 'woman'],
  '👨‍👨‍👦': ['boy', 'family', 'man'],
  '👨‍👨‍👧': ['family', 'girl', 'man'],
  '👨‍👨‍👧‍👦': ['boy', 'family', 'girl', 'man'],
  '👨‍👨‍👦‍👦': ['boy', 'family', 'man'],
  '👨‍👨‍👧‍👧': ['family', 'girl', 'man'],
  '👩‍👩‍👦': ['boy', 'family', 'woman'],
  '👩‍👩‍👧': ['family', 'girl', 'woman'],
  '👩‍👩‍👧‍👦': ['boy', 'family', 'girl', 'woman'],
  '👩‍👩‍👦‍👦': ['boy', 'family', 'woman'],
  '👩‍👩‍👧‍👧': ['family', 'girl', 'woman'],
  '👨‍👦': ['boy', 'family', 'man'],
  '👨‍👦‍👦': ['boy', 'family', 'man'],
  '👨‍👧': ['family', 'girl', 'man'],
  '👨‍👧‍👦': ['boy', 'family', 'girl', 'man'],
  '👨‍👧‍👧': ['family', 'girl', 'man'],
  '👩‍👦': ['boy', 'family', 'woman'],
  '👩‍👦‍👦': ['boy', 'family', 'woman'],
  '👩‍👧': ['family', 'girl', 'woman'],
  '👩‍👧‍👦': ['boy', 'family', 'girl', 'woman'],
  '👩‍👧‍👧': ['family', 'girl', 'woman'],
  '🗣️': ['head', 'person', 'speaking', 'symbol'],
  '👤': ['bust', 'in', 'person', 'silhouette', 'symbol'],
  '👥': ['busts', 'in', 'person', 'silhouette', 'symbol'],
  '🫂': ['hugging', 'people', 'person', 'symbol'],
  '👪': ['family', 'person', 'symbol'],
  '🧑‍🧑‍🧒': ['adult', 'child', 'family', 'person', 'symbol'],
  '🧑‍🧑‍🧒‍🧒': ['adult', 'child', 'family', 'person', 'symbol'],
  '🧑‍🧒': ['adult', 'child', 'family', 'person', 'symbol'],
  '🧑‍🧒‍🧒': ['adult', 'child', 'family', 'person', 'symbol'],
  '👣': ['footprints', 'person', 'symbol'],
  '🐵': ['animal', 'face', 'mammal', 'monkey'],
  '🐒': ['animal', 'mammal', 'monkey'],
  '🦍': ['animal', 'gorilla', 'mammal'],
  '🦧': ['animal', 'mammal', 'orangutan'],
  '🐶': ['animal', 'dog', 'face', 'mammal'],
  '🐕': ['animal', 'dog', 'mammal'],
  '🦮': ['animal', 'dog', 'guide', 'mammal'],
  '🐕‍🦺': ['animal', 'dog', 'mammal', 'service'],
  '🐩': ['animal', 'mammal', 'poodle'],
  '🐺': ['animal', 'mammal', 'wolf'],
  '🦊': ['animal', 'fox', 'mammal'],
  '🦝': ['animal', 'mammal', 'raccoon'],
  '🐱': ['animal', 'cat', 'face', 'mammal'],
  '🐈': ['animal', 'cat', 'mammal'],
  '🐈‍⬛': ['animal', 'black', 'cat', 'mammal'],
  '🦁': ['animal', 'lion', 'mammal'],
  '🐯': ['animal', 'face', 'mammal', 'tiger'],
  '🐅': ['animal', 'mammal', 'tiger'],
  '🐆': ['animal', 'leopard', 'mammal'],
  '🐴': ['animal', 'face', 'horse', 'mammal'],
  '🫎': ['animal', 'mammal', 'moose'],
  '🫏': ['animal', 'donkey', 'mammal'],
  '🐎': ['animal', 'horse', 'mammal'],
  '🦄': ['animal', 'mammal', 'unicorn'],
  '🦓': ['animal', 'mammal', 'zebra'],
  '🦌': ['animal', 'deer', 'mammal'],
  '🦬': ['animal', 'bison', 'mammal'],
  '🐮': ['animal', 'cow', 'face', 'mammal'],
  '🐂': ['animal', 'mammal', 'ox'],
  '🐃': ['animal', 'buffalo', 'mammal', 'water'],
  '🐄': ['animal', 'cow', 'mammal'],
  '🐷': ['animal', 'face', 'mammal', 'pig'],
  '🐖': ['animal', 'mammal', 'pig'],
  '🐗': ['animal', 'boar', 'mammal'],
  '🐽': ['animal', 'mammal', 'nose', 'pig'],
  '🐏': ['animal', 'mammal', 'ram'],
  '🐑': ['animal', 'ewe', 'mammal'],
  '🐐': ['animal', 'goat', 'mammal'],
  '🐪': ['animal', 'camel', 'mammal'],
  '🐫': ['animal', 'camel', 'hump', 'mammal', 'two'],
  '🦙': ['animal', 'llama', 'mammal'],
  '🦒': ['animal', 'giraffe', 'mammal'],
  '🐘': ['animal', 'elephant', 'mammal'],
  '🦣': ['animal', 'mammal', 'mammoth'],
  '🦏': ['animal', 'mammal', 'rhinoceros'],
  '🦛': ['animal', 'hippopotamus', 'mammal'],
  '🐭': ['animal', 'face', 'mammal', 'mouse'],
  '🐁': ['animal', 'mammal', 'mouse'],
  '🐀': ['animal', 'mammal', 'rat'],
  '🐹': ['animal', 'hamster', 'mammal'],
  '🐰': ['animal', 'face', 'mammal', 'rabbit'],
  '🐇': ['animal', 'mammal', 'rabbit'],
  '🐿️': ['animal', 'chipmunk', 'mammal'],
  '🦫': ['animal', 'beaver', 'mammal'],
  '🦔': ['animal', 'hedgehog', 'mammal'],
  '🦇': ['animal', 'bat', 'mammal'],
  '🐻': ['animal', 'bear', 'mammal'],
  '🐻‍❄️': ['animal', 'bear', 'mammal', 'polar'],
  '🐨': ['animal', 'koala', 'mammal'],
  '🐼': ['animal', 'mammal', 'panda'],
  '🦥': ['animal', 'mammal', 'sloth'],
  '🦦': ['animal', 'mammal', 'otter'],
  '🦨': ['animal', 'mammal', 'skunk'],
  '🦘': ['animal', 'kangaroo', 'mammal'],
  '🦡': ['animal', 'badger', 'mammal'],
  '🐾': ['animal', 'mammal', 'paw', 'prints'],
  '🦃': ['animal', 'bird', 'turkey'],
  '🐔': ['animal', 'bird', 'chicken'],
  '🐓': ['animal', 'bird', 'rooster'],
  '🐣': ['animal', 'bird', 'chick', 'hatching'],
  '🐤': ['animal', 'baby', 'bird', 'chick'],
  '🐥': ['animal', 'baby', 'bird', 'chick', 'facing', 'front'],
  '🐦': ['animal', 'bird'],
  '🐧': ['animal', 'bird', 'penguin'],
  '🕊️': ['animal', 'bird', 'dove'],
  '🦅': ['animal', 'bird', 'eagle'],
  '🦆': ['animal', 'bird', 'duck'],
  '🦢': ['animal', 'bird', 'swan'],
  '🦉': ['animal', 'bird', 'owl'],
  '🦤': ['animal', 'bird', 'dodo'],
  '🪶': ['animal', 'bird', 'feather'],
  '🦩': ['animal', 'bird', 'flamingo'],
  '🦚': ['animal', 'bird', 'peacock'],
  '🦜': ['animal', 'bird', 'parrot'],
  '🪽': ['animal', 'bird', 'wing'],
  '🐦‍⬛': ['animal', 'bird', 'black'],
  '🪿': ['animal', 'bird', 'goose'],
  '🐦‍🔥': ['animal', 'bird', 'phoenix'],
  '🐸': ['amphibian', 'animal', 'frog'],
  '🐊': ['animal', 'crocodile', 'reptile'],
  '🐢': ['animal', 'reptile', 'turtle'],
  '🦎': ['animal', 'lizard', 'reptile'],
  '🐍': ['animal', 'reptile', 'snake'],
  '🐲': ['animal', 'dragon', 'face', 'reptile'],
  '🐉': ['animal', 'dragon', 'reptile'],
  '🦕': ['animal', 'reptile', 'sauropod'],
  '🦖': ['animal', 'reptile', 'rex', 't'],
  '🐳': ['animal', 'marine', 'spouting', 'whale'],
  '🐋': ['animal', 'marine', 'whale'],
  '🐬': ['animal', 'dolphin', 'marine'],
  '🦭': ['animal', 'marine', 'seal'],
  '🐟': ['animal', 'fish', 'marine'],
  '🐠': ['animal', 'fish', 'marine', 'tropical'],
  '🐡': ['animal', 'blowfish', 'marine'],
  '🦈': ['animal', 'marine', 'shark'],
  '🐙': ['animal', 'marine', 'octopus'],
  '🐚': ['animal', 'marine', 'shell', 'spiral'],
  '🪸': ['animal', 'coral', 'marine'],
  '🪼': ['animal', 'jellyfish', 'marine'],
  '🐌': ['animal', 'bug', 'snail'],
  '🦋': ['animal', 'bug', 'butterfly'],
  '🐛': ['animal', 'bug'],
  '🐜': ['animal', 'ant', 'bug'],
  '🐝': ['animal', 'bug', 'honeybee'],
  '🪲': ['animal', 'beetle', 'bug'],
  '🐞': ['animal', 'beetle', 'bug', 'lady'],
  '🦗': ['animal', 'bug', 'cricket'],
  '🪳': ['animal', 'bug', 'cockroach'],
  '🕷️': ['animal', 'bug', 'spider'],
  '🕸️': ['animal', 'bug', 'spider', 'web'],
  '🦂': ['animal', 'bug', 'scorpion'],
  '🦟': ['animal', 'bug', 'mosquito'],
  '🪰': ['animal', 'bug', 'fly'],
  '🪱': ['animal', 'bug', 'worm'],
  '🦠': ['animal', 'bug', 'microbe'],
  '💐': ['bouquet', 'flower', 'plant'],
  '🌸': ['blossom', 'cherry', 'flower', 'plant'],
  '💮': ['flower', 'plant', 'white'],
  '🪷': ['flower', 'lotus', 'plant'],
  '🏵️': ['flower', 'plant', 'rosette'],
  '🌹': ['flower', 'plant', 'rose'],
  '🥀': ['flower', 'plant', 'wilted'],
  '🌺': ['flower', 'hibiscus', 'plant'],
  '🌻': ['flower', 'plant', 'sunflower'],
  '🌼': ['blossom', 'flower', 'plant'],
  '🌷': ['flower', 'plant', 'tulip'],
  '🪻': ['flower', 'hyacinth', 'plant'],
  '🌱': ['other', 'plant', 'seedling'],
  '🪴': ['other', 'plant', 'potted'],
  '🌲': ['evergreen', 'other', 'plant', 'tree'],
  '🌳': ['deciduous', 'other', 'plant', 'tree'],
  '🌴': ['other', 'palm', 'plant', 'tree'],
  '🌵': ['cactus', 'other', 'plant'],
  '🌾': ['of', 'other', 'plant', 'rice', 'sheaf'],
  '🌿': ['herb', 'other', 'plant'],
  '☘️': ['other', 'plant', 'shamrock'],
  '🍀': ['clover', 'four', 'leaf', 'other', 'plant'],
  '🍁': ['leaf', 'maple', 'other', 'plant'],
  '🍂': ['fallen', 'leaf', 'other', 'plant'],
  '🍃': ['fluttering', 'in', 'leaf', 'other', 'plant', 'wind'],
  '🪹': ['empty', 'nest', 'other', 'plant'],
  '🪺': ['eggs', 'nest', 'other', 'plant', 'with'],
  '🍄': ['mushroom', 'other', 'plant'],
  '🍇': ['food', 'fruit', 'grapes'],
  '🍈': ['food', 'fruit', 'melon'],
  '🍉': ['food', 'fruit', 'watermelon'],
  '🍊': ['food', 'fruit', 'tangerine'],
  '🍋': ['food', 'fruit', 'lemon'],
  '🍋‍🟩': ['food', 'fruit', 'lime'],
  '🍌': ['banana', 'food', 'fruit'],
  '🍍': ['food', 'fruit', 'pineapple'],
  '🥭': ['food', 'fruit', 'mango'],
  '🍎': ['apple', 'food', 'fruit', 'red'],
  '🍏': ['apple', 'food', 'fruit', 'green'],
  '🍐': ['food', 'fruit', 'pear'],
  '🍑': ['food', 'fruit', 'peach'],
  '🍒': ['cherries', 'food', 'fruit'],
  '🍓': ['food', 'fruit', 'strawberry'],
  '🫐': ['blueberries', 'food', 'fruit'],
  '🥝': ['food', 'fruit', 'kiwi'],
  '🍅': ['food', 'fruit', 'tomato'],
  '🫒': ['food', 'fruit', 'olive'],
  '🥥': ['coconut', 'food', 'fruit'],
  '🥑': ['avocado', 'food', 'vegetable'],
  '🍆': ['eggplant', 'food', 'vegetable'],
  '🥔': ['food', 'potato', 'vegetable'],
  '🥕': ['carrot', 'food', 'vegetable'],
  '🌽': ['corn', 'ear', 'food', 'of', 'vegetable'],
  '🌶️': ['food', 'hot', 'pepper', 'vegetable'],
  '🫑': ['bell', 'food', 'pepper', 'vegetable'],
  '🥒': ['cucumber', 'food', 'vegetable'],
  '🥬': ['food', 'green', 'leafy', 'vegetable'],
  '🥦': ['broccoli', 'food', 'vegetable'],
  '🧄': ['food', 'garlic', 'vegetable'],
  '🧅': ['food', 'onion', 'vegetable'],
  '🥜': ['food', 'peanuts', 'vegetable'],
  '🫘': ['beans', 'food', 'vegetable'],
  '🌰': ['chestnut', 'food', 'vegetable'],
  '🫚': ['food', 'ginger', 'root', 'vegetable'],
  '🫛': ['food', 'pea', 'pod', 'vegetable'],
  '🍄‍🟫': ['brown', 'food', 'mushroom', 'vegetable'],
  '🍞': ['bread', 'food', 'prepared'],
  '🥐': ['croissant', 'food', 'prepared'],
  '🥖': ['baguette', 'bread', 'food', 'prepared'],
  '🫓': ['flatbread', 'food', 'prepared'],
  '🥨': ['food', 'prepared', 'pretzel'],
  '🥯': ['bagel', 'food', 'prepared'],
  '🥞': ['food', 'pancakes', 'prepared'],
  '🧇': ['food', 'prepared', 'waffle'],
  '🧀': ['cheese', 'food', 'prepared', 'wedge'],
  '🍖': ['bone', 'food', 'meat', 'on', 'prepared'],
  '🍗': ['food', 'leg', 'poultry', 'prepared'],
  '🥩': ['cut', 'food', 'meat', 'of', 'prepared'],
  '🥓': ['bacon', 'food', 'prepared'],
  '🍔': ['food', 'hamburger', 'prepared'],
  '🍟': ['food', 'french', 'fries', 'prepared'],
  '🍕': ['food', 'pizza', 'prepared'],
  '🌭': ['dog', 'food', 'hot', 'prepared'],
  '🥪': ['food', 'prepared', 'sandwich'],
  '🌮': ['food', 'prepared', 'taco'],
  '🌯': ['burrito', 'food', 'prepared'],
  '🫔': ['food', 'prepared', 'tamale'],
  '🥙': ['flatbread', 'food', 'prepared', 'stuffed'],
  '🧆': ['falafel', 'food', 'prepared'],
  '🥚': ['egg', 'food', 'prepared'],
  '🍳': ['cooking', 'food', 'prepared'],
  '🥘': ['food', 'of', 'pan', 'prepared', 'shallow'],
  '🍲': ['food', 'of', 'pot', 'prepared'],
  '🫕': ['fondue', 'food', 'prepared'],
  '🥣': ['bowl', 'food', 'prepared', 'spoon', 'with'],
  '🥗': ['food', 'green', 'prepared', 'salad'],
  '🍿': ['food', 'popcorn', 'prepared'],
  '🧈': ['butter', 'food', 'prepared'],
  '🧂': ['food', 'prepared', 'salt'],
  '🥫': ['canned', 'food', 'prepared'],
  '🍱': ['asian', 'bento', 'box', 'food'],
  '🍘': ['asian', 'cracker', 'food', 'rice'],
  '🍙': ['asian', 'ball', 'food', 'rice'],
  '🍚': ['asian', 'cooked', 'food', 'rice'],
  '🍛': ['asian', 'curry', 'food', 'rice'],
  '🍜': ['asian', 'bowl', 'food', 'steaming'],
  '🍝': ['asian', 'food', 'spaghetti'],
  '🍠': ['asian', 'food', 'potato', 'roasted', 'sweet'],
  '🍢': ['asian', 'food', 'oden'],
  '🍣': ['asian', 'food', 'sushi'],
  '🍤': ['asian', 'food', 'fried', 'shrimp'],
  '🍥': ['asian', 'cake', 'fish', 'food', 'swirl', 'with'],
  '🥮': ['asian', 'cake', 'food', 'moon'],
  '🍡': ['asian', 'dango', 'food'],
  '🥟': ['asian', 'dumpling', 'food'],
  '🥠': ['asian', 'cookie', 'food', 'fortune'],
  '🥡': ['asian', 'box', 'food', 'takeout'],
  '🦀': ['crab', 'food', 'marine'],
  '🦞': ['food', 'lobster', 'marine'],
  '🦐': ['food', 'marine', 'shrimp'],
  '🦑': ['food', 'marine', 'squid'],
  '🦪': ['food', 'marine', 'oyster'],
  '🍦': ['cream', 'food', 'ice', 'soft', 'sweet'],
  '🍧': ['food', 'ice', 'shaved', 'sweet'],
  '🍨': ['cream', 'food', 'ice', 'sweet'],
  '🍩': ['doughnut', 'food', 'sweet'],
  '🍪': ['cookie', 'food', 'sweet'],
  '🎂': ['birthday', 'cake', 'food', 'sweet'],
  '🍰': ['food', 'shortcake', 'sweet'],
  '🧁': ['cupcake', 'food', 'sweet'],
  '🥧': ['food', 'pie', 'sweet'],
  '🍫': ['bar', 'chocolate', 'food', 'sweet'],
  '🍬': ['candy', 'food', 'sweet'],
  '🍭': ['food', 'lollipop', 'sweet'],
  '🍮': ['custard', 'food', 'sweet'],
  '🍯': ['food', 'honey', 'pot', 'sweet'],
  '🍼': ['baby', 'bottle', 'drink'],
  '🥛': ['drink', 'glass', 'milk', 'of'],
  '☕': ['beverage', 'drink', 'hot'],
  '🫖': ['drink', 'teapot'],
  '🍵': ['drink', 'handle', 'teacup', 'without'],
  '🍶': ['drink', 'sake'],
  '🍾': ['bottle', 'cork', 'drink', 'popping', 'with'],
  '🍷': ['drink', 'glass', 'wine'],
  '🍸': ['cocktail', 'drink', 'glass'],
  '🍹': ['drink', 'tropical'],
  '🍺': ['beer', 'drink', 'mug'],
  '🍻': ['beer', 'clinking', 'drink', 'mugs'],
  '🥂': ['clinking', 'drink', 'glasses'],
  '🥃': ['drink', 'glass', 'tumbler'],
  '🫗': ['drink', 'liquid', 'pouring'],
  '🥤': ['cup', 'drink', 'straw', 'with'],
  '🧋': ['bubble', 'drink', 'tea'],
  '🧃': ['beverage', 'box', 'drink'],
  '🧉': ['drink', 'mate'],
  '🧊': ['drink', 'ice'],
  '🥢': ['chopsticks', 'dishware'],
  '🍽️': ['and', 'dishware', 'fork', 'knife', 'plate', 'with'],
  '🍴': ['and', 'dishware', 'fork', 'knife'],
  '🥄': ['dishware', 'spoon'],
  '🔪': ['dishware', 'kitchen', 'knife'],
  '🫙': ['dishware', 'jar'],
  '🏺': ['amphora', 'dishware'],
  '🌍': ['africa', 'europe', 'globe', 'map', 'place', 'showing'],
  '🌎': ['americas', 'globe', 'map', 'place', 'showing'],
  '🌏': ['asia', 'australia', 'globe', 'map', 'place', 'showing'],
  '🌐': ['globe', 'map', 'meridians', 'place', 'with'],
  '🗺️': ['map', 'place', 'world'],
  '🗾': ['japan', 'map', 'of', 'place'],
  '🧭': ['compass', 'map', 'place'],
  '🏔️': ['capped', 'geographic', 'mountain', 'place', 'snow'],
  '⛰️': ['geographic', 'mountain', 'place'],
  '🌋': ['geographic', 'place', 'volcano'],
  '🗻': ['fuji', 'geographic', 'mount', 'place'],
  '🏕️': ['camping', 'geographic', 'place'],
  '🏖️': ['beach', 'geographic', 'place', 'umbrella', 'with'],
  '🏜️': ['desert', 'geographic', 'place'],
  '🏝️': ['desert', 'geographic', 'island', 'place'],
  '🏞️': ['geographic', 'national', 'park', 'place'],
  '🏟️': ['building', 'place', 'stadium'],
  '🏛️': ['building', 'classical', 'place'],
  '🏗️': ['building', 'construction', 'place'],
  '🧱': ['brick', 'building', 'place'],
  '🪨': ['building', 'place', 'rock'],
  '🪵': ['building', 'place', 'wood'],
  '🛖': ['building', 'hut', 'place'],
  '🏘️': ['building', 'houses', 'place'],
  '🏚️': ['building', 'derelict', 'house', 'place'],
  '🏠': ['building', 'house', 'place'],
  '🏡': ['building', 'garden', 'house', 'place', 'with'],
  '🏢': ['building', 'office', 'place'],
  '🏣': ['building', 'japanese', 'office', 'place', 'post'],
  '🏤': ['building', 'office', 'place', 'post'],
  '🏥': ['building', 'hospital', 'place'],
  '🏦': ['bank', 'building', 'place'],
  '🏨': ['building', 'hotel', 'place'],
  '🏩': ['building', 'hotel', 'love', 'place'],
  '🏪': ['building', 'convenience', 'place', 'store'],
  '🏫': ['building', 'place', 'school'],
  '🏬': ['building', 'department', 'place', 'store'],
  '🏭': ['building', 'factory', 'place'],
  '🏯': ['building', 'castle', 'japanese', 'place'],
  '🏰': ['building', 'castle', 'place'],
  '💒': ['building', 'place', 'wedding'],
  '🗼': ['building', 'place', 'tokyo', 'tower'],
  '🗽': ['building', 'liberty', 'of', 'place', 'statue'],
  '⛪': ['church', 'place', 'religious'],
  '🕌': ['mosque', 'place', 'religious'],
  '🛕': ['hindu', 'place', 'religious', 'temple'],
  '🕍': ['place', 'religious', 'synagogue'],
  '⛩️': ['place', 'religious', 'shinto', 'shrine'],
  '🕋': ['kaaba', 'place', 'religious'],
  '⛲': ['fountain', 'other', 'place'],
  '⛺': ['other', 'place', 'tent'],
  '🌁': ['foggy', 'other', 'place'],
  '🌃': ['night', 'other', 'place', 'stars', 'with'],
  '🏙️': ['cityscape', 'other', 'place'],
  '🌄': ['mountains', 'other', 'over', 'place', 'sunrise'],
  '🌅': ['other', 'place', 'sunrise'],
  '🌆': ['at', 'cityscape', 'dusk', 'other', 'place'],
  '🌇': ['other', 'place', 'sunset'],
  '🌉': ['at', 'bridge', 'night', 'other', 'place'],
  '♨️': ['hot', 'other', 'place', 'springs'],
  '🎠': ['carousel', 'horse', 'other', 'place'],
  '🛝': ['other', 'place', 'playground', 'slide'],
  '🎡': ['ferris', 'other', 'place', 'wheel'],
  '🎢': ['coaster', 'other', 'place', 'roller'],
  '💈': ['barber', 'other', 'place', 'pole'],
  '🎪': ['circus', 'other', 'place', 'tent'],
  '🚂': ['ground', 'locomotive', 'transport'],
  '🚃': ['car', 'ground', 'railway', 'transport'],
  '🚄': ['ground', 'high', 'speed', 'train', 'transport'],
  '🚅': ['bullet', 'ground', 'train', 'transport'],
  '🚆': ['ground', 'train', 'transport'],
  '🚇': ['ground', 'metro', 'transport'],
  '🚈': ['ground', 'light', 'rail', 'transport'],
  '🚉': ['ground', 'station', 'transport'],
  '🚊': ['ground', 'tram', 'transport'],
  '🚝': ['ground', 'monorail', 'transport'],
  '🚞': ['ground', 'mountain', 'railway', 'transport'],
  '🚋': ['car', 'ground', 'tram', 'transport'],
  '🚌': ['bus', 'ground', 'transport'],
  '🚍': ['bus', 'ground', 'oncoming', 'transport'],
  '🚎': ['ground', 'transport', 'trolleybus'],
  '🚐': ['ground', 'minibus', 'transport'],
  '🚑': ['ambulance', 'ground', 'transport'],
  '🚒': ['engine', 'fire', 'ground', 'transport'],
  '🚓': ['car', 'ground', 'police', 'transport'],
  '🚔': ['car', 'ground', 'oncoming', 'police', 'transport'],
  '🚕': ['ground', 'taxi', 'transport'],
  '🚖': ['ground', 'oncoming', 'taxi', 'transport'],
  '🚗': ['automobile', 'ground', 'transport'],
  '🚘': ['automobile', 'ground', 'oncoming', 'transport'],
  '🚙': ['ground', 'sport', 'transport', 'utility', 'vehicle'],
  '🛻': ['ground', 'pickup', 'transport', 'truck'],
  '🚚': ['delivery', 'ground', 'transport', 'truck'],
  '🚛': ['articulated', 'ground', 'lorry', 'transport'],
  '🚜': ['ground', 'tractor', 'transport'],
  '🏎️': ['car', 'ground', 'racing', 'transport'],
  '🏍️': ['ground', 'motorcycle', 'transport'],
  '🛵': ['ground', 'motor', 'scooter', 'transport'],
  '🦽': ['ground', 'manual', 'transport', 'wheelchair'],
  '🦼': ['ground', 'motorized', 'transport', 'wheelchair'],
  '🛺': ['auto', 'ground', 'rickshaw', 'transport'],
  '🚲': ['bicycle', 'ground', 'transport'],
  '🛴': ['ground', 'kick', 'scooter', 'transport'],
  '🛹': ['ground', 'skateboard', 'transport'],
  '🛼': ['ground', 'roller', 'skate', 'transport'],
  '🚏': ['bus', 'ground', 'stop', 'transport'],
  '🛣️': ['ground', 'motorway', 'transport'],
  '🛤️': ['ground', 'railway', 'track', 'transport'],
  '🛢️': ['drum', 'ground', 'oil', 'transport'],
  '⛽': ['fuel', 'ground', 'pump', 'transport'],
  '🛞': ['ground', 'transport', 'wheel'],
  '🚨': ['car', 'ground', 'light', 'police', 'transport'],
  '🚥': ['ground', 'horizontal', 'light', 'traffic', 'transport'],
  '🚦': ['ground', 'light', 'traffic', 'transport', 'vertical'],
  '🛑': ['ground', 'sign', 'stop', 'transport'],
  '🚧': ['construction', 'ground', 'transport'],
  '⚓': ['anchor', 'transport', 'water'],
  '🛟': ['buoy', 'ring', 'transport', 'water'],
  '⛵': ['sailboat', 'transport', 'water'],
  '🛶': ['canoe', 'transport', 'water'],
  '🚤': ['speedboat', 'transport', 'water'],
  '🛳️': ['passenger', 'ship', 'transport', 'water'],
  '⛴️': ['ferry', 'transport', 'water'],
  '🛥️': ['boat', 'motor', 'transport', 'water'],
  '🚢': ['ship', 'transport', 'water'],
  '✈️': ['air', 'airplane', 'transport'],
  '🛩️': ['air', 'airplane', 'small', 'transport'],
  '🛫': ['air', 'airplane', 'departure', 'transport'],
  '🛬': ['air', 'airplane', 'arrival', 'transport'],
  '🪂': ['air', 'parachute', 'transport'],
  '💺': ['air', 'seat', 'transport'],
  '🚁': ['air', 'helicopter', 'transport'],
  '🚟': ['air', 'railway', 'suspension', 'transport'],
  '🚠': ['air', 'cableway', 'mountain', 'transport'],
  '🚡': ['aerial', 'air', 'tramway', 'transport'],
  '🛰️': ['air', 'satellite', 'transport'],
  '🚀': ['air', 'rocket', 'transport'],
  '🛸': ['air', 'flying', 'saucer', 'transport'],
  '🛎️': ['bell', 'bellhop', 'hotel'],
  '🧳': ['hotel', 'luggage'],
  '⌛': ['done', 'hourglass', 'time'],
  '⏳': ['done', 'hourglass', 'not', 'time'],
  '⌚': ['time', 'watch'],
  '⏰': ['alarm', 'clock', 'time'],
  '⏱️': ['stopwatch', 'time'],
  '⏲️': ['clock', 'time', 'timer'],
  '🕰️': ['clock', 'mantelpiece', 'time'],
  '🕛': ['clock', 'o', 'time', 'twelve'],
  '🕧': ['thirty', 'time', 'twelve'],
  '🕐': ['clock', 'o', 'one', 'time'],
  '🕜': ['one', 'thirty', 'time'],
  '🕑': ['clock', 'o', 'time', 'two'],
  '🕝': ['thirty', 'time', 'two'],
  '🕒': ['clock', 'o', 'three', 'time'],
  '🕞': ['thirty', 'three', 'time'],
  '🕓': ['clock', 'four', 'o', 'time'],
  '🕟': ['four', 'thirty', 'time'],
  '🕔': ['clock', 'five', 'o', 'time'],
  '🕠': ['five', 'thirty', 'time'],
  '🕕': ['clock', 'o', 'six', 'time'],
  '🕡': ['six', 'thirty', 'time'],
  '🕖': ['clock', 'o', 'seven', 'time'],
  '🕢': ['seven', 'thirty', 'time'],
  '🕗': ['clock', 'eight', 'o', 'time'],
  '🕣': ['eight', 'thirty', 'time'],
  '🕘': ['clock', 'nine', 'o', 'time'],
  '🕤': ['nine', 'thirty', 'time'],
  '🕙': ['clock', 'o', 'ten', 'time'],
  '🕥': ['ten', 'thirty', 'time'],
  '🕚': ['clock', 'eleven', 'o', 'time'],
  '🕦': ['eleven', 'thirty', 'time'],
  '🌑': ['moon', 'new', 'sky', 'weather'],
  '🌒': ['crescent', 'moon', 'sky', 'waxing', 'weather'],
  '🌓': ['first', 'moon', 'quarter', 'sky', 'weather'],
  '🌔': ['gibbous', 'moon', 'sky', 'waxing', 'weather'],
  '🌕': ['full', 'moon', 'sky', 'weather'],
  '🌖': ['gibbous', 'moon', 'sky', 'waning', 'weather'],
  '🌗': ['last', 'moon', 'quarter', 'sky', 'weather'],
  '🌘': ['crescent', 'moon', 'sky', 'waning', 'weather'],
  '🌙': ['crescent', 'moon', 'sky', 'weather'],
  '🌚': ['face', 'moon', 'new', 'sky', 'weather'],
  '🌛': ['face', 'first', 'moon', 'quarter', 'sky', 'weather'],
  '🌜': ['face', 'last', 'moon', 'quarter', 'sky', 'weather'],
  '🌡️': ['sky', 'thermometer', 'weather'],
  '☀️': ['sky', 'sun', 'weather'],
  '🌝': ['face', 'full', 'moon', 'sky', 'weather'],
  '🌞': ['face', 'sky', 'sun', 'weather', 'with'],
  '🪐': ['planet', 'ringed', 'sky', 'weather'],
  '⭐': ['sky', 'star', 'weather'],
  '🌟': ['glowing', 'sky', 'star', 'weather'],
  '🌠': ['shooting', 'sky', 'star', 'weather'],
  '🌌': ['milky', 'sky', 'way', 'weather'],
  '☁️': ['cloud', 'sky', 'weather'],
  '⛅': ['behind', 'cloud', 'sky', 'sun', 'weather'],
  '⛈️': ['and', 'cloud', 'lightning', 'rain', 'sky', 'weather', 'with'],
  '🌤️': ['behind', 'cloud', 'sky', 'small', 'sun', 'weather'],
  '🌥️': ['behind', 'cloud', 'large', 'sky', 'sun', 'weather'],
  '🌦️': ['behind', 'cloud', 'rain', 'sky', 'sun', 'weather'],
  '🌧️': ['cloud', 'rain', 'sky', 'weather', 'with'],
  '🌨️': ['cloud', 'sky', 'snow', 'weather', 'with'],
  '🌩️': ['cloud', 'lightning', 'sky', 'weather', 'with'],
  '🌪️': ['sky', 'tornado', 'weather'],
  '🌫️': ['fog', 'sky', 'weather'],
  '🌬️': ['face', 'sky', 'weather', 'wind'],
  '🌀': ['cyclone', 'sky', 'weather'],
  '🌈': ['rainbow', 'sky', 'weather'],
  '🌂': ['closed', 'sky', 'umbrella', 'weather'],
  '☂️': ['sky', 'umbrella', 'weather'],
  '☔': ['drops', 'rain', 'sky', 'umbrella', 'weather', 'with'],
  '⛱️': ['ground', 'on', 'sky', 'umbrella', 'weather'],
  '⚡': ['high', 'sky', 'voltage', 'weather'],
  '❄️': ['sky', 'snowflake', 'weather'],
  '☃️': ['sky', 'snowman', 'weather'],
  '⛄': ['sky', 'snow', 'snowman', 'weather', 'without'],
  '☄️': ['comet', 'sky', 'weather'],
  '🔥': ['fire', 'sky', 'weather'],
  '💧': ['droplet', 'sky', 'weather'],
  '🌊': ['sky', 'water', 'wave', 'weather'],
  '🎃': ['event', 'jack', 'lantern', 'o'],
  '🎄': ['christmas', 'event', 'tree'],
  '🎆': ['event', 'fireworks'],
  '🎇': ['event', 'sparkler'],
  '🧨': ['event', 'firecracker'],
  '✨': ['event', 'sparkles'],
  '🎈': ['balloon', 'event'],
  '🎉': ['event', 'party', 'popper'],
  '🎊': ['ball', 'confetti', 'event'],
  '🎋': ['event', 'tanabata', 'tree'],
  '🎍': ['decoration', 'event', 'pine'],
  '🎎': ['dolls', 'event', 'japanese'],
  '🎏': ['carp', 'event', 'streamer'],
  '🎐': ['chime', 'event', 'wind'],
  '🎑': ['ceremony', 'event', 'moon', 'viewing'],
  '🧧': ['envelope', 'event', 'red'],
  '🎀': ['event', 'ribbon'],
  '🎁': ['event', 'gift', 'wrapped'],
  '🎗️': ['event', 'reminder', 'ribbon'],
  '🎟️': ['admission', 'event', 'tickets'],
  '🎫': ['event', 'ticket'],
  '🎖️': ['award', 'medal', 'military'],
  '🏆': ['award', 'medal', 'trophy'],
  '🏅': ['award', 'medal', 'sports'],
  '🥇': ['1st', 'award', 'medal', 'place'],
  '🥈': ['2nd', 'award', 'medal', 'place'],
  '🥉': ['3rd', 'award', 'medal', 'place'],
  '⚽': ['ball', 'soccer', 'sport'],
  '⚾': ['baseball', 'sport'],
  '🥎': ['softball', 'sport'],
  '🏀': ['basketball', 'sport'],
  '🏐': ['sport', 'volleyball'],
  '🏈': ['american', 'football', 'sport'],
  '🏉': ['football', 'rugby', 'sport'],
  '🎾': ['sport', 'tennis'],
  '🥏': ['disc', 'flying', 'sport'],
  '🎳': ['bowling', 'sport'],
  '🏏': ['cricket', 'game', 'sport'],
  '🏑': ['field', 'hockey', 'sport'],
  '🏒': ['hockey', 'ice', 'sport'],
  '🥍': ['lacrosse', 'sport'],
  '🏓': ['ping', 'pong', 'sport'],
  '🏸': ['badminton', 'sport'],
  '🥊': ['boxing', 'glove', 'sport'],
  '🥋': ['arts', 'martial', 'sport', 'uniform'],
  '🥅': ['goal', 'net', 'sport'],
  '⛳': ['flag', 'hole', 'in', 'sport'],
  '⛸️': ['ice', 'skate', 'sport'],
  '🎣': ['fishing', 'pole', 'sport'],
  '🤿': ['diving', 'mask', 'sport'],
  '🎽': ['running', 'shirt', 'sport'],
  '🎿': ['skis', 'sport'],
  '🛷': ['sled', 'sport'],
  '🥌': ['curling', 'sport', 'stone'],
  '🎯': ['bullseye', 'game'],
  '🪀': ['game', 'yo'],
  '🪁': ['game', 'kite'],
  '🔫': ['game', 'pistol', 'water'],
  '🎱': ['8', 'ball', 'game', 'pool'],
  '🔮': ['ball', 'crystal', 'game'],
  '🪄': ['game', 'magic', 'wand'],
  '🎮': ['game', 'video'],
  '🕹️': ['game', 'joystick'],
  '🎰': ['game', 'machine', 'slot'],
  '🎲': ['die', 'game'],
  '🧩': ['game', 'piece', 'puzzle'],
  '🧸': ['bear', 'game', 'teddy'],
  '🪅': ['ata', 'game', 'pi'],
  '🪩': ['ball', 'game', 'mirror'],
  '🪆': ['dolls', 'game', 'nesting'],
  '♠️': ['game', 'spade', 'suit'],
  '♥️': ['game', 'heart', 'suit'],
  '♦️': ['diamond', 'game', 'suit'],
  '♣️': ['club', 'game', 'suit'],
  '♟️': ['chess', 'game', 'pawn'],
  '🃏': ['game', 'joker'],
  '🀄': ['dragon', 'game', 'mahjong', 'red'],
  '🎴': ['cards', 'flower', 'game', 'playing'],
  '🎭': ['arts', 'crafts', 'performing'],
  '🖼️': ['arts', 'crafts', 'framed', 'picture'],
  '🎨': ['artist', 'arts', 'crafts', 'palette'],
  '🧵': ['arts', 'crafts', 'thread'],
  '🪡': ['arts', 'crafts', 'needle', 'sewing'],
  '🧶': ['arts', 'crafts', 'yarn'],
  '🪢': ['arts', 'crafts', 'knot'],
  '👓': ['clothing', 'glasses'],
  '🕶️': ['clothing', 'sunglasses'],
  '🥽': ['clothing', 'goggles'],
  '🥼': ['clothing', 'coat', 'lab'],
  '🦺': ['clothing', 'safety', 'vest'],
  '👔': ['clothing', 'necktie'],
  '👕': ['clothing', 'shirt', 't'],
  '👖': ['clothing', 'jeans'],
  '🧣': ['clothing', 'scarf'],
  '🧤': ['clothing', 'gloves'],
  '🧥': ['clothing', 'coat'],
  '🧦': ['clothing', 'socks'],
  '👗': ['clothing', 'dress'],
  '👘': ['clothing', 'kimono'],
  '🥻': ['clothing', 'sari'],
  '🩱': ['clothing', 'one', 'piece', 'swimsuit'],
  '🩲': ['briefs', 'clothing'],
  '🩳': ['clothing', 'shorts'],
  '👙': ['bikini', 'clothing'],
  '👚': ['clothes', 'clothing', 's', 'woman'],
  '🪭': ['clothing', 'fan', 'folding', 'hand'],
  '👛': ['clothing', 'purse'],
  '👜': ['clothing', 'handbag'],
  '👝': ['bag', 'clothing', 'clutch'],
  '🛍️': ['bags', 'clothing', 'shopping'],
  '🎒': ['backpack', 'clothing'],
  '🩴': ['clothing', 'sandal', 'thong'],
  '👞': ['clothing', 'man', 's', 'shoe'],
  '👟': ['clothing', 'running', 'shoe'],
  '🥾': ['boot', 'clothing', 'hiking'],
  '🥿': ['clothing', 'flat', 'shoe'],
  '👠': ['clothing', 'heeled', 'high', 'shoe'],
  '👡': ['clothing', 's', 'sandal', 'woman'],
  '🩰': ['ballet', 'clothing', 'shoes'],
  '👢': ['boot', 'clothing', 's', 'woman'],
  '🪮': ['clothing', 'hair', 'pick'],
  '👑': ['clothing', 'crown'],
  '👒': ['clothing', 'hat', 's', 'woman'],
  '🎩': ['clothing', 'hat', 'top'],
  '🎓': ['cap', 'clothing', 'graduation'],
  '🧢': ['billed', 'cap', 'clothing'],
  '🪖': ['clothing', 'helmet', 'military'],
  '⛑️': ['clothing', 'helmet', 'rescue', 's', 'worker'],
  '📿': ['beads', 'clothing', 'prayer'],
  '💄': ['clothing', 'lipstick'],
  '💍': ['clothing', 'ring'],
  '💎': ['clothing', 'gem', 'stone'],
  '🔇': ['muted', 'sound', 'speaker'],
  '🔈': ['low', 'sound', 'speaker', 'volume'],
  '🔉': ['medium', 'sound', 'speaker', 'volume'],
  '🔊': ['high', 'sound', 'speaker', 'volume'],
  '📢': ['loudspeaker', 'sound'],
  '📣': ['megaphone', 'sound'],
  '📯': ['horn', 'postal', 'sound'],
  '🔔': ['bell', 'sound'],
  '🔕': ['bell', 'slash', 'sound', 'with'],
  '🎼': ['music', 'musical', 'score'],
  '🎵': ['music', 'musical', 'note'],
  '🎶': ['music', 'musical', 'notes'],
  '🎙️': ['microphone', 'music', 'studio'],
  '🎚️': ['level', 'music', 'slider'],
  '🎛️': ['control', 'knobs', 'music'],
  '🎤': ['microphone', 'music'],
  '🎧': ['headphone', 'music'],
  '📻': ['music', 'radio'],
  '🎷': ['instrument', 'musical', 'saxophone'],
  '🪗': ['accordion', 'instrument', 'musical'],
  '🎸': ['guitar', 'instrument', 'musical'],
  '🎹': ['instrument', 'keyboard', 'musical'],
  '🎺': ['instrument', 'musical', 'trumpet'],
  '🎻': ['instrument', 'musical', 'violin'],
  '🪕': ['banjo', 'instrument', 'musical'],
  '🥁': ['drum', 'instrument', 'musical'],
  '🪘': ['drum', 'instrument', 'long', 'musical'],
  '🪇': ['instrument', 'maracas', 'musical'],
  '🪈': ['flute', 'instrument', 'musical'],
  '📱': ['mobile', 'phone'],
  '📲': ['arrow', 'mobile', 'phone', 'with'],
  '☎️': ['phone', 'telephone'],
  '📞': ['phone', 'receiver', 'telephone'],
  '📟': ['pager', 'phone'],
  '📠': ['fax', 'machine', 'phone'],
  '🔋': ['battery', 'computer'],
  '🪫': ['battery', 'computer', 'low'],
  '🔌': ['computer', 'electric', 'plug'],
  '💻': ['computer', 'laptop'],
  '🖥️': ['computer', 'desktop'],
  '🖨️': ['computer', 'printer'],
  '⌨️': ['computer', 'keyboard'],
  '🖱️': ['computer', 'mouse'],
  '🖲️': ['computer', 'trackball'],
  '💽': ['computer', 'disk'],
  '💾': ['computer', 'disk', 'floppy'],
  '💿': ['computer', 'disk', 'optical'],
  '📀': ['computer', 'dvd'],
  '🧮': ['abacus', 'computer'],
  '🎥': ['camera', 'light', 'movie', 'video'],
  '🎞️': ['film', 'frames', 'light', 'video'],
  '📽️': ['film', 'light', 'projector', 'video'],
  '🎬': ['board', 'clapper', 'light', 'video'],
  '📺': ['light', 'television', 'video'],
  '📷': ['camera', 'light', 'video'],
  '📸': ['camera', 'flash', 'light', 'video', 'with'],
  '📹': ['camera', 'light', 'video'],
  '📼': ['light', 'video', 'videocassette'],
  '🔍': ['glass', 'left', 'light', 'magnifying', 'tilted', 'video'],
  '🔎': ['glass', 'light', 'magnifying', 'right', 'tilted', 'video'],
  '🕯️': ['candle', 'light', 'video'],
  '💡': ['bulb', 'light', 'video'],
  '🔦': ['flashlight', 'light', 'video'],
  '🏮': ['lantern', 'light', 'paper', 'red', 'video'],
  '🪔': ['diya', 'lamp', 'light', 'video'],
  '📔': ['book', 'cover', 'decorative', 'notebook', 'paper', 'with'],
  '📕': ['book', 'closed', 'paper'],
  '📖': ['book', 'open', 'paper'],
  '📗': ['book', 'green', 'paper'],
  '📘': ['blue', 'book', 'paper'],
  '📙': ['book', 'orange', 'paper'],
  '📚': ['book', 'books', 'paper'],
  '📓': ['book', 'notebook', 'paper'],
  '📒': ['book', 'ledger', 'paper'],
  '📃': ['book', 'curl', 'page', 'paper', 'with'],
  '📜': ['book', 'paper', 'scroll'],
  '📄': ['book', 'facing', 'page', 'paper', 'up'],
  '📰': ['book', 'newspaper', 'paper'],
  '🗞️': ['book', 'newspaper', 'paper', 'rolled', 'up'],
  '📑': ['book', 'bookmark', 'paper', 'tabs'],
  '🔖': ['book', 'bookmark', 'paper'],
  '🏷️': ['book', 'label', 'paper'],
  '💰': ['bag', 'money'],
  '🪙': ['coin', 'money'],
  '💴': ['banknote', 'money', 'yen'],
  '💵': ['banknote', 'dollar', 'money'],
  '💶': ['banknote', 'euro', 'money'],
  '💷': ['banknote', 'money', 'pound'],
  '💸': ['money', 'wings', 'with'],
  '💳': ['card', 'credit', 'money'],
  '🧾': ['money', 'receipt'],
  '💹': ['chart', 'increasing', 'money', 'with', 'yen'],
  '✉️': ['envelope', 'mail'],
  '📧': ['e', 'mail'],
  '📨': ['envelope', 'incoming', 'mail'],
  '📩': ['arrow', 'envelope', 'mail', 'with'],
  '📤': ['mail', 'outbox', 'tray'],
  '📥': ['inbox', 'mail', 'tray'],
  '📦': ['mail', 'package'],
  '📫': ['closed', 'flag', 'mail', 'mailbox', 'raised', 'with'],
  '📪': ['closed', 'flag', 'lowered', 'mail', 'mailbox', 'with'],
  '📬': ['flag', 'mail', 'mailbox', 'open', 'raised', 'with'],
  '📭': ['flag', 'lowered', 'mail', 'mailbox', 'open', 'with'],
  '📮': ['mail', 'postbox'],
  '🗳️': ['ballot', 'box', 'mail', 'with'],
  '✏️': ['pencil', 'writing'],
  '✒️': ['black', 'nib', 'writing'],
  '🖋️': ['fountain', 'pen', 'writing'],
  '🖊️': ['pen', 'writing'],
  '🖌️': ['paintbrush', 'writing'],
  '🖍️': ['crayon', 'writing'],
  '📝': ['memo', 'writing'],
  '💼': ['briefcase', 'office'],
  '📁': ['file', 'folder', 'office'],
  '📂': ['file', 'folder', 'office', 'open'],
  '🗂️': ['card', 'dividers', 'index', 'office'],
  '📅': ['calendar', 'office'],
  '📆': ['calendar', 'off', 'office', 'tear'],
  '🗒️': ['notepad', 'office', 'spiral'],
  '🗓️': ['calendar', 'office', 'spiral'],
  '📇': ['card', 'index', 'office'],
  '📈': ['chart', 'increasing', 'office'],
  '📉': ['chart', 'decreasing', 'office'],
  '📊': ['bar', 'chart', 'office'],
  '📋': ['clipboard', 'office'],
  '📌': ['office', 'pushpin'],
  '📍': ['office', 'pushpin', 'round'],
  '📎': ['office', 'paperclip'],
  '🖇️': ['linked', 'office', 'paperclips'],
  '📏': ['office', 'ruler', 'straight'],
  '📐': ['office', 'ruler', 'triangular'],
  '✂️': ['office', 'scissors'],
  '🗃️': ['box', 'card', 'file', 'office'],
  '🗄️': ['cabinet', 'file', 'office'],
  '🗑️': ['office', 'wastebasket'],
  '🔒': ['lock', 'locked'],
  '🔓': ['lock', 'unlocked'],
  '🔏': ['lock', 'locked', 'pen', 'with'],
  '🔐': ['key', 'lock', 'locked', 'with'],
  '🔑': ['key', 'lock'],
  '🗝️': ['key', 'lock', 'old'],
  '🔨': ['hammer', 'tool'],
  '🪓': ['axe', 'tool'],
  '⛏️': ['pick', 'tool'],
  '⚒️': ['and', 'hammer', 'pick', 'tool'],
  '🛠️': ['and', 'hammer', 'tool', 'wrench'],
  '🗡️': ['dagger', 'tool'],
  '⚔️': ['crossed', 'swords', 'tool'],
  '💣': ['bomb', 'tool'],
  '🪃': ['boomerang', 'tool'],
  '🏹': ['and', 'arrow', 'bow', 'tool'],
  '🛡️': ['shield', 'tool'],
  '🪚': ['carpentry', 'saw', 'tool'],
  '🔧': ['tool', 'wrench'],
  '🪛': ['screwdriver', 'tool'],
  '🔩': ['and', 'bolt', 'nut', 'tool'],
  '⚙️': ['gear', 'tool'],
  '🗜️': ['clamp', 'tool'],
  '⚖️': ['balance', 'scale', 'tool'],
  '🦯': ['cane', 'tool', 'white'],
  '🔗': ['link', 'tool'],
  '⛓️‍💥': ['broken', 'chain', 'tool'],
  '⛓️': ['chains', 'tool'],
  '🪝': ['hook', 'tool'],
  '🧰': ['tool', 'toolbox'],
  '🧲': ['magnet', 'tool'],
  '🪜': ['ladder', 'tool'],
  '⚗️': ['alembic', 'science'],
  '🧪': ['science', 'test', 'tube'],
  '🧫': ['dish', 'petri', 'science'],
  '🧬': ['dna', 'science'],
  '🔬': ['microscope', 'science'],
  '🔭': ['science', 'telescope'],
  '📡': ['antenna', 'satellite', 'science'],
  '💉': ['medical', 'syringe'],
  '🩸': ['blood', 'drop', 'medical', 'of'],
  '💊': ['medical', 'pill'],
  '🩹': ['adhesive', 'bandage', 'medical'],
  '🩼': ['crutch', 'medical'],
  '🩺': ['medical', 'stethoscope'],
  '🩻': ['medical', 'ray', 'x'],
  '🚪': ['door', 'household'],
  '🛗': ['elevator', 'household'],
  '🪞': ['household', 'mirror'],
  '🪟': ['household', 'window'],
  '🛏️': ['bed', 'household'],
  '🛋️': ['and', 'couch', 'household', 'lamp'],
  '🪑': ['chair', 'household'],
  '🚽': ['household', 'toilet'],
  '🪠': ['household', 'plunger'],
  '🚿': ['household', 'shower'],
  '🛁': ['bathtub', 'household'],
  '🪤': ['household', 'mouse', 'trap'],
  '🪒': ['household', 'razor'],
  '🧴': ['bottle', 'household', 'lotion'],
  '🧷': ['household', 'pin', 'safety'],
  '🧹': ['broom', 'household'],
  '🧺': ['basket', 'household'],
  '🧻': ['household', 'of', 'paper', 'roll'],
  '🪣': ['bucket', 'household'],
  '🧼': ['household', 'soap'],
  '🫧': ['bubbles', 'household'],
  '🪥': ['household', 'toothbrush'],
  '🧽': ['household', 'sponge'],
  '🧯': ['extinguisher', 'fire', 'household'],
  '🛒': ['cart', 'household', 'shopping'],
  '🚬': ['cigarette', 'object', 'other'],
  '⚰️': ['coffin', 'object', 'other'],
  '🪦': ['headstone', 'object', 'other'],
  '⚱️': ['funeral', 'object', 'other', 'urn'],
  '🧿': ['amulet', 'nazar', 'object', 'other'],
  '🪬': ['hamsa', 'object', 'other'],
  '🗿': ['moai', 'object', 'other'],
  '🪧': ['object', 'other', 'placard'],
  '🪪': ['card', 'identification', 'object', 'other'],
  '🏧': ['atm', 'sign', 'transport'],
  '🚮': ['bin', 'in', 'litter', 'sign', 'transport'],
  '🚰': ['potable', 'sign', 'transport', 'water'],
  '♿': ['sign', 'symbol', 'transport', 'wheelchair'],
  '🚹': ['men', 'room', 's', 'sign', 'transport'],
  '🚺': ['room', 's', 'sign', 'transport', 'women'],
  '🚻': ['restroom', 'sign', 'transport'],
  '🚼': ['baby', 'sign', 'symbol', 'transport'],
  '🚾': ['closet', 'sign', 'transport', 'water'],
  '🛂': ['control', 'passport', 'sign', 'transport'],
  '🛃': ['customs', 'sign', 'transport'],
  '🛄': ['baggage', 'claim', 'sign', 'transport'],
  '🛅': ['left', 'luggage', 'sign', 'transport'],
  '⚠️': ['warning'],
  '🚸': ['children', 'crossing', 'warning'],
  '⛔': ['entry', 'no', 'warning'],
  '🚫': ['prohibited', 'warning'],
  '🚳': ['bicycles', 'no', 'warning'],
  '🚭': ['no', 'smoking', 'warning'],
  '🚯': ['littering', 'no', 'warning'],
  '🚱': ['non', 'potable', 'warning', 'water'],
  '🚷': ['no', 'pedestrians', 'warning'],
  '📵': ['mobile', 'no', 'phones', 'warning'],
  '🔞': ['eighteen', 'no', 'one', 'under', 'warning'],
  '☢️': ['radioactive', 'warning'],
  '☣️': ['biohazard', 'warning'],
  '⬆️': ['arrow', 'up'],
  '↗️': ['arrow', 'right', 'up'],
  '➡️': ['arrow', 'right'],
  '↘️': ['arrow', 'down', 'right'],
  '⬇️': ['arrow', 'down'],
  '↙️': ['arrow', 'down', 'left'],
  '⬅️': ['arrow', 'left'],
  '↖️': ['arrow', 'left', 'up'],
  '↕️': ['arrow', 'down', 'up'],
  '↔️': ['arrow', 'left', 'right'],
  '↩️': ['arrow', 'curving', 'left', 'right'],
  '↪️': ['arrow', 'curving', 'left', 'right'],
  '⤴️': ['arrow', 'curving', 'right', 'up'],
  '⤵️': ['arrow', 'curving', 'down', 'right'],
  '🔃': ['arrow', 'arrows', 'clockwise', 'vertical'],
  '🔄': ['arrow', 'arrows', 'button', 'counterclockwise'],
  '🔙': ['arrow', 'back'],
  '🔚': ['arrow', 'end'],
  '🔛': ['arrow', 'on'],
  '🔜': ['arrow', 'soon'],
  '🔝': ['arrow', 'top'],
  '🛐': ['of', 'place', 'religion', 'worship'],
  '⚛️': ['atom', 'religion', 'symbol'],
  '🕉️': ['om', 'religion'],
  '✡️': ['david', 'of', 'religion', 'star'],
  '☸️': ['dharma', 'of', 'religion', 'wheel'],
  '☯️': ['religion', 'yang', 'yin'],
  '✝️': ['cross', 'latin', 'religion'],
  '☦️': ['cross', 'orthodox', 'religion'],
  '☪️': ['and', 'crescent', 'religion', 'star'],
  '☮️': ['peace', 'religion', 'symbol'],
  '🕎': ['menorah', 'religion'],
  '🔯': ['dotted', 'pointed', 'religion', 'six', 'star'],
  '🪯': ['khanda', 'religion'],
  '♈': ['aries', 'zodiac'],
  '♉': ['taurus', 'zodiac'],
  '♊': ['gemini', 'zodiac'],
  '♋': ['cancer', 'zodiac'],
  '♌': ['leo', 'zodiac'],
  '♍': ['virgo', 'zodiac'],
  '♎': ['libra', 'zodiac'],
  '♏': ['scorpio', 'zodiac'],
  '♐': ['sagittarius', 'zodiac'],
  '♑': ['capricorn', 'zodiac'],
  '♒': ['aquarius', 'zodiac'],
  '♓': ['pisces', 'zodiac'],
  '⛎': ['ophiuchus', 'zodiac'],
  '🔀': ['av', 'button', 'shuffle', 'symbol', 'tracks'],
  '🔁': ['av', 'button', 'repeat', 'symbol'],
  '🔂': ['av', 'button', 'repeat', 'single', 'symbol'],
  '▶️': ['av', 'button', 'play', 'symbol'],
  '⏩': ['av', 'button', 'fast', 'forward', 'symbol'],
  '⏭️': ['av', 'button', 'next', 'symbol', 'track'],
  '⏯️': ['av', 'button', 'or', 'pause', 'play', 'symbol'],
  '◀️': ['av', 'button', 'reverse', 'symbol'],
  '⏪': ['av', 'button', 'fast', 'reverse', 'symbol'],
  '⏮️': ['av', 'button', 'last', 'symbol', 'track'],
  '🔼': ['av', 'button', 'symbol', 'upwards'],
  '⏫': ['av', 'button', 'fast', 'symbol', 'up'],
  '🔽': ['av', 'button', 'downwards', 'symbol'],
  '⏬': ['av', 'button', 'down', 'fast', 'symbol'],
  '⏸️': ['av', 'button', 'pause', 'symbol'],
  '⏹️': ['av', 'button', 'stop', 'symbol'],
  '⏺️': ['av', 'button', 'record', 'symbol'],
  '⏏️': ['av', 'button', 'eject', 'symbol'],
  '🎦': ['av', 'cinema', 'symbol'],
  '🔅': ['av', 'button', 'dim', 'symbol'],
  '🔆': ['av', 'bright', 'button', 'symbol'],
  '📶': ['antenna', 'av', 'bars', 'symbol'],
  '🛜': ['av', 'symbol', 'wireless'],
  '📳': ['av', 'mode', 'symbol', 'vibration'],
  '📴': ['av', 'mobile', 'off', 'phone', 'symbol'],
  '♀️': ['female', 'gender', 'sign'],
  '♂️': ['gender', 'male', 'sign'],
  '⚧️': ['gender', 'symbol', 'transgender'],
  '✖️': ['math', 'multiply'],
  '➕': ['math', 'plus'],
  '➖': ['math', 'minus'],
  '➗': ['divide', 'math'],
  '🟰': ['equals', 'heavy', 'math', 'sign'],
  '♾️': ['infinity', 'math'],
  '‼️': ['double', 'exclamation', 'mark', 'punctuation'],
  '⁉️': ['exclamation', 'mark', 'punctuation', 'question'],
  '❓': ['mark', 'punctuation', 'question', 'red'],
  '❔': ['mark', 'punctuation', 'question', 'white'],
  '❕': ['exclamation', 'mark', 'punctuation', 'white'],
  '❗': ['exclamation', 'mark', 'punctuation', 'red'],
  '〰️': ['dash', 'punctuation', 'wavy'],
  '💱': ['currency', 'exchange'],
  '💲': ['currency', 'dollar', 'heavy', 'sign'],
  '⚕️': ['medical', 'other', 'symbol'],
  '♻️': ['other', 'recycling', 'symbol'],
  '⚜️': ['de', 'fleur', 'lis', 'other', 'symbol'],
  '🔱': ['emblem', 'other', 'symbol', 'trident'],
  '📛': ['badge', 'name', 'other', 'symbol'],
  '🔰': ['beginner', 'for', 'japanese', 'other', 'symbol'],
  '⭕': ['circle', 'hollow', 'other', 'red', 'symbol'],
  '✅': ['button', 'check', 'mark', 'other', 'symbol'],
  '☑️': ['box', 'check', 'other', 'symbol', 'with'],
  '✔️': ['check', 'mark', 'other', 'symbol'],
  '❌': ['cross', 'mark', 'other', 'symbol'],
  '❎': ['button', 'cross', 'mark', 'other', 'symbol'],
  '➰': ['curly', 'loop', 'other', 'symbol'],
  '➿': ['curly', 'double', 'loop', 'other', 'symbol'],
  '〽️': ['alternation', 'mark', 'other', 'part', 'symbol'],
  '✳️': ['asterisk', 'eight', 'other', 'spoked', 'symbol'],
  '✴️': ['eight', 'other', 'pointed', 'star', 'symbol'],
  '❇️': ['other', 'sparkle', 'symbol'],
  '©️': ['copyright', 'other', 'symbol'],
  '®️': ['other', 'registered', 'symbol'],
  '™️': ['mark', 'other', 'symbol', 'trade'],
  '#️⃣': ['keycap'],
  '*️⃣': ['keycap'],
  '0️⃣': ['0', 'keycap'],
  '1️⃣': ['1', 'keycap'],
  '2️⃣': ['2', 'keycap'],
  '3️⃣': ['3', 'keycap'],
  '4️⃣': ['4', 'keycap'],
  '5️⃣': ['5', 'keycap'],
  '6️⃣': ['6', 'keycap'],
  '7️⃣': ['7', 'keycap'],
  '8️⃣': ['8', 'keycap'],
  '9️⃣': ['9', 'keycap'],
  '🔟': ['10', 'keycap'],
  '🔠': ['alphanum', 'input', 'latin', 'uppercase'],
  '🔡': ['alphanum', 'input', 'latin', 'lowercase'],
  '🔢': ['alphanum', 'input', 'numbers'],
  '🔣': ['alphanum', 'input', 'symbols'],
  '🔤': ['alphanum', 'input', 'latin', 'letters'],
  '🅰️': ['a', 'alphanum', 'blood', 'button', 'type'],
  '🆎': ['ab', 'alphanum', 'blood', 'button', 'type'],
  '🅱️': ['alphanum', 'b', 'blood', 'button', 'type'],
  '🆑': ['alphanum', 'button', 'cl'],
  '🆒': ['alphanum', 'button', 'cool'],
  '🆓': ['alphanum', 'button', 'free'],
  'ℹ️': ['alphanum', 'information'],
  '🆔': ['alphanum', 'button', 'id'],
  'Ⓜ️': ['alphanum', 'circled', 'm'],
  '🆕': ['alphanum', 'button', 'new'],
  '🆖': ['alphanum', 'button', 'ng'],
  '🅾️': ['alphanum', 'blood', 'button', 'o', 'type'],
  '🆗': ['alphanum', 'button', 'ok'],
  '🅿️': ['alphanum', 'button', 'p'],
  '🆘': ['alphanum', 'button', 'sos'],
  '🆙': ['alphanum', 'button', 'up'],
  '🆚': ['alphanum', 'button', 'vs'],
  '🈁': ['alphanum', 'button', 'here', 'japanese'],
  '🈂️': ['alphanum', 'button', 'charge', 'japanese', 'service'],
  '🈷️': ['alphanum', 'amount', 'button', 'japanese', 'monthly'],
  '🈶': ['alphanum', 'button', 'charge', 'free', 'japanese', 'not', 'of'],
  '🈯': ['alphanum', 'button', 'japanese', 'reserved'],
  '🉐': ['alphanum', 'bargain', 'button', 'japanese'],
  '🈹': ['alphanum', 'button', 'discount', 'japanese'],
  '🈚': ['alphanum', 'button', 'charge', 'free', 'japanese', 'of'],
  '🈲': ['alphanum', 'button', 'japanese', 'prohibited'],
  '🉑': ['acceptable', 'alphanum', 'button', 'japanese'],
  '🈸': ['alphanum', 'application', 'button', 'japanese'],
  '🈴': ['alphanum', 'button', 'grade', 'japanese', 'passing'],
  '🈳': ['alphanum', 'button', 'japanese', 'vacancy'],
  '㊗️': ['alphanum', 'button', 'congratulations', 'japanese'],
  '㊙️': ['alphanum', 'button', 'japanese', 'secret'],
  '🈺': ['alphanum', 'business', 'button', 'for', 'japanese', 'open'],
  '🈵': ['alphanum', 'button', 'japanese', 'no', 'vacancy'],
  '🔴': ['circle', 'geometric', 'red'],
  '🟠': ['circle', 'geometric', 'orange'],
  '🟡': ['circle', 'geometric', 'yellow'],
  '🟢': ['circle', 'geometric', 'green'],
  '🔵': ['blue', 'circle', 'geometric'],
  '🟣': ['circle', 'geometric', 'purple'],
  '🟤': ['brown', 'circle', 'geometric'],
  '⚫': ['black', 'circle', 'geometric'],
  '⚪': ['circle', 'geometric', 'white'],
  '🟥': ['geometric', 'red', 'square'],
  '🟧': ['geometric', 'orange', 'square'],
  '🟨': ['geometric', 'square', 'yellow'],
  '🟩': ['geometric', 'green', 'square'],
  '🟦': ['blue', 'geometric', 'square'],
  '🟪': ['geometric', 'purple', 'square'],
  '🟫': ['brown', 'geometric', 'square'],
  '⬛': ['black', 'geometric', 'large', 'square'],
  '⬜': ['geometric', 'large', 'square', 'white'],
  '◼️': ['black', 'geometric', 'medium', 'square'],
  '◻️': ['geometric', 'medium', 'square', 'white'],
  '◾': ['black', 'geometric', 'medium', 'small', 'square'],
  '◽': ['geometric', 'medium', 'small', 'square', 'white'],
  '▪️': ['black', 'geometric', 'small', 'square'],
  '▫️': ['geometric', 'small', 'square', 'white'],
  '🔶': ['diamond', 'geometric', 'large', 'orange'],
  '🔷': ['blue', 'diamond', 'geometric', 'large'],
  '🔸': ['diamond', 'geometric', 'orange', 'small'],
  '🔹': ['blue', 'diamond', 'geometric', 'small'],
  '🔺': ['geometric', 'pointed', 'red', 'triangle', 'up'],
  '🔻': ['down', 'geometric', 'pointed', 'red', 'triangle'],
  '💠': ['a', 'diamond', 'dot', 'geometric', 'with'],
  '🔘': ['button', 'geometric', 'radio'],
  '🔳': ['button', 'geometric', 'square', 'white'],
  '🔲': ['black', 'button', 'geometric', 'square'],
  '🏁': ['chequered', 'flag'],
  '🚩': ['flag', 'triangular'],
  '🎌': ['crossed', 'flag', 'flags'],
  '🏴': ['black', 'flag'],
  '🏳️': ['flag', 'white'],
  '🏳️‍🌈': ['flag', 'rainbow'],
  '🏳️‍⚧️': ['flag', 'transgender'],
  '🏴‍☠️': ['flag', 'pirate'],
  '🇦🇨': ['ascension', 'country', 'flag', 'island'],
  '🇦🇩': ['andorra', 'country', 'flag'],
  '🇦🇪': ['arab', 'country', 'emirates', 'flag', 'united'],
  '🇦🇫': ['afghanistan', 'country', 'flag'],
  '🇦🇬': ['antigua', 'barbuda', 'country', 'flag'],
  '🇦🇮': ['anguilla', 'country', 'flag'],
  '🇦🇱': ['albania', 'country', 'flag'],
  '🇦🇲': ['armenia', 'country', 'flag'],
  '🇦🇴': ['angola', 'country', 'flag'],
  '🇦🇶': ['antarctica', 'country', 'flag'],
  '🇦🇷': ['argentina', 'country', 'flag'],
  '🇦🇸': ['american', 'country', 'flag', 'samoa'],
  '🇦🇹': ['austria', 'country', 'flag'],
  '🇦🇺': ['australia', 'country', 'flag'],
  '🇦🇼': ['aruba', 'country', 'flag'],
  '🇦🇽': ['country', 'flag', 'islands', 'land'],
  '🇦🇿': ['azerbaijan', 'country', 'flag'],
  '🇧🇦': ['bosnia', 'country', 'flag', 'herzegovina'],
  '🇧🇧': ['barbados', 'country', 'flag'],
  '🇧🇩': ['bangladesh', 'country', 'flag'],
  '🇧🇪': ['belgium', 'country', 'flag'],
  '🇧🇫': ['burkina', 'country', 'faso', 'flag'],
  '🇧🇬': ['bulgaria', 'country', 'flag'],
  '🇧🇭': ['bahrain', 'country', 'flag'],
  '🇧🇮': ['burundi', 'country', 'flag'],
  '🇧🇯': ['benin', 'country', 'flag'],
  '🇧🇱': ['barth', 'country', 'flag', 'lemy', 'st'],
  '🇧🇲': ['bermuda', 'country', 'flag'],
  '🇧🇳': ['brunei', 'country', 'flag'],
  '🇧🇴': ['bolivia', 'country', 'flag'],
  '🇧🇶': ['caribbean', 'country', 'flag', 'netherlands'],
  '🇧🇷': ['brazil', 'country', 'flag'],
  '🇧🇸': ['bahamas', 'country', 'flag'],
  '🇧🇹': ['bhutan', 'country', 'flag'],
  '🇧🇻': ['bouvet', 'country', 'flag', 'island'],
  '🇧🇼': ['botswana', 'country', 'flag'],
  '🇧🇾': ['belarus', 'country', 'flag'],
  '🇧🇿': ['belize', 'country', 'flag'],
  '🇨🇦': ['canada', 'country', 'flag'],
  '🇨🇨': ['cocos', 'country', 'flag', 'islands', 'keeling'],
  '🇨🇩': ['congo', 'country', 'flag', 'kinshasa'],
  '🇨🇫': ['african', 'central', 'country', 'flag', 'republic'],
  '🇨🇬': ['brazzaville', 'congo', 'country', 'flag'],
  '🇨🇭': ['country', 'flag', 'switzerland'],
  '🇨🇮': ['c', 'country', 'd', 'flag', 'ivoire', 'te'],
  '🇨🇰': ['cook', 'country', 'flag', 'islands'],
  '🇨🇱': ['chile', 'country', 'flag'],
  '🇨🇲': ['cameroon', 'country', 'flag'],
  '🇨🇳': ['china', 'country', 'flag'],
  '🇨🇴': ['colombia', 'country', 'flag'],
  '🇨🇵': ['clipperton', 'country', 'flag', 'island'],
  '🇨🇷': ['costa', 'country', 'flag', 'rica'],
  '🇨🇺': ['country', 'cuba', 'flag'],
  '🇨🇻': ['cape', 'country', 'flag', 'verde'],
  '🇨🇼': ['ao', 'country', 'cura', 'flag'],
  '🇨🇽': ['christmas', 'country', 'flag', 'island'],
  '🇨🇾': ['country', 'cyprus', 'flag'],
  '🇨🇿': ['country', 'czechia', 'flag'],
  '🇩🇪': ['country', 'flag', 'germany'],
  '🇩🇬': ['country', 'diego', 'flag', 'garcia'],
  '🇩🇯': ['country', 'djibouti', 'flag'],
  '🇩🇰': ['country', 'denmark', 'flag'],
  '🇩🇲': ['country', 'dominica', 'flag'],
  '🇩🇴': ['country', 'dominican', 'flag', 'republic'],
  '🇩🇿': ['algeria', 'country', 'flag'],
  '🇪🇦': ['ceuta', 'country', 'flag', 'melilla'],
  '🇪🇨': ['country', 'ecuador', 'flag'],
  '🇪🇪': ['country', 'estonia', 'flag'],
  '🇪🇬': ['country', 'egypt', 'flag'],
  '🇪🇭': ['country', 'flag', 'sahara', 'western'],
  '🇪🇷': ['country', 'eritrea', 'flag'],
  '🇪🇸': ['country', 'flag', 'spain'],
  '🇪🇹': ['country', 'ethiopia', 'flag'],
  '🇪🇺': ['country', 'european', 'flag', 'union'],
  '🇫🇮': ['country', 'finland', 'flag'],
  '🇫🇯': ['country', 'fiji', 'flag'],
  '🇫🇰': ['country', 'falkland', 'flag', 'islands'],
  '🇫🇲': ['country', 'flag', 'micronesia'],
  '🇫🇴': ['country', 'faroe', 'flag', 'islands'],
  '🇫🇷': ['country', 'flag', 'france'],
  '🇬🇦': ['country', 'flag', 'gabon'],
  '🇬🇧': ['country', 'flag', 'kingdom', 'united'],
  '🇬🇩': ['country', 'flag', 'grenada'],
  '🇬🇪': ['country', 'flag', 'georgia'],
  '🇬🇫': ['country', 'flag', 'french', 'guiana'],
  '🇬🇬': ['country', 'flag', 'guernsey'],
  '🇬🇭': ['country', 'flag', 'ghana'],
  '🇬🇮': ['country', 'flag', 'gibraltar'],
  '🇬🇱': ['country', 'flag', 'greenland'],
  '🇬🇲': ['country', 'flag', 'gambia'],
  '🇬🇳': ['country', 'flag', 'guinea'],
  '🇬🇵': ['country', 'flag', 'guadeloupe'],
  '🇬🇶': ['country', 'equatorial', 'flag', 'guinea'],
  '🇬🇷': ['country', 'flag', 'greece'],
  '🇬🇸': ['country', 'flag', 'georgia', 'islands', 'sandwich', 'south'],
  '🇬🇹': ['country', 'flag', 'guatemala'],
  '🇬🇺': ['country', 'flag', 'guam'],
  '🇬🇼': ['bissau', 'country', 'flag', 'guinea'],
  '🇬🇾': ['country', 'flag', 'guyana'],
  '🇭🇰': ['china', 'country', 'flag', 'hong', 'kong', 'sar'],
  '🇭🇲': ['country', 'flag', 'heard', 'islands', 'mcdonald'],
  '🇭🇳': ['country', 'flag', 'honduras'],
  '🇭🇷': ['country', 'croatia', 'flag'],
  '🇭🇹': ['country', 'flag', 'haiti'],
  '🇭🇺': ['country', 'flag', 'hungary'],
  '🇮🇨': ['canary', 'country', 'flag', 'islands'],
  '🇮🇩': ['country', 'flag', 'indonesia'],
  '🇮🇪': ['country', 'flag', 'ireland'],
  '🇮🇱': ['country', 'flag', 'israel'],
  '🇮🇲': ['country', 'flag', 'isle', 'man', 'of'],
  '🇮🇳': ['country', 'flag', 'india'],
  '🇮🇴': ['british', 'country', 'flag', 'indian', 'ocean', 'territory'],
  '🇮🇶': ['country', 'flag', 'iraq'],
  '🇮🇷': ['country', 'flag', 'iran'],
  '🇮🇸': ['country', 'flag', 'iceland'],
  '🇮🇹': ['country', 'flag', 'italy'],
  '🇯🇪': ['country', 'flag', 'jersey'],
  '🇯🇲': ['country', 'flag', 'jamaica'],
  '🇯🇴': ['country', 'flag', 'jordan'],
  '🇯🇵': ['country', 'flag', 'japan'],
  '🇰🇪': ['country', 'flag', 'kenya'],
  '🇰🇬': ['country', 'flag', 'kyrgyzstan'],
  '🇰🇭': ['cambodia', 'country', 'flag'],
  '🇰🇮': ['country', 'flag', 'kiribati'],
  '🇰🇲': ['comoros', 'country', 'flag'],
  '🇰🇳': ['country', 'flag', 'kitts', 'nevis', 'st'],
  '🇰🇵': ['country', 'flag', 'korea', 'north'],
  '🇰🇷': ['country', 'flag', 'korea', 'south'],
  '🇰🇼': ['country', 'flag', 'kuwait'],
  '🇰🇾': ['cayman', 'country', 'flag', 'islands'],
  '🇰🇿': ['country', 'flag', 'kazakhstan'],
  '🇱🇦': ['country', 'flag', 'laos'],
  '🇱🇧': ['country', 'flag', 'lebanon'],
  '🇱🇨': ['country', 'flag', 'lucia', 'st'],
  '🇱🇮': ['country', 'flag', 'liechtenstein'],
  '🇱🇰': ['country', 'flag', 'lanka', 'sri'],
  '🇱🇷': ['country', 'flag', 'liberia'],
  '🇱🇸': ['country', 'flag', 'lesotho'],
  '🇱🇹': ['country', 'flag', 'lithuania'],
  '🇱🇺': ['country', 'flag', 'luxembourg'],
  '🇱🇻': ['country', 'flag', 'latvia'],
  '🇱🇾': ['country', 'flag', 'libya'],
  '🇲🇦': ['country', 'flag', 'morocco'],
  '🇲🇨': ['country', 'flag', 'monaco'],
  '🇲🇩': ['country', 'flag', 'moldova'],
  '🇲🇪': ['country', 'flag', 'montenegro'],
  '🇲🇫': ['country', 'flag', 'martin', 'st'],
  '🇲🇬': ['country', 'flag', 'madagascar'],
  '🇲🇭': ['country', 'flag', 'islands', 'marshall'],
  '🇲🇰': ['country', 'flag', 'macedonia', 'north'],
  '🇲🇱': ['country', 'flag', 'mali'],
  '🇲🇲': ['burma', 'country', 'flag', 'myanmar'],
  '🇲🇳': ['country', 'flag', 'mongolia'],
  '🇲🇴': ['china', 'country', 'flag', 'macao', 'sar'],
  '🇲🇵': ['country', 'flag', 'islands', 'mariana', 'northern'],
  '🇲🇶': ['country', 'flag', 'martinique'],
  '🇲🇷': ['country', 'flag', 'mauritania'],
  '🇲🇸': ['country', 'flag', 'montserrat'],
  '🇲🇹': ['country', 'flag', 'malta'],
  '🇲🇺': ['country', 'flag', 'mauritius'],
  '🇲🇻': ['country', 'flag', 'maldives'],
  '🇲🇼': ['country', 'flag', 'malawi'],
  '🇲🇽': ['country', 'flag', 'mexico'],
  '🇲🇾': ['country', 'flag', 'malaysia'],
  '🇲🇿': ['country', 'flag', 'mozambique'],
  '🇳🇦': ['country', 'flag', 'namibia'],
  '🇳🇨': ['caledonia', 'country', 'flag', 'new'],
  '🇳🇪': ['country', 'flag', 'niger'],
  '🇳🇫': ['country', 'flag', 'island', 'norfolk'],
  '🇳🇬': ['country', 'flag', 'nigeria'],
  '🇳🇮': ['country', 'flag', 'nicaragua'],
  '🇳🇱': ['country', 'flag', 'netherlands'],
  '🇳🇴': ['country', 'flag', 'norway'],
  '🇳🇵': ['country', 'flag', 'nepal'],
  '🇳🇷': ['country', 'flag', 'nauru'],
  '🇳🇺': ['country', 'flag', 'niue'],
  '🇳🇿': ['country', 'flag', 'new', 'zealand'],
  '🇴🇲': ['country', 'flag', 'oman'],
  '🇵🇦': ['country', 'flag', 'panama'],
  '🇵🇪': ['country', 'flag', 'peru'],
  '🇵🇫': ['country', 'flag', 'french', 'polynesia'],
  '🇵🇬': ['country', 'flag', 'guinea', 'new', 'papua'],
  '🇵🇭': ['country', 'flag', 'philippines'],
  '🇵🇰': ['country', 'flag', 'pakistan'],
  '🇵🇱': ['country', 'flag', 'poland'],
  '🇵🇲': ['country', 'flag', 'miquelon', 'pierre', 'st'],
  '🇵🇳': ['country', 'flag', 'islands', 'pitcairn'],
  '🇵🇷': ['country', 'flag', 'puerto', 'rico'],
  '🇵🇸': ['country', 'flag', 'palestinian', 'territories'],
  '🇵🇹': ['country', 'flag', 'portugal'],
  '🇵🇼': ['country', 'flag', 'palau'],
  '🇵🇾': ['country', 'flag', 'paraguay'],
  '🇶🇦': ['country', 'flag', 'qatar'],
  '🇷🇪': ['country', 'flag', 'r', 'union'],
  '🇷🇴': ['country', 'flag', 'romania'],
  '🇷🇸': ['country', 'flag', 'serbia'],
  '🇷🇺': ['country', 'flag', 'russia'],
  '🇷🇼': ['country', 'flag', 'rwanda'],
  '🇸🇦': ['arabia', 'country', 'flag', 'saudi'],
  '🇸🇧': ['country', 'flag', 'islands', 'solomon'],
  '🇸🇨': ['country', 'flag', 'seychelles'],
  '🇸🇩': ['country', 'flag', 'sudan'],
  '🇸🇪': ['country', 'flag', 'sweden'],
  '🇸🇬': ['country', 'flag', 'singapore'],
  '🇸🇭': ['country', 'flag', 'helena', 'st'],
  '🇸🇮': ['country', 'flag', 'slovenia'],
  '🇸🇯': ['country', 'flag', 'jan', 'mayen', 'svalbard'],
  '🇸🇰': ['country', 'flag', 'slovakia'],
  '🇸🇱': ['country', 'flag', 'leone', 'sierra'],
  '🇸🇲': ['country', 'flag', 'marino', 'san'],
  '🇸🇳': ['country', 'flag', 'senegal'],
  '🇸🇴': ['country', 'flag', 'somalia'],
  '🇸🇷': ['country', 'flag', 'suriname'],
  '🇸🇸': ['country', 'flag', 'south', 'sudan'],
  '🇸🇹': ['country', 'flag', 'ncipe', 'o', 'pr', 's', 'tom'],
  '🇸🇻': ['country', 'el', 'flag', 'salvador'],
  '🇸🇽': ['country', 'flag', 'maarten', 'sint'],
  '🇸🇾': ['country', 'flag', 'syria'],
  '🇸🇿': ['country', 'eswatini', 'flag'],
  '🇹🇦': ['country', 'cunha', 'da', 'flag', 'tristan'],
  '🇹🇨': ['caicos', 'country', 'flag', 'islands', 'turks'],
  '🇹🇩': ['chad', 'country', 'flag'],
  '🇹🇫': ['country', 'flag', 'french', 'southern', 'territories'],
  '🇹🇬': ['country', 'flag', 'togo'],
  '🇹🇭': ['country', 'flag', 'thailand'],
  '🇹🇯': ['country', 'flag', 'tajikistan'],
  '🇹🇰': ['country', 'flag', 'tokelau'],
  '🇹🇱': ['country', 'flag', 'leste', 'timor'],
  '🇹🇲': ['country', 'flag', 'turkmenistan'],
  '🇹🇳': ['country', 'flag', 'tunisia'],
  '🇹🇴': ['country', 'flag', 'tonga'],
  '🇹🇷': ['country', 'flag', 'rkiye', 't'],
  '🇹🇹': ['country', 'flag', 'tobago', 'trinidad'],
  '🇹🇻': ['country', 'flag', 'tuvalu'],
  '🇹🇼': ['country', 'flag', 'taiwan'],
  '🇹🇿': ['country', 'flag', 'tanzania'],
  '🇺🇦': ['country', 'flag', 'ukraine'],
  '🇺🇬': ['country', 'flag', 'uganda'],
  '🇺🇲': ['country', 'flag', 'islands', 'outlying', 's', 'u'],
  '🇺🇳': ['country', 'flag', 'nations', 'united'],
  '🇺🇸': ['country', 'flag', 'states', 'united'],
  '🇺🇾': ['country', 'flag', 'uruguay'],
  '🇺🇿': ['country', 'flag', 'uzbekistan'],
  '🇻🇦': ['city', 'country', 'flag', 'vatican'],
  '🇻🇨': ['country', 'flag', 'grenadines', 'st', 'vincent'],
  '🇻🇪': ['country', 'flag', 'venezuela'],
  '🇻🇬': ['british', 'country', 'flag', 'islands', 'virgin'],
  '🇻🇮': ['country', 'flag', 'islands', 's', 'u', 'virgin'],
  '🇻🇳': ['country', 'flag', 'vietnam'],
  '🇻🇺': ['country', 'flag', 'vanuatu'],
  '🇼🇫': ['country', 'flag', 'futuna', 'wallis'],
  '🇼🇸': ['country', 'flag', 'samoa'],
  '🇽🇰': ['country', 'flag', 'kosovo'],
  '🇾🇪': ['country', 'flag', 'yemen'],
  '🇾🇹': ['country', 'flag', 'mayotte'],
  '🇿🇦': ['africa', 'country', 'flag', 'south'],
  '🇿🇲': ['country', 'flag', 'zambia'],
  '🇿🇼': ['country', 'flag', 'zimbabwe'],
  '🏴󠁧󠁢󠁥󠁮󠁧󠁿': ['england', 'flag', 'subdivision'],
  '🏴󠁧󠁢󠁳󠁣󠁴󠁿': ['flag', 'scotland', 'subdivision'],
  '🏴󠁧󠁢󠁷󠁬󠁳󠁿': ['flag', 'subdivision', 'wales'],
};
