-- Grant the api role full data access to all schemas.
-- The api role should be able to read/write all data and execute all functions,
-- but should NOT be able to modify the schema (CREATE/ALTER/DROP).

-- Schema usage
GRANT USAGE ON SCHEMA public TO api;
GRANT USAGE ON SCHEMA "user" TO api;
GRANT USAGE ON SCHEMA admin TO api;
GRANT USAGE ON SCHEMA extensions TO api;

-- Tables: full data access
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO api;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA "user" TO api;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA admin TO api;

-- Functions: execute
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO api;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA "user" TO api;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA admin TO api;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA extensions TO api;

-- Sequences: usage (for bigint primary keys)
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO api;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA "user" TO api;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA admin TO api;

-- Auto-grant on future objects created by postgres role
ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO api;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT EXECUTE ON FUNCTIONS TO api;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT USAGE ON SEQUENCES TO api;

-- Auto-grant on future objects created by migrator role (used in CI)
ALTER DEFAULT PRIVILEGES FOR ROLE migrator GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO api;
ALTER DEFAULT PRIVILEGES FOR ROLE migrator GRANT EXECUTE ON FUNCTIONS TO api;
ALTER DEFAULT PRIVILEGES FOR ROLE migrator GRANT USAGE ON SEQUENCES TO api;

-- Readonly role: SELECT-only access to all tables and views.
GRANT USAGE ON SCHEMA public TO readonly;
GRANT USAGE ON SCHEMA "user" TO readonly;
GRANT USAGE ON SCHEMA admin TO readonly;
GRANT USAGE ON SCHEMA extensions TO readonly;

GRANT SELECT ON ALL TABLES IN SCHEMA public TO readonly;
GRANT SELECT ON ALL TABLES IN SCHEMA "user" TO readonly;
GRANT SELECT ON ALL TABLES IN SCHEMA admin TO readonly;
GRANT SELECT ON ALL TABLES IN SCHEMA extensions TO readonly;

-- Auto-grant SELECT on future tables/views for readonly role
ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT SELECT ON TABLES TO readonly;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT USAGE ON SEQUENCES TO readonly;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT EXECUTE ON FUNCTIONS TO readonly;

ALTER DEFAULT PRIVILEGES FOR ROLE migrator GRANT SELECT ON TABLES TO readonly;
ALTER DEFAULT PRIVILEGES FOR ROLE migrator GRANT USAGE ON SEQUENCES TO readonly;
ALTER DEFAULT PRIVILEGES FOR ROLE migrator GRANT EXECUTE ON FUNCTIONS TO readonly;
