# A list of devices you want to take the screenshots from
# For macOS, we don't specify devices but can set window sizes
devices([
  "Mac"
])

# A list of languages which should be used
languages([
  "en-US"
])

# The name of the scheme which contains the UI Tests
scheme("Runner")

# Where should the resulting screenshots be stored?
output_directory("./fastlane/screenshots")

# Clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

# Arguments to pass to the app on launch
# launch_arguments([])

# For more information about all available options run
# fastlane action snapshot
