name = "event-sync"
main = "src/index.ts"
compatibility_date = "2024-11-18"
compatibility_flags = ["nodejs_compat"]
upload_source_maps = true

[env.development]
[env.development.define]
  ENV = '"development"'
  RELEASE = '"dev"'
  PACKAGE = '"event-sync"'

[[env.development.queues.consumers]]
  queue = "event-sync-development"
  max_batch_size = 100
  max_batch_timeout = 3
  max_retries = 3

[env.development.ai]
  binding = "AI"

[env.production]
[env.production.define]
  ENV = '"production"'
  RELEASE = '"prod"'
  PACKAGE = '"event-sync"'

[[env.production.queues.consumers]]
  queue = "event-sync-production"
  max_batch_size = 100
  max_batch_timeout = 3
  max_retries = 3

[env.production.ai]
  binding = "AI"

[placement]
  mode = "smart"

[observability.logs]
  enabled = true
