name = "api"
main = "src/index.ts"
compatibility_date = "2025-07-05"
compatibility_flags = ["nodejs_compat"]
upload_source_maps = true

[env.development]
[env.development.define]
  ENV = '"development"'
  RELEASE = '"dev"'
  PACKAGE = '"api"'

[[env.development.queues.producers]]
  queue = "sync-development"
  binding = "SYNC_QUEUE"

[[env.development.services]]
  binding = "ONBOARDING"
  service = "onboarding"

[env.production]
routes = [
  { pattern = "sync-api.plot.day", custom_domain = true }
]
[env.production.define]
  ENV = '"production"'
  RELEASE = '"prod"'
  PACKAGE = '"api"'

[[env.production.queues.producers]]
  queue = "sync-production"
  binding = "SYNC_QUEUE"

[[env.production.services]]
  binding = "ONBOARDING"
  service = "onboarding-production"

[ai]
  binding = "AI"

[observability.logs]
  enabled = true
