name = "api"
main = "src/index.ts"
compatibility_date = "2024-11-18"
compatibility_flags = ["nodejs_compat"]
upload_source_maps = true

[define]
  ENV = '"development"'
  RELEASE = '"dev"'
  PACKAGE = '"api"'

[[queues.producers]]
  queue = "sync"
  binding = "SYNC_QUEUE"

[observability.logs]
  enabled = true
