name = "api"
main = "src/index.ts"
compatibility_date = "2025-07-05"
compatibility_flags = ["nodejs_compat"]
upload_source_maps = true

[env.development]
[env.development.define]
  ENV = '"development"'
  RELEASE = '"dev"'
  PACKAGE = '"api"'

[env.production]
routes = [
  { pattern = "sync-api.plot.day", custom_domain = true }
]
[env.production.define]
  ENV = '"production"'
  RELEASE = '"prod"'
  PACKAGE = '"api"'

[ai]
  binding = "AI"

[[queues.producers]]
  queue = "sync"
  binding = "SYNC_QUEUE"

[[services]]
  binding = "ONBOARDING"
  service = "onboarding"

[observability.logs]
  enabled = true
