CREATE TABLE "public"."domain" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" timestamp with time zone DEFAULT now(),
    "domain" text NOT NULL,
    "organization_id" bigint
);

CREATE UNIQUE INDEX domain_pkey ON public.domain USING btree (id);

ALTER TABLE "public"."domain"
    ADD CONSTRAINT "domain_pkey" PRIMARY KEY USING INDEX "domain_pkey";

ALTER TABLE "public"."domain"
    ADD CONSTRAINT "domain_domain_unique" UNIQUE (DOMAIN);

ALTER TABLE "public"."domain"
    ADD CONSTRAINT "domain_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES organization (id) ON DELETE SET NULL NOT valid;

ALTER TABLE "public"."domain" validate CONSTRAINT "domain_organization_id_fkey";

