CREATE TYPE "public"."user_status" AS ENUM (
    'waitlisted',
    'active'
);

CREATE TABLE "public"."user" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 10000) NOT NULL,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    "email" text NOT NULL,
    "name" text,
    "timezone" text,
    "avatar_url" text,
    "invitation" text,
    "activated_at" timestamp with time zone
);

CREATE UNIQUE INDEX user_email_key ON public."user" USING btree (email);

CREATE UNIQUE INDEX user_pkey ON public."user" USING btree (id);

ALTER TABLE "public"."user"
    ADD CONSTRAINT "user_pkey" PRIMARY KEY USING INDEX "user_pkey";

