CREATE TABLE "public"."user" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    "email" text NOT NULL,
    "name" text NOT NULL,
    "timezone" text NOT NULL DEFAULT 'America/New_York' ::text,
    "avatar_url" text
);

CREATE UNIQUE INDEX user_email_key ON public."user" USING btree (email);

CREATE UNIQUE INDEX user_pkey ON public."user" USING btree (id);

ALTER TABLE "public"."user"
    ADD CONSTRAINT "user_pkey" PRIMARY KEY USING INDEX "user_pkey";

