CREATE TABLE "public"."waitlist" (
    "id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 10000) NOT NULL,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    "email" text NOT NULL,
    "invitation" text,
    "activated_at" timestamp with time zone
);

ALTER TABLE "public"."waitlist" ENABLE ROW LEVEL SECURITY;

