CREATE TABLE "public"."waitlist" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" timestamp with time zone DEFAULT now(),
    "email" text NOT NULL,
    "provider" public.provider,
    "sync_error" text,
    "user_id" bigint
);

CREATE UNIQUE INDEX waitlist_pkey ON public.waitlist USING btree (id);

ALTER TABLE "public"."waitlist"
    ADD CONSTRAINT "waitlist_pkey" PRIMARY KEY USING INDEX "waitlist_pkey";

CREATE UNIQUE INDEX waitlist_email_key ON public.waitlist USING btree (email);

ALTER TABLE "public"."waitlist"
    ADD CONSTRAINT "waitlist_email_key" UNIQUE USING INDEX "waitlist_email_key";

ALTER TABLE "public"."waitlist"
    ADD CONSTRAINT "waitlist_user_id_fkey" FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE SET NULL NOT valid;

ALTER TABLE "public"."waitlist" validate CONSTRAINT "waitlist_user_id_fkey";

