CREATE TABLE "public"."account" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    "auth_user_id" uuid NOT NULL,
    "user_id" bigint NOT NULL,
    "credentials" jsonb,
    "provider" provider NOT NULL,
    "email" text,
    "domain_id" bigint,
    "contact_sync_state" jsonb
);

CREATE UNIQUE INDEX account_pkey ON public.account USING btree (id);

ALTER TABLE "public"."account"
    ADD CONSTRAINT "account_pkey" PRIMARY KEY USING INDEX "account_pkey";

ALTER TABLE "public"."account"
    ADD CONSTRAINT "account_auth_user_id_fkey" FOREIGN KEY (auth_user_id) REFERENCES auth.users (id) ON DELETE CASCADE NOT valid;

ALTER TABLE "public"."account" validate CONSTRAINT "account_auth_user_id_fkey";

ALTER TABLE "public"."account"
    ADD CONSTRAINT "account_domain_id_fkey" FOREIGN KEY (domain_id) REFERENCES DOMAIN (id) ON DELETE SET NULL NOT valid;

ALTER TABLE "public"."account" validate CONSTRAINT "account_domain_id_fkey";

ALTER TABLE "public"."account"
    ADD CONSTRAINT "account_user_id_fkey" FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT valid;

ALTER TABLE "public"."account" validate CONSTRAINT "account_user_id_fkey";

CREATE UNIQUE INDEX account_auth_user_id_key ON public.account USING btree (auth_user_id);

CREATE INDEX account_user_id_idx ON public.account USING btree (user_id);

