CREATE TABLE "public"."category" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" timestamp with time zone DEFAULT now(),
    "user_id" bigint NOT NULL,
    "path" ltree NOT NULL,
    "name" text NOT NULL,
    "priority" text DEFAULT 'O' NOT NULL,
    "budget_weekly" integer,
    "minimize" boolean DEFAULT TRUE NOT NULL
);

CREATE UNIQUE INDEX category_pkey ON public.category USING btree (id);

ALTER TABLE "public"."category"
    ADD CONSTRAINT "category_pkey" PRIMARY KEY USING INDEX "category_pkey";

ALTER TABLE "public"."category"
    ADD CONSTRAINT "category_user_id_fkey" FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT valid;

ALTER TABLE "public"."category" validate CONSTRAINT "category_user_id_fkey";

CREATE INDEX category_path_idx ON "public"."category" USING GIST (user_id, path);

