CREATE TABLE "public"."budget" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    "category_id" bigint NOT NULL,
    "week" daterange,
    "order" text,
    "budget" integer
);

CREATE UNIQUE INDEX budget_pkey ON public.budget USING btree (id);

ALTER TABLE "public"."budget"
    ADD CONSTRAINT "budget_pkey" PRIMARY KEY USING INDEX "budget_pkey";

ALTER TABLE "public"."budget"
    ADD CONSTRAINT "budget_category_id_fkey" FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE CASCADE NOT valid;

ALTER TABLE "public"."budget" validate CONSTRAINT "budget_category_id_fkey";

-- Define a computed relation for PostgREST joins
-- https://postgrest.org/en/stable/references/api/resource_embedding.html#computed-relationships
CREATE OR REPLACE FUNCTION public.budget (category)
    RETURNS SETOF budget
    LANGUAGE sql
    STABLE
    AS $function$
    SELECT
        *
    FROM
        budget
    WHERE
        category_id = $1.id;
$function$;

