CREATE TABLE "public"."calendar" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    "account_id" bigint NOT NULL,
    "provider_id" text NOT NULL,
    "starts_at" timestamp with time zone,
    "ends_at" timestamp with time zone,
    "sync_state" jsonb,
    "watch_id" text,
    "watch_secret" text,
    "watch_expires_at" timestamp with time zone,
    "sequence" numeric NOT NULL DEFAULT '1' ::numeric,
    "full_sync_at" timestamp with time zone,
    "synced_at" timestamp with time zone,
    "sync_error" text,
    "full_sync_started_at" timestamp with time zone,
    "name" text,
    "enabled" boolean NOT NULL DEFAULT FALSE,
    "ready" boolean NOT NULL DEFAULT FALSE
);

CREATE UNIQUE INDEX calendar_pkey ON public.calendar USING btree (id);

ALTER TABLE "public"."calendar"
    ADD CONSTRAINT "calendar_pkey" PRIMARY KEY USING INDEX "calendar_pkey";

ALTER TABLE "public"."calendar"
    ADD CONSTRAINT "calendar_account_id_fkey" FOREIGN KEY (account_id) REFERENCES account (id) ON DELETE CASCADE NOT valid;

ALTER TABLE "public"."calendar" validate CONSTRAINT "calendar_account_id_fkey";

CREATE UNIQUE INDEX calendar_account_id_provider_id_key ON public.calendar USING btree (account_id, provider_id);

CREATE INDEX calendar_account_id_idx ON public.calendar USING btree (account_id);

CREATE OR REPLACE FUNCTION public.calendars (account)
    RETURNS SETOF calendar
    LANGUAGE sql
    STABLE
    AS $function$
    SELECT
        calendar.*
    FROM
        calendar
    WHERE
        calendar.account_id = $1.id
$function$;

