CREATE TABLE "public"."contact" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    "user_id" bigint NOT NULL,
    "email" text,
    "name" text,
    "contact_user_id" bigint,
    "domain_id" bigint
);

CREATE UNIQUE INDEX contact_pkey ON public.contact USING btree (id);

ALTER TABLE "public"."contact"
    ADD CONSTRAINT "contact_pkey" PRIMARY KEY USING INDEX "contact_pkey";

ALTER TABLE "public"."contact"
    ADD CONSTRAINT "contact_domain_id_fkey" FOREIGN KEY (domain_id) REFERENCES DOMAIN (id) ON DELETE SET NULL NOT valid;

ALTER TABLE "public"."contact" validate CONSTRAINT "contact_domain_id_fkey";

ALTER TABLE "public"."contact"
    ADD CONSTRAINT "contact_user_id_fkey" FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT valid;

ALTER TABLE "public"."contact" validate CONSTRAINT "contact_user_id_fkey";

ALTER TABLE "public"."contact"
    ADD CONSTRAINT "contact_contact_user_id_fkey" FOREIGN KEY (contact_user_id) REFERENCES "user" (id) ON DELETE SET NULL NOT valid;

ALTER TABLE "public"."contact" validate CONSTRAINT "contact_contact_user_id_fkey";

CREATE UNIQUE INDEX contact_user_id_email_key ON public.contact USING btree (user_id, email);

ALTER TABLE "public"."contact"
    ADD CONSTRAINT "contact_user_id_email_key" UNIQUE USING INDEX "contact_user_id_email_key";

