CREATE TABLE "public"."event" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" timestamp with time zone NOT NULL DEFAULT now(),
    "calendar_id" bigint NOT NULL,
    "provider_id" text NOT NULL,
    "series" text,
    "name" text,
    "status" event_status NOT NULL DEFAULT 'confirmed' ::event_status,
    "at" tstzrange NOT NULL,
    "attended" tstzrange,
    "provider_link" text,
    "summary" text,
    "description" text,
    "visibility" event_visibility NOT NULL DEFAULT 'normal' ::event_visibility,
    "availability" event_availability NOT NULL DEFAULT 'busy' ::event_availability,
    "conferencing_url" text,
    "organizer_email" text,
    "sequence" integer NOT NULL DEFAULT 1
);

CREATE UNIQUE INDEX event_calendar_id_provider_id_key ON public.event USING btree (calendar_id, provider_id);

CREATE UNIQUE INDEX event_pkey ON public.event USING btree (id);

ALTER TABLE "public"."event"
    ADD CONSTRAINT "event_pkey" PRIMARY KEY USING INDEX "event_pkey";

ALTER TABLE "public"."event"
    ADD CONSTRAINT "event_calendar_id_fkey" FOREIGN KEY (calendar_id) REFERENCES calendar (id) ON DELETE CASCADE NOT valid;

ALTER TABLE "public"."event" validate CONSTRAINT "event_calendar_id_fkey";

ALTER TABLE "public"."event"
    ADD CONSTRAINT "event_calendar_id_provider_id_key" UNIQUE USING INDEX "event_calendar_id_provider_id_key";

ALTER publication supabase_realtime
    ADD TABLE public.event;

CREATE INDEX event_at_idx ON event USING spgist (at);

