CREATE TABLE "public"."label" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" timestamp with time zone DEFAULT now(),
    "user_id" bigint,
    "name" text NOT NULL,
    "description" text
);

CREATE UNIQUE INDEX label_pkey ON public.label USING btree (id);

ALTER TABLE "public"."label"
    ADD CONSTRAINT "label_pkey" PRIMARY KEY USING INDEX "label_pkey";

ALTER TABLE "public"."label"
    ADD CONSTRAINT "label_user_id_fkey" FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT valid;

ALTER TABLE "public"."label" validate CONSTRAINT "label_user_id_fkey";

ALTER TABLE "public"."label"
    ADD CONSTRAINT "label_name_user_id_unique" UNIQUE NULLS NOT DISTINCT (user_id, name);

