CREATE TABLE "public"."event_label" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" timestamp with time zone DEFAULT now(),
    "event_id" bigint,
    "series" text,
    "label_id" bigint NOT NULL,
    "priority" smallint NOT NULL DEFAULT '100' ::smallint,
    "negate" boolean NOT NULL DEFAULT FALSE
);

CREATE UNIQUE INDEX event_label_pkey ON public.event_label USING btree (id);

ALTER TABLE "public"."event_label"
    ADD CONSTRAINT "event_label_pkey" PRIMARY KEY USING INDEX "event_label_pkey";

ALTER TABLE "public"."event_label"
    ADD CONSTRAINT "event_label_event_id_fkey" FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE NOT valid;

ALTER TABLE "public"."event_label" validate CONSTRAINT "event_label_event_id_fkey";

ALTER TABLE "public"."event_label"
    ADD CONSTRAINT "event_label_label_id_fkey" FOREIGN KEY (label_id) REFERENCES label (id) ON DELETE CASCADE NOT valid;

ALTER TABLE "public"."event_label" validate CONSTRAINT "event_label_label_id_fkey";

CREATE UNIQUE INDEX event_label_event_id_series_label_id_key ON public.event_label USING btree (event_id, series, label_id) NULLS NOT DISTINCT;

CREATE INDEX event_label_event_id_idx ON public.event_label USING btree (event_id);

