CREATE TABLE "public"."response" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" timestamp with time zone DEFAULT now(),
    "user_id" bigint NOT NULL,
    "provider_id" text NOT NULL,
    "response" event_response,
    "ready" boolean DEFAULT FALSE NOT NULL,
    "reviewed" boolean DEFAULT FALSE NOT NULL
);

CREATE UNIQUE INDEX response_pkey ON public.response USING btree (id);

ALTER TABLE "public"."response"
    ADD CONSTRAINT "response_pkey" PRIMARY KEY USING INDEX "response_pkey";

ALTER TABLE "public"."response"
    ADD CONSTRAINT "response_user_id_fkey" FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT valid;

ALTER TABLE "public"."response" validate CONSTRAINT "response_user_id_fkey";

CREATE UNIQUE INDEX response_user_id_provider_id_key ON public.response USING btree (user_id, provider_id);

ALTER TABLE "public"."response"
    ADD CONSTRAINT "response_user_id_provider_id_key" UNIQUE USING INDEX "response_user_id_provider_id_key";

