CREATE TABLE "public"."target" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" timestamp with time zone DEFAULT now(),
    "user_id" bigint NOT NULL,
    "label_id" bigint NOT NULL,
    "target" real NOT NULL,
    "org" boolean NOT NULL DEFAULT FALSE
);

CREATE UNIQUE INDEX target_pkey ON public.target USING btree (id);

ALTER TABLE "public"."target"
    ADD CONSTRAINT "target_pkey" PRIMARY KEY USING INDEX "target_pkey";

ALTER TABLE "public"."target"
    ADD CONSTRAINT "target_label_id_fkey" FOREIGN KEY (label_id) REFERENCES label (id) ON DELETE CASCADE NOT valid;

ALTER TABLE "public"."target" validate CONSTRAINT "target_label_id_fkey";

ALTER TABLE "public"."target"
    ADD CONSTRAINT "target_user_id_fkey" FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT valid;

ALTER TABLE "public"."target" validate CONSTRAINT "target_user_id_fkey";

