CREATE TABLE "public"."note" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "created_at" timestamp with time zone DEFAULT now(),
    "category_id" bigint NOT NULL,
    "body" text NOT NULL,
    "author" bigint
);

CREATE UNIQUE INDEX note_pkey ON public.note USING btree (id);

ALTER TABLE "public"."note"
    ADD CONSTRAINT "note_pkey" PRIMARY KEY USING INDEX "note_pkey";

ALTER TABLE "public"."note"
    ADD CONSTRAINT "note_category_id_fkey" FOREIGN KEY (category_id) REFERENCES category (id) NOT valid;

ALTER TABLE "public"."note" validate CONSTRAINT "note_category_id_fkey";

ALTER TABLE "public"."note"
    ADD CONSTRAINT "note_author_fkey" FOREIGN KEY (author) REFERENCES "user" (id) ON DELETE SET NULL NOT valid;

ALTER TABLE "public"."note" validate CONSTRAINT "note_author_fkey";

