export { default, OutlookCalendar } from "./outlook-calendar";
export {
  getOutlookCalendarChannels,
  OUTLOOK_CALENDAR_SCOPE,
  OUTLOOK_CALENDAR_LINK_TYPES,
  type Calendar,
} from "./channels";
export {
  type OutlookCalendarSyncHost,
  type WatchState,
  type OutlookInitResult,
  type SyncOutlookBatchResult,
  type SubscriptionRenewalSchedule,
  type RenewOutlookWatchResult,
  type SetupOutlookWatchResult,
  type StartIncrementalSyncResult,
  type RSVPParams,
  SYNC_LOCK_TTL_MS,
  RENEWAL_LEAD_MS,
  SUBSCRIPTION_DURATION_DAYS,
  buildEventSources,
  extractRSVPParamsFn,
  getApiFn,
  tryGetApiFn,
  getUserEmailFn,
  ensureUserIdentityFn,
  getCalendarsFn,
  firstSeenAtFn,
  clearBuffersFn,
  prepareEventInstanceFn,
  processOutlookEventsFn,
  initOutlookCalendarFn,
  startSyncFn,
  stopSyncFn,
  syncOutlookBatchFn,
  scheduleSubscriptionRenewalFn,
  renewOutlookWatchFn,
  setupOutlookWatchFn,
  watchNeedsReactiveRenewalFn,
  startIncrementalSyncFn,
  updateEventRSVPWithApiFn,
} from "./sync";
