name = "sync"
main = "src/index.ts"
compatibility_date = "2024-11-18"
compatibility_flags = ["nodejs_compat"]
upload_source_maps = true

[[queues.producers]]
  queue = "event-sync"
  binding = "EVENT_QUEUE"

[[queues.producers]]
  queue = "contact-sync"
  binding = "CONTACT_SYNC_QUEUE"

[[queues.consumers]]
  queue = "sync"
  max_batch_size = 1
  max_retries = 5

[triggers]
  crons = ["*/47 * * * *"]
