name = "sync"
main = "src/index.ts"
compatibility_date = "2024-11-18"
compatibility_flags = ["nodejs_compat"]
upload_source_maps = true

[env.development]
[env.development.define]
  ENV = '"development"'
  RELEASE = '"dev"'
  PACKAGE = '"sync"'

[[env.development.queues.producers]]
  queue = "event-sync-development"
  binding = "EVENT_QUEUE"

[[env.development.queues.producers]]
  queue = "contact-sync-development"
  binding = "CONTACT_SYNC_QUEUE"

[[env.development.queues.consumers]]
  queue = "sync-development"
  max_batch_size = 1
  max_retries = 5

[env.production]
[env.production.define]
  ENV = '"production"'
  RELEASE = '"prod"'
  PACKAGE = '"sync"'

[env.production.triggers]
  crons = ["*/47 * * * *"]

[[env.production.queues.producers]]
  queue = "event-sync-production"
  binding = "EVENT_QUEUE"

[[env.production.queues.producers]]
  queue = "contact-sync-production"
  binding = "CONTACT_SYNC_QUEUE"

[[env.production.queues.consumers]]
  queue = "sync-production"
  max_batch_size = 1
  max_retries = 5


[observability.logs]
  enabled = true
