name = "plot-sync"
main = "src/index.ts"
compatibility_date = "2024-11-18"
upload_source_maps = true

[[queues.producers]]
  queue = "plot-event-queue"
  binding = "EVENT_QUEUE"

[[queues.producers]]
  queue = "plot-contact-sync-queue"
  binding = "CONTACT_SYNC_QUEUE"

[[queues.consumers]]
  queue = "plot-sync-queue"
  max_batch_size = 1
  max_retries = 5

[triggers]
  crons = ["*/47 * * * *"]
