-- Generated SQL for agent table
-- This file is auto-generated by the gen-sql script
-- Do not edit manually


INSERT INTO public.agent (id, name, description, author_name, author_email, author_url, tools)
VALUES ('chat', 'AI Chat', 'Chat with AI models', 'Plot', 'team@plot.day', 'https://plot.day', '[{"id":"plot"},{"id":"ai"}]'::jsonb)
ON CONFLICT (id) 
DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  author_name = EXCLUDED.author_name,
  author_email = EXCLUDED.author_email,
  author_url = EXCLUDED.author_url,
  tools = EXCLUDED.tools,
  updated_at = now();


INSERT INTO public.agent (id, name, description, author_name, author_email, author_url, tools)
VALUES ('google-calendar', 'Google Calendar', 'Sync with Google Calendar', 'Plot', 'team@plot.day', 'https://plot.day', '[{"id":"auth","tools":[{"id":"plot"},{"id":"store"}]},{"id":"plot"},{"id":"run"},{"id":"store"},{"id":"webhook"}]'::jsonb)
ON CONFLICT (id) 
DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  author_name = EXCLUDED.author_name,
  author_email = EXCLUDED.author_email,
  author_url = EXCLUDED.author_url,
  tools = EXCLUDED.tools,
  updated_at = now();


INSERT INTO public.agent (id, name, description, author_name, author_email, author_url, tools)
VALUES ('google-contacts', 'Google Contacts', 'Sync with Google Contacts', 'Plot', 'team@plot.day', 'https://plot.day', '[{"id":"auth","tools":[{"id":"plot"},{"id":"store"}]},{"id":"plot"},{"id":"run"},{"id":"store"}]'::jsonb)
ON CONFLICT (id) 
DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  author_name = EXCLUDED.author_name,
  author_email = EXCLUDED.author_email,
  author_url = EXCLUDED.author_url,
  tools = EXCLUDED.tools,
  updated_at = now();


INSERT INTO public.agent (id, name, description, author_name, author_email, author_url, tools)
VALUES ('outlook-calendar', 'Outlook Calendar', 'Sync with Microsoft Outlook Calendar', 'Plot', 'team@plot.day', 'https://plot.day', '[{"id":"auth","tools":[{"id":"plot"},{"id":"store"}]},{"id":"plot"},{"id":"run"},{"id":"store"},{"id":"webhook"}]'::jsonb)
ON CONFLICT (id) 
DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  author_name = EXCLUDED.author_name,
  author_email = EXCLUDED.author_email,
  author_url = EXCLUDED.author_url,
  tools = EXCLUDED.tools,
  updated_at = now();


INSERT INTO public.agent (id, name, description, author_name, author_email, author_url, tools)
VALUES ('plot', 'Plot', 'Support setting up, using, and automating Plot', 'Plot', 'team@plot.day', 'https://plot.day', '[{"id":"plot"}]'::jsonb)
ON CONFLICT (id) 
DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  author_name = EXCLUDED.author_name,
  author_email = EXCLUDED.author_email,
  author_url = EXCLUDED.author_url,
  tools = EXCLUDED.tools,
  updated_at = now();
