-- Grant USAGE on all schemas to readonly and api
GRANT USAGE ON SCHEMA public, "user", admin, extensions TO readonly;
GRANT USAGE ON SCHEMA admin TO api;

-- Retroactive grants for all existing tables in all schemas
-- (Note: GRANT ON ALL TABLES includes VIEWS in PostgreSQL)
GRANT SELECT ON ALL TABLES IN SCHEMA public, "user", admin, extensions TO readonly;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA admin TO api;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA admin, extensions TO api;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA admin TO api;

-- Future grants for tables/views created by migrator or postgres
-- We use the global version (no IN SCHEMA) to ensure it applies to all schemas
ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO api;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT EXECUTE ON FUNCTIONS TO api;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT USAGE ON SEQUENCES TO api;

ALTER DEFAULT PRIVILEGES FOR ROLE migrator GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO api;
ALTER DEFAULT PRIVILEGES FOR ROLE migrator GRANT EXECUTE ON FUNCTIONS TO api;
ALTER DEFAULT PRIVILEGES FOR ROLE migrator GRANT USAGE ON SEQUENCES TO api;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT SELECT ON TABLES TO readonly;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT USAGE ON SEQUENCES TO readonly;
ALTER DEFAULT PRIVILEGES FOR ROLE postgres GRANT EXECUTE ON FUNCTIONS TO readonly;

ALTER DEFAULT PRIVILEGES FOR ROLE migrator GRANT SELECT ON TABLES TO readonly;
ALTER DEFAULT PRIVILEGES FOR ROLE migrator GRANT USAGE ON SEQUENCES TO readonly;
ALTER DEFAULT PRIVILEGES FOR ROLE migrator GRANT EXECUTE ON FUNCTIONS TO readonly;
