-- AUTO-GENERATED by pnpm gen-onboarding from libs/db/onboarding/*. Do not edit by hand.

-- Global onboarding thread + note content reconcile (affects all users).
-- Threads are authored by the system Plot twist instance and routed via the
-- @plot.updates auto-maintained announce topic (the @plot.updates topic is how
-- every user receives them — file_thread_priority_for_topic_members files them).
DO $$
DECLARE
    c_system_instance_id CONSTANT uuid := '0199b6f4-ae64-7718-0000-000000000001';
    c_twist_package_id CONSTANT uuid := '0199b6f4-ae64-7718-8a02-44716f30358f';
    v_plot_twist_id bigint;
    v_updates_topic_id uuid;
    v_thread_id uuid;
    v_note_id uuid;
BEGIN
    SELECT id INTO v_plot_twist_id FROM public.twist
        WHERE twist_package_id = c_twist_package_id AND environment = 'public' LIMIT 1;
    SELECT id INTO v_updates_topic_id FROM public.topic
        WHERE key = '@plot.updates' AND auto_maintained = TRUE AND team_id IS NULL LIMIT 1;
    -- Atlas-robust: skip on fresh DBs where the system twist / topic isn't seeded yet.
    IF v_plot_twist_id IS NULL OR v_updates_topic_id IS NULL THEN RETURN; END IF;

    -- welcome
    SELECT id INTO v_thread_id FROM public.thread
        WHERE key = 'welcome' AND twist_id = v_plot_twist_id AND archived_at IS NULL LIMIT 1;
    IF v_thread_id IS NULL THEN
        -- topic_id (not just the topic text) is what file_thread_priority_for_topic_members
        -- keys on — without it new users never get the thread filed / never see it.
        INSERT INTO public.thread (created_by, twist_id, icon, title, preview, key, topic_id, topic, contacts)
            VALUES (c_system_instance_id, v_plot_twist_id, 'twist:' || v_plot_twist_id::text,
                'Everything in its place', 'Plot is your workspace for making progress on what matters.', 'welcome', v_updates_topic_id, 'topic:' || v_updates_topic_id::text,
                ARRAY[c_system_instance_id])
        RETURNING id INTO v_thread_id;
    ELSE
        UPDATE public.thread SET title = 'Everything in its place', preview = 'Plot is your workspace for making progress on what matters.',
                topic_id = v_updates_topic_id, topic = 'topic:' || v_updates_topic_id::text
            WHERE id = v_thread_id
              AND (title, preview, topic_id) IS DISTINCT FROM ('Everything in its place', 'Plot is your workspace for making progress on what matters.', v_updates_topic_id);
    END IF;
    SELECT id INTO v_note_id FROM public.note
        WHERE thread_id = v_thread_id AND key = 'building-blocks' AND link_id IS NULL AND archived_at IS NULL LIMIT 1;
    IF v_note_id IS NULL THEN
        INSERT INTO public.note (author_id, created_by, thread_id, source_created_at, content, key)
            VALUES (c_system_instance_id, c_system_instance_id, v_thread_id, now() + (0 * interval '1 minute'), 'Plot is your workspace for collaborating without losing yourself in tools. **Focuses**, **Threads**, and **Notes** are the building blocks:

- **Focuses** are the parts of your work and life you direct your attention toward — Work, Personal, Launch New Product, Learn French. New threads arrive in your **Inbox**, and you organize by moving them into a focus.
- **Threads** are everything related to one piece of work, collected in one place: notes, messages, events, links to items in other apps, chats with twists.
- **Notes** are the content inside threads — your own, messages to others, or comments synced back to a connected app. Any note can be marked as a task.', 'building-blocks');
    ELSE
        UPDATE public.note SET content = 'Plot is your workspace for collaborating without losing yourself in tools. **Focuses**, **Threads**, and **Notes** are the building blocks:

- **Focuses** are the parts of your work and life you direct your attention toward — Work, Personal, Launch New Product, Learn French. New threads arrive in your **Inbox**, and you organize by moving them into a focus.
- **Threads** are everything related to one piece of work, collected in one place: notes, messages, events, links to items in other apps, chats with twists.
- **Notes** are the content inside threads — your own, messages to others, or comments synced back to a connected app. Any note can be marked as a task.'
            WHERE id = v_note_id AND content IS DISTINCT FROM 'Plot is your workspace for collaborating without losing yourself in tools. **Focuses**, **Threads**, and **Notes** are the building blocks:

- **Focuses** are the parts of your work and life you direct your attention toward — Work, Personal, Launch New Product, Learn French. New threads arrive in your **Inbox**, and you organize by moving them into a focus.
- **Threads** are everything related to one piece of work, collected in one place: notes, messages, events, links to items in other apps, chats with twists.
- **Notes** are the content inside threads — your own, messages to others, or comments synced back to a connected app. Any note can be marked as a task.';
    END IF;
    SELECT id INTO v_note_id FROM public.note
        WHERE thread_id = v_thread_id AND key = 'attention' AND link_id IS NULL AND archived_at IS NULL LIMIT 1;
    IF v_note_id IS NULL THEN
        INSERT INTO public.note (author_id, created_by, thread_id, source_created_at, content, key)
            VALUES (c_system_instance_id, c_system_instance_id, v_thread_id, now() + (1 * interval '1 minute'), 'When a thread needs your attention, mark it **To do** (⌘D) — it moves into the **Doing** section of your agenda and feed. You can also **Snooze** it (⌘⇧D) to act on it later. When you finish your part, mark it done — your tasks are completed and linked items in connected apps are updated (e.g. closing a Linear ticket).', 'attention');
    ELSE
        UPDATE public.note SET content = 'When a thread needs your attention, mark it **To do** (⌘D) — it moves into the **Doing** section of your agenda and feed. You can also **Snooze** it (⌘⇧D) to act on it later. When you finish your part, mark it done — your tasks are completed and linked items in connected apps are updated (e.g. closing a Linear ticket).'
            WHERE id = v_note_id AND content IS DISTINCT FROM 'When a thread needs your attention, mark it **To do** (⌘D) — it moves into the **Doing** section of your agenda and feed. You can also **Snooze** it (⌘⇧D) to act on it later. When you finish your part, mark it done — your tasks are completed and linked items in connected apps are updated (e.g. closing a Linear ticket).';
    END IF;
    SELECT id INTO v_note_id FROM public.note
        WHERE thread_id = v_thread_id AND key = 'feed-sections' AND link_id IS NULL AND archived_at IS NULL LIMIT 1;
    IF v_note_id IS NULL THEN
        INSERT INTO public.note (author_id, created_by, thread_id, source_created_at, content, key)
            VALUES (c_system_instance_id, c_system_instance_id, v_thread_id, now() + (2 * interval '1 minute'), 'Your activity feed groups everything into three sections, in order:

- **Doing** — what you''re actively working on, with unread updates pinned at the top (most urgent first).
- **Scheduled** — what you''ve planned for upcoming days.
- **Activity** — recent history across your focuses.

From an update at the top of Doing, mark it **To do** to keep working on it, or **Snooze** it to drop it into a future day.', 'feed-sections');
    ELSE
        UPDATE public.note SET content = 'Your activity feed groups everything into three sections, in order:

- **Doing** — what you''re actively working on, with unread updates pinned at the top (most urgent first).
- **Scheduled** — what you''ve planned for upcoming days.
- **Activity** — recent history across your focuses.

From an update at the top of Doing, mark it **To do** to keep working on it, or **Snooze** it to drop it into a future day.'
            WHERE id = v_note_id AND content IS DISTINCT FROM 'Your activity feed groups everything into three sections, in order:

- **Doing** — what you''re actively working on, with unread updates pinned at the top (most urgent first).
- **Scheduled** — what you''ve planned for upcoming days.
- **Activity** — recent history across your focuses.

From an update at the top of Doing, mark it **To do** to keep working on it, or **Snooze** it to drop it into a future day.';
    END IF;
    SELECT id INTO v_note_id FROM public.note
        WHERE thread_id = v_thread_id AND key = 'links' AND link_id IS NULL AND archived_at IS NULL LIMIT 1;
    IF v_note_id IS NULL THEN
        INSERT INTO public.note (author_id, created_by, thread_id, source_created_at, content, key)
            VALUES (c_system_instance_id, c_system_instance_id, v_thread_id, now() + (3 * interval '1 minute'), 'Threads can contain links to items in external services — documents, calendar events, web pages, issues, and more. These are created by connections (more on that later). Links keep everything related to your work in one place, so you always have the context you need.', 'links');
    ELSE
        UPDATE public.note SET content = 'Threads can contain links to items in external services — documents, calendar events, web pages, issues, and more. These are created by connections (more on that later). Links keep everything related to your work in one place, so you always have the context you need.'
            WHERE id = v_note_id AND content IS DISTINCT FROM 'Threads can contain links to items in external services — documents, calendar events, web pages, issues, and more. These are created by connections (more on that later). Links keep everything related to your work in one place, so you always have the context you need.';
    END IF;

    -- priorities
    SELECT id INTO v_thread_id FROM public.thread
        WHERE key = 'priorities' AND twist_id = v_plot_twist_id AND archived_at IS NULL LIMIT 1;
    IF v_thread_id IS NULL THEN
        -- topic_id (not just the topic text) is what file_thread_priority_for_topic_members
        -- keys on — without it new users never get the thread filed / never see it.
        INSERT INTO public.thread (created_by, twist_id, icon, title, preview, key, topic_id, topic, contacts)
            VALUES (c_system_instance_id, v_plot_twist_id, 'twist:' || v_plot_twist_id::text,
                'Create your initial focuses', 'Focuses are the areas you organize your threads around. Create one and Plot gathers the matching threads from your Inbox so you can file them in a tap.', 'priorities', v_updates_topic_id, 'topic:' || v_updates_topic_id::text,
                ARRAY[c_system_instance_id])
        RETURNING id INTO v_thread_id;
    ELSE
        UPDATE public.thread SET title = 'Create your initial focuses', preview = 'Focuses are the areas you organize your threads around. Create one and Plot gathers the matching threads from your Inbox so you can file them in a tap.',
                topic_id = v_updates_topic_id, topic = 'topic:' || v_updates_topic_id::text
            WHERE id = v_thread_id
              AND (title, preview, topic_id) IS DISTINCT FROM ('Create your initial focuses', 'Focuses are the areas you organize your threads around. Create one and Plot gathers the matching threads from your Inbox so you can file them in a tap.', v_updates_topic_id);
    END IF;
    SELECT id INTO v_note_id FROM public.note
        WHERE thread_id = v_thread_id AND key = 'intro' AND link_id IS NULL AND archived_at IS NULL LIMIT 1;
    IF v_note_id IS NULL THEN
        INSERT INTO public.note (author_id, created_by, thread_id, source_created_at, content, key)
            VALUES (c_system_instance_id, c_system_instance_id, v_thread_id, now() + (0 * interval '1 minute'), 'Focuses are the areas you direct your attention — roles like VP Marketing or Parent, goals like Launch New Product or Run a Marathon. They''re flat: no focus lives inside another. New threads land in your **Inbox**, and moving one into a focus is how you keep things organized.', 'intro');
    ELSE
        UPDATE public.note SET content = 'Focuses are the areas you direct your attention — roles like VP Marketing or Parent, goals like Launch New Product or Run a Marathon. They''re flat: no focus lives inside another. New threads land in your **Inbox**, and moving one into a focus is how you keep things organized.'
            WHERE id = v_note_id AND content IS DISTINCT FROM 'Focuses are the areas you direct your attention — roles like VP Marketing or Parent, goals like Launch New Product or Run a Marathon. They''re flat: no focus lives inside another. New threads land in your **Inbox**, and moving one into a focus is how you keep things organized.';
    END IF;
    SELECT id INTO v_note_id FROM public.note
        WHERE thread_id = v_thread_id AND key = 'inbox-everything' AND link_id IS NULL AND archived_at IS NULL LIMIT 1;
    IF v_note_id IS NULL THEN
        INSERT INTO public.note (author_id, created_by, thread_id, source_created_at, content, key)
            VALUES (c_system_instance_id, c_system_instance_id, v_thread_id, now() + (1 * interval '1 minute'), 'Open a focus to see just its threads. Your **Inbox** holds everything you haven''t sorted into a focus yet. And **Everything** shows all your threads across every focus and your Inbox at once — the place to look when you''re not sure where something is.', 'inbox-everything');
    ELSE
        UPDATE public.note SET content = 'Open a focus to see just its threads. Your **Inbox** holds everything you haven''t sorted into a focus yet. And **Everything** shows all your threads across every focus and your Inbox at once — the place to look when you''re not sure where something is.'
            WHERE id = v_note_id AND content IS DISTINCT FROM 'Open a focus to see just its threads. Your **Inbox** holds everything you haven''t sorted into a focus yet. And **Everything** shows all your threads across every focus and your Inbox at once — the place to look when you''re not sure where something is.';
    END IF;
    SELECT id INTO v_note_id FROM public.note
        WHERE thread_id = v_thread_id AND key = 'create-and-match' AND link_id IS NULL AND archived_at IS NULL LIMIT 1;
    IF v_note_id IS NULL THEN
        INSERT INTO public.note (author_id, created_by, thread_id, source_created_at, content, key)
            VALUES (c_system_instance_id, c_system_instance_id, v_thread_id, now() + (2 * interval '1 minute'), 'When you create a focus, describe what belongs in it and Plot finds the matching threads already in your Inbox, so you can file them in one step. Start with a handful of focuses for the areas you care about most — Work, Personal, a current project — and add more whenever you need them.', 'create-and-match');
    ELSE
        UPDATE public.note SET content = 'When you create a focus, describe what belongs in it and Plot finds the matching threads already in your Inbox, so you can file them in one step. Start with a handful of focuses for the areas you care about most — Work, Personal, a current project — and add more whenever you need them.'
            WHERE id = v_note_id AND content IS DISTINCT FROM 'When you create a focus, describe what belongs in it and Plot finds the matching threads already in your Inbox, so you can file them in one step. Start with a handful of focuses for the areas you care about most — Work, Personal, a current project — and add more whenever you need them.';
    END IF;
    SELECT id INTO v_note_id FROM public.note
        WHERE thread_id = v_thread_id AND key = 'todo' AND link_id IS NULL AND archived_at IS NULL LIMIT 1;
    IF v_note_id IS NULL THEN
        INSERT INTO public.note (author_id, created_by, thread_id, source_created_at, content, key)
            VALUES (c_system_instance_id, c_system_instance_id, v_thread_id, now() + (3 * interval '1 minute'), 'Create your first focus — for example, **Work** or **Personal**. You can always add more later.', 'todo');
    ELSE
        UPDATE public.note SET content = 'Create your first focus — for example, **Work** or **Personal**. You can always add more later.'
            WHERE id = v_note_id AND content IS DISTINCT FROM 'Create your first focus — for example, **Work** or **Personal**. You can always add more later.';
    END IF;

    -- connections
    SELECT id INTO v_thread_id FROM public.thread
        WHERE key = 'connections' AND twist_id = v_plot_twist_id AND archived_at IS NULL LIMIT 1;
    IF v_thread_id IS NULL THEN
        -- topic_id (not just the topic text) is what file_thread_priority_for_topic_members
        -- keys on — without it new users never get the thread filed / never see it.
        INSERT INTO public.thread (created_by, twist_id, icon, title, preview, key, topic_id, topic, contacts)
            VALUES (c_system_instance_id, v_plot_twist_id, 'twist:' || v_plot_twist_id::text,
                'Add your Connections', 'Connections sync items from your other apps and services into Plot, often two-way.', 'connections', v_updates_topic_id, 'topic:' || v_updates_topic_id::text,
                ARRAY[c_system_instance_id])
        RETURNING id INTO v_thread_id;
    ELSE
        UPDATE public.thread SET title = 'Add your Connections', preview = 'Connections sync items from your other apps and services into Plot, often two-way.',
                topic_id = v_updates_topic_id, topic = 'topic:' || v_updates_topic_id::text
            WHERE id = v_thread_id
              AND (title, preview, topic_id) IS DISTINCT FROM ('Add your Connections', 'Connections sync items from your other apps and services into Plot, often two-way.', v_updates_topic_id);
    END IF;
    SELECT id INTO v_note_id FROM public.note
        WHERE thread_id = v_thread_id AND key = 'intro' AND link_id IS NULL AND archived_at IS NULL LIMIT 1;
    IF v_note_id IS NULL THEN
        INSERT INTO public.note (author_id, created_by, thread_id, source_created_at, content, key)
            VALUES (c_system_instance_id, c_system_instance_id, v_thread_id, now() + (0 * interval '1 minute'), '**Connections** sync items from your other apps and services into Plot, often two-way. For example, connect your calendar to see events as threads, or connect your email to bring in conversations. You can view and interact with items right from Plot — see and add comments on documents, respond to messages, update issues — the goal is to bring everything into one place.', 'intro');
    ELSE
        UPDATE public.note SET content = '**Connections** sync items from your other apps and services into Plot, often two-way. For example, connect your calendar to see events as threads, or connect your email to bring in conversations. You can view and interact with items right from Plot — see and add comments on documents, respond to messages, update issues — the goal is to bring everything into one place.'
            WHERE id = v_note_id AND content IS DISTINCT FROM '**Connections** sync items from your other apps and services into Plot, often two-way. For example, connect your calendar to see events as threads, or connect your email to bring in conversations. You can view and interact with items right from Plot — see and add comments on documents, respond to messages, update issues — the goal is to bring everything into one place.';
    END IF;
    SELECT id INTO v_note_id FROM public.note
        WHERE thread_id = v_thread_id AND key = 'channels' AND link_id IS NULL AND archived_at IS NULL LIMIT 1;
    IF v_note_id IS NULL THEN
        INSERT INTO public.note (author_id, created_by, thread_id, source_created_at, content, key)
            VALUES (c_system_instance_id, c_system_instance_id, v_thread_id, now() + (1 * interval '1 minute'), 'Each connection has channels you can enable or disable, letting you control exactly what syncs. Use the **Manage connections** command to browse available connections, vote for upcoming ones, and manage which are active.', 'channels');
    ELSE
        UPDATE public.note SET content = 'Each connection has channels you can enable or disable, letting you control exactly what syncs. Use the **Manage connections** command to browse available connections, vote for upcoming ones, and manage which are active.'
            WHERE id = v_note_id AND content IS DISTINCT FROM 'Each connection has channels you can enable or disable, letting you control exactly what syncs. Use the **Manage connections** command to browse available connections, vote for upcoming ones, and manage which are active.';
    END IF;
    SELECT id INTO v_note_id FROM public.note
        WHERE thread_id = v_thread_id AND key = 'todo' AND link_id IS NULL AND archived_at IS NULL LIMIT 1;
    IF v_note_id IS NULL THEN
        INSERT INTO public.note (author_id, created_by, thread_id, source_created_at, content, key)
            VALUES (c_system_instance_id, c_system_instance_id, v_thread_id, now() + (2 * interval '1 minute'), 'Set up your first connection using the **Manage connections** command.', 'todo');
    ELSE
        UPDATE public.note SET content = 'Set up your first connection using the **Manage connections** command.'
            WHERE id = v_note_id AND content IS DISTINCT FROM 'Set up your first connection using the **Manage connections** command.';
    END IF;

    -- getting-around
    SELECT id INTO v_thread_id FROM public.thread
        WHERE key = 'getting-around' AND twist_id = v_plot_twist_id AND archived_at IS NULL LIMIT 1;
    IF v_thread_id IS NULL THEN
        -- topic_id (not just the topic text) is what file_thread_priority_for_topic_members
        -- keys on — without it new users never get the thread filed / never see it.
        INSERT INTO public.thread (created_by, twist_id, icon, title, preview, key, topic_id, topic, contacts)
            VALUES (c_system_instance_id, v_plot_twist_id, 'twist:' || v_plot_twist_id::text,
                'Getting Around', 'Keyboard and touch shortcuts', 'getting-around', v_updates_topic_id, 'topic:' || v_updates_topic_id::text,
                ARRAY[c_system_instance_id])
        RETURNING id INTO v_thread_id;
    ELSE
        UPDATE public.thread SET title = 'Getting Around', preview = 'Keyboard and touch shortcuts',
                topic_id = v_updates_topic_id, topic = 'topic:' || v_updates_topic_id::text
            WHERE id = v_thread_id
              AND (title, preview, topic_id) IS DISTINCT FROM ('Getting Around', 'Keyboard and touch shortcuts', v_updates_topic_id);
    END IF;
    SELECT id INTO v_note_id FROM public.note
        WHERE thread_id = v_thread_id AND key = 'intro' AND link_id IS NULL AND archived_at IS NULL LIMIT 1;
    IF v_note_id IS NULL THEN
        INSERT INTO public.note (author_id, created_by, thread_id, source_created_at, content, key)
            VALUES (c_system_instance_id, c_system_instance_id, v_thread_id, now() + (0 * interval '1 minute'), 'Plot''s goal is to get you to meaningful work as quickly as possible. Here are some tips for navigating efficiently.', 'intro');
    ELSE
        UPDATE public.note SET content = 'Plot''s goal is to get you to meaningful work as quickly as possible. Here are some tips for navigating efficiently.'
            WHERE id = v_note_id AND content IS DISTINCT FROM 'Plot''s goal is to get you to meaningful work as quickly as possible. Here are some tips for navigating efficiently.';
    END IF;
    SELECT id INTO v_note_id FROM public.note
        WHERE thread_id = v_thread_id AND key = 'keyboard' AND link_id IS NULL AND archived_at IS NULL LIMIT 1;
    IF v_note_id IS NULL THEN
        INSERT INTO public.note (author_id, created_by, thread_id, source_created_at, content, key)
            VALUES (c_system_instance_id, c_system_instance_id, v_thread_id, now() + (1 * interval '1 minute'), '**Keyboard Navigation**

- **⌘/** (Ctrl+/ on Windows): Search across all your threads and focuses
- **⌘K** (Ctrl+K on Windows): Open the command palette
- **⌘J** (Ctrl+J on Windows): Switch to another focus (⌘⌥J / Ctrl+Alt+J on web browsers)
- **⌘D** (Ctrl+D on Windows): To do / Mark done — toggle whether you''re doing this thread
- **⌘⇧D** (Ctrl+Shift+D on Windows): Snooze a thread for a future day
- **⌘Up/Down** (Ctrl+Up/Down on Windows): Open previous/next thread
- **⌘Delete** (Ctrl+Backspace on Windows): Archive a thread
- **⌘N** (Ctrl+N on Windows): Create a new note (⌘⇧N / Ctrl+Shift+N on web browsers)
- **⌘Enter** (Ctrl+Enter on Windows): On a new thread, save as a task instead of a note', 'keyboard');
    ELSE
        UPDATE public.note SET content = '**Keyboard Navigation**

- **⌘/** (Ctrl+/ on Windows): Search across all your threads and focuses
- **⌘K** (Ctrl+K on Windows): Open the command palette
- **⌘J** (Ctrl+J on Windows): Switch to another focus (⌘⌥J / Ctrl+Alt+J on web browsers)
- **⌘D** (Ctrl+D on Windows): To do / Mark done — toggle whether you''re doing this thread
- **⌘⇧D** (Ctrl+Shift+D on Windows): Snooze a thread for a future day
- **⌘Up/Down** (Ctrl+Up/Down on Windows): Open previous/next thread
- **⌘Delete** (Ctrl+Backspace on Windows): Archive a thread
- **⌘N** (Ctrl+N on Windows): Create a new note (⌘⇧N / Ctrl+Shift+N on web browsers)
- **⌘Enter** (Ctrl+Enter on Windows): On a new thread, save as a task instead of a note'
            WHERE id = v_note_id AND content IS DISTINCT FROM '**Keyboard Navigation**

- **⌘/** (Ctrl+/ on Windows): Search across all your threads and focuses
- **⌘K** (Ctrl+K on Windows): Open the command palette
- **⌘J** (Ctrl+J on Windows): Switch to another focus (⌘⌥J / Ctrl+Alt+J on web browsers)
- **⌘D** (Ctrl+D on Windows): To do / Mark done — toggle whether you''re doing this thread
- **⌘⇧D** (Ctrl+Shift+D on Windows): Snooze a thread for a future day
- **⌘Up/Down** (Ctrl+Up/Down on Windows): Open previous/next thread
- **⌘Delete** (Ctrl+Backspace on Windows): Archive a thread
- **⌘N** (Ctrl+N on Windows): Create a new note (⌘⇧N / Ctrl+Shift+N on web browsers)
- **⌘Enter** (Ctrl+Enter on Windows): On a new thread, save as a task instead of a note';
    END IF;
    SELECT id INTO v_note_id FROM public.note
        WHERE thread_id = v_thread_id AND key = 'touch' AND link_id IS NULL AND archived_at IS NULL LIMIT 1;
    IF v_note_id IS NULL THEN
        INSERT INTO public.note (author_id, created_by, thread_id, source_created_at, content, key)
            VALUES (c_system_instance_id, c_system_instance_id, v_thread_id, now() + (2 * interval '1 minute'), '**Touch Gestures**

- **Long press** on items to open the menu
- **Swipe right** on threads: To do (or Mark done if it''s already in Doing)
- **Swipe left** on threads: Snooze for later
- **Share** a link from another app to Plot using the share sheet (iOS and Android)', 'touch');
    ELSE
        UPDATE public.note SET content = '**Touch Gestures**

- **Long press** on items to open the menu
- **Swipe right** on threads: To do (or Mark done if it''s already in Doing)
- **Swipe left** on threads: Snooze for later
- **Share** a link from another app to Plot using the share sheet (iOS and Android)'
            WHERE id = v_note_id AND content IS DISTINCT FROM '**Touch Gestures**

- **Long press** on items to open the menu
- **Swipe right** on threads: To do (or Mark done if it''s already in Doing)
- **Swipe left** on threads: Snooze for later
- **Share** a link from another app to Plot using the share sheet (iOS and Android)';
    END IF;

    -- twists
    SELECT id INTO v_thread_id FROM public.thread
        WHERE key = 'twists' AND twist_id = v_plot_twist_id AND archived_at IS NULL LIMIT 1;
    IF v_thread_id IS NULL THEN
        -- topic_id (not just the topic text) is what file_thread_priority_for_topic_members
        -- keys on — without it new users never get the thread filed / never see it.
        INSERT INTO public.thread (created_by, twist_id, icon, title, preview, key, topic_id, topic, contacts)
            VALUES (c_system_instance_id, v_plot_twist_id, 'twist:' || v_plot_twist_id::text,
                'Explore Twists', 'Twists are automations, workflows, and agents that do helpful things with your threads.', 'twists', v_updates_topic_id, 'topic:' || v_updates_topic_id::text,
                ARRAY[c_system_instance_id])
        RETURNING id INTO v_thread_id;
    ELSE
        UPDATE public.thread SET title = 'Explore Twists', preview = 'Twists are automations, workflows, and agents that do helpful things with your threads.',
                topic_id = v_updates_topic_id, topic = 'topic:' || v_updates_topic_id::text
            WHERE id = v_thread_id
              AND (title, preview, topic_id) IS DISTINCT FROM ('Explore Twists', 'Twists are automations, workflows, and agents that do helpful things with your threads.', v_updates_topic_id);
    END IF;
    SELECT id INTO v_note_id FROM public.note
        WHERE thread_id = v_thread_id AND key = 'intro' AND link_id IS NULL AND archived_at IS NULL LIMIT 1;
    IF v_note_id IS NULL THEN
        INSERT INTO public.note (author_id, created_by, thread_id, source_created_at, content, key)
            VALUES (c_system_instance_id, c_system_instance_id, v_thread_id, now() + (0 * interval '1 minute'), '**Twists** are automations, workflows, and agents that do helpful things with your threads — often working with items from your connections. For example, a twist might triage your inbox, summarize meeting notes, or create follow-up tasks from action items.', 'intro');
    ELSE
        UPDATE public.note SET content = '**Twists** are automations, workflows, and agents that do helpful things with your threads — often working with items from your connections. For example, a twist might triage your inbox, summarize meeting notes, or create follow-up tasks from action items.'
            WHERE id = v_note_id AND content IS DISTINCT FROM '**Twists** are automations, workflows, and agents that do helpful things with your threads — often working with items from your connections. For example, a twist might triage your inbox, summarize meeting notes, or create follow-up tasks from action items.';
    END IF;
    SELECT id INTO v_note_id FROM public.note
        WHERE thread_id = v_thread_id AND key = 'custom' AND link_id IS NULL AND archived_at IS NULL LIMIT 1;
    IF v_note_id IS NULL THEN
        INSERT INTO public.note (author_id, created_by, thread_id, source_created_at, content, key)
            VALUES (c_system_instance_id, c_system_instance_id, v_thread_id, now() + (1 * interval '1 minute'), 'You can also **create your own twists**, either by describing what you want (Plot AI will generate it for you) or by writing code. Custom twists can automate any workflow specific to your needs.', 'custom');
    ELSE
        UPDATE public.note SET content = 'You can also **create your own twists**, either by describing what you want (Plot AI will generate it for you) or by writing code. Custom twists can automate any workflow specific to your needs.'
            WHERE id = v_note_id AND content IS DISTINCT FROM 'You can also **create your own twists**, either by describing what you want (Plot AI will generate it for you) or by writing code. Custom twists can automate any workflow specific to your needs.';
    END IF;
    SELECT id INTO v_note_id FROM public.note
        WHERE thread_id = v_thread_id AND key = 'mention-plot' AND link_id IS NULL AND archived_at IS NULL LIMIT 1;
    IF v_note_id IS NULL THEN
        INSERT INTO public.note (author_id, created_by, thread_id, source_created_at, content, key)
            VALUES (c_system_instance_id, c_system_instance_id, v_thread_id, now() + (2 * interval '1 minute'), 'You can also **@mention Plot** in any thread to ask questions about your notes and links. Plot will search your content and answer using AI.', 'mention-plot');
    ELSE
        UPDATE public.note SET content = 'You can also **@mention Plot** in any thread to ask questions about your notes and links. Plot will search your content and answer using AI.'
            WHERE id = v_note_id AND content IS DISTINCT FROM 'You can also **@mention Plot** in any thread to ask questions about your notes and links. Plot will search your content and answer using AI.';
    END IF;
    SELECT id INTO v_note_id FROM public.note
        WHERE thread_id = v_thread_id AND key = 'todo' AND link_id IS NULL AND archived_at IS NULL LIMIT 1;
    IF v_note_id IS NULL THEN
        INSERT INTO public.note (author_id, created_by, thread_id, source_created_at, content, key)
            VALUES (c_system_instance_id, c_system_instance_id, v_thread_id, now() + (3 * interval '1 minute'), 'Try **@mentioning Plot** in any thread to ask a question about your notes.', 'todo');
    ELSE
        UPDATE public.note SET content = 'Try **@mentioning Plot** in any thread to ask a question about your notes.'
            WHERE id = v_note_id AND content IS DISTINCT FROM 'Try **@mentioning Plot** in any thread to ask a question about your notes.';
    END IF;

    -- notifications
    SELECT id INTO v_thread_id FROM public.thread
        WHERE key = 'notifications' AND twist_id = v_plot_twist_id AND archived_at IS NULL LIMIT 1;
    IF v_thread_id IS NULL THEN
        -- topic_id (not just the topic text) is what file_thread_priority_for_topic_members
        -- keys on — without it new users never get the thread filed / never see it.
        INSERT INTO public.thread (created_by, twist_id, icon, title, preview, key, topic_id, topic, contacts)
            VALUES (c_system_instance_id, v_plot_twist_id, 'twist:' || v_plot_twist_id::text,
                'Set up Notifications', 'Plot delivers notifications based on urgency, not instantly. Adjust per-focus timing to match how you work.', 'notifications', v_updates_topic_id, 'topic:' || v_updates_topic_id::text,
                ARRAY[c_system_instance_id])
        RETURNING id INTO v_thread_id;
    ELSE
        UPDATE public.thread SET title = 'Set up Notifications', preview = 'Plot delivers notifications based on urgency, not instantly. Adjust per-focus timing to match how you work.',
                topic_id = v_updates_topic_id, topic = 'topic:' || v_updates_topic_id::text
            WHERE id = v_thread_id
              AND (title, preview, topic_id) IS DISTINCT FROM ('Set up Notifications', 'Plot delivers notifications based on urgency, not instantly. Adjust per-focus timing to match how you work.', v_updates_topic_id);
    END IF;
    SELECT id INTO v_note_id FROM public.note
        WHERE thread_id = v_thread_id AND key = 'intro' AND link_id IS NULL AND archived_at IS NULL LIMIT 1;
    IF v_note_id IS NULL THEN
        INSERT INTO public.note (author_id, created_by, thread_id, source_created_at, content, key)
            VALUES (c_system_instance_id, c_system_instance_id, v_thread_id, now() + (0 * interval '1 minute'), 'Plot has smart notifications that are timed based on urgency rather than sending everything immediately. This means new messages and updates won''t interrupt you the moment they arrive — instead, they''re delivered within a timeframe you control. If you''re used to getting notified immediately for every message, you may want to adjust these defaults.', 'intro');
    ELSE
        UPDATE public.note SET content = 'Plot has smart notifications that are timed based on urgency rather than sending everything immediately. This means new messages and updates won''t interrupt you the moment they arrive — instead, they''re delivered within a timeframe you control. If you''re used to getting notified immediately for every message, you may want to adjust these defaults.'
            WHERE id = v_note_id AND content IS DISTINCT FROM 'Plot has smart notifications that are timed based on urgency rather than sending everything immediately. This means new messages and updates won''t interrupt you the moment they arrive — instead, they''re delivered within a timeframe you control. If you''re used to getting notified immediately for every message, you may want to adjust these defaults.';
    END IF;
    SELECT id INTO v_note_id FROM public.note
        WHERE thread_id = v_thread_id AND key = 'timing' AND link_id IS NULL AND archived_at IS NULL LIMIT 1;
    IF v_note_id IS NULL THEN
        INSERT INTO public.note (author_id, created_by, thread_id, source_created_at, content, key)
            VALUES (c_system_instance_id, c_system_instance_id, v_thread_id, now() + (1 * interval '1 minute'), 'Each focus has two timing settings:

- **See requests within** (default: 30 minutes) — how quickly you''re notified about messages and mentions
- **See updates within** (default: 1 hour) — how quickly you''re notified about other changes

To adjust, open a focus''s command menu and choose **Notifications**, or tap the notification icon on a focus.', 'timing');
    ELSE
        UPDATE public.note SET content = 'Each focus has two timing settings:

- **See requests within** (default: 30 minutes) — how quickly you''re notified about messages and mentions
- **See updates within** (default: 1 hour) — how quickly you''re notified about other changes

To adjust, open a focus''s command menu and choose **Notifications**, or tap the notification icon on a focus.'
            WHERE id = v_note_id AND content IS DISTINCT FROM 'Each focus has two timing settings:

- **See requests within** (default: 30 minutes) — how quickly you''re notified about messages and mentions
- **See updates within** (default: 1 hour) — how quickly you''re notified about other changes

To adjust, open a focus''s command menu and choose **Notifications**, or tap the notification icon on a focus.';
    END IF;
    SELECT id INTO v_note_id FROM public.note
        WHERE thread_id = v_thread_id AND key = 'quiet-hours' AND link_id IS NULL AND archived_at IS NULL LIMIT 1;
    IF v_note_id IS NULL THEN
        INSERT INTO public.note (author_id, created_by, thread_id, source_created_at, content, key)
            VALUES (c_system_instance_id, c_system_instance_id, v_thread_id, now() + (2 * interval '1 minute'), 'Plot also has **quiet hours** (default: 9 PM – 7 AM) during which notifications are silenced. You can customize quiet hours per focus in the same Notifications settings.', 'quiet-hours');
    ELSE
        UPDATE public.note SET content = 'Plot also has **quiet hours** (default: 9 PM – 7 AM) during which notifications are silenced. You can customize quiet hours per focus in the same Notifications settings.'
            WHERE id = v_note_id AND content IS DISTINCT FROM 'Plot also has **quiet hours** (default: 9 PM – 7 AM) during which notifications are silenced. You can customize quiet hours per focus in the same Notifications settings.';
    END IF;
    SELECT id INTO v_note_id FROM public.note
        WHERE thread_id = v_thread_id AND key = 'todo' AND link_id IS NULL AND archived_at IS NULL LIMIT 1;
    IF v_note_id IS NULL THEN
        INSERT INTO public.note (author_id, created_by, thread_id, source_created_at, content, key)
            VALUES (c_system_instance_id, c_system_instance_id, v_thread_id, now() + (3 * interval '1 minute'), 'Adjust notification timing for your most important focus.', 'todo');
    ELSE
        UPDATE public.note SET content = 'Adjust notification timing for your most important focus.'
            WHERE id = v_note_id AND content IS DISTINCT FROM 'Adjust notification timing for your most important focus.';
    END IF;

    -- clean-up
    SELECT id INTO v_thread_id FROM public.thread
        WHERE key = 'clean-up' AND twist_id = v_plot_twist_id AND archived_at IS NULL LIMIT 1;
    IF v_thread_id IS NULL THEN
        -- topic_id (not just the topic text) is what file_thread_priority_for_topic_members
        -- keys on — without it new users never get the thread filed / never see it.
        INSERT INTO public.thread (created_by, twist_id, icon, title, preview, key, topic_id, topic, contacts)
            VALUES (c_system_instance_id, v_plot_twist_id, 'twist:' || v_plot_twist_id::text,
                'Clean up without losing anything', 'Archive hides mistakes and the focuses you''re no longer working in — their threads return to your Inbox. To finish a thread, tap **Finish** instead.', 'clean-up', v_updates_topic_id, 'topic:' || v_updates_topic_id::text,
                ARRAY[c_system_instance_id])
        RETURNING id INTO v_thread_id;
    ELSE
        UPDATE public.thread SET title = 'Clean up without losing anything', preview = 'Archive hides mistakes and the focuses you''re no longer working in — their threads return to your Inbox. To finish a thread, tap **Finish** instead.',
                topic_id = v_updates_topic_id, topic = 'topic:' || v_updates_topic_id::text
            WHERE id = v_thread_id
              AND (title, preview, topic_id) IS DISTINCT FROM ('Clean up without losing anything', 'Archive hides mistakes and the focuses you''re no longer working in — their threads return to your Inbox. To finish a thread, tap **Finish** instead.', v_updates_topic_id);
    END IF;
    SELECT id INTO v_note_id FROM public.note
        WHERE thread_id = v_thread_id AND key = 'archive' AND link_id IS NULL AND archived_at IS NULL LIMIT 1;
    IF v_note_id IS NULL THEN
        INSERT INTO public.note (author_id, created_by, thread_id, source_created_at, content, key)
            VALUES (c_system_instance_id, c_system_instance_id, v_thread_id, now() + (0 * interval '1 minute'), '**Archive a thread** when it shouldn''t have been created — a duplicate, a stray, or a mistake. Archive isn''t how you mark work done: when you''ve finished your part, tap **Finish** instead. That keeps the thread in Activity for everyone and completes your tasks plus any linked items in connected apps.

**Archive a focus** when you''re no longer working in that area. It drops out of your sidebar and its threads return to your **Inbox** — nothing is lost, and unarchiving the focus puts them back.

Archive hides items everywhere — for you and anyone you share with. Nothing is deleted; you can bring items back anytime.', 'archive');
    ELSE
        UPDATE public.note SET content = '**Archive a thread** when it shouldn''t have been created — a duplicate, a stray, or a mistake. Archive isn''t how you mark work done: when you''ve finished your part, tap **Finish** instead. That keeps the thread in Activity for everyone and completes your tasks plus any linked items in connected apps.

**Archive a focus** when you''re no longer working in that area. It drops out of your sidebar and its threads return to your **Inbox** — nothing is lost, and unarchiving the focus puts them back.

Archive hides items everywhere — for you and anyone you share with. Nothing is deleted; you can bring items back anytime.'
            WHERE id = v_note_id AND content IS DISTINCT FROM '**Archive a thread** when it shouldn''t have been created — a duplicate, a stray, or a mistake. Archive isn''t how you mark work done: when you''ve finished your part, tap **Finish** instead. That keeps the thread in Activity for everyone and completes your tasks plus any linked items in connected apps.

**Archive a focus** when you''re no longer working in that area. It drops out of your sidebar and its threads return to your **Inbox** — nothing is lost, and unarchiving the focus puts them back.

Archive hides items everywhere — for you and anyone you share with. Nothing is deleted; you can bring items back anytime.';
    END IF;
    SELECT id INTO v_note_id FROM public.note
        WHERE thread_id = v_thread_id AND key = 'show-archived' AND link_id IS NULL AND archived_at IS NULL LIMIT 1;
    IF v_note_id IS NULL THEN
        INSERT INTO public.note (author_id, created_by, thread_id, source_created_at, content, key)
            VALUES (c_system_instance_id, c_system_instance_id, v_thread_id, now() + (1 * interval '1 minute'), 'To archive, open the command menu on any thread or focus. To see archived items, choose **Show archived** from a focus''s **More commands** menu — archived threads and notes reappear so you can unarchive them.', 'show-archived');
    ELSE
        UPDATE public.note SET content = 'To archive, open the command menu on any thread or focus. To see archived items, choose **Show archived** from a focus''s **More commands** menu — archived threads and notes reappear so you can unarchive them.'
            WHERE id = v_note_id AND content IS DISTINCT FROM 'To archive, open the command menu on any thread or focus. To see archived items, choose **Show archived** from a focus''s **More commands** menu — archived threads and notes reappear so you can unarchive them.';
    END IF;
END $$;

-- Regenerated per-user-state functions (new signups only).
CREATE OR REPLACE FUNCTION public.file_onboarding_schedules ()
    RETURNS TRIGGER
    LANGUAGE plpgsql
    AS $$
DECLARE
    v_thread_key text;
    v_date_offset integer;
    v_order integer;
    v_active boolean;
    v_importance smallint;
BEGIN
    -- Skip if explicitly requested (e.g. during repair migrations for existing users)
    IF current_setting('plot.skip_onboarding_schedules', true) = 'true' THEN
        RETURN NEW;
    END IF;

    SELECT key INTO v_thread_key FROM public.thread WHERE id = NEW.thread_id;

    -- ONBOARDING:BEGIN schedules
    IF v_thread_key IN ('welcome', 'priorities', 'connections', 'getting-around', 'twists', 'notifications', 'clean-up') THEN
        CASE v_thread_key
            WHEN 'welcome' THEN v_date_offset := 0; v_order := 100; v_active := FALSE; v_importance := 95;
            WHEN 'priorities' THEN v_date_offset := 0; v_order := 200; v_active := TRUE; v_importance := 90;
            WHEN 'connections' THEN v_date_offset := 0; v_order := 300; v_active := TRUE; v_importance := 85;
            WHEN 'getting-around' THEN v_date_offset := 0; v_order := 400; v_active := FALSE; v_importance := 80;
            WHEN 'twists' THEN v_date_offset := 1; v_order := 500; v_active := TRUE; v_importance := 70;
            WHEN 'notifications' THEN v_date_offset := 2; v_order := 600; v_active := TRUE; v_importance := 65;
            WHEN 'clean-up' THEN v_date_offset := 3; v_order := 700; v_active := FALSE; v_importance := 60;
        END CASE;

        INSERT INTO public.thread_state (user_id, thread_id, active, importance, "order", "on")
        VALUES (NEW.user_id, NEW.thread_id, v_active, v_importance, v_order,
            CASE WHEN v_date_offset = 0 THEN daterange('1970-01-01', NULL)
                 ELSE daterange((CURRENT_DATE + v_date_offset), NULL) END)
        ON CONFLICT (user_id, thread_id) DO NOTHING;
    END IF;
-- ONBOARDING:END schedules

    RETURN NEW;
END;
$$;
CREATE OR REPLACE FUNCTION public.file_onboarding_todos ()
    RETURNS TRIGGER
    LANGUAGE plpgsql
    AS $$
DECLARE
    v_thread_key text;
    v_contact_id uuid;
BEGIN
    -- Escape hatch for repair migrations.
    IF current_setting('plot.skip_onboarding_todos', true) = 'true' THEN
        RETURN NEW;
    END IF;

    SELECT key INTO v_thread_key FROM public.thread WHERE id = NEW.thread_id;
    -- ONBOARDING:BEGIN todos
    IF v_thread_key NOT IN ('priorities', 'connections', 'twists', 'notifications') THEN
        RETURN NEW;
    END IF;
-- ONBOARDING:END todos

    -- Use the user's primary linked contact as the actor — same actor used
    -- elsewhere for per-user task ownership.
    SELECT uc.contact_id INTO v_contact_id
    FROM public.user_contact uc
    WHERE uc.user_id = NEW.user_id
      AND uc."primary" = TRUE
      AND uc.linked = TRUE
      AND uc.archived_at IS NULL
    LIMIT 1;

    IF v_contact_id IS NULL THEN
        RETURN NEW;
    END IF;

    -- ON CONFLICT DO NOTHING preserves prior decisions: if the user previously
    -- had this Todo and archived it (with or without marking Done), we leave
    -- the archived row alone instead of resurrecting it.
    INSERT INTO public.note_tag (actor_id, note_id, tag_id)
    SELECT v_contact_id, n.id, 1
    FROM public.note n
    WHERE n.thread_id = NEW.thread_id
      AND n.key = 'todo'
      AND n.archived_at IS NULL
    ON CONFLICT (actor_id, note_id, tag_id) DO NOTHING;

    RETURN NEW;
END;
$$;
CREATE OR REPLACE FUNCTION public.activate_invited_user (p_user_id uuid)
    RETURNS jsonb
    LANGUAGE plpgsql
    SET search_path TO 'public'
    AS $function$
DECLARE
    c_system_instance_id CONSTANT uuid := '0199b6f4-ae64-7718-0000-000000000001';
    c_twist_package_id CONSTANT uuid := '0199b6f4-ae64-7718-8a02-44716f30358f';
    v_root_priority_id uuid;
    v_new_path ltree;
    v_plot_team_group_id uuid;
    v_plot_twist_id bigint;
    v_user_contact_id uuid;
    v_welcome_thread_id uuid;
BEGIN
    -- Already has a root priority?
    SELECT
        id INTO v_root_priority_id
    FROM
        public.priority
    WHERE
        user_id = p_user_id
        AND nlevel (path) = 1
    ORDER BY
        created_at ASC
    LIMIT 1;
    IF v_root_priority_id IS NOT NULL THEN
        RETURN jsonb_build_object('activated', FALSE, 'already_active', TRUE, 'root_priority_id', v_root_priority_id);
    END IF;
    -- Create the root priority. default_priority_user_id fills user_id
    -- from created_by, so the new row is fully owned by the user.
    v_new_path := generate_path (NULL);
    INSERT INTO public.priority (created_by, user_id, title, path, color)
        VALUES (p_user_id, p_user_id, 'Everything', v_new_path, 0)
    RETURNING
        id INTO v_root_priority_id;
    -- Resolve the Plot Team group once — used for the welcome thread's
    -- groups array (so the user's first message reaches the Plot team).
    -- Prefer the full "Plot" team's auto-maintained group (everyone on the
    -- team, what we want in prod); fall back to the Plot publisher admin
    -- group for environments where the Plot team doesn't exist yet.
    SELECT
        COALESCE((
            SELECT
                g.id
            FROM public.group g
            JOIN public.team t ON t.id = g.team_id
            WHERE
                g.auto_maintained = TRUE
                AND g.auto_team_admin_team_id IS NULL
                AND t.name = 'Plot' LIMIT 1), (
        SELECT
            g.id
        FROM public.group g
        WHERE
            g.auto_maintained = TRUE
            AND g.auto_publisher_id = (
                SELECT
                    id
                FROM public.publisher
            WHERE
                name = 'Plot' LIMIT 1)
LIMIT 1)) INTO v_plot_team_group_id;
    -- No special hardcoded focuses are seeded. Onboarding threads (the
    -- per-user welcome below and the shared global onboarding set) land in
    -- the user's Inbox/root via classify_thread_for_user's root_fallback and
    -- a shared topic = 'onboarding'. The user organizes them however they
    -- like; moving one into a focus carries the rest along (topic match).
    -- Seed a per-user welcome thread authored by the shared system Plot
    -- twist_instance (same pattern as the global onboarding threads). The
    -- thread is visible only to the new user (via contacts) and the Plot
    -- Team (via groups). It pins to the top of the user's agenda with
    -- order = 50, ahead of the global 'welcome' thread (order = 100).
    --
    -- Skipped entirely when the Plot Team group hasn't been seeded yet —
    -- avoids noisy welcomes in ephemeral test databases that don't have
    -- the Plot publisher/team bootstrapped.
    IF v_plot_team_group_id IS NOT NULL THEN
        SELECT
            id INTO v_plot_twist_id
        FROM
            public.twist
        WHERE
            twist_package_id = c_twist_package_id
            AND environment = 'public'
        LIMIT 1;
        -- The API worker inserts the primary contact row a moment after
        -- this trigger runs, so user_contact may not exist yet. Seed it
        -- ourselves via upsert_user_contact (idempotent via ON CONFLICT
        -- (email) + ON CONFLICT (user_id, contact_id)) so the welcome
        -- thread's contacts array has the user's primary contact from
        -- the start.
        DECLARE v_user_email text;
        v_user_name text;
        v_user_avatar text;
        BEGIN
            SELECT
                email,
                name,
                avatar_url INTO v_user_email,
                v_user_name,
                v_user_avatar
            FROM
                public."user"
            WHERE
                id = p_user_id;
            IF v_user_email IS NOT NULL THEN
                PERFORM
                    public.upsert_user_contact (p_user_id, v_user_email, v_user_name, v_user_avatar);
            END IF;
        END;
        SELECT
            contact_id INTO v_user_contact_id
        FROM
            public.user_contact
        WHERE
            user_id = p_user_id
            AND "primary" = TRUE
            AND linked = TRUE
            AND archived_at IS NULL
        LIMIT 1;
        -- twist_id is intentionally NULL: welcome-user is a per-user thread
        -- and must not participate in cross-user (twist_id, key) dedup. The
        -- twist_instance_id in created_by is what makes this "twist-authored"
        -- for peer-filing purposes; icon preserves the visual attribution.
        -- contacts: the synthetic "Plot Team" sender (so the row header
        -- attributes the thread to Plot Team, same as the shared onboarding
        -- threads) PLUS the user's own contact (load-bearing for the user's
        -- own visibility — _otherContactIds excludes self, so only "Plot Team"
        -- shows). groups carries the Plot Team group so replies reach the team.
        -- ONBOARDING:BEGIN welcome-user
        INSERT INTO public.thread (created_by, icon, title, preview, key, topic, contacts, groups)
            VALUES (c_system_instance_id, CASE WHEN v_plot_twist_id IS NOT NULL THEN 'twist:' || v_plot_twist_id::text END,
                'Welcome to Plot!', 'Glad something brought you here.', 'welcome-user', 'onboarding',
                ARRAY[c_system_instance_id] || (CASE WHEN v_user_contact_id IS NOT NULL THEN ARRAY[v_user_contact_id] ELSE ARRAY[]::uuid[] END),
                ARRAY[v_plot_team_group_id])
        RETURNING id INTO v_welcome_thread_id;
        INSERT INTO public.thread_priority (thread_id, user_id, priority_id)
            VALUES (v_welcome_thread_id, p_user_id, v_root_priority_id)
        ON CONFLICT ON CONSTRAINT thread_priority_pkey DO NOTHING;
        INSERT INTO public.thread_state (user_id, thread_id, importance, "order", "on")
            VALUES (p_user_id, v_welcome_thread_id, 100, 50, daterange('1970-01-01', NULL))
        ON CONFLICT (user_id, thread_id) DO NOTHING;
        INSERT INTO public.note (author_id, created_by, thread_id, source_created_at, content, key)
            VALUES (c_system_instance_id, c_system_instance_id, v_welcome_thread_id, now() + interval '0 millisecond', 'Glad something brought you here. Maybe it''s a project you want to move forward, a team you want to work with more clearly, or a sense that more is possible when you direct your best energy into the work only you can do.

Plot is built for collaborating without getting buried — every conversation has a place, and the best of your day stays yours. Tell us what you''re trying to make progress on, where you''re stuck, or what''s not quite working yet. We read every reply.', 'welcome')
        ON CONFLICT (thread_id, link_id, key) WHERE key IS NOT NULL DO NOTHING;
        INSERT INTO public.note (author_id, created_by, thread_id, source_created_at, content, key)
            VALUES (c_system_instance_id, c_system_instance_id, v_welcome_thread_id, now() + interval '1 millisecond', 'Your account has been upgraded to the **Core plan** free for 30 days so you can try up to 5 connections and 2 twists. You can choose to keep the upgrade or go **Pro** at any time. Otherwise, after 30 days, you''ll automatically continue on the Free plan, which includes unlimited history and sharing. Any connections or twists over your new limit will be archived.', 'core-trial')
        ON CONFLICT (thread_id, link_id, key) WHERE key IS NOT NULL DO NOTHING;
-- ONBOARDING:END welcome-user
    END IF;
    -- Priority routing is learned from user moves (thread_priority.user_moved).
    -- New users start with no training examples; incoming threads land in the
    -- root priority (Inbox) until the user moves one into a focus they create.
    -- classify_thread_for_user then picks that focus up automatically for
    -- similar future threads.
    RETURN jsonb_build_object('activated', TRUE, 'already_active', FALSE, 'root_priority_id', v_root_priority_id);
END;
$function$;
