-- Drop "link" view
DROP VIEW "user"."link";
-- Drop "link_x" view
DROP VIEW "public"."link_x";
-- Modify "link" table
ALTER TABLE "public"."link" ADD COLUMN "logo" text NULL;
-- Create "link_x" view
CREATE VIEW "public"."link_x" (
  "id",
  "created_at",
  "updated_at",
  "thread_id",
  "source",
  "source_created_at",
  "source_priority_root",
  "author_id",
  "twist_id",
  "created_by",
  "updated_by",
  "sync_depth",
  "title",
  "preview",
  "assignee_id",
  "type",
  "status",
  "actions",
  "meta",
  "source_url",
  "logo",
  "channel_id",
  "embedding",
  "match",
  "merged_from_thread_id",
  "priority_id",
  "priority_path"
) AS SELECT l.id,
    l.created_at,
    l.updated_at,
    l.thread_id,
    l.source,
    l.source_created_at,
    l.source_priority_root,
    l.author_id,
    l.twist_id,
    l.created_by,
    l.updated_by,
    l.sync_depth,
    l.title,
    l.preview,
    l.assignee_id,
    l.type,
    l.status,
    l.actions,
    l.meta,
    l.source_url,
    l.logo,
    l.channel_id,
    l.embedding,
    l.match,
    l.merged_from_thread_id,
    COALESCE(l.priority_id, t.priority_id) AS priority_id,
    COALESCE(pp.path, tp.path) AS priority_path
   FROM public.link l
     LEFT JOIN public.thread t ON t.id = l.thread_id
     LEFT JOIN public.priority tp ON tp.id = t.priority_id
     LEFT JOIN public.priority pp ON pp.id = l.priority_id;
-- Create "link" view
CREATE VIEW "user"."link" (
  "user_id",
  "id",
  "created_at",
  "updated_at",
  "thread_id",
  "source",
  "source_created_at",
  "author_id",
  "twist_id",
  "created_by",
  "updated_by",
  "sync_depth",
  "title",
  "preview",
  "assignee_id",
  "type",
  "status",
  "actions",
  "meta",
  "source_url",
  "logo",
  "priority_id",
  "merged_from_thread_id",
  "priority_path"
) AS SELECT upe.user_id,
    l.id,
    l.created_at,
    l.updated_at,
    l.thread_id,
    l.source,
    l.source_created_at,
    l.author_id,
    l.twist_id,
    l.created_by,
    l.updated_by,
    l.sync_depth,
    l.title,
    l.preview,
    l.assignee_id,
    l.type,
    l.status,
    l.actions,
    l.meta,
    l.source_url,
    l.logo,
    l.priority_id,
    l.merged_from_thread_id,
    upe.path AS priority_path
   FROM public.link_x l
     JOIN "user".priority_expanded upe ON l.priority_id = upe.priority_id;
