-- AUTO-GENERATED by pnpm gen-onboarding from libs/db/onboarding/*. Do not edit by hand.

-- Global onboarding thread + note content reconcile (affects all users).
-- Threads are authored by the system Plot twist instance and routed via the
-- @plot.updates auto-maintained announce topic (the @plot.updates topic is how
-- every user receives them — file_thread_priority_for_topic_members files them).
DO $$
DECLARE
    c_system_instance_id CONSTANT uuid := '0199b6f4-ae64-7718-0000-000000000001';
    c_twist_package_id CONSTANT uuid := '0199b6f4-ae64-7718-8a02-44716f30358f';
    v_plot_twist_id bigint;
    v_updates_topic_id uuid;
    v_thread_id uuid;
    v_note_id uuid;
BEGIN
    SELECT id INTO v_plot_twist_id FROM public.twist
        WHERE twist_package_id = c_twist_package_id AND environment = 'public' LIMIT 1;
    SELECT id INTO v_updates_topic_id FROM public.topic
        WHERE key = '@plot.updates' AND auto_maintained = TRUE AND team_id IS NULL LIMIT 1;
    -- Atlas-robust: skip on fresh DBs where the system twist / topic isn't seeded yet.
    IF v_plot_twist_id IS NULL OR v_updates_topic_id IS NULL THEN RETURN; END IF;

    -- welcome
    SELECT id INTO v_thread_id FROM public.thread
        WHERE key = 'welcome' AND created_by = c_system_instance_id AND archived_at IS NULL LIMIT 1;
    IF v_thread_id IS NULL THEN
        -- topic_id (not just the topic text) is what file_thread_priority_for_topic_members
        -- keys on — without it new users never get the thread filed / never see it.
        INSERT INTO public.thread (created_by, twist_id, icon, title, preview, key, topic_id, topic, contacts)
            VALUES (c_system_instance_id, v_plot_twist_id, 'twist:' || v_plot_twist_id::text,
                'Everything in its place', 'Plot is designed around a simple workflow that keeps your focus where you choose while knowing what''s happening.', 'welcome', v_updates_topic_id, 'topic:' || v_updates_topic_id::text,
                ARRAY[c_system_instance_id])
        RETURNING id INTO v_thread_id;
    ELSE
        UPDATE public.thread SET title = 'Everything in its place', preview = 'Plot is designed around a simple workflow that keeps your focus where you choose while knowing what''s happening.',
                topic_id = v_updates_topic_id, topic = 'topic:' || v_updates_topic_id::text
            WHERE id = v_thread_id
              AND (title, preview, topic_id) IS DISTINCT FROM ('Everything in its place', 'Plot is designed around a simple workflow that keeps your focus where you choose while knowing what''s happening.', v_updates_topic_id);
    END IF;
    SELECT id INTO v_note_id FROM public.note
        WHERE thread_id = v_thread_id AND key = 'building-blocks' AND link_id IS NULL AND archived_at IS NULL LIMIT 1;
    IF v_note_id IS NULL THEN
        INSERT INTO public.note (author_id, created_by, thread_id, source_created_at, content, key)
            VALUES (c_system_instance_id, c_system_instance_id, v_thread_id, now() + (0 * interval '1 minute'), 'Plot is designed around a simple workflow that keeps your focus where you choose while knowing what''s happening.

New and updated threads arrive at the top of **Active**. _When a thread…_

- _… is just FYI_: Simply read it and it''ll move to **Done**.
- _… needs follow-up or careful reading_: Mark it **To do** to keep it in **Active**.
- _… deserves attention later_: Mark it **Do later** to move it out of **Active** until a future day.
- _… belongs in another focus_: **Move** it. Plot learns and moves similar threads there in the future.
- _… never needs attention_: **Mute** it. You can always find threads in Done or with search, but muted threads (and similar ones) will skip **Active**.

Instead of interruptions fragmenting your day, you can trust that everything gets done at the best time.', 'building-blocks');
    ELSE
        UPDATE public.note SET content = 'Plot is designed around a simple workflow that keeps your focus where you choose while knowing what''s happening.

New and updated threads arrive at the top of **Active**. _When a thread…_

- _… is just FYI_: Simply read it and it''ll move to **Done**.
- _… needs follow-up or careful reading_: Mark it **To do** to keep it in **Active**.
- _… deserves attention later_: Mark it **Do later** to move it out of **Active** until a future day.
- _… belongs in another focus_: **Move** it. Plot learns and moves similar threads there in the future.
- _… never needs attention_: **Mute** it. You can always find threads in Done or with search, but muted threads (and similar ones) will skip **Active**.

Instead of interruptions fragmenting your day, you can trust that everything gets done at the best time.'
            WHERE id = v_note_id AND content IS DISTINCT FROM 'Plot is designed around a simple workflow that keeps your focus where you choose while knowing what''s happening.

New and updated threads arrive at the top of **Active**. _When a thread…_

- _… is just FYI_: Simply read it and it''ll move to **Done**.
- _… needs follow-up or careful reading_: Mark it **To do** to keep it in **Active**.
- _… deserves attention later_: Mark it **Do later** to move it out of **Active** until a future day.
- _… belongs in another focus_: **Move** it. Plot learns and moves similar threads there in the future.
- _… never needs attention_: **Mute** it. You can always find threads in Done or with search, but muted threads (and similar ones) will skip **Active**.

Instead of interruptions fragmenting your day, you can trust that everything gets done at the best time.';
    END IF;
    SELECT id INTO v_note_id FROM public.note
        WHERE thread_id = v_thread_id AND key = 'focuses' AND link_id IS NULL AND archived_at IS NULL LIMIT 1;
    IF v_note_id IS NULL THEN
        INSERT INTO public.note (author_id, created_by, thread_id, source_created_at, content, key)
            VALUES (c_system_instance_id, c_system_instance_id, v_thread_id, now() + (1 * interval '1 minute'), 'By bringing all you work together, Plot eliminates time and attention lost to jump around tools. Instead of organizing your work by _where_ it is, you organize it by _how_ you work on it. This lets you make real progress in an area you choose.

Create focuses for:

- _Important projects_: With everything related to a project in one focus, you can find what you need quickly, with a clear view of what''s outstanding. Even better, you can send related messages and replies without getting pulled into unrelated work that happens to be in the same chat, inbox, or app.
- _Core roles_: At work, you might have direct responsibilities while also managing others. Putting these in separate focuses ensures you make progress on your goals while giving your team the attention they deserve.
- _Secondary roles_: Your work for extra roles you take on, like volunteering, can easily slip. Create a focus and schedule it once a week to deliver on your commitments.
- _Key activities_: Certain activities are done best with concentrated focus, like customer and sales conversations, or reviewing progress from a large team. In a focus, you choose how much and how often to invest your time.

Focuses aren''t just for the high priority stuff. By creating focuses for low-urgency items, you can safely ignore them for days before efficiently catching up. Reading, promotions, and unsolicited requests often fit here.', 'focuses');
    ELSE
        UPDATE public.note SET content = 'By bringing all you work together, Plot eliminates time and attention lost to jump around tools. Instead of organizing your work by _where_ it is, you organize it by _how_ you work on it. This lets you make real progress in an area you choose.

Create focuses for:

- _Important projects_: With everything related to a project in one focus, you can find what you need quickly, with a clear view of what''s outstanding. Even better, you can send related messages and replies without getting pulled into unrelated work that happens to be in the same chat, inbox, or app.
- _Core roles_: At work, you might have direct responsibilities while also managing others. Putting these in separate focuses ensures you make progress on your goals while giving your team the attention they deserve.
- _Secondary roles_: Your work for extra roles you take on, like volunteering, can easily slip. Create a focus and schedule it once a week to deliver on your commitments.
- _Key activities_: Certain activities are done best with concentrated focus, like customer and sales conversations, or reviewing progress from a large team. In a focus, you choose how much and how often to invest your time.

Focuses aren''t just for the high priority stuff. By creating focuses for low-urgency items, you can safely ignore them for days before efficiently catching up. Reading, promotions, and unsolicited requests often fit here.'
            WHERE id = v_note_id AND content IS DISTINCT FROM 'By bringing all you work together, Plot eliminates time and attention lost to jump around tools. Instead of organizing your work by _where_ it is, you organize it by _how_ you work on it. This lets you make real progress in an area you choose.

Create focuses for:

- _Important projects_: With everything related to a project in one focus, you can find what you need quickly, with a clear view of what''s outstanding. Even better, you can send related messages and replies without getting pulled into unrelated work that happens to be in the same chat, inbox, or app.
- _Core roles_: At work, you might have direct responsibilities while also managing others. Putting these in separate focuses ensures you make progress on your goals while giving your team the attention they deserve.
- _Secondary roles_: Your work for extra roles you take on, like volunteering, can easily slip. Create a focus and schedule it once a week to deliver on your commitments.
- _Key activities_: Certain activities are done best with concentrated focus, like customer and sales conversations, or reviewing progress from a large team. In a focus, you choose how much and how often to invest your time.

Focuses aren''t just for the high priority stuff. By creating focuses for low-urgency items, you can safely ignore them for days before efficiently catching up. Reading, promotions, and unsolicited requests often fit here.';
    END IF;
    SELECT id INTO v_note_id FROM public.note
        WHERE thread_id = v_thread_id AND key = 'notifications' AND link_id IS NULL AND archived_at IS NULL LIMIT 1;
    IF v_note_id IS NULL THEN
        INSERT INTO public.note (author_id, created_by, thread_id, source_created_at, content, key)
            VALUES (c_system_instance_id, c_system_instance_id, v_thread_id, now() + (2 * interval '1 minute'), '**Notifications** let you choose when updates in a focus should interrupt you based on how quickly you need know about them. For many, your best move is to turn notifications off and schedule the right time for the focus. For others, set how quickly and the times they are sent to maintain your desired response time. While you can get an immediate notification for everything, every time you choose to silence or batch notifications, you gain focus for what is more important each day.', 'notifications');
    ELSE
        UPDATE public.note SET content = '**Notifications** let you choose when updates in a focus should interrupt you based on how quickly you need know about them. For many, your best move is to turn notifications off and schedule the right time for the focus. For others, set how quickly and the times they are sent to maintain your desired response time. While you can get an immediate notification for everything, every time you choose to silence or batch notifications, you gain focus for what is more important each day.'
            WHERE id = v_note_id AND content IS DISTINCT FROM '**Notifications** let you choose when updates in a focus should interrupt you based on how quickly you need know about them. For many, your best move is to turn notifications off and schedule the right time for the focus. For others, set how quickly and the times they are sent to maintain your desired response time. While you can get an immediate notification for everything, every time you choose to silence or batch notifications, you gain focus for what is more important each day.';
    END IF;

    -- getting-around
    SELECT id INTO v_thread_id FROM public.thread
        WHERE key = 'getting-around' AND created_by = c_system_instance_id AND archived_at IS NULL LIMIT 1;
    IF v_thread_id IS NULL THEN
        -- topic_id (not just the topic text) is what file_thread_priority_for_topic_members
        -- keys on — without it new users never get the thread filed / never see it.
        INSERT INTO public.thread (created_by, twist_id, icon, title, preview, key, topic_id, topic, contacts)
            VALUES (c_system_instance_id, v_plot_twist_id, 'twist:' || v_plot_twist_id::text,
                'Getting Around', 'Keyboard and touch shortcuts', 'getting-around', v_updates_topic_id, 'topic:' || v_updates_topic_id::text,
                ARRAY[c_system_instance_id])
        RETURNING id INTO v_thread_id;
    ELSE
        UPDATE public.thread SET title = 'Getting Around', preview = 'Keyboard and touch shortcuts',
                topic_id = v_updates_topic_id, topic = 'topic:' || v_updates_topic_id::text
            WHERE id = v_thread_id
              AND (title, preview, topic_id) IS DISTINCT FROM ('Getting Around', 'Keyboard and touch shortcuts', v_updates_topic_id);
    END IF;
    SELECT id INTO v_note_id FROM public.note
        WHERE thread_id = v_thread_id AND key = 'intro' AND link_id IS NULL AND archived_at IS NULL LIMIT 1;
    IF v_note_id IS NULL THEN
        INSERT INTO public.note (author_id, created_by, thread_id, source_created_at, content, key)
            VALUES (c_system_instance_id, c_system_instance_id, v_thread_id, now() + (0 * interval '1 minute'), 'Plot''s goal is to get you to meaningful work as quickly as possible. Here are some tips for navigating efficiently.', 'intro');
    ELSE
        UPDATE public.note SET content = 'Plot''s goal is to get you to meaningful work as quickly as possible. Here are some tips for navigating efficiently.'
            WHERE id = v_note_id AND content IS DISTINCT FROM 'Plot''s goal is to get you to meaningful work as quickly as possible. Here are some tips for navigating efficiently.';
    END IF;
    SELECT id INTO v_note_id FROM public.note
        WHERE thread_id = v_thread_id AND key = 'keyboard' AND link_id IS NULL AND archived_at IS NULL LIMIT 1;
    IF v_note_id IS NULL THEN
        INSERT INTO public.note (author_id, created_by, thread_id, source_created_at, content, key)
            VALUES (c_system_instance_id, c_system_instance_id, v_thread_id, now() + (1 * interval '1 minute'), '**Keyboard Navigation**

- **⌘N** (Ctrl+N on Windows, ⌘⌃N / Ctrl+Alt+N on web browsers): Create a new note
- **⌘/** (Ctrl+/ on Windows): Search across all your threads and focuses
- **⌘K** (Ctrl+K on Windows): Open the command palette
- **⌘J** (Ctrl+J on Windows, ⌘⌃J / Ctrl+Alt+J on web browsers): Switch to another focus
- **⌘D** (Ctrl+D on Windows): To do / Done — toggle whether this thread requires action
- **⌘⇧D** (Ctrl+Shift+D on Windows): Schedule a thread to do later
- **⌘Up/Down** (Ctrl+Up/Down on Windows): Open previous/next thread
- **⌘Enter** (Ctrl+Enter on Windows): When adding a note, mark it (and the thread) to do', 'keyboard');
    ELSE
        UPDATE public.note SET content = '**Keyboard Navigation**

- **⌘N** (Ctrl+N on Windows, ⌘⌃N / Ctrl+Alt+N on web browsers): Create a new note
- **⌘/** (Ctrl+/ on Windows): Search across all your threads and focuses
- **⌘K** (Ctrl+K on Windows): Open the command palette
- **⌘J** (Ctrl+J on Windows, ⌘⌃J / Ctrl+Alt+J on web browsers): Switch to another focus
- **⌘D** (Ctrl+D on Windows): To do / Done — toggle whether this thread requires action
- **⌘⇧D** (Ctrl+Shift+D on Windows): Schedule a thread to do later
- **⌘Up/Down** (Ctrl+Up/Down on Windows): Open previous/next thread
- **⌘Enter** (Ctrl+Enter on Windows): When adding a note, mark it (and the thread) to do'
            WHERE id = v_note_id AND content IS DISTINCT FROM '**Keyboard Navigation**

- **⌘N** (Ctrl+N on Windows, ⌘⌃N / Ctrl+Alt+N on web browsers): Create a new note
- **⌘/** (Ctrl+/ on Windows): Search across all your threads and focuses
- **⌘K** (Ctrl+K on Windows): Open the command palette
- **⌘J** (Ctrl+J on Windows, ⌘⌃J / Ctrl+Alt+J on web browsers): Switch to another focus
- **⌘D** (Ctrl+D on Windows): To do / Done — toggle whether this thread requires action
- **⌘⇧D** (Ctrl+Shift+D on Windows): Schedule a thread to do later
- **⌘Up/Down** (Ctrl+Up/Down on Windows): Open previous/next thread
- **⌘Enter** (Ctrl+Enter on Windows): When adding a note, mark it (and the thread) to do';
    END IF;
    SELECT id INTO v_note_id FROM public.note
        WHERE thread_id = v_thread_id AND key = 'touch' AND link_id IS NULL AND archived_at IS NULL LIMIT 1;
    IF v_note_id IS NULL THEN
        INSERT INTO public.note (author_id, created_by, thread_id, source_created_at, content, key)
            VALUES (c_system_instance_id, c_system_instance_id, v_thread_id, now() + (2 * interval '1 minute'), '**Touch Gestures**

- **Long press** on items to drag and reorder
- **Swipe right** on threads: To do
- **Swipe right (long)** on threads: Schedule to do later
- **Swipe left** on threads: Done
- **Swipe left (long)** on items to open a menu with all commands', 'touch');
    ELSE
        UPDATE public.note SET content = '**Touch Gestures**

- **Long press** on items to drag and reorder
- **Swipe right** on threads: To do
- **Swipe right (long)** on threads: Schedule to do later
- **Swipe left** on threads: Done
- **Swipe left (long)** on items to open a menu with all commands'
            WHERE id = v_note_id AND content IS DISTINCT FROM '**Touch Gestures**

- **Long press** on items to drag and reorder
- **Swipe right** on threads: To do
- **Swipe right (long)** on threads: Schedule to do later
- **Swipe left** on threads: Done
- **Swipe left (long)** on items to open a menu with all commands';
    END IF;

    UPDATE public.thread
        SET archived_at = now()
        WHERE key = 'clean-up' AND created_by = c_system_instance_id AND archived_at IS NULL;

    UPDATE public.thread
        SET archived_at = now()
        WHERE key = 'connections' AND created_by = c_system_instance_id AND archived_at IS NULL;

    UPDATE public.thread
        SET archived_at = now()
        WHERE key = 'notifications' AND created_by = c_system_instance_id AND archived_at IS NULL;

    UPDATE public.thread
        SET archived_at = now()
        WHERE key = 'priorities' AND created_by = c_system_instance_id AND archived_at IS NULL;

    UPDATE public.thread
        SET archived_at = now()
        WHERE key = 'twists' AND created_by = c_system_instance_id AND archived_at IS NULL;

    UPDATE public.note n SET archived_at = now()
        FROM public.thread t
        WHERE t.id = n.thread_id AND t.key = 'clean-up' AND t.created_by = c_system_instance_id
          AND n.key = 'archive' AND n.archived_at IS NULL;

    UPDATE public.note n SET archived_at = now()
        FROM public.thread t
        WHERE t.id = n.thread_id AND t.key = 'clean-up' AND t.created_by = c_system_instance_id
          AND n.key = 'show-archived' AND n.archived_at IS NULL;

    UPDATE public.note n SET archived_at = now()
        FROM public.thread t
        WHERE t.id = n.thread_id AND t.key = 'connections' AND t.created_by = c_system_instance_id
          AND n.key = 'channels' AND n.archived_at IS NULL;

    UPDATE public.note n SET archived_at = now()
        FROM public.thread t
        WHERE t.id = n.thread_id AND t.key = 'connections' AND t.created_by = c_system_instance_id
          AND n.key = 'intro' AND n.archived_at IS NULL;

    UPDATE public.note n SET archived_at = now()
        FROM public.thread t
        WHERE t.id = n.thread_id AND t.key = 'connections' AND t.created_by = c_system_instance_id
          AND n.key = 'todo' AND n.archived_at IS NULL;

    UPDATE public.note n SET archived_at = now()
        FROM public.thread t
        WHERE t.id = n.thread_id AND t.key = 'notifications' AND t.created_by = c_system_instance_id
          AND n.key = 'intro' AND n.archived_at IS NULL;

    UPDATE public.note n SET archived_at = now()
        FROM public.thread t
        WHERE t.id = n.thread_id AND t.key = 'notifications' AND t.created_by = c_system_instance_id
          AND n.key = 'quiet-hours' AND n.archived_at IS NULL;

    UPDATE public.note n SET archived_at = now()
        FROM public.thread t
        WHERE t.id = n.thread_id AND t.key = 'notifications' AND t.created_by = c_system_instance_id
          AND n.key = 'timing' AND n.archived_at IS NULL;

    UPDATE public.note n SET archived_at = now()
        FROM public.thread t
        WHERE t.id = n.thread_id AND t.key = 'notifications' AND t.created_by = c_system_instance_id
          AND n.key = 'todo' AND n.archived_at IS NULL;

    UPDATE public.note n SET archived_at = now()
        FROM public.thread t
        WHERE t.id = n.thread_id AND t.key = 'priorities' AND t.created_by = c_system_instance_id
          AND n.key = 'create-and-match' AND n.archived_at IS NULL;

    UPDATE public.note n SET archived_at = now()
        FROM public.thread t
        WHERE t.id = n.thread_id AND t.key = 'priorities' AND t.created_by = c_system_instance_id
          AND n.key = 'inbox-everything' AND n.archived_at IS NULL;

    UPDATE public.note n SET archived_at = now()
        FROM public.thread t
        WHERE t.id = n.thread_id AND t.key = 'priorities' AND t.created_by = c_system_instance_id
          AND n.key = 'intro' AND n.archived_at IS NULL;

    UPDATE public.note n SET archived_at = now()
        FROM public.thread t
        WHERE t.id = n.thread_id AND t.key = 'priorities' AND t.created_by = c_system_instance_id
          AND n.key = 'todo' AND n.archived_at IS NULL;

    UPDATE public.note n SET archived_at = now()
        FROM public.thread t
        WHERE t.id = n.thread_id AND t.key = 'twists' AND t.created_by = c_system_instance_id
          AND n.key = 'custom' AND n.archived_at IS NULL;

    UPDATE public.note n SET archived_at = now()
        FROM public.thread t
        WHERE t.id = n.thread_id AND t.key = 'twists' AND t.created_by = c_system_instance_id
          AND n.key = 'intro' AND n.archived_at IS NULL;

    UPDATE public.note n SET archived_at = now()
        FROM public.thread t
        WHERE t.id = n.thread_id AND t.key = 'twists' AND t.created_by = c_system_instance_id
          AND n.key = 'mention-plot' AND n.archived_at IS NULL;

    UPDATE public.note n SET archived_at = now()
        FROM public.thread t
        WHERE t.id = n.thread_id AND t.key = 'twists' AND t.created_by = c_system_instance_id
          AND n.key = 'todo' AND n.archived_at IS NULL;

    UPDATE public.note n SET archived_at = now()
        FROM public.thread t
        WHERE t.id = n.thread_id AND t.key = 'welcome' AND t.created_by = c_system_instance_id
          AND n.key = 'attention' AND n.archived_at IS NULL;

    UPDATE public.note n SET archived_at = now()
        FROM public.thread t
        WHERE t.id = n.thread_id AND t.key = 'welcome' AND t.created_by = c_system_instance_id
          AND n.key = 'feed-sections' AND n.archived_at IS NULL;

    UPDATE public.note n SET archived_at = now()
        FROM public.thread t
        WHERE t.id = n.thread_id AND t.key = 'welcome' AND t.created_by = c_system_instance_id
          AND n.key = 'links' AND n.archived_at IS NULL;
END $$;

-- Regenerated per-user-state functions (new signups only).
CREATE OR REPLACE FUNCTION public.file_onboarding_schedules ()
    RETURNS TRIGGER
    LANGUAGE plpgsql
    AS $$
DECLARE
    v_thread_key text;
    v_date_offset integer;
    v_order integer;
    v_active boolean;
    v_importance smallint;
BEGIN
    -- Skip if explicitly requested (e.g. during repair migrations for existing users)
    IF current_setting('plot.skip_onboarding_schedules', true) = 'true' THEN
        RETURN NEW;
    END IF;

    SELECT key INTO v_thread_key FROM public.thread WHERE id = NEW.thread_id;

    -- ONBOARDING:BEGIN schedules
    IF v_thread_key IN ('welcome', 'getting-around') THEN
        CASE v_thread_key
            WHEN 'welcome' THEN v_date_offset := 0; v_order := 100; v_active := TRUE; v_importance := 95;
            WHEN 'getting-around' THEN v_date_offset := 0; v_order := 400; v_active := FALSE; v_importance := 80;
        END CASE;

        INSERT INTO public.thread_state (user_id, thread_id, active, importance, "order", "on")
        VALUES (NEW.user_id, NEW.thread_id, v_active, v_importance, v_order,
            CASE WHEN v_date_offset = 0 THEN daterange('1970-01-01', NULL)
                 ELSE daterange((CURRENT_DATE + v_date_offset), NULL) END)
        ON CONFLICT (user_id, thread_id) DO NOTHING;
    END IF;
-- ONBOARDING:END schedules

    RETURN NEW;
END;
$$;
CREATE OR REPLACE FUNCTION public.file_onboarding_todos ()
    RETURNS TRIGGER
    LANGUAGE plpgsql
    AS $$
DECLARE
    v_thread_key text;
    v_contact_id uuid;
BEGIN
    -- Escape hatch for repair migrations.
    IF current_setting('plot.skip_onboarding_todos', true) = 'true' THEN
        RETURN NEW;
    END IF;

    SELECT key INTO v_thread_key FROM public.thread WHERE id = NEW.thread_id;
    -- ONBOARDING:BEGIN todos
    RETURN NEW;
-- ONBOARDING:END todos

    -- Use the user's primary linked contact as the actor — same actor used
    -- elsewhere for per-user task ownership.
    SELECT uc.contact_id INTO v_contact_id
    FROM public.user_contact uc
    WHERE uc.user_id = NEW.user_id
      AND uc."primary" = TRUE
      AND uc.linked = TRUE
      AND uc.archived_at IS NULL
    LIMIT 1;

    IF v_contact_id IS NULL THEN
        RETURN NEW;
    END IF;

    -- ON CONFLICT DO NOTHING preserves prior decisions: if the user previously
    -- had this Todo and archived it (with or without marking Done), we leave
    -- the archived row alone instead of resurrecting it.
    INSERT INTO public.note_tag (actor_id, note_id, tag_id)
    SELECT v_contact_id, n.id, 1
    FROM public.note n
    WHERE n.thread_id = NEW.thread_id
      AND n.key = 'todo'
      AND n.archived_at IS NULL
    ON CONFLICT (actor_id, note_id, tag_id) DO NOTHING;

    RETURN NEW;
END;
$$;
CREATE OR REPLACE FUNCTION public.activate_invited_user (p_user_id uuid)
    RETURNS jsonb
    LANGUAGE plpgsql
    SET search_path TO 'public'
    AS $function$
DECLARE
    c_system_instance_id CONSTANT uuid := '0199b6f4-ae64-7718-0000-000000000001';
    c_twist_package_id CONSTANT uuid := '0199b6f4-ae64-7718-8a02-44716f30358f';
    v_root_priority_id uuid;
    v_new_path ltree;
    v_plot_team_group_id uuid;
    v_plot_twist_id bigint;
    v_user_contact_id uuid;
    v_welcome_thread_id uuid;
BEGIN
    -- Already has a root priority?
    SELECT
        id INTO v_root_priority_id
    FROM
        public.priority
    WHERE
        user_id = p_user_id
        AND nlevel (path) = 1
    ORDER BY
        created_at ASC
    LIMIT 1;
    IF v_root_priority_id IS NOT NULL THEN
        RETURN jsonb_build_object('activated', FALSE, 'already_active', TRUE, 'root_priority_id', v_root_priority_id);
    END IF;
    -- Create the root priority. default_priority_user_id fills user_id
    -- from created_by, so the new row is fully owned by the user.
    v_new_path := generate_path (NULL);
    INSERT INTO public.priority (created_by, user_id, title, path, color)
        VALUES (p_user_id, p_user_id, 'Everything', v_new_path, 0)
    RETURNING
        id INTO v_root_priority_id;
    -- Resolve the Plot Team group once — used for the welcome thread's
    -- groups array (so the user's first message reaches the Plot team).
    -- Prefer the full "Plot" team's auto-maintained group (everyone on the
    -- team, what we want in prod); fall back to the Plot publisher admin
    -- group for environments where the Plot team doesn't exist yet.
    SELECT
        COALESCE((
            SELECT
                g.id
            FROM public.group g
            JOIN public.team t ON t.id = g.team_id
            WHERE
                g.auto_maintained = TRUE
                AND g.auto_team_admin_team_id IS NULL
                AND t.name = 'Plot' LIMIT 1), (
        SELECT
            g.id
        FROM public.group g
        WHERE
            g.auto_maintained = TRUE
            AND g.auto_publisher_id = (
                SELECT
                    id
                FROM public.publisher
            WHERE
                name = 'Plot' LIMIT 1)
LIMIT 1)) INTO v_plot_team_group_id;
    -- No special hardcoded focuses are seeded. Onboarding threads (the
    -- per-user welcome below and the shared global onboarding set) land in
    -- the user's Inbox/root via classify_thread_for_user's root_fallback and
    -- a shared topic = 'onboarding'. The user organizes them however they
    -- like; moving one into a focus carries the rest along (topic match).
    -- Seed a per-user welcome thread authored by the shared system Plot
    -- twist_instance (same pattern as the global onboarding threads). The
    -- thread is visible only to the new user (via contacts) and the Plot
    -- Team (via groups). It pins to the top of the user's agenda with
    -- order = 50, ahead of the global 'welcome' thread (order = 100).
    --
    -- Skipped entirely when the Plot Team group hasn't been seeded yet —
    -- avoids noisy welcomes in ephemeral test databases that don't have
    -- the Plot publisher/team bootstrapped.
    IF v_plot_team_group_id IS NOT NULL THEN
        SELECT
            id INTO v_plot_twist_id
        FROM
            public.twist
        WHERE
            twist_package_id = c_twist_package_id
            AND environment = 'public'
        LIMIT 1;
        -- The API worker inserts the primary contact row a moment after
        -- this trigger runs, so user_contact may not exist yet. Seed it
        -- ourselves via upsert_user_contact (idempotent via ON CONFLICT
        -- (email) + ON CONFLICT (user_id, contact_id)) so the welcome
        -- thread's contacts array has the user's primary contact from
        -- the start.
        DECLARE v_user_email text;
        v_user_name text;
        v_user_avatar text;
        BEGIN
            SELECT
                email,
                name,
                avatar_url INTO v_user_email,
                v_user_name,
                v_user_avatar
            FROM
                public."user"
            WHERE
                id = p_user_id;
            IF v_user_email IS NOT NULL THEN
                PERFORM
                    public.upsert_user_contact (p_user_id, v_user_email, v_user_name, v_user_avatar);
            END IF;
        END;
        SELECT
            contact_id INTO v_user_contact_id
        FROM
            public.user_contact
        WHERE
            user_id = p_user_id
            AND "primary" = TRUE
            AND linked = TRUE
            AND archived_at IS NULL
        LIMIT 1;
        -- twist_id is intentionally NULL: welcome-user is a per-user thread
        -- and must not participate in cross-user (twist_id, key) dedup. The
        -- twist_instance_id in created_by is what makes this "twist-authored"
        -- for peer-filing purposes; icon preserves the visual attribution.
        -- contacts: the synthetic "Plot Team" sender (so the row header
        -- attributes the thread to Plot Team, same as the shared onboarding
        -- threads) PLUS the user's own contact (load-bearing for the user's
        -- own visibility — _otherContactIds excludes self, so only "Plot Team"
        -- shows). groups carries the Plot Team group so replies reach the team.
        -- ONBOARDING:BEGIN welcome-user
        INSERT INTO public.thread (created_by, icon, title, preview, key, topic, contacts, groups)
            VALUES (c_system_instance_id, CASE WHEN v_plot_twist_id IS NOT NULL THEN 'twist:' || v_plot_twist_id::text END,
                'Welcome to Plot!', 'We''re so glad something brought you here.', 'welcome-user', 'onboarding',
                ARRAY[c_system_instance_id] || (CASE WHEN v_user_contact_id IS NOT NULL THEN ARRAY[v_user_contact_id] ELSE ARRAY[]::uuid[] END),
                ARRAY[v_plot_team_group_id])
        RETURNING id INTO v_welcome_thread_id;
        INSERT INTO public.thread_priority (thread_id, user_id, priority_id)
            VALUES (v_welcome_thread_id, p_user_id, v_root_priority_id)
        ON CONFLICT ON CONSTRAINT thread_priority_pkey DO NOTHING;
        INSERT INTO public.thread_state (user_id, thread_id, importance, "order", "on")
            VALUES (p_user_id, v_welcome_thread_id, 100, 50, daterange('1970-01-01', NULL))
        ON CONFLICT (user_id, thread_id) DO NOTHING;
        INSERT INTO public.note (author_id, created_by, thread_id, source_created_at, content, key)
            VALUES (c_system_instance_id, c_system_instance_id, v_welcome_thread_id, now() + interval '0 millisecond', 'We''re so glad something brought you here.
Maybe you''re trying to get traction on something new by bringing all the scattered pieces together.
You might be part of a team doing big things and want to overcome collaboration overhead.
Perhaps your life is full of many good things and you want to give them all your best.

Plot is built for making progress on what matters and getting more done with others.
Rather than chasing Inbox Zero, we believe in investing your time and attention based on your priorities.
Plot supports you working with others in the areas you choose while gathering everything else for the right time.

We''d love to hear what you''re working on and how Plot can help. Feel free to reply in this thread that includes the Plot team.', 'welcome')
        ON CONFLICT (thread_id, link_id, key) WHERE key IS NOT NULL DO NOTHING;
        INSERT INTO public.note (author_id, created_by, thread_id, source_created_at, content, key)
            VALUES (c_system_instance_id, c_system_instance_id, v_welcome_thread_id, now() + interval '1 millisecond', 'Your account has been upgraded to the **Core plan** free for 30 days so you can try up to 5 connections and 2 twists. You can choose to keep the upgrade or go **Pro** at any time. Otherwise, after 30 days, you''ll automatically continue on the Free plan, which includes unlimited history and sharing. Any connections or twists over your new limit will be archived.', 'core-trial')
        ON CONFLICT (thread_id, link_id, key) WHERE key IS NOT NULL DO NOTHING;
-- ONBOARDING:END welcome-user
    END IF;
    -- Priority routing is learned from user moves (thread_priority.user_moved).
    -- New users start with no training examples; incoming threads land in the
    -- root priority (Inbox) until the user moves one into a focus they create.
    -- classify_thread_for_user then picks that focus up automatically for
    -- similar future threads.
    RETURN jsonb_build_object('activated', TRUE, 'already_active', FALSE, 'root_priority_id', v_root_priority_id);
END;
$function$;
