-- Drop "thread_x" view
DROP VIEW "public"."thread_x";
-- Modify "thread" table
ALTER TABLE "public"."thread" ADD COLUMN "author_id" uuid NULL;
-- Set comment to column: "author_id" on table: "thread"
COMMENT ON COLUMN "public"."thread"."author_id" IS 'The actor (contact or twist_instance) credited with causing this thread''s creation. User threads: user''s primary contact. Connector threads: resolved external link author. Non-connection twist threads: the twist_instance. Immutable after first set.';
-- Create "thread_x" view
CREATE VIEW "public"."thread_x" (
  "id",
  "created_at",
  "updated_at",
  "created_by",
  "author_id",
  "updated_by",
  "archived_at",
  "draft",
  "contacts",
  "dropped_contacts",
  "title",
  "preview",
  "last_note_created_at",
  "sync_depth",
  "last_note_source_created_at",
  "key",
  "icon",
  "groups",
  "topic",
  "embedding",
  "twist_id",
  "pending_contacts",
  "contact_meta",
  "seq",
  "last_note_seq",
  "merged_into_thread_id",
  "team_id",
  "external_contacts"
) AS SELECT id,
    created_at,
    updated_at,
    created_by,
    author_id,
    updated_by,
    archived_at,
    draft,
    contacts,
    dropped_contacts,
    title,
    preview,
    last_note_created_at,
    sync_depth,
    last_note_source_created_at,
    key,
    icon,
    groups,
    topic,
    embedding,
    twist_id,
    pending_contacts,
    contact_meta,
    seq,
    last_note_seq,
    merged_into_thread_id,
    team_id,
    external_contacts
   FROM public.thread a;
