-- Drop "thread_x" view
DROP VIEW "public"."thread_x";
-- Modify "thread" table
ALTER TABLE "public"."thread" ADD COLUMN "pending_create_link" jsonb NULL;
-- Create "thread_x" view
CREATE VIEW "public"."thread_x" (
  "id",
  "created_at",
  "updated_at",
  "created_by",
  "author_id",
  "updated_by",
  "archived_at",
  "draft",
  "contacts",
  "dropped_contacts",
  "title",
  "preview",
  "last_note_created_at",
  "sync_depth",
  "last_note_source_created_at",
  "key",
  "icon",
  "assignee_id",
  "groups",
  "topic",
  "embedding",
  "twist_id",
  "topic_id",
  "pending_contacts",
  "contact_meta",
  "pending_create_link",
  "facets",
  "seq",
  "last_note_seq",
  "merged_into_thread_id",
  "team_id",
  "external_contacts"
) AS SELECT id,
    created_at,
    updated_at,
    created_by,
    author_id,
    updated_by,
    archived_at,
    draft,
    contacts,
    dropped_contacts,
    title,
    preview,
    last_note_created_at,
    sync_depth,
    last_note_source_created_at,
    key,
    icon,
    assignee_id,
    groups,
    topic,
    embedding,
    twist_id,
    topic_id,
    pending_contacts,
    contact_meta,
    pending_create_link,
    facets,
    seq,
    last_note_seq,
    merged_into_thread_id,
    team_id,
    external_contacts
   FROM public.thread a;
