-- Modify "activate_invited_user" function attribute
ALTER FUNCTION "public"."activate_invited_user" SECURITY INVOKER;
-- Modify "accept_invitations_on_signup" function attribute
ALTER FUNCTION "public"."accept_invitations_on_signup" SECURITY INVOKER;
-- Modify "ensure_assignee_priority_contact" function attribute
ALTER FUNCTION "public"."ensure_assignee_priority_contact" SECURITY INVOKER;
-- Modify "ensure_priority_user_contact" function attribute
ALTER FUNCTION "public"."ensure_priority_user_contact" SECURITY INVOKER;
-- Modify "user_has_priority_access" function attribute
ALTER FUNCTION "public"."user_has_priority_access" SECURITY INVOKER;
-- Modify "get_accessible_twists" function attribute
ALTER FUNCTION "public"."get_accessible_twists" SECURITY INVOKER;
-- Modify "get_activity_mentions" function attribute
ALTER FUNCTION "public"."get_activity_mentions" SECURITY INVOKER;
-- Modify "get_invitation_token" function attribute
ALTER FUNCTION "public"."get_invitation_token" SECURITY INVOKER;
-- Modify "get_pending_user_sync" function attribute
ALTER FUNCTION "public"."get_pending_user_sync" SECURITY INVOKER;
-- Modify "get_primary_contact_id" function attribute
ALTER FUNCTION "public"."get_primary_contact_id" SECURITY INVOKER;
-- Modify "get_priority_twist_owner_contact" function attribute
ALTER FUNCTION "public"."get_priority_twist_owner_contact" SECURITY INVOKER;
-- Modify "get_stale_twist_syncs" function attribute
ALTER FUNCTION "public"."get_stale_twist_syncs" SECURITY INVOKER;
-- Modify "get_stale_user_syncs" function attribute
ALTER FUNCTION "public"."get_stale_user_syncs" SECURITY INVOKER;
-- Modify "insert_email_domain" function attribute
ALTER FUNCTION "public"."insert_email_domain" SECURITY INVOKER;
-- Modify "insert_priority_user" function attribute
ALTER FUNCTION "public"."insert_priority_user" SECURITY INVOKER;
-- Modify "is_accessible_twist" function attribute
ALTER FUNCTION "public"."is_accessible_twist" SECURITY INVOKER;
-- Modify "prevent_priority_twist_immutable_changes" function attribute
ALTER FUNCTION "public"."prevent_priority_twist_immutable_changes" SECURITY INVOKER;
-- Modify "redeem_invitation_token" function attribute
ALTER FUNCTION "public"."redeem_invitation_token" SECURITY INVOKER;
-- Modify "set_priority_twist_owner_id" function attribute
ALTER FUNCTION "public"."set_priority_twist_owner_id" SECURITY INVOKER;
-- Modify "setup_help_feedback_priority" function attribute
ALTER FUNCTION "public"."setup_help_feedback_priority" SECURITY INVOKER;
-- Modify "share_priority" function attribute
ALTER FUNCTION "public"."share_priority" SECURITY INVOKER;
-- Modify "sync_twist_for_activity" function attribute
ALTER FUNCTION "public"."sync_twist_for_activity" SECURITY INVOKER;
-- Modify "sync_twist_for_activity_tag" function attribute
ALTER FUNCTION "public"."sync_twist_for_activity_tag" SECURITY INVOKER;
-- Modify "sync_twist_for_note" function attribute
ALTER FUNCTION "public"."sync_twist_for_note" SECURITY INVOKER;
-- Modify "sync_twist_for_note_tag" function attribute
ALTER FUNCTION "public"."sync_twist_for_note_tag" SECURITY INVOKER;
-- Modify "sync_user_for_activity" function attribute
ALTER FUNCTION "public"."sync_user_for_activity" SECURITY INVOKER;
-- Modify "sync_user_for_activity_read" function attribute
ALTER FUNCTION "public"."sync_user_for_activity_read" SECURITY INVOKER;
-- Modify "sync_user_for_activity_tag" function attribute
ALTER FUNCTION "public"."sync_user_for_activity_tag" SECURITY INVOKER;
-- Modify "sync_user_for_contact" function attribute
ALTER FUNCTION "public"."sync_user_for_contact" SECURITY INVOKER;
-- Modify "sync_user_for_note" function attribute
ALTER FUNCTION "public"."sync_user_for_note" SECURITY INVOKER;
-- Modify "sync_user_for_note_tag" function attribute
ALTER FUNCTION "public"."sync_user_for_note_tag" SECURITY INVOKER;
-- Modify "sync_user_for_priority" function attribute
ALTER FUNCTION "public"."sync_user_for_priority" SECURITY INVOKER;
-- Modify "sync_user_for_priority_contact" function attribute
ALTER FUNCTION "public"."sync_user_for_priority_contact" SECURITY INVOKER;
-- Modify "sync_user_for_priority_twist" function attribute
ALTER FUNCTION "public"."sync_user_for_priority_twist" SECURITY INVOKER;
-- Modify "sync_user_for_priority_user" function attribute
ALTER FUNCTION "public"."sync_user_for_priority_user" SECURITY INVOKER;
-- Modify "sync_user_for_session" function attribute
ALTER FUNCTION "public"."sync_user_for_session" SECURITY INVOKER;
-- Modify "sync_user_on_connect" function attribute
ALTER FUNCTION "public"."sync_user_on_connect" SECURITY INVOKER;
-- Modify "update_activity_on_note_change" function attribute
ALTER FUNCTION "public"."update_activity_on_note_change" SECURITY INVOKER;
-- Modify "update_invitation_sent_at" function attribute
ALTER FUNCTION "public"."update_invitation_sent_at" SECURITY INVOKER;
-- Modify "upsert_user_contact" function attribute
ALTER FUNCTION "public"."upsert_user_contact" SECURITY INVOKER;
-- Modify "assert_priority_access" function attribute
ALTER FUNCTION "user"."assert_priority_access" SECURITY INVOKER;
-- Modify "delete_activity_read" function attribute
ALTER FUNCTION "user"."delete_activity_read" SECURITY INVOKER;
-- Modify "mentioned_in_activity" function attribute
ALTER FUNCTION "user"."mentioned_in_activity" SECURITY INVOKER;
-- Modify "update_activity_tags" function attribute
ALTER FUNCTION "user"."update_activity_tags" SECURITY INVOKER;
-- Modify "update_note_tags" function attribute
ALTER FUNCTION "user"."update_note_tags" SECURITY INVOKER;
-- Modify "upsert_activity" function attribute
ALTER FUNCTION "user"."upsert_activity" SECURITY INVOKER;
-- Modify "upsert_activity_exception" function attribute
ALTER FUNCTION "user"."upsert_activity_exception" SECURITY INVOKER;
-- Modify "upsert_activity_read" function attribute
ALTER FUNCTION "user"."upsert_activity_read" SECURITY INVOKER;
-- Modify "upsert_activity_tag" function attribute
ALTER FUNCTION "user"."upsert_activity_tag" SECURITY INVOKER;
-- Modify "upsert_note" function attribute
ALTER FUNCTION "user"."upsert_note" SECURITY INVOKER;
-- Modify "upsert_note_tag" function attribute
ALTER FUNCTION "user"."upsert_note_tag" SECURITY INVOKER;
-- Modify "upsert_priority" function attribute
ALTER FUNCTION "user"."upsert_priority" SECURITY INVOKER;
-- Modify "upsert_priority_member" function attribute
ALTER FUNCTION "user"."upsert_priority_member" SECURITY INVOKER;
-- Modify "upsert_priority_twist" function attribute
ALTER FUNCTION "user"."upsert_priority_twist" SECURITY INVOKER;
-- Modify "upsert_priority_user" function attribute
ALTER FUNCTION "user"."upsert_priority_user" SECURITY INVOKER;
-- Modify "upsert_session" function attribute
ALTER FUNCTION "user"."upsert_session" SECURITY INVOKER;
-- Modify "upsert_user_settings" function attribute
ALTER FUNCTION "user"."upsert_user_settings" SECURITY INVOKER;
