# A list of devices you want to take the screenshots from
devices([
  "iPhone 15 Pro Max",    # 6.7" display
  "iPhone 15 Pro",        # 6.1" display
  "iPad Pro (12.9-inch) (6th generation)"  # 12.9" display
])

# A list of languages which should be used
languages([
  "en-US"
])

# The name of the scheme which contains the UI Tests
scheme("Runner")

# Where should the resulting screenshots be stored?
output_directory("./fastlane/screenshots")

# Clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

# Arguments to pass to the app on launch
# launch_arguments([])

# Environment variables to pass to the app
# override_status_bar(true)

# For more information about all available options run
# fastlane action snapshot
