#!/bin/bash
fail=0
for var_name in $@; do
  if [ -z "${!var_name}" ]; then
    echo "!!! Environment variable $var_name not set" >&2
    fail=1
  else
    echo "$var_name:${!var_name}";
  fi
done
if [ $fail -eq 1 ]; then
  echo "--fail"
  exit 1
fi
