#!/usr/bin/env bash

set -euo pipefail

ENV=${ENV:-production}
RELEASE=${GITHUB_SHA:-$(git rev-parse HEAD)}
PACKAGE=$(echo $npm_package_name | cut -d'/' -f2)
definitions="ENV:\"$ENV\" RELEASE:\"$RELEASE\" PACKAGE:\"$PACKAGE\""

if [[ -v DEPLOY_VARS ]]; then
  VARS="--var $DEPLOY_VARS"
else
  VARS="--keep-vars"
fi

export POSTHOG_CLI_ENV_ID=$POSTHOG_PROJECT
export POSTHOG_CLI_TOKEN=$POSTHOG_CLI_KEY

wrangler deploy --dry-run --outdir build --define $definitions --env $ENV
if [[ -v POSTHOG_CLI_KEY ]]; then
  posthog-cli sourcemap inject --directory build --project $PACKAGE
fi
wrangler deploy --no-bundle build/index.js --define $definitions $VARS --env $ENV
if [[ -v POSTHOG_CLI_KEY ]]; then
  posthog-cli sourcemap upload --directory build
fi
