#!/bin/bash

set -euo pipefail

RELEASE=${GITHUB_SHA:-$(git rev-parse HEAD)}
PACKAGE=$(echo $npm_package_name | cut -d'/' -f2)

if [[ -n "$SENTRY_AUTH_TOKEN_CF" ]]; then
  export SENTRY_AUTH_TOKEN="$SENTRY_AUTH_TOKEN_CF"
fi

wrangler deploy --dry-run --outdir build
sentry-cli sourcemaps inject --org plotday --project workers build
wrangler deploy --var PACKAGE:$PACKAGE RELEASE:$RELEASE --no-bundle build/index.js
sentry-cli sourcemaps upload --org plotday --project workers --release=$RELEASE --dist=$PACKAGE build
