#!/bin/bash

set -euo pipefail

ENV=${ENV:-production}
ALL=$($(dirname "$0")/gen-env $ENV $npm_package_config_deploy_vars)
SECRETS=$(echo "$ALL" | grep -E 'SECRET|KEY|TOKEN' || true)
SECRETS=$(echo "$SECRETS" | $(dirname "$0")/env-to-json)
VARS=$(echo "$ALL" | grep -Ev 'SECRET|KEY|TOKEN' || true)
VARS=$(echo "$VARS" | sed 's/=\([^=]*\)$/:\1/')

echo "$SECRETS" | wrangler secret bulk --env $ENV
export DEPLOY_VARS="$VARS"
$(dirname "$0")/deploy-worker
