#!/usr/bin/env bash

# Given .env templates (.env*.1p), generate an .env file:
# 1. replacing vars specified in workspace-level .env files
# 2. replacing 1Password secret references

export ENV=$1
case $ENV in
development) ;;
production) ;;
*)
  echo "Usage: $0 <development|production> [VAR]+" >&2
  exit 1
  ;;
esac

shift
VARS="$@ $npm_package_deploy_vars"

filter_existing_paths() {
  local paths="$@"
  local existing_paths=""

  # Iterate over each path
  for path in $paths; do
    # Check if the path exists
    if [ -e "$path" ]; then
      # Append space to separate existing paths
      existing_paths="$existing_paths$path "
    fi
  done

  # Remove trailing space
  echo "${existing_paths% }"
}

WORKSPACE_PATH="$(dirname -- "${BASH_SOURCE[0]}")/.."
WORKSPACE_FILES=$(filter_existing_paths $WORKSPACE_PATH/.env $WORKSPACE_PATH/.env.local $WORKSPACE_PATH/.env.$ENV $WORKSPACE_PATH/.env.$ENV.local)

NAMES=()
VALUES=()

# Parse .env files into arrays
for file in $WORKSPACE_FILES; do
  while IFS= read -r line; do
    case "$line" in
    [a-zA-Z_]*=*)
      var_name="${line%%=*}"
      var_value="${line#*=}"
      NAMES[${#NAMES[@]}]="$var_name"
      VALUES[${#VALUES[@]}]="$var_value"
      ;;
    esac
  done <"$file"
done

# Function to get a variable's value by name
get_var_value() {
  local search="$1"
  local i=0
  while [ $i -lt ${#NAMES[@]} ]; do
    if [ "${NAMES[$i]}" = "$search" ]; then
      echo "${VALUES[$i]}"
      return 0
    fi
    i=$((i + 1))
  done
  return 1
}

fail=0
result=""

for var in $VARS; do
  var_ref=
  var_value=
  # Hardcoded values
  if [[ "$var" =~ ^([^=:]*)= ]]; then
    var_name="${BASH_REMATCH[1]}"
    var_value="${var#*=}"
  # Aliases
  elif [[ "$var" =~ ^([^=:]*): ]]; then
    var_name="${BASH_REMATCH[1]}"
    var_ref=${var#*:}
  # References
  else
    var_name=$var
    var_ref=$var
  fi

  if [ -n "$var_ref" ]; then
    got_val=$(get_var_value "$var_ref")
    if [ $? -eq 0 ]; then
      var_value="$got_val"
    else
      var_value=""
    fi
  fi

  if [ -z "$var_value" ]; then
    echo "!!! Environment variable $var not set" >&2
    fail=1
  fi
  result="${result}${var_name}=${var_value}"$'\n'
done

if [ $fail -eq 1 ]; then
  exit 1
fi

printf "%s" "$result" | op --account plotco inject
