// Env vars come from .env, generated by `pnpm get-env` (see package.json
// config.deploy_vars). WXT exposes any var prefixed with WXT_ to client code
// via import.meta.env. The aliases in deploy_vars map root API_ROOT /
// APP_ROOT / SITE_ROOT to WXT_* names for that exposure.
const env = (import.meta as { env?: Record<string, string | undefined> }).env ?? {};

export const PLOT_API_BASE: string = env.WXT_API_ROOT ?? "https://api.plot.day";
export const PLOT_APP_BASE: string = env.WXT_APP_ROOT ?? "https://app.plot.day";
export const PLOT_SITE_BASE: string = env.WXT_SITE_ROOT ?? "https://plot.day";
