import type { Bindings } from "../../env";
import { PROVIDER_CONFIGS } from "../../provider";
import { Callbacks } from "../../state/callbacks";
import type { Storage } from "../../state/storage";
import { type ActivityLink, ActivityLinkType } from "@plotday/sdk/plot";
import type {
  AuthLevel,
  AuthProvider,
  AuthToken,
  Authorization,
  Auth as IAuth,
} from "@plotday/sdk/tools/auth";
import type { Callback } from "@plotday/sdk/tools/callback";
import type { Store } from "@plotday/sdk/tools/store";
import { CallbackTool } from "./callback";
import { Tool } from "./tool";

type AuthState = {
  provider: AuthProvider;
  level: AuthLevel;
  scopes: string[];
  codeVerifier?: string; // Optional for Google Sign-In flows
  timestamp?: number; // Optional for Google Sign-In flows
  callback?: Callback;
};

type OnAuthCallbackContext = {
  callerCallback: Callback;
};

export class Auth extends Tool implements IAuth {
  private store: Store;
  private env: Bindings;
  private priorityAgentId: string;
  // These are callbacks we create and call
  private authCallbacks: DurableObjectStub<Callbacks>;
  private callbacks: DurableObjectNamespace<Callbacks>;
  private path: string[];

  private static GetStub(
    callbacks: DurableObjectNamespace<Callbacks>,
    priorityAgentId: string
  ) {
    const callbacksId = callbacks.idFromName(priorityAgentId);
    return callbacks.get(callbacksId);
  }

  constructor({
    store,
    env,
    priorityAgentId,
    callbacks,
    path, // path to this tool within the agent's tool hierarchy
  }: {
    store: Store;
    env: Bindings;
    priorityAgentId: string;
    callbacks: DurableObjectNamespace<Callbacks>;
    path: string[];
  }) {
    super();
    this.store = store;
    this.env = env;
    this.priorityAgentId = priorityAgentId;
    this.callbacks = callbacks;
    this.authCallbacks = Auth.GetStub(callbacks, priorityAgentId);
    this.path = path;
  }

  async request(
    {
      provider,
      level,
      scopes,
    }: {
      provider: AuthProvider;
      level: AuthLevel;
      scopes: string[];
    },
    callback: Callback
  ): Promise<ActivityLink> {
    if (!(provider in PROVIDER_CONFIGS)) {
      throw new Error(`Provider ${provider} not supported`);
    }

    // Create wrapped callback to onAuth
    const onAuthCallback = await this.authCallbacks.create({
      priorityAgentId: this.priorityAgentId,
      path: this.path,
      functionName: "onAuth",
      context: { callerCallback: callback } satisfies OnAuthCallbackContext,
    });

    // Create and return auth link with auth config - URLs will be generated by API calls
    const authLink: ActivityLink = {
      title: `Continue with ${PROVIDER_CONFIGS[provider].name}`,
      type: ActivityLinkType.auth,
      provider,
      level,
      scopes,
      callback: onAuthCallback,
    };

    return authLink;
  }

  async onAuth(
    tokenInfo: {
      access_token: string;
      refresh_token?: string;
      expires_in?: number;
      provider: AuthProvider;
      level: AuthLevel;
      scopes: string[];
      client_id: string;
    },
    context: OnAuthCallbackContext
  ): Promise<void> {
    // Generate unique ID for this authorization
    const authorizationId = crypto.randomUUID();

    const tokenKey = `auth_token:${authorizationId}`;
    const token = {
      client_id: tokenInfo.client_id,
      access_token: tokenInfo.access_token,
      refresh_token: tokenInfo.refresh_token,
      scopes: tokenInfo.scopes,
      expires_at: tokenInfo.expires_in
        ? Date.now() + tokenInfo.expires_in * 1000
        : undefined,
    };
    await this.store.set(tokenKey, token);

    // Create Authorization object to pass to callback
    const authorization: Authorization = {
      id: authorizationId,
      provider: tokenInfo.provider,
      scopes: tokenInfo.scopes,
    };

    // Call original user callback with Authorization
    try {
      // @ts-ignore type instantiation issue
      await CallbackTool.Call(
        this.callbacks,
        context.callerCallback,
        authorization
      );
    } catch (error) {
      console.error("Error executing original auth callback:", error);
    }
  }

  async get(authorization: Authorization): Promise<AuthToken | null> {
    // Get stored token from the store using authorization ID
    const tokenKey = `auth_token:${authorization.id}`;
    const tokenData = await this.store.get<{
      access_token: string;
      refresh_token?: string;
      scopes: string[];
      expires_at?: number;
      client_id?: string;
    }>(tokenKey);

    if (!tokenData) {
      return null;
    }

    // Check if token is expired
    if (tokenData.expires_at && Date.now() > tokenData.expires_at) {
      // Token is expired, try to refresh if we have a refresh token
      if (tokenData.refresh_token && tokenData.client_id) {
        try {
          const refreshedToken = await this.refreshToken({
            clientId: tokenData.client_id,
            refreshToken: tokenData.refresh_token,
            provider: authorization.provider,
          });

          // Update stored token
          await this.store.set(tokenKey, {
            access_token: refreshedToken.access_token,
            refresh_token:
              refreshedToken.refresh_token || tokenData.refresh_token,
            scopes: tokenData.scopes,
            expires_at: refreshedToken.expires_in
              ? Date.now() + refreshedToken.expires_in * 1000
              : undefined,
          });

          return {
            token: refreshedToken.access_token,
            scopes: tokenData.scopes,
          };
        } catch (error) {
          console.error("Failed to refresh token:", error);
          // Clear expired token
          await this.store.clear(tokenKey);
          return null;
        }
      }

      // No refresh token or refresh failed, clear expired token
      await this.store.clear(tokenKey);
      return null;
    }

    return {
      token: tokenData.access_token,
      scopes: tokenData.scopes,
    };
  }

  static async HandleOauthCallback(
    storage: DurableObjectNamespace<Storage>,
    callbacks: DurableObjectNamespace<Callbacks>,
    params: Record<string, string>,
    env: Bindings
  ): Promise<Response> {
    try {
      const { state, error, provider, level, scopes, callback } = params;

      if (error) {
        console.error("OAuth error:", error);
        return new Response(
          JSON.stringify({ error: `OAuth error: ${error}` }),
          {
            status: 400,
            headers: { "Content-Type": "application/json" },
          }
        );
      }

      let authState: AuthState;

      // Check if this is a Google Sign-In flow (no state) or standard OAuth (with state)
      if (!state && provider) {
        // Google Sign-In flow: validate direct parameters
        if (!provider) throw new Error("Missing provider parameter");
        if (!level) throw new Error("Missing level parameter");

        const scopeArray = scopes ? scopes.split(",").map((s) => s.trim()) : [];

        authState = {
          provider: provider as AuthProvider,
          level: level as AuthLevel,
          scopes: scopeArray,
          callback: callback as Callback | undefined,
          // No codeVerifier or timestamp for Google Sign-In
        };
      } else if (state) {
        // Standard OAuth flow: retrieve state from global storage
        const storageStub = storage.idFromName("auth");
        const storageObj = storage.get(storageStub);
        const rawAuthState = await storageObj.get(state);
        const retrievedAuthState = rawAuthState
          ? (JSON.parse(rawAuthState) as AuthState)
          : null;

        if (!retrievedAuthState) {
          return new Response(
            JSON.stringify({ error: "Invalid or expired state" }),
            {
              status: 400,
              headers: { "Content-Type": "application/json" },
            }
          );
        }

        authState = retrievedAuthState;

        // Check state timestamp (expire after 1 hour) - only for standard OAuth
        if (authState.timestamp && Date.now() - authState.timestamp > 3600000) {
          await storageObj.clear(state);
          console.error("State expired");
          return new Response(JSON.stringify({ error: "State expired" }), {
            status: 400,
            headers: { "Content-Type": "application/json" },
          });
        }

        // Cleanup state after successful validation
        await storageObj.clear(state);
      } else {
        // Neither state nor provider provided
        console.error("Missing both state and provider parameters");
        return new Response(
          JSON.stringify({
            error: "Missing required authentication parameters",
          }),
          {
            status: 400,
            headers: { "Content-Type": "application/json" },
          }
        );
      }

      const { code, clientId, redirectUri, pkce } = params;
      if (!code) throw new Error("Missing code parameter");
      if (!clientId) throw new Error("Missing clientId parameter");
      if (!redirectUri) throw new Error("Missing redirectUri parameter");

      // Exchange code for tokens using static helper
      const tokenResponse = await Auth.exchangeCodeForTokens({
        clientId,
        code,
        codeVerifier:
          pkce && authState.codeVerifier ? authState.codeVerifier : undefined,
        provider: authState.provider,
        redirectUri,
        env,
      });

      // Call the wrapped callback (onAuth) with token info
      if (authState.callback) {
        try {
          const { shardKey } = Callbacks.parseToken(authState.callback);
          const callbacksId = callbacks.idFromName(shardKey);
          const callbacksStub = callbacks.get(callbacksId);
          // @ts-ignore type instantiation issue
          await callbacksStub.call(authState.callback, {
            access_token: tokenResponse.access_token,
            refresh_token: tokenResponse.refresh_token,
            expires_in: tokenResponse.expires_in,
            provider: authState.provider,
            level: authState.level,
            scopes: authState.scopes,
            client_id: clientId,
          });
        } catch (error) {
          console.error("Error executing auth callback:", error);
          // Don't fail the auth flow even if callback fails
        }
      }

      return new Response(
        JSON.stringify({
          message: "Authentication successful! You can close this window.",
        }),
        {
          status: 200,
          headers: { "Content-Type": "application/json" },
        }
      );
    } catch (error) {
      console.error("Error handling OAuth callback:", error);
      const errorMessage =
        error instanceof Error ? error.message : "Unknown error";
      return new Response(
        JSON.stringify({ error: `Authentication failed: ${errorMessage}` }),
        {
          status: 500,
          headers: { "Content-Type": "application/json" },
        }
      );
    }
  }

  private static GenerateRandomString(length: number): string {
    const charset =
      "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_~";
    const values = crypto.getRandomValues(new Uint8Array(length));
    return Array.from(values)
      .map((x) => charset[x % charset.length])
      .join("");
  }

  private static GenerateCodeVerifier(): string {
    return Auth.GenerateRandomString(128);
  }

  private static async GenerateCodeChallenge(
    codeVerifier: string
  ): Promise<string> {
    const encoder = new TextEncoder();
    const data = encoder.encode(codeVerifier);
    const digest = await crypto.subtle.digest("SHA-256", data);

    // Convert to base64url
    return btoa(String.fromCharCode(...new Uint8Array(digest)))
      .replace(/\+/g, "-")
      .replace(/\//g, "_")
      .replace(/=/g, "");
  }

  private static async exchangeCodeForTokens({
    code,
    codeVerifier,
    provider,
    redirectUri,
    clientId,
    env,
  }: {
    code: string;
    codeVerifier?: string;
    provider: AuthProvider;
    redirectUri: string;
    clientId: string;
    env: Bindings;
  }): Promise<{
    access_token: string;
    refresh_token?: string;
    expires_in?: number;
  }> {
    const config = PROVIDER_CONFIGS[provider];
    if (!config) {
      throw new Error(`Token exchange not implemented for ${provider}`);
    }

    const clientSecret = Auth.SecretFromId(env, provider, clientId);

    const params = new URLSearchParams({
      client_id: clientId,
      ...(clientSecret ? { client_secret: clientSecret } : null),
      code,
      grant_type: "authorization_code",
      redirect_uri: redirectUri,
      ...(codeVerifier ? { code_verifier: codeVerifier } : {}),
    });

    const response = await fetch(config.tokenUrl, {
      method: "POST",
      headers: {
        "Content-Type": "application/x-www-form-urlencoded",
      },
      body: params.toString(),
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`Token exchange failed: ${response.status} ${errorText}`);
    }

    const tokenData = (await response.json()) as {
      access_token: string;
      refresh_token?: string;
      expires_in?: number;
    };
    return {
      access_token: tokenData.access_token,
      refresh_token: tokenData.refresh_token,
      expires_in: tokenData.expires_in,
    };
  }

  private async refreshToken({
    clientId,
    refreshToken,
    provider,
  }: {
    clientId: string;
    refreshToken: string;
    provider: AuthProvider;
  }): Promise<{
    access_token: string;
    refresh_token?: string;
    expires_in?: number;
  }> {
    const config = PROVIDER_CONFIGS[provider];
    if (!config) {
      throw new Error(`Token refresh not implemented for ${provider}`);
    }

    const clientSecret = Auth.SecretFromId(this.env, provider, clientId);

    const params = new URLSearchParams({
      client_id: clientId,
      ...(clientSecret ? { client_secret: clientSecret } : null),
      refresh_token: refreshToken,
      grant_type: "refresh_token",
    });

    const response = await fetch(config.tokenUrl, {
      method: "POST",
      headers: {
        "Content-Type": "application/x-www-form-urlencoded",
      },
      body: params.toString(),
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`Token refresh failed: ${response.status} ${errorText}`);
    }

    const tokenData = (await response.json()) as {
      access_token: string;
      refresh_token?: string;
      expires_in?: number;
    };
    return {
      access_token: tokenData.access_token,
      refresh_token: tokenData.refresh_token,
      expires_in: tokenData.expires_in,
    };
  }

  static async GenerateAuthUrl({
    provider,
    level,
    scopes,
    callback,
    redirectUri,
    platform,
    env,
    storage,
  }: {
    provider: AuthProvider;
    level: AuthLevel;
    scopes: string[];
    callback?: Callback;
    redirectUri: string;
    platform?: "ios" | "android" | "desktop";
    env: Bindings;
    storage: DurableObjectNamespace<Storage>;
  }): Promise<{ url: string; clientId: string; state: string } | null> {
    const config = PROVIDER_CONFIGS[provider];
    if (!config) {
      throw new Error(`Provider ${provider} not supported`);
    }

    // Generate fresh PKCE parameters for this specific OAuth flow
    const codeVerifier = Auth.GenerateCodeVerifier();
    const codeChallenge = await Auth.GenerateCodeChallenge(codeVerifier);

    // Use global auth storage
    const storageStub = storage.idFromName("auth");
    const storageObj = storage.get(storageStub);

    // Generate unique state and store globally
    const state = crypto.randomUUID();
    await storageObj.set(
      state,
      JSON.stringify({
        provider,
        level,
        scopes,
        codeVerifier,
        timestamp: Date.now(),
        callback,
      } satisfies AuthState)
    );

    const clientId = (env[
      `${Auth.EnvPrefix(provider, platform)}_ID` as keyof Bindings
    ] ?? env[`${Auth.EnvPrefix(provider)}_ID` as keyof Bindings]) as string;

    const params = new URLSearchParams({
      response_type: "code",
      client_id: clientId,
      redirect_uri: redirectUri,
      scope: scopes.join(" "),
      state,
      code_challenge: codeChallenge,
      code_challenge_method: "S256",
      ...config.additionalParams,
    });

    const url = `${config.authUrl}?${params.toString()}`;

    return { url, clientId, state };
  }

  private static ALL_PLATFORMS: (undefined | "ios" | "android" | "desktop")[] =
    [undefined, "desktop", "ios", "android"];
  private static EnvPrefix(
    provider: AuthProvider,
    platform?: "ios" | "android" | "desktop"
  ) {
    return `AUTH_${provider.toUpperCase()}${
      platform ? `_${platform.toUpperCase()}` : ""
    }`;
  }

  private static SecretFromId(
    env: Bindings,
    provider: AuthProvider,
    id: string
  ) {
    const prefix = Auth.ALL_PLATFORMS.map((platform) =>
      Auth.EnvPrefix(provider, platform)
    ).find((p) => env[`${p}_ID` as keyof Bindings] === id);
    return prefix
      ? (env[`${prefix}_SECRET` as keyof Bindings] as string | undefined)
      : undefined;
  }
}
