/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";
import type { IPostgresInterval } from "postgres-interval";

export type ActivityKind = "document" | "entertainment" | "exercise" | "family" | "focus" | "meal" | "meeting" | "messages" | "phone" | "social" | "travel" | "videoconference";

export type ActivityType = "action" | "event" | "note";

export type ArrayType<T> = ArrayTypeImpl<T> extends (infer U)[]
  ? U[]
  : ArrayTypeImpl<T>;

export type ArrayTypeImpl<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S[], I[], U[]>
  : T[];

export type EnterBehavior = "enter_newline" | "enter_submits";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Interval = ColumnType<IPostgresInterval, IPostgresInterval | number | string, IPostgresInterval | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type SubscriptionPlan = "free";

export type SubscriptionStatus = "active" | "canceled" | "incomplete" | "incomplete_expired" | "past_due" | "trialing" | "unpaid";

export type SyncOperation = "create" | "update";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type TwistEnvironment = "personal" | "private" | "public" | "review";

export interface Activity {
  archived_at: Timestamp | null;
  assignee_id: string | null;
  at: string | null;
  /**
   * The actor to credit with creating this activity. For activities created by twists on behalf of contacts or users, this is the contact/user. For activities created directly by users or twists, this is the user/twist ID.
   */
  author_id: string;
  created_at: Generated<Timestamp>;
  /**
   * The user_id or priority_twist_id that actually created this activity. Unlike author_id, this always reflects the entity that performed the creation action, used for filtering callbacks and permissions.
   */
  created_by: string;
  /**
   * The twist definition ID (twist_admin.id) that created this activity. Null for user-created activities. No longer used in unique constraint (replaced by source_priority_root).
   */
  created_by_twist_id: Int8 | null;
  done_at: Timestamp | null;
  draft: Generated<boolean>;
  duration: Interval | null;
  embedding: string | null;
  id: Generated<string>;
  kind: ActivityKind | null;
  /**
   * Cached MAX(note.created_at) for non-draft, non-archived notes. Maintained by trigger. Used for unread status in user_activity and user_priority_unread views.
   */
  last_note_created_at: Timestamp | null;
  /**
   * Cached MAX(note.source_created_at) for non-draft, non-archived notes. Maintained by trigger. Used for display, sorting, and range_at computation in user_activity view.
   */
  last_note_source_created_at: Timestamp | null;
  meta: Json | null;
  on: string | null;
  order: Generated<number>;
  /**
   * The PickPriorityConfig used to automatically select this activity's priority. Null if priority was explicitly specified. Used when moving activities to find similar activities to move. Not exposed to app or API.
   */
  pick_priority: Json | null;
  preview: string | null;
  priority_id: string;
  private: Generated<boolean>;
  recurrence_exdates: ArrayType<Timestamp> | null;
  recurrence_rule: string | null;
  /**
   * External source identifier for deduplication and sync. Provided as a top-level field in the Activity type (not stored in meta). Indexed for efficient lookups. Used with source_priority_root for upsert behavior.
   */
  source: string | null;
  /**
   * When this activity was originally created in its source system (e.g., GitHub issue creation date, email sent date). Defaults to now() but can be set by twists. Used for display and sorting. For unread status, use created_at which tracks when the activity entered Plot's database.
   */
  source_created_at: Generated<Timestamp>;
  /**
   * Root element of the priority path (e.g., first segment of the ltree). Set by trigger when source is non-null. Used with source to ensure uniqueness per top-level priority.
   */
  source_priority_root: string | null;
  sync_depth: number | null;
  title: string | null;
  type: Generated<ActivityType>;
  updated_at: Generated<Timestamp>;
  updated_by: Generated<number>;
}

export interface ActivityException {
  activity_id: string;
  archived_at: Timestamp | null;
  at: string | null;
  created_at: Generated<Timestamp>;
  done_at: Timestamp | null;
  duration: Interval | null;
  id: Generated<string>;
  meta: Json | null;
  /**
   * Original occurrence date/datetime in text format. For dates: YYYY-MM-DD, for datetimes: YYYY-MM-DDTHH:MM
   */
  occurrence: string;
  on: string | null;
  preview: string | null;
  title: string | null;
  updated_at: Generated<Timestamp>;
  updated_by: Generated<number>;
}

export interface ActivityRead {
  activity_id: string;
  read_at: Generated<Timestamp>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface ActivityTag {
  activity_id: string;
  actor_id: string;
  archived_at: Timestamp | null;
  id: Generated<Int8>;
  /**
   * Original occurrence date/datetime in text format. For dates: YYYY-MM-DD, for datetimes: YYYY-MM-DDTHH:MM
   */
  occurrence: string | null;
  sync_depth: number | null;
  tag_id: number;
  updated_at: Generated<Timestamp>;
  updated_by: Generated<number>;
}

export interface ActivityTags {
  activity_id: string | null;
  occurrence: string | null;
  tags: Json | null;
  updated_at: Timestamp | null;
  updated_by: number | null;
}

export interface ActivityX {
  archived_at: Timestamp | null;
  assignee_id: string | null;
  at: string | null;
  author_id: string | null;
  created_at: Timestamp | null;
  created_by: string | null;
  created_by_twist_id: Int8 | null;
  done_at: Timestamp | null;
  draft: boolean | null;
  duration: Interval | null;
  embedding: string | null;
  id: string | null;
  kind: ActivityKind | null;
  last_note_created_at: Timestamp | null;
  last_note_source_created_at: Timestamp | null;
  mentions: string[] | null;
  meta: Json | null;
  on: string | null;
  order: number | null;
  pick_priority: Json | null;
  preview: string | null;
  priority_id: string | null;
  priority_path: string | null;
  private: boolean | null;
  recurrence_exdates: ArrayType<Timestamp> | null;
  recurrence_rule: string | null;
  source: string | null;
  source_created_at: Timestamp | null;
  source_priority_root: string | null;
  sync_depth: number | null;
  title: string | null;
  type: ActivityType | null;
  updated_at: Timestamp | null;
  updated_by: number | null;
}

export interface Actor {
  archived_at: Timestamp | null;
  avatar_url: string | null;
  created_at: Timestamp | null;
  email: string | null;
  id: string | null;
  name: string | null;
  type: string | null;
  updated_at: Timestamp | null;
}

export interface AtlasSchemaRevisionsAtlasSchemaRevisions {
  applied: Generated<Int8>;
  description: string;
  error: string | null;
  error_stmt: string | null;
  executed_at: Timestamp;
  execution_time: Int8;
  hash: string;
  operator_version: string;
  partial_hashes: Json | null;
  total: Generated<Int8>;
  type: Generated<Int8>;
  version: string;
}

export interface Contact {
  archived_at: Timestamp | null;
  avatar_url: string | null;
  created_at: Generated<Timestamp>;
  email: string;
  id: Generated<string>;
  name: string | null;
  primary: Generated<boolean>;
  updated_at: Generated<Timestamp>;
  user_id: string | null;
}

export interface ContactExternalAccount {
  account_id: string;
  contact_id: string;
  data_fetched_at: Generated<Timestamp>;
  last_reported_at: Timestamp | null;
  provider: string;
}

export interface ContactInvitation {
  contact_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  redeemed_at: Timestamp | null;
  redeemed_by: string | null;
  sent_at: Generated<Timestamp>;
  token: string;
}

export interface Cost {
  amount: Numeric | null;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  name: string;
  start: Timestamp;
  updated_at: Generated<Timestamp>;
}

export interface Domain {
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  name: string;
  organization_id: Int8 | null;
}

export interface ExtensionsPgAllForeignKeys {
  fk_columns: string[] | null;
  fk_constraint_name: string | null;
  fk_schema_name: string | null;
  fk_table_name: string | null;
  fk_table_oid: number | null;
  is_deferrable: boolean | null;
  is_deferred: boolean | null;
  match_type: string | null;
  on_delete: string | null;
  on_update: string | null;
  pk_columns: string[] | null;
  pk_constraint_name: string | null;
  pk_index_name: string | null;
  pk_schema_name: string | null;
  pk_table_name: string | null;
  pk_table_oid: number | null;
}

export interface ExtensionsPgStatStatements {
  calls: Int8 | null;
  dbid: number | null;
  jit_deform_count: Int8 | null;
  jit_deform_time: number | null;
  jit_emission_count: Int8 | null;
  jit_emission_time: number | null;
  jit_functions: Int8 | null;
  jit_generation_time: number | null;
  jit_inlining_count: Int8 | null;
  jit_inlining_time: number | null;
  jit_optimization_count: Int8 | null;
  jit_optimization_time: number | null;
  local_blk_read_time: number | null;
  local_blk_write_time: number | null;
  local_blks_dirtied: Int8 | null;
  local_blks_hit: Int8 | null;
  local_blks_read: Int8 | null;
  local_blks_written: Int8 | null;
  max_exec_time: number | null;
  max_plan_time: number | null;
  mean_exec_time: number | null;
  mean_plan_time: number | null;
  min_exec_time: number | null;
  min_plan_time: number | null;
  minmax_stats_since: Timestamp | null;
  parallel_workers_launched: Int8 | null;
  parallel_workers_to_launch: Int8 | null;
  plans: Int8 | null;
  query: string | null;
  queryid: Int8 | null;
  rows: Int8 | null;
  shared_blk_read_time: number | null;
  shared_blk_write_time: number | null;
  shared_blks_dirtied: Int8 | null;
  shared_blks_hit: Int8 | null;
  shared_blks_read: Int8 | null;
  shared_blks_written: Int8 | null;
  stats_since: Timestamp | null;
  stddev_exec_time: number | null;
  stddev_plan_time: number | null;
  temp_blk_read_time: number | null;
  temp_blk_write_time: number | null;
  temp_blks_read: Int8 | null;
  temp_blks_written: Int8 | null;
  toplevel: boolean | null;
  total_exec_time: number | null;
  total_plan_time: number | null;
  userid: number | null;
  wal_buffers_full: Int8 | null;
  wal_bytes: Numeric | null;
  wal_fpi: Int8 | null;
  wal_records: Int8 | null;
}

export interface ExtensionsPgStatStatementsInfo {
  dealloc: Int8 | null;
  stats_reset: Timestamp | null;
}

export interface ExtensionsTapFunky {
  args: string | null;
  is_definer: boolean | null;
  is_strict: boolean | null;
  is_visible: boolean | null;
  kind: string | null;
  langoid: number | null;
  name: string | null;
  oid: number | null;
  owner: string | null;
  returns: string | null;
  returns_set: boolean | null;
  schema: string | null;
  volatility: string | null;
}

export interface Note {
  activity_id: string;
  archived_at: Timestamp | null;
  /**
   * The actor to credit with creating this note. For notes created by twists on behalf of contacts or users, this is the contact/user. For notes created directly by users or twists, this is the user/twist ID.
   */
  author_id: string;
  content: string | null;
  created_at: Generated<Timestamp>;
  /**
   * The user_id or priority_twist_id that actually created this note. Unlike author_id, this always reflects the entity that performed the creation action, used for filtering callbacks and permissions.
   */
  created_by: string;
  draft: Generated<boolean>;
  id: Generated<string>;
  /**
   * External identifier for deduplication and sync within an activity. Provided as a top-level field in the Note type. Indexed for efficient lookups. Used with activity_id for upsert behavior, allowing notes to be idempotently created or updated by external key (e.g., "description" for Jira issue descriptions).
   */
  key: string | null;
  links: Json | null;
  /**
   * Array of actor IDs (user_id, contact_id, or priority_twist_id) that are mentioned in this note via @-mentions.
   */
  mentions: string[] | null;
  private: Generated<boolean>;
  re_note_id: string | null;
  /**
   * When this note was originally created in its source system (e.g., email sent date, comment creation date). Defaults to now() but can be set by twists. Used for display and sorting. For unread status, use created_at which tracks when the note entered Plot's database.
   */
  source_created_at: Generated<Timestamp>;
  sync_depth: number | null;
  updated_at: Generated<Timestamp>;
  updated_by: Generated<number>;
}

export interface NoteTag {
  actor_id: string;
  archived_at: Timestamp | null;
  id: Generated<Int8>;
  note_id: string;
  sync_depth: number | null;
  tag_id: number;
  updated_at: Generated<Timestamp>;
  updated_by: Generated<number>;
}

export interface NoteTags {
  note_id: string | null;
  tags: Json | null;
  updated_at: Timestamp | null;
  updated_by: number | null;
}

export interface Organization {
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  name: string;
}

export interface Priority {
  archived_at: Timestamp | null;
  color: number | null;
  created_at: Generated<Timestamp>;
  created_by: string;
  id: Generated<string>;
  key: string | null;
  path: string;
  sync_depth: number | null;
  title: string;
  updated_at: Generated<Timestamp>;
  updated_by: Generated<number>;
}

export interface PriorityChild {
  archived_at: Timestamp | null;
  child_id: string | null;
  priority_id: string | null;
}

export interface PriorityChildTwist {
  archived_at: Timestamp | null;
  author_email: string | null;
  author_name: string | null;
  author_url: string | null;
  config: Json | null;
  created_at: Timestamp | null;
  id: string | null;
  name: string | null;
  owner_id: string | null;
  priority_child_id: string | null;
  priority_id: string | null;
  suspended_at: Timestamp | null;
  twist_environment: TwistEnvironment | null;
  twist_id: Int8 | null;
  updated_at: Timestamp | null;
  version: string | null;
}

export interface PriorityContact {
  contact_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  invited_at: Timestamp | null;
  invited_by: string | null;
  priority_id: string;
  updated_at: Generated<Timestamp>;
}

export interface PriorityMember {
  archived_at: Timestamp | null;
  contact_id: string | null;
  created_at: Timestamp | null;
  invited_by: string | null;
  personal: boolean | null;
  priority_id: string | null;
  status: string | null;
  updated_at: Timestamp | null;
}

export interface PrioritySettings {
  color: number | null;
  order: number | null;
  path: string | null;
  pomodoro: number | null;
  priority_id: string;
  title: string | null;
  top_order: number | null;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface PrioritySettingsInherited {
  color: number | null;
  path: string | null;
  pomodoro: number | null;
  priority_id: string | null;
  user_id: string | null;
}

export interface PriorityTags {
  count: Int8 | null;
  priority_id: string | null;
  tag_id: number | null;
  updated_at: Timestamp | null;
}

export interface PriorityTwist {
  archived_at: Timestamp | null;
  config: Generated<Json>;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  owner_id: string;
  priority_id: string | null;
  suspended_at: Timestamp | null;
  twist_id: Int8;
  updated_at: Generated<Timestamp>;
}

export interface PriorityTwistActivityCreate {
  archived_at: Timestamp | null;
  assignee_id: string | null;
  at: string | null;
  author_id: string | null;
  author_name: string | null;
  author_type: string | null;
  created_at: Timestamp | null;
  created_by: string | null;
  done_at: Timestamp | null;
  draft: boolean | null;
  duration: Interval | null;
  id: string | null;
  mentions: string[] | null;
  meta: Json | null;
  on: string | null;
  order: number | null;
  preview: string | null;
  priority_id: string | null;
  priority_title: string | null;
  priority_twist_id: string | null;
  private: boolean | null;
  recurrence_exdates: ArrayType<Timestamp> | null;
  recurrence_rule: string | null;
  source: string | null;
  source_created_at: Timestamp | null;
  sync_depth: number | null;
  tags: Json | null;
  title: string | null;
  type: ActivityType | null;
  updated_at: Timestamp | null;
  updated_by: number | null;
}

export interface PriorityTwistActivityTagChange {
  activity_id: string | null;
  actor_id: string | null;
  change_type: string | null;
  occurrence: string | null;
  priority_twist_id: string | null;
  tag_id: number | null;
  updated_at: Timestamp | null;
}

export interface PriorityTwistActivityUpdate {
  archived_at: Timestamp | null;
  assignee_id: string | null;
  at: string | null;
  author_id: string | null;
  author_name: string | null;
  author_type: string | null;
  created_at: Timestamp | null;
  created_by: string | null;
  done_at: Timestamp | null;
  draft: boolean | null;
  duration: Interval | null;
  id: string | null;
  mentions: string[] | null;
  meta: Json | null;
  on: string | null;
  order: number | null;
  preview: string | null;
  priority_id: string | null;
  priority_title: string | null;
  priority_twist_id: string | null;
  private: boolean | null;
  recurrence_exdates: ArrayType<Timestamp> | null;
  recurrence_rule: string | null;
  source: string | null;
  source_created_at: Timestamp | null;
  sync_depth: number | null;
  tags: Json | null;
  title: string | null;
  type: ActivityType | null;
  updated_at: Timestamp | null;
  updated_by: number | null;
}

export interface PriorityTwistNoteCreate {
  activity_created_by: string | null;
  activity_id: string | null;
  activity_mentions: string[] | null;
  activity_meta: Json | null;
  activity_title: string | null;
  archived_at: Timestamp | null;
  author_id: string | null;
  author_name: string | null;
  author_type: string | null;
  content: string | null;
  created_at: Timestamp | null;
  created_by: string | null;
  draft: boolean | null;
  first_mentioned_at: Timestamp | null;
  id: string | null;
  key: string | null;
  links: Json | null;
  mentions: string[] | null;
  priority_id: string | null;
  priority_twist_id: string | null;
  private: boolean | null;
  re_note_id: string | null;
  source_created_at: Timestamp | null;
  sync_depth: number | null;
  tags: Json | null;
  updated_at: Timestamp | null;
  updated_by: number | null;
}

export interface PriorityTwistNoteUpdate {
  activity_created_by: string | null;
  activity_id: string | null;
  activity_mentions: string[] | null;
  activity_meta: Json | null;
  activity_title: string | null;
  archived_at: Timestamp | null;
  author_id: string | null;
  author_name: string | null;
  author_type: string | null;
  content: string | null;
  created_at: Timestamp | null;
  created_by: string | null;
  draft: boolean | null;
  id: string | null;
  key: string | null;
  links: Json | null;
  mentions: string[] | null;
  priority_id: string | null;
  priority_twist_id: string | null;
  private: boolean | null;
  re_note_id: string | null;
  source_created_at: Timestamp | null;
  sync_depth: number | null;
  tags: Json | null;
  updated_at: Timestamp | null;
  updated_by: number | null;
}

export interface PriorityTwistSync {
  entity: string;
  last_sync_at: Generated<Timestamp>;
  last_update_at: Timestamp;
  operation: SyncOperation;
  priority_twist_id: string;
}

export interface PriorityUser {
  archived_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  personal: Generated<boolean>;
  priority_id: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface Publisher {
  created_at: Generated<Timestamp>;
  email: string | null;
  id: Generated<Int8>;
  name: string;
  updated_at: Generated<Timestamp>;
  url: string | null;
}

export interface Series {
  created_at: Generated<Timestamp>;
  embedding: string | null;
  id: Generated<Int8>;
  invitees: string[] | null;
  priority_id: string | null;
  series: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface Session {
  archived_at: Timestamp | null;
  at: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  pomodoro: number | null;
  pomodoro_at: Timestamp | null;
  precedence: Generated<number>;
  priority_id: string | null;
  updated_at: Generated<Timestamp>;
  updated_by: Generated<number>;
  user_id: string;
}

export interface Token {
  archived_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  last_used_at: Timestamp | null;
  name: string | null;
  publisher_id: Int8 | null;
  token: string;
  updated_at: Generated<Timestamp>;
  user_id: string | null;
}

export interface Twist {
  archived_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  description: string | null;
  environment: Generated<TwistEnvironment>;
  id: Generated<Int8>;
  name: string;
  permissions: Json | null;
  twist_admin_id: Int8;
  updated_at: Generated<Timestamp>;
  version: string;
}

export interface TwistAdmin {
  auto_approve: Generated<boolean>;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  priority_id: string | null;
  publisher_id: Int8 | null;
  twist_package_id: Generated<string>;
  updated_at: Generated<Timestamp>;
  user_id: string | null;
}

export interface Usage {
  amount: number;
  cost_id: Int8;
  created_at: Generated<Timestamp>;
  hour: Timestamp;
  id: Generated<Int8>;
  priority_twist_id: string;
  updated_at: Generated<Timestamp>;
}

export interface User {
  avatar_url: string | null;
  clerk_id: string | null;
  created_at: Generated<Timestamp>;
  email: string;
  id: Generated<string>;
  name: string | null;
  updated_at: Generated<Timestamp>;
}

export interface UserActivity {
  archived_at: Timestamp | null;
  assignee_id: string | null;
  at: string | null;
  author_id: string | null;
  created_at: Timestamp | null;
  created_by_twist_id: Int8 | null;
  done_at: Timestamp | null;
  draft: boolean | null;
  duration: Interval | null;
  id: string | null;
  kind: ActivityKind | null;
  last_note_created_at: Timestamp | null;
  last_note_source_created_at: Timestamp | null;
  mentions: string[] | null;
  meta: Json | null;
  on: string | null;
  order: number | null;
  preview: string | null;
  priority_id: string | null;
  priority_path: string | null;
  private: boolean | null;
  range_at: string | null;
  range_on: string | null;
  recurrence_exdates: ArrayType<Timestamp> | null;
  recurrence_rule: string | null;
  source: string | null;
  source_created_at: Timestamp | null;
  title: string | null;
  type: ActivityType | null;
  unread: boolean | null;
  updated_at: Timestamp | null;
  updated_by: number | null;
  user_id: string | null;
}

export interface UserActivityException {
  activity_id: string | null;
  archived_at: Timestamp | null;
  at: string | null;
  id: string | null;
  occurrence: string | null;
  on: string | null;
  preview: string | null;
  priority_path: string | null;
  range_at: string | null;
  range_on: string | null;
  title: string | null;
  updated_at: Timestamp | null;
  user_id: string | null;
}

export interface UserActivityTags {
  archived_at: Timestamp | null;
  id: string | null;
  occurrence: string | null;
  priority_path: string | null;
  range_at: string | null;
  range_on: string | null;
  tags: Json | null;
  updated_at: Timestamp | null;
  user_id: string | null;
}

export interface UserActor {
  archived_at: Timestamp | null;
  avatar_url: string | null;
  created_at: Timestamp | null;
  email: string | null;
  id: string | null;
  name: string | null;
  self: boolean | null;
  type: string | null;
  updated_at: Timestamp | null;
  user_id: string | null;
}

export interface UserNote {
  activity_id: string | null;
  archived_at: Timestamp | null;
  author_id: string | null;
  content: string | null;
  created_at: Timestamp | null;
  created_by: string | null;
  draft: boolean | null;
  id: string | null;
  links: Json | null;
  mentions: string[] | null;
  private: boolean | null;
  re_note_id: string | null;
  source_created_at: Timestamp | null;
  updated_at: Timestamp | null;
  updated_by: number | null;
  user_id: string | null;
}

export interface UserNoteTags {
  archived_at: Timestamp | null;
  id: string | null;
  priority_path: string | null;
  range_at: string | null;
  range_on: string | null;
  tags: Json | null;
  updated_at: Timestamp | null;
  user_id: string | null;
}

export interface UserPriority {
  archived_at: Timestamp | null;
  color: number | null;
  created_at: Timestamp | null;
  created_by: string | null;
  global_path: string | null;
  id: string | null;
  key: string | null;
  order: number | null;
  path: string | null;
  personal: boolean | null;
  pomodoro: number | null;
  root: boolean | null;
  title: string | null;
  top_order: number | null;
  unread: boolean | null;
  updated_at: Timestamp | null;
  updated_by: number | null;
  user_id: string | null;
}

export interface UserPriorityActor {
  actor_id: string | null;
  archived_at: Timestamp | null;
  created_at: Timestamp | null;
  priority_path: string | null;
  updated_at: Timestamp | null;
  user_id: string | null;
}

export interface UserPriorityExpanded {
  archived_at: Timestamp | null;
  joined_at: Timestamp | null;
  path: string | null;
  priority_id: string | null;
  user_id: string | null;
}

export interface UserPriorityUnread {
  priority_id: string | null;
  unread: boolean | null;
  updated_at: Timestamp | null;
  user_id: string | null;
}

export interface UserSettings {
  enter_behavior: EnterBehavior | null;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface UserSubscription {
  billing_cycle_end: Timestamp;
  billing_cycle_start: Timestamp;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  plan: Generated<SubscriptionPlan>;
  status: Generated<SubscriptionStatus>;
  stripe_customer_id: string | null;
  stripe_subscription_id: string | null;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface UserSync {
  entity: string;
  last_sync_at: Generated<Timestamp>;
  last_update_at: Timestamp;
  user_id: string;
}

export interface UserTwist {
  archived_at: Timestamp | null;
  config: Json | null;
  created_at: Timestamp | null;
  id: string | null;
  name: string | null;
  owner_id: string | null;
  priority_id: string | null;
  twist_environment: TwistEnvironment | null;
  twist_id: Int8 | null;
  updated_at: Timestamp | null;
  user_id: string | null;
}

export interface DB {
  activity: Activity;
  activity_exception: ActivityException;
  activity_read: ActivityRead;
  activity_tag: ActivityTag;
  activity_tags: ActivityTags;
  activity_x: ActivityX;
  actor: Actor;
  "atlas_schema_revisions.atlas_schema_revisions": AtlasSchemaRevisionsAtlasSchemaRevisions;
  contact: Contact;
  contact_external_account: ContactExternalAccount;
  contact_invitation: ContactInvitation;
  cost: Cost;
  domain: Domain;
  "extensions.pg_all_foreign_keys": ExtensionsPgAllForeignKeys;
  "extensions.pg_stat_statements": ExtensionsPgStatStatements;
  "extensions.pg_stat_statements_info": ExtensionsPgStatStatementsInfo;
  "extensions.tap_funky": ExtensionsTapFunky;
  note: Note;
  note_tag: NoteTag;
  note_tags: NoteTags;
  organization: Organization;
  priority: Priority;
  priority_child: PriorityChild;
  priority_child_twist: PriorityChildTwist;
  priority_contact: PriorityContact;
  priority_member: PriorityMember;
  priority_settings: PrioritySettings;
  priority_settings_inherited: PrioritySettingsInherited;
  priority_tags: PriorityTags;
  priority_twist: PriorityTwist;
  priority_twist_activity_create: PriorityTwistActivityCreate;
  priority_twist_activity_tag_change: PriorityTwistActivityTagChange;
  priority_twist_activity_update: PriorityTwistActivityUpdate;
  priority_twist_note_create: PriorityTwistNoteCreate;
  priority_twist_note_update: PriorityTwistNoteUpdate;
  priority_twist_sync: PriorityTwistSync;
  priority_user: PriorityUser;
  publisher: Publisher;
  series: Series;
  session: Session;
  token: Token;
  twist: Twist;
  twist_admin: TwistAdmin;
  usage: Usage;
  user: User;
  user_settings: UserSettings;
  user_subscription: UserSubscription;
  user_sync: UserSync;
  "user.activity": UserActivity;
  "user.activity_exception": UserActivityException;
  "user.activity_tags": UserActivityTags;
  "user.actor": UserActor;
  "user.note": UserNote;
  "user.note_tags": UserNoteTags;
  "user.priority": UserPriority;
  "user.priority_actor": UserPriorityActor;
  "user.priority_expanded": UserPriorityExpanded;
  "user.priority_unread": UserPriorityUnread;
  "user.twist": UserTwist;
}
