/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";
import type { IPostgresInterval } from "postgres-interval";

export type ArrayType<T> = ArrayTypeImpl<T> extends (infer U)[]
  ? U[]
  : ArrayTypeImpl<T>;

export type ArrayTypeImpl<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S[], I[], U[]>
  : T[];

export type EnterBehavior = "enter_newline" | "enter_submits";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Interval = ColumnType<IPostgresInterval, IPostgresInterval | number | string, IPostgresInterval | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type OrganizationRole = "admin" | "member";

export type SubscriptionPlan = "business" | "free" | "pro";

export type SubscriptionStatus = "active" | "canceled" | "incomplete" | "incomplete_expired" | "past_due" | "trialing" | "unpaid";

export type SyncOperation = "create" | "update";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type TwistEnvironment = "personal" | "private" | "public" | "review";

export interface Actor {
  archived_at: Timestamp | null;
  avatar_url: string | null;
  created_at: Timestamp | null;
  email: string | null;
  id: string | null;
  name: string | null;
  type: string | null;
  updated_at: Timestamp | null;
}

export interface AtlasSchemaRevisionsAtlasSchemaRevisions {
  applied: Generated<Int8>;
  description: string;
  error: string | null;
  error_stmt: string | null;
  executed_at: Timestamp;
  execution_time: Int8;
  hash: string;
  operator_version: string;
  partial_hashes: Json | null;
  total: Generated<Int8>;
  type: Generated<Int8>;
  version: string;
}

export interface Contact {
  archived_at: Timestamp | null;
  avatar_url: string | null;
  created_at: Generated<Timestamp>;
  email: string;
  id: Generated<string>;
  name: string | null;
  primary: Generated<boolean>;
  updated_at: Generated<Timestamp>;
  user_id: string | null;
}

export interface ContactExternalAccount {
  account_id: string;
  contact_id: string;
  data_fetched_at: Generated<Timestamp>;
  last_reported_at: Timestamp | null;
  provider: string;
}

export interface ContactInvitation {
  contact_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  redeemed_at: Timestamp | null;
  redeemed_by: string | null;
  sent_at: Generated<Timestamp>;
  token: string;
}

export interface Cost {
  amount: Numeric | null;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  name: string;
  start: Timestamp;
  updated_at: Generated<Timestamp>;
}

export interface Device {
  app_version: string | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  platform: string;
  push_token: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface Domain {
  auto_join: Generated<boolean>;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  name: string;
  organization_id: Int8 | null;
}

export interface ExtensionsPgAllForeignKeys {
  fk_columns: string[] | null;
  fk_constraint_name: string | null;
  fk_schema_name: string | null;
  fk_table_name: string | null;
  fk_table_oid: number | null;
  is_deferrable: boolean | null;
  is_deferred: boolean | null;
  match_type: string | null;
  on_delete: string | null;
  on_update: string | null;
  pk_columns: string[] | null;
  pk_constraint_name: string | null;
  pk_index_name: string | null;
  pk_schema_name: string | null;
  pk_table_name: string | null;
  pk_table_oid: number | null;
}

export interface ExtensionsPgStatStatements {
  calls: Int8 | null;
  dbid: number | null;
  jit_deform_count: Int8 | null;
  jit_deform_time: number | null;
  jit_emission_count: Int8 | null;
  jit_emission_time: number | null;
  jit_functions: Int8 | null;
  jit_generation_time: number | null;
  jit_inlining_count: Int8 | null;
  jit_inlining_time: number | null;
  jit_optimization_count: Int8 | null;
  jit_optimization_time: number | null;
  local_blk_read_time: number | null;
  local_blk_write_time: number | null;
  local_blks_dirtied: Int8 | null;
  local_blks_hit: Int8 | null;
  local_blks_read: Int8 | null;
  local_blks_written: Int8 | null;
  max_exec_time: number | null;
  max_plan_time: number | null;
  mean_exec_time: number | null;
  mean_plan_time: number | null;
  min_exec_time: number | null;
  min_plan_time: number | null;
  minmax_stats_since: Timestamp | null;
  parallel_workers_launched: Int8 | null;
  parallel_workers_to_launch: Int8 | null;
  plans: Int8 | null;
  query: string | null;
  queryid: Int8 | null;
  rows: Int8 | null;
  shared_blk_read_time: number | null;
  shared_blk_write_time: number | null;
  shared_blks_dirtied: Int8 | null;
  shared_blks_hit: Int8 | null;
  shared_blks_read: Int8 | null;
  shared_blks_written: Int8 | null;
  stats_since: Timestamp | null;
  stddev_exec_time: number | null;
  stddev_plan_time: number | null;
  temp_blk_read_time: number | null;
  temp_blk_write_time: number | null;
  temp_blks_read: Int8 | null;
  temp_blks_written: Int8 | null;
  toplevel: boolean | null;
  total_exec_time: number | null;
  total_plan_time: number | null;
  userid: number | null;
  wal_buffers_full: Int8 | null;
  wal_bytes: Numeric | null;
  wal_fpi: Int8 | null;
  wal_records: Int8 | null;
}

export interface ExtensionsPgStatStatementsInfo {
  dealloc: Int8 | null;
  stats_reset: Timestamp | null;
}

export interface ExtensionsTapFunky {
  args: string | null;
  is_definer: boolean | null;
  is_strict: boolean | null;
  is_visible: boolean | null;
  kind: string | null;
  langoid: number | null;
  name: string | null;
  oid: number | null;
  owner: string | null;
  returns: string | null;
  returns_set: boolean | null;
  schema: string | null;
  volatility: string | null;
}

export interface Link {
  actions: Json | null;
  assignee_id: string | null;
  /**
   * The actor to credit with creating this link. For links created by twists on behalf of contacts or users, this is the contact/user.
   */
  author_id: string | null;
  channel_id: string | null;
  created_at: Generated<Timestamp>;
  /**
   * The user_id or priority_twist_id that actually created this link. Used for filtering callbacks and permissions.
   */
  created_by: string | null;
  embedding: string | null;
  id: Generated<string>;
  logo: string | null;
  /**
   * The PickPriorityConfig used to automatically select this link's priority. Null if priority was explicitly specified. Used when moving links to find similar links to move.
   */
  match: Json | null;
  merged_from_thread_id: string | null;
  meta: Json | null;
  preview: string | null;
  priority_id: string | null;
  /**
   * External source identifier for deduplication and sync. Used with source_priority_root for upsert behavior.
   */
  source: string | null;
  /**
   * When this link was originally created in its source system. Defaults to now() but can be set by twists.
   */
  source_created_at: Generated<Timestamp>;
  /**
   * Root element of the priority path. Set by trigger when source is non-null. Used with source to ensure uniqueness per top-level priority.
   */
  source_priority_root: string | null;
  source_url: string | null;
  /**
   * Source-defined status string (e.g., open, done, closed). Free text.
   */
  status: string | null;
  sync_depth: number | null;
  thread_id: string | null;
  title: string | null;
  /**
   * The twist definition ID (twist_admin.id) that created this link. Null for user-created links.
   */
  twist_id: Int8 | null;
  /**
   * Source-defined type string (e.g., issue, pull_request, email, event). Free text, with structured registry in source linkTypes config.
   */
  type: string | null;
  updated_at: Generated<Timestamp>;
  updated_by: Generated<number>;
}

export interface LinkX {
  actions: Json | null;
  assignee_id: string | null;
  author_id: string | null;
  channel_id: string | null;
  created_at: Timestamp | null;
  created_by: string | null;
  embedding: string | null;
  id: string | null;
  logo: string | null;
  match: Json | null;
  merged_from_thread_id: string | null;
  meta: Json | null;
  preview: string | null;
  priority_id: string | null;
  priority_path: string | null;
  source: string | null;
  source_created_at: Timestamp | null;
  source_priority_root: string | null;
  source_url: string | null;
  status: string | null;
  sync_depth: number | null;
  thread_id: string | null;
  title: string | null;
  twist_id: Int8 | null;
  type: string | null;
  updated_at: Timestamp | null;
  updated_by: number | null;
}

export interface Note {
  actions: Json | null;
  archived_at: Timestamp | null;
  /**
   * The actor to credit with creating this note. For notes created by twists on behalf of contacts or users, this is the contact/user. For notes created directly by users or twists, this is the user/twist ID.
   */
  author_id: string;
  content: string | null;
  created_at: Generated<Timestamp>;
  /**
   * The user_id or priority_twist_id that actually created this note. Unlike author_id, this always reflects the entity that performed the creation action, used for filtering callbacks and permissions.
   */
  created_by: string;
  draft: Generated<boolean>;
  embedding: string | null;
  id: Generated<string>;
  /**
   * External identifier for deduplication and sync within a thread. Provided as a top-level field in the Note type. Indexed for efficient lookups. Used with thread_id for upsert behavior, allowing notes to be idempotently created or updated by external key (e.g., "description" for Jira issue descriptions).
   */
  key: string | null;
  /**
   * Array of actor IDs (user_id, contact_id, or priority_twist_id) that are mentioned in this note via @-mentions.
   */
  mentions: string[] | null;
  merged_from_thread_id: string | null;
  private: Generated<boolean>;
  re_note_id: string | null;
  /**
   * When this note was originally created in its source system (e.g., email sent date, comment creation date). Defaults to now() but can be set by twists. Used for display and sorting. For unread status, use created_at which tracks when the note entered Plot's database.
   */
  source_created_at: Generated<Timestamp>;
  sync_depth: number | null;
  thread_id: string;
  updated_at: Generated<Timestamp>;
  updated_by: Generated<number>;
}

export interface NoteTag {
  actor_id: string;
  archived_at: Timestamp | null;
  id: Generated<Int8>;
  note_id: string;
  sync_depth: number | null;
  tag_id: number;
  updated_at: Generated<Timestamp>;
  updated_by: Generated<number>;
}

export interface NoteTags {
  note_id: string | null;
  tags: Json | null;
  updated_at: Timestamp | null;
  updated_by: number | null;
}

export interface Organization {
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  name: string;
  updated_at: Generated<Timestamp>;
}

export interface OrganizationInvitation {
  created_at: Generated<Timestamp>;
  email: string;
  id: Generated<Int8>;
  invited_by: string;
  organization_id: Int8;
  role: Generated<OrganizationRole>;
}

export interface OrganizationMember {
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  organization_id: Int8;
  role: Generated<OrganizationRole>;
  user_id: string;
}

export interface OrganizationSubscription {
  billing_cycle_end: Timestamp;
  billing_cycle_start: Timestamp;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  organization_id: Int8;
  plan: Generated<SubscriptionPlan>;
  status: Generated<SubscriptionStatus>;
  stripe_customer_id: string | null;
  stripe_subscription_id: string | null;
  updated_at: Generated<Timestamp>;
}

export interface Priority {
  archived_at: Timestamp | null;
  color: number | null;
  created_at: Generated<Timestamp>;
  created_by: string;
  id: Generated<string>;
  key: string | null;
  organization_id: Int8 | null;
  path: string;
  sync_depth: number | null;
  title: string;
  updated_at: Generated<Timestamp>;
  updated_by: Generated<number>;
}

export interface PriorityChild {
  archived_at: Timestamp | null;
  child_id: string | null;
  priority_id: string | null;
}

export interface PriorityChildTwist {
  archived_at: Timestamp | null;
  author_email: string | null;
  author_name: string | null;
  author_url: string | null;
  config: Json | null;
  created_at: Timestamp | null;
  id: string | null;
  is_source: boolean | null;
  name: string | null;
  owner_id: string | null;
  priority_child_id: string | null;
  priority_id: string | null;
  suspended_at: Timestamp | null;
  twist_environment: TwistEnvironment | null;
  twist_id: Int8 | null;
  updated_at: Timestamp | null;
  version: string | null;
}

export interface PriorityContact {
  contact_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  invited_at: Timestamp | null;
  invited_by: string | null;
  priority_id: string;
  updated_at: Generated<Timestamp>;
}

export interface PriorityMember {
  archived_at: Timestamp | null;
  contact_id: string | null;
  created_at: Timestamp | null;
  invited_by: string | null;
  personal: boolean | null;
  priority_id: string | null;
  role: string | null;
  status: string | null;
  updated_at: Timestamp | null;
}

export interface PrioritySettings {
  color: number | null;
  order: number | null;
  path: string | null;
  pomodoro: number | null;
  priority_id: string;
  title: string | null;
  top_order: number | null;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface PrioritySettingsInherited {
  color: number | null;
  path: string | null;
  pomodoro: number | null;
  priority_id: string | null;
  user_id: string | null;
}

export interface PriorityTags {
  count: Int8 | null;
  priority_id: string | null;
  tag_id: number | null;
  updated_at: Timestamp | null;
}

export interface PriorityTwist {
  archived_at: Timestamp | null;
  config: Generated<Json>;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  owner_id: string;
  priority_id: string | null;
  suspended_at: Timestamp | null;
  twist_id: Int8;
  updated_at: Generated<Timestamp>;
}

export interface PriorityTwistChannel {
  channel_id: string;
  created_at: Generated<Timestamp>;
  enabled: Generated<boolean>;
  id: Generated<Int8>;
  priority_twist_id: string;
  source_priority_twist_id: string;
  updated_at: Generated<Timestamp>;
}

export interface PriorityTwistChannelLinkCreate {
  actions: Json | null;
  assignee_id: string | null;
  author_id: string | null;
  author_name: string | null;
  author_type: string | null;
  channel_id: string | null;
  created_at: Timestamp | null;
  created_by: string | null;
  id: string | null;
  meta: Json | null;
  preview: string | null;
  priority_id: string | null;
  priority_title: string | null;
  priority_twist_id: string | null;
  source: string | null;
  source_created_at: Timestamp | null;
  source_url: string | null;
  status: string | null;
  sync_depth: number | null;
  thread_id: string | null;
  title: string | null;
  twist_id: Int8 | null;
  type: string | null;
  updated_at: Timestamp | null;
  updated_by: number | null;
}

export interface PriorityTwistChannelLinkUpdate {
  actions: Json | null;
  assignee_id: string | null;
  author_id: string | null;
  author_name: string | null;
  author_type: string | null;
  channel_id: string | null;
  created_at: Timestamp | null;
  created_by: string | null;
  id: string | null;
  meta: Json | null;
  preview: string | null;
  priority_id: string | null;
  priority_title: string | null;
  priority_twist_id: string | null;
  source: string | null;
  source_created_at: Timestamp | null;
  source_url: string | null;
  status: string | null;
  sync_depth: number | null;
  thread_id: string | null;
  title: string | null;
  twist_id: Int8 | null;
  type: string | null;
  updated_at: Timestamp | null;
  updated_by: number | null;
}

export interface PriorityTwistChannelNoteCreate {
  actions: Json | null;
  archived_at: Timestamp | null;
  author_id: string | null;
  author_name: string | null;
  author_type: string | null;
  content: string | null;
  created_at: Timestamp | null;
  created_by: string | null;
  draft: boolean | null;
  id: string | null;
  key: string | null;
  link_channel_id: string | null;
  link_id: string | null;
  link_meta: Json | null;
  link_source: string | null;
  link_source_url: string | null;
  link_title: string | null;
  link_type: string | null;
  mentions: string[] | null;
  priority_id: string | null;
  priority_twist_id: string | null;
  private: boolean | null;
  re_note_id: string | null;
  source_created_at: Timestamp | null;
  sync_depth: number | null;
  tags: Json | null;
  thread_created_by: string | null;
  thread_id: string | null;
  thread_title: string | null;
  updated_at: Timestamp | null;
  updated_by: number | null;
}

export interface PriorityTwistChild {
  archived_at: Timestamp | null;
  priority_id: string | null;
  priority_twist_id: string | null;
}

export interface PriorityTwistLinkUpdate {
  actions: Json | null;
  assignee_id: string | null;
  author_id: string | null;
  author_name: string | null;
  author_type: string | null;
  created_at: Timestamp | null;
  created_by: string | null;
  id: string | null;
  meta: Json | null;
  preview: string | null;
  priority_id: string | null;
  priority_title: string | null;
  priority_twist_id: string | null;
  source: string | null;
  source_created_at: Timestamp | null;
  status: string | null;
  sync_depth: number | null;
  thread_id: string | null;
  title: string | null;
  twist_id: Int8 | null;
  type: string | null;
  updated_at: Timestamp | null;
  updated_by: number | null;
}

export interface PriorityTwistNoteCreate {
  actions: Json | null;
  archived_at: Timestamp | null;
  author_id: string | null;
  author_name: string | null;
  author_type: string | null;
  content: string | null;
  created_at: Timestamp | null;
  created_by: string | null;
  draft: boolean | null;
  id: string | null;
  key: string | null;
  mentions: string[] | null;
  priority_id: string | null;
  priority_twist_id: string | null;
  private: boolean | null;
  re_note_id: string | null;
  source_created_at: Timestamp | null;
  sync_depth: number | null;
  tags: Json | null;
  thread_created_by: string | null;
  thread_id: string | null;
  thread_meta: Json | null;
  thread_title: string | null;
  updated_at: Timestamp | null;
  updated_by: number | null;
}

export interface PriorityTwistNoteUpdate {
  actions: Json | null;
  archived_at: Timestamp | null;
  author_id: string | null;
  author_name: string | null;
  author_type: string | null;
  content: string | null;
  created_at: Timestamp | null;
  created_by: string | null;
  draft: boolean | null;
  id: string | null;
  key: string | null;
  mentions: string[] | null;
  priority_id: string | null;
  priority_twist_id: string | null;
  private: boolean | null;
  re_note_id: string | null;
  source_created_at: Timestamp | null;
  sync_depth: number | null;
  tags: Json | null;
  thread_created_by: string | null;
  thread_id: string | null;
  thread_meta: Json | null;
  thread_title: string | null;
  updated_at: Timestamp | null;
  updated_by: number | null;
}

export interface PriorityTwistScheduleContact {
  archived_at: Timestamp | null;
  contact_id: string | null;
  link_id: string | null;
  priority_id: string | null;
  priority_twist_id: string | null;
  role: string | null;
  schedule_contact_id: Int8 | null;
  schedule_id: string | null;
  status: string | null;
  thread_id: string | null;
  updated_at: Timestamp | null;
}

export interface PriorityTwistSync {
  entity: string;
  last_sync_at: Generated<Timestamp>;
  last_update_at: Timestamp;
  operation: SyncOperation;
  priority_twist_id: string;
}

export interface PriorityTwistThreadRead {
  priority_id: string | null;
  priority_twist_id: string | null;
  read_at: Timestamp | null;
  thread_id: string | null;
  updated_at: Timestamp | null;
  user_id: string | null;
}

export interface PriorityTwistThreadSchedule {
  at: string | null;
  on: string | null;
  priority_id: string | null;
  priority_twist_id: string | null;
  schedule_id: string | null;
  thread_id: string | null;
  updated_at: Timestamp | null;
  user_id: string | null;
}

export interface PriorityTwistThreadTagChange {
  actor_id: string | null;
  change_type: string | null;
  occurrence: string | null;
  priority_twist_id: string | null;
  tag_id: number | null;
  thread_id: string | null;
  updated_at: Timestamp | null;
}

export interface PriorityTwistThreadUpdate {
  archived_at: Timestamp | null;
  created_at: Timestamp | null;
  created_by: string | null;
  draft: boolean | null;
  id: string | null;
  mentions: string[] | null;
  preview: string | null;
  priority_id: string | null;
  priority_title: string | null;
  priority_twist_id: string | null;
  private: boolean | null;
  sync_depth: number | null;
  tags: Json | null;
  title: string | null;
  updated_at: Timestamp | null;
  updated_by: number | null;
}

export interface PriorityUser {
  archived_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  personal: Generated<boolean>;
  priority_id: string;
  role: Generated<string>;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface Publisher {
  created_at: Generated<Timestamp>;
  email: string | null;
  id: Generated<Int8>;
  name: string;
  updated_at: Generated<Timestamp>;
  url: string | null;
}

export interface Schedule {
  archived_at: Timestamp | null;
  at: string | null;
  created_at: Generated<Timestamp>;
  duration: Interval | null;
  id: Generated<string>;
  link_id: string | null;
  occurrence: string | null;
  on: string | null;
  order: number | null;
  recurrence_exdates: ArrayType<Timestamp> | null;
  recurrence_rule: string | null;
  thread_id: string | null;
  updated_at: Generated<Timestamp>;
  user_id: string | null;
}

export interface ScheduleContact {
  archived_at: Timestamp | null;
  contact_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  role: Generated<string>;
  schedule_id: string;
  status: string | null;
  updated_at: Generated<Timestamp>;
}

export interface Series {
  created_at: Generated<Timestamp>;
  embedding: string | null;
  id: Generated<Int8>;
  invitees: string[] | null;
  priority_id: string | null;
  series: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface Session {
  archived_at: Timestamp | null;
  at: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  pomodoro: number | null;
  pomodoro_at: Timestamp | null;
  precedence: Generated<number>;
  priority_id: string | null;
  updated_at: Generated<Timestamp>;
  updated_by: Generated<number>;
  user_id: string;
}

export interface SourceChannel {
  /**
   * Provider-specific global ID for the channel. The same calendar/project has the same ID across users.
   */
  channel_id: string;
  create_threads: Generated<boolean>;
  created_at: Generated<Timestamp>;
  enabled: Generated<boolean>;
  id: Generated<Int8>;
  /**
   * The priority this channel syncs data to. NULL means the channel is known but not routed to any priority.
   */
  priority_id: string | null;
  priority_twist_id: string;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface Thread {
  archived_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  /**
   * The user_id or priority_twist_id that actually created this thread. Unlike author_id, this always reflects the entity that performed the creation action, used for filtering callbacks and permissions.
   */
  created_by: string;
  draft: Generated<boolean>;
  id: Generated<string>;
  /**
   * Cached MAX(note.created_at) for non-draft, non-archived notes. Maintained by trigger. Used for unread status in user_thread and user_priority_unread views.
   */
  last_note_created_at: Timestamp | null;
  /**
   * Cached MAX(note.source_created_at) for non-draft, non-archived notes. Maintained by trigger. Used for display, sorting, and range_at computation in user_thread view.
   */
  last_note_source_created_at: Timestamp | null;
  preview: string | null;
  priority_id: string;
  private: Generated<boolean>;
  sync_depth: number | null;
  title: string | null;
  updated_at: Generated<Timestamp>;
  updated_by: Generated<number>;
}

export interface ThreadRead {
  bumped_at: Timestamp | null;
  read_at: Generated<Timestamp>;
  thread_id: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface ThreadTag {
  actor_id: string;
  archived_at: Timestamp | null;
  id: Generated<Int8>;
  /**
   * Original occurrence date/datetime in text format. For dates: YYYY-MM-DD, for datetimes: YYYY-MM-DDTHH:MM
   */
  occurrence: string | null;
  sync_depth: number | null;
  tag_id: number;
  thread_id: string;
  updated_at: Generated<Timestamp>;
  updated_by: Generated<number>;
}

export interface ThreadTags {
  occurrence: string | null;
  tags: Json | null;
  thread_id: string | null;
  updated_at: Timestamp | null;
  updated_by: number | null;
}

export interface ThreadX {
  archived_at: Timestamp | null;
  created_at: Timestamp | null;
  created_by: string | null;
  draft: boolean | null;
  id: string | null;
  last_note_created_at: Timestamp | null;
  last_note_source_created_at: Timestamp | null;
  mentions: string[] | null;
  preview: string | null;
  priority_id: string | null;
  priority_path: string | null;
  private: boolean | null;
  sync_depth: number | null;
  title: string | null;
  updated_at: Timestamp | null;
  updated_by: number | null;
}

export interface Token {
  archived_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  last_used_at: Timestamp | null;
  name: string | null;
  publisher_id: Int8 | null;
  token: string;
  updated_at: Generated<Timestamp>;
  user_id: string | null;
}

export interface Twist {
  archived_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  description: string | null;
  environment: Generated<TwistEnvironment>;
  id: Generated<Int8>;
  is_source: Generated<boolean>;
  logo_url: string | null;
  logo_url_dark: string | null;
  name: string;
  options: Json | null;
  permissions: Json | null;
  twist_admin_id: Int8;
  updated_at: Generated<Timestamp>;
  version: string;
}

export interface TwistAdmin {
  auto_approve: Generated<boolean>;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  priority_id: string | null;
  publisher_id: Int8 | null;
  twist_package_id: Generated<string>;
  updated_at: Generated<Timestamp>;
  user_id: string | null;
}

export interface Usage {
  amount: number;
  cost_id: Int8;
  created_at: Generated<Timestamp>;
  hour: Timestamp;
  id: Generated<Int8>;
  priority_twist_id: string;
  updated_at: Generated<Timestamp>;
}

export interface User {
  avatar_url: string | null;
  clerk_id: string | null;
  created_at: Generated<Timestamp>;
  email: string;
  id: Generated<string>;
  name: string | null;
  updated_at: Generated<Timestamp>;
}

export interface UserActor {
  archived_at: Timestamp | null;
  avatar_url: string | null;
  created_at: Timestamp | null;
  email: string | null;
  id: string | null;
  name: string | null;
  self: boolean | null;
  type: string | null;
  updated_at: Timestamp | null;
  user_id: string | null;
}

export interface UserLink {
  actions: Json | null;
  assignee_id: string | null;
  author_id: string | null;
  created_at: Timestamp | null;
  created_by: string | null;
  id: string | null;
  logo: string | null;
  merged_from_thread_id: string | null;
  meta: Json | null;
  preview: string | null;
  priority_id: string | null;
  priority_path: string | null;
  source: string | null;
  source_created_at: Timestamp | null;
  source_url: string | null;
  status: string | null;
  sync_depth: number | null;
  thread_id: string | null;
  title: string | null;
  twist_id: Int8 | null;
  type: string | null;
  updated_at: Timestamp | null;
  updated_by: number | null;
  user_id: string | null;
}

export interface UserNote {
  actions: Json | null;
  archived_at: Timestamp | null;
  author_id: string | null;
  content: string | null;
  created_at: Timestamp | null;
  created_by: string | null;
  draft: boolean | null;
  id: string | null;
  mentions: string[] | null;
  merged_from_thread_id: string | null;
  private: boolean | null;
  re_note_id: string | null;
  source_created_at: Timestamp | null;
  thread_id: string | null;
  updated_at: Timestamp | null;
  updated_by: number | null;
  user_id: string | null;
}

export interface UserNoteTags {
  archived_at: Timestamp | null;
  id: string | null;
  priority_id: string | null;
  priority_path: string | null;
  tags: Json | null;
  updated_at: Timestamp | null;
  user_id: string | null;
}

export interface UserPriority {
  archived_at: Timestamp | null;
  color: number | null;
  created_at: Timestamp | null;
  created_by: string | null;
  global_path: string | null;
  id: string | null;
  key: string | null;
  order: number | null;
  organization_id: Int8 | null;
  path: string | null;
  personal: boolean | null;
  pomodoro: number | null;
  role: string | null;
  root: boolean | null;
  title: string | null;
  top_order: number | null;
  unread: boolean | null;
  updated_at: Timestamp | null;
  updated_by: number | null;
  user_id: string | null;
}

export interface UserPriorityActor {
  actor_id: string | null;
  archived_at: Timestamp | null;
  created_at: Timestamp | null;
  priority_path: string | null;
  updated_at: Timestamp | null;
  user_id: string | null;
}

export interface UserPriorityExpanded {
  archived_at: Timestamp | null;
  joined_at: Timestamp | null;
  path: string | null;
  priority_id: string | null;
  role: string | null;
  user_id: string | null;
}

export interface UserPriorityUnread {
  priority_id: string | null;
  unread: boolean | null;
  updated_at: Timestamp | null;
  user_id: string | null;
}

export interface UserSchedule {
  archived_at: Timestamp | null;
  at: string | null;
  contacts: Json | null;
  created_at: Timestamp | null;
  duration: Interval | null;
  id: string | null;
  link_id: string | null;
  occurrence: string | null;
  on: string | null;
  order: number | null;
  priority_path: string | null;
  range_at: string | null;
  range_on: string | null;
  recurrence_exdates: ArrayType<Timestamp> | null;
  recurrence_rule: string | null;
  schedule_user_id: string | null;
  thread_id: string | null;
  updated_at: Timestamp | null;
  user_id: string | null;
}

export interface UserSettings {
  ai_enabled: boolean | null;
  enter_behavior: EnterBehavior | null;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface UserSourceChannel {
  channel_id: string | null;
  create_threads: boolean | null;
  created_at: Timestamp | null;
  enabled: boolean | null;
  id: Int8 | null;
  priority_id: string | null;
  priority_twist_id: string | null;
  title: string | null;
  updated_at: Timestamp | null;
  user_id: string | null;
}

export interface UserSubscription {
  billing_cycle_end: Timestamp;
  billing_cycle_start: Timestamp;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  plan: Generated<SubscriptionPlan>;
  status: Generated<SubscriptionStatus>;
  stripe_customer_id: string | null;
  stripe_subscription_id: string | null;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface UserSync {
  entity: string;
  last_sync_at: Generated<Timestamp>;
  last_update_at: Timestamp;
  user_id: string;
}

export interface UserThread {
  activity_at: Timestamp | null;
  agenda_at: Timestamp | null;
  archived_at: Timestamp | null;
  bumped_at: Timestamp | null;
  created_at: Timestamp | null;
  draft: boolean | null;
  id: string | null;
  last_note_created_at: Timestamp | null;
  last_note_source_created_at: Timestamp | null;
  mentions: string[] | null;
  preview: string | null;
  priority_id: string | null;
  priority_path: string | null;
  private: boolean | null;
  title: string | null;
  unread: boolean | null;
  updated_at: Timestamp | null;
  updated_by: number | null;
  user_id: string | null;
}

export interface UserThreadTags {
  archived_at: Timestamp | null;
  id: string | null;
  occurrence: string | null;
  priority_id: string | null;
  priority_path: string | null;
  tags: Json | null;
  updated_at: Timestamp | null;
  user_id: string | null;
}

export interface UserTwist {
  archived_at: Timestamp | null;
  config: Json | null;
  created_at: Timestamp | null;
  default_mention_created: boolean | null;
  default_mention_mentioned: boolean | null;
  id: string | null;
  is_source: boolean | null;
  link_types: Json | null;
  logo_url: string | null;
  logo_url_dark: string | null;
  name: string | null;
  owner_id: string | null;
  priority_id: string | null;
  twist_environment: TwistEnvironment | null;
  twist_id: Int8 | null;
  updated_at: Timestamp | null;
  user_id: string | null;
}

export interface DB {
  actor: Actor;
  "atlas_schema_revisions.atlas_schema_revisions": AtlasSchemaRevisionsAtlasSchemaRevisions;
  contact: Contact;
  contact_external_account: ContactExternalAccount;
  contact_invitation: ContactInvitation;
  cost: Cost;
  device: Device;
  domain: Domain;
  "extensions.pg_all_foreign_keys": ExtensionsPgAllForeignKeys;
  "extensions.pg_stat_statements": ExtensionsPgStatStatements;
  "extensions.pg_stat_statements_info": ExtensionsPgStatStatementsInfo;
  "extensions.tap_funky": ExtensionsTapFunky;
  link: Link;
  link_x: LinkX;
  note: Note;
  note_tag: NoteTag;
  note_tags: NoteTags;
  organization: Organization;
  organization_invitation: OrganizationInvitation;
  organization_member: OrganizationMember;
  organization_subscription: OrganizationSubscription;
  priority: Priority;
  priority_child: PriorityChild;
  priority_child_twist: PriorityChildTwist;
  priority_contact: PriorityContact;
  priority_member: PriorityMember;
  priority_settings: PrioritySettings;
  priority_settings_inherited: PrioritySettingsInherited;
  priority_tags: PriorityTags;
  priority_twist: PriorityTwist;
  priority_twist_channel: PriorityTwistChannel;
  priority_twist_channel_link_create: PriorityTwistChannelLinkCreate;
  priority_twist_channel_link_update: PriorityTwistChannelLinkUpdate;
  priority_twist_channel_note_create: PriorityTwistChannelNoteCreate;
  priority_twist_child: PriorityTwistChild;
  priority_twist_link_update: PriorityTwistLinkUpdate;
  priority_twist_note_create: PriorityTwistNoteCreate;
  priority_twist_note_update: PriorityTwistNoteUpdate;
  priority_twist_schedule_contact: PriorityTwistScheduleContact;
  priority_twist_sync: PriorityTwistSync;
  priority_twist_thread_read: PriorityTwistThreadRead;
  priority_twist_thread_schedule: PriorityTwistThreadSchedule;
  priority_twist_thread_tag_change: PriorityTwistThreadTagChange;
  priority_twist_thread_update: PriorityTwistThreadUpdate;
  priority_user: PriorityUser;
  publisher: Publisher;
  schedule: Schedule;
  schedule_contact: ScheduleContact;
  series: Series;
  session: Session;
  source_channel: SourceChannel;
  thread: Thread;
  thread_read: ThreadRead;
  thread_tag: ThreadTag;
  thread_tags: ThreadTags;
  thread_x: ThreadX;
  token: Token;
  twist: Twist;
  twist_admin: TwistAdmin;
  usage: Usage;
  user: User;
  user_settings: UserSettings;
  user_subscription: UserSubscription;
  user_sync: UserSync;
  "user.actor": UserActor;
  "user.link": UserLink;
  "user.note": UserNote;
  "user.note_tags": UserNoteTags;
  "user.priority": UserPriority;
  "user.priority_actor": UserPriorityActor;
  "user.priority_expanded": UserPriorityExpanded;
  "user.priority_unread": UserPriorityUnread;
  "user.schedule": UserSchedule;
  "user.source_channel": UserSourceChannel;
  "user.thread": UserThread;
  "user.thread_tags": UserThreadTags;
  "user.twist": UserTwist;
}
