export { default, OutlookMail } from "./outlook-mail";
export { getOutlookMailChannels, OUTLOOK_MAIL_SCOPES, OUTLOOK_MAIL_LINK_TYPES } from "./channels";
// Sync/send/subscription/self-heal logic, extracted as host-pattern functions
// so a future combined Outlook connector can reuse them (mirrors
// @plotday/connector-gmail).
export {
  type OutlookMailSyncHost,
  type SubscriptionState,
  type IncrementalState,
  type InitialSyncState,
  type DeltaState,
  type PendingMessage,
  type InitialSyncBatchResult,
  type OutlookMailWebhookResult,
  SELF_HEAL_INTERVAL_MS,
  SUB_PREEMPTIVE_RENEW_MS,
  RENEWAL_LEAD_MS,
  SUBSCRIPTION_DURATION_DAYS,
  MAX_MESSAGE_FETCH_ATTEMPTS,
  MAX_DELTA_PAGES_PER_HEAL,
  MAX_INCREMENTAL_MESSAGES_PER_BATCH,
  INCREMENTAL_SYNC_COALESCE_MS,
  INCREMENTAL_SYNC_TASK_KEY,
  PENDING_MSG_PREFIX,
  queueIncrementalSyncFn,
  drainNotifiedMessagesFn,
  migrateLegacyPendingMessagesFn,
  COMPOSE_DEDUP_WINDOW_MS,
  DIRECT_ATTACH_MAX_BYTES,
  fnv1aHex,
  pickChannelForConversation,
  mergePendingMessages,
  getApiFn,
  getApiAnyFn,
  getEnabledChannelsFn,
  addEnabledChannelFn,
  removeEnabledChannelFn,
  isChannelEnabledFn,
  ensureUserEmailFn,
  getWellKnownFn,
  requeueInitialSyncFn,
  recoverMailboxDeliveryFn,
  upgradeFn,
  ensureMailboxSubscriptionFn,
  setupMailboxSubscriptionFn,
  teardownMailboxSubscriptionFn,
  getMailboxRenewalSchedule,
  renewMailboxSubscriptionFn,
  selfHealCheckFn,
  folderDeltaCatchUpFn,
  initialSyncBatchFn,
  fetchConversationsFn,
  onOutlookMailWebhookFn,
  incrementalSyncBatchFn,
  processConversationsFn,
  onThreadReadFn,
  onThreadToDoFn,
  onNoteCreatedFn,
  onCreateLinkFn,
  downloadAttachmentFn,
} from "./sync";
