name = "agent-events"
main = "src/index.ts"
compatibility_date = "2025-07-05"
compatibility_flags = ["nodejs_compat"]
upload_source_maps = true

[env.development]
[env.development.define]
  ENV = '"development"'
  RELEASE = '"dev"'
  PACKAGE = '"agent-events"'

[env.production]
[env.production.define]
  ENV = '"production"'
  RELEASE = '"prod"'
  PACKAGE = '"agent-events"'

[observability.logs]
  enabled = true