name = "dev"
main = "src/index.ts"
compatibility_date = "2024-11-18"
compatibility_flags = ["nodejs_compat"]

[define]
  ENV = '"development"'
  RELEASE = '"dev"'
  PACKAGE = '"dev"'

[[queues.producers]]
  queue = "sync"
  binding = "SYNC_QUEUE"

[[queues.producers]]
  queue = "contact-sync"
  binding = "CONTACT_SYNC_QUEUE"

[[queues.producers]]
  queue = "event-sync"
  binding = "EVENT_QUEUE"

[[queues.consumers]]
  queue = "sync"
  max_batch_size = 1
  max_retries = 0

[[queues.consumers]]
  queue = "contact-sync"
  max_batch_size = 1
  max_retries = 0

[[queues.consumers]]
  queue = "event-sync"
  max_batch_size = 10
  max_batch_timeout = 3
  max_retries = 0

[ai]
  binding = "AI"


[dev]
  port = 8780
