name = "dev"
main = "src/index.ts"
compatibility_date = "2024-11-18"
compatibility_flags = ["nodejs_compat"]

[[queues.producers]]
  queue = "sync-dev"
  binding = "SYNC_QUEUE"

[[queues.producers]]
  queue = "contact-sync-dev"
  binding = "CONTACT_SYNC_QUEUE"

[[queues.producers]]
  queue = "event-sync-dev"
  binding = "EVENT_QUEUE"

[[queues.consumers]]
  queue = "sync-dev"
  max_batch_size = 1
  max_retries = 0

[[queues.consumers]]
  queue = "contact-sync-dev"
  max_batch_size = 1
  max_retries = 0

[[queues.consumers]]
  queue = "event-sync-dev"
  max_batch_size = 10
  max_batch_timeout = 3
  max_retries = 0

[dev]
  port = 8780
