import { z } from "zod";
import type { Automation, Format, Reach } from "@plotday/twister/facets";

// Single source of truth for the LLM derivation prompt. Mirrors the SDK facet
// vocabulary; the gate enforces the same values.
export const FACET_REGISTRY = {
  format: {
    description: "The kind of content.",
    values: {
      chat: "A short, conversational message (e.g. a quick chat).",
      message: "Substantive personal or business correspondence.",
      reading: "Long-form content meant to be read: newsletters, articles, digests.",
      notification: "A transactional or system notification (app alerts, 'X commented').",
      receipt: "A purchase, order, or payment confirmation.",
      invoice: "A bill, payment request, or statement.",
      promotion: "A marketing or promotional blast (sales, offers, deals).",
      otp: "A one-time password or verification code.",
      confirm: "An email verification or account-confirmation message.",
    } satisfies Record<Format, string>,
  },
  automation: {
    description: "Whether a person or a system produced the message.",
    values: {
      human: "Composed by a person.",
      automated: "Generated by a system, bot, or no-reply sender.",
    } satisfies Record<Automation, string>,
  },
  reach: {
    description: "How the user was addressed.",
    values: {
      direct: "Sent specifically to the user (and maybe a few others).",
      list: "A broadcast / mailing-list / bulk message.",
    } satisfies Record<Reach, string>,
  },
} as const;

const FORMAT_VALUES = Object.keys(FACET_REGISTRY.format.values) as [Format, ...Format[]];
const AUTOMATION_VALUES = Object.keys(FACET_REGISTRY.automation.values) as [Automation, ...Automation[]];
const REACH_VALUES = Object.keys(FACET_REGISTRY.reach.values) as [Reach, ...Reach[]];

function dimFilter<T extends string>(values: [T, ...T[]]) {
  return z
    .object({
      include: z.array(z.enum(values)).optional(),
      exclude: z.array(z.enum(values)).optional(),
    })
    .optional();
}

// The stored shape of priority.facet_filters and the LLM output contract.
export const FacetFiltersSchema = z.object({
  format: dimFilter(FORMAT_VALUES),
  automation: dimFilter(AUTOMATION_VALUES),
  reach: dimFilter(REACH_VALUES),
  trustedSendersOnly: z.boolean().optional(),
});

export type FacetFilters = z.infer<typeof FacetFiltersSchema>;

// Human-readable description of every dimension/value for the LLM prompt.
export function registryPromptBlock(): string {
  const lines: string[] = [];
  for (const dim of ["format", "automation", "reach"] as const) {
    lines.push(`${dim} — ${FACET_REGISTRY[dim].description}`);
    for (const [value, desc] of Object.entries(FACET_REGISTRY[dim].values)) {
      lines.push(`  - ${value}: ${desc}`);
    }
  }
  lines.push(
    "trustedSendersOnly — when true, only admit messages from senders the user already engages with (people they've messaged or whose threads they've filed here) or colleagues in their own email domain."
  );
  return lines.join("\n");
}
