import { type SupabaseClient } from "@plotday/db";
import { type ActivityLink, ActivityLinkType } from "@plotday/twister/plot";
import {
  type Callback,
  type NoFunctions,
} from "@plotday/twister/tools/callbacks";
import {
  type AuthLevel,
  type AuthProvider,
  type AuthToken,
  type Authorization,
  type Integrations as IAuth,
} from "@plotday/twister/tools/integrations";
import type { Store as IStore } from "@plotday/twister/tools/store";

import { type Bindings, type TwistEnvironment } from "../../env";
import {
  PROVIDER_CONFIGS,
  type ProviderData,
  type StoredTokenData,
} from "../../provider";
import { CallbacksState } from "../../state/callbacks";
import superjson from "superjson";

import type { Storage } from "../../state/storage";
import { createLogger } from "../../utils/logger";
import { getRpcFunctionName } from "../../utils/rpc";
import { Tool } from "./tool";

type AuthState = {
  provider: AuthProvider;
  level: AuthLevel;
  scopes: string[];
  codeVerifier?: string; // Optional for Google Sign-In flows
  timestamp?: number; // Optional for Google Sign-In flows
  callback?: Callback;
};

export class Integrations extends Tool implements IAuth {
  private store: IStore;
  private env: Bindings;
  private supabase: SupabaseClient;
  private priorityTwistId: string;
  // These are callbacks we create and call
  private callbacks: DurableObjectStub<CallbacksState>;
  private twistId: string;
  private environment: TwistEnvironment;
  private path: string[];

  private static GetStub(
    callbacks: DurableObjectNamespace<CallbacksState>,
    priorityTwistId: string
  ) {
    const callbacksId = callbacks.idFromName(priorityTwistId);
    return callbacks.get(callbacksId);
  }

  constructor(options: {
    store: IStore;
    env: Bindings;
    supabase: SupabaseClient;
    priorityTwistId: string;
    twistId: string;
    environment: TwistEnvironment;
    path: string[];
  }) {
    super();
    this.store = options.store;
    this.env = options.env;
    this.supabase = options.supabase;
    this.priorityTwistId = options.priorityTwistId;
    this.twistId = options.twistId;
    this.environment = options.environment;
    this.callbacks = Integrations.GetStub(
      options.env.CALLBACKS,
      options.priorityTwistId
    );
    this.path = options.path;
  }

  async request<TCallback extends (auth: Authorization, ...args: any[]) => any>(
    {
      provider,
      level,
      scopes,
    }: {
      provider: AuthProvider;
      level: AuthLevel;
      scopes: string[];
    },
    callback: TCallback,
    ...extraArgs: TCallback extends (auth: any, ...rest: infer R) => any
      ? NoFunctions<R>
      : []
  ): Promise<ActivityLink> {
    if (!(provider in PROVIDER_CONFIGS)) {
      throw new Error(`Provider ${provider} not supported`);
    }

    // Create callback token from the provided function
    // The callback is to a function on the parent, so use parent path
    // Use helper to access name property from RPC stub
    const callbackFunctionName = await getRpcFunctionName(callback);
    if (!callbackFunctionName) {
      throw new Error(
        "Cannot create callback: function has no name. Use named functions or methods."
      );
    }
    const callbackToken = await this.callbacks.create({
      priorityTwistId: this.priorityTwistId,
      path: this.path.slice(0, -1), // Remove this tool from path to target parent
      functionName: callbackFunctionName,
      extraArgs,
    });

    // Create wrapped callback to onAuth
    const onAuthCallback = await this.callbacks.create({
      priorityTwistId: this.priorityTwistId,
      path: this.path,
      functionName: "onAuth",
      extraArgs: [callbackToken],
    });

    // Create and return auth link with auth config - URLs will be generated by API calls
    const authLink: ActivityLink = {
      title: `Continue with ${PROVIDER_CONFIGS[provider].name}`,
      type: ActivityLinkType.auth,
      provider,
      level,
      scopes,
      callback: onAuthCallback,
    };

    return authLink;
  }

  async onAuth(
    tokenInfo: {
      access_token: string;
      refresh_token?: string;
      expires_in?: number;
      provider: AuthProvider;
      level: AuthLevel;
      scopes: string[];
      client_id: string;
      // Raw provider response data (will be parsed)
      [key: string]: any;
    },
    callbackToken: Callback
  ): Promise<void> {
    // Generate unique ID for this authorization
    const authorizationId = crypto.randomUUID();

    const config = PROVIDER_CONFIGS[tokenInfo.provider];

    // Parse provider-specific data if handler exists (may be async)
    const providerData =
      (await config?.parseTokenResponse?.(tokenInfo)) ?? null;

    const tokenKey = `auth_token:${authorizationId}`;
    const token: StoredTokenData = {
      client_id: tokenInfo.client_id,
      access_token: tokenInfo.access_token,
      refresh_token: tokenInfo.refresh_token ?? null,
      scopes: tokenInfo.scopes,
      expires_at: tokenInfo.expires_in
        ? Date.now() + tokenInfo.expires_in * 1000
        : null,
      providerData,
    };
    await this.store.set(tokenKey, token);

    // Extract email from providerData and link to contact
    const email = this.extractEmail(providerData);
    if (email) {
      await this.linkContactByEmail(email);
    }

    // Create Authorization object to pass to callback
    const authorization: Authorization = {
      id: authorizationId,
      provider: tokenInfo.provider,
      scopes: tokenInfo.scopes,
    };

    // Call original user callback with Authorization
    try {
      await this.callbacks.callCallback(callbackToken, authorization);
    } catch (error) {
      const logger = createLogger({ priority_twist_id: this.priorityTwistId });
      logger.error("Error executing original auth callback", error as Error, {
        authorization_id: authorizationId,
        provider: tokenInfo.provider,
      });
    }
  }

  private extractEmail(providerData: ProviderData | null): string | null {
    if (!providerData) {
      return null;
    }

    // Check for email field in provider data
    if ("email" in providerData && typeof providerData.email === "string") {
      return providerData.email.toLowerCase();
    }

    return null;
  }

  private async linkContactByEmail(email: string): Promise<void> {
    try {
      // Get the user_id from the priority_twist owner
      const { data: priorityTwist, error: ptError } = await this.supabase
        .from("priority_twist")
        .select("owner_id")
        .eq("id", this.priorityTwistId)
        .single();

      if (ptError || !priorityTwist?.owner_id) {
        const logger = createLogger({ priority_twist_id: this.priorityTwistId });
        logger.warn("Cannot link contact: priority_twist has no owner", {
          email,
          error: ptError?.message,
        });
        return;
      }

      const userId = priorityTwist.owner_id;

      // Check if contact exists with this email
      const { data: existingContact } = await this.supabase
        .from("contact")
        .select("id, user_id")
        .eq("email", email)
        .single();

      if (!existingContact) {
        // Create new contact linked to current user
        await this.supabase
          .from("contact")
          .insert({
            email,
            user_id: userId,
            name: null,
            avatar_url: null,
          });

        const logger = createLogger({ priority_twist_id: this.priorityTwistId });
        logger.info("Created new contact from OAuth", { email, user_id: userId });
      } else if (existingContact.user_id === null) {
        // Unclaimed contact - link to current user
        await this.supabase
          .from("contact")
          .update({ user_id: userId })
          .eq("id", existingContact.id);

        const logger = createLogger({ priority_twist_id: this.priorityTwistId });
        logger.info("Linked existing contact from OAuth", {
          email,
          user_id: userId,
        });
      } else if (existingContact.user_id !== userId) {
        // Contact belongs to another user - skip silently
        // We can't easily check if the other user is still active via Supabase client
        // and this is a non-critical feature, so we just leave it as-is
        const logger = createLogger({
          priority_twist_id: this.priorityTwistId,
        });
        logger.debug("Contact email already claimed by another user", {
          email,
          current_user_id: userId,
          contact_user_id: existingContact.user_id,
        });
      }
      // else: Contact already linked to current user, nothing to do
    } catch (error) {
      const logger = createLogger({ priority_twist_id: this.priorityTwistId });
      logger.error("Error linking contact by email", error as Error, { email });
      // Don't throw - we don't want to fail the OAuth flow if contact linking fails
    }
  }

  async get(authorization: Authorization): Promise<AuthToken | null> {
    // Get stored token from the store using authorization ID
    const tokenKey = `auth_token:${authorization.id}`;
    const tokenData = await this.store.get<StoredTokenData>(tokenKey);

    if (!tokenData) {
      return null;
    }

    const config = PROVIDER_CONFIGS[authorization.provider];

    // Check if token is expired
    if (tokenData.expires_at && Date.now() > tokenData.expires_at) {
      // Token is expired, try to refresh if we have a refresh token
      if (tokenData.refresh_token && tokenData.client_id) {
        try {
          const refreshedToken = await this.refreshToken({
            clientId: tokenData.client_id,
            refreshToken: tokenData.refresh_token,
            provider: authorization.provider,
          });

          // Update stored token - preserve providerData automatically
          const updatedToken: StoredTokenData = {
            client_id: tokenData.client_id,
            access_token: refreshedToken.access_token,
            refresh_token:
              refreshedToken.refresh_token || tokenData.refresh_token || null,
            scopes: tokenData.scopes,
            expires_at: refreshedToken.expires_in
              ? Date.now() + refreshedToken.expires_in * 1000
              : null,
            providerData: tokenData.providerData, // Preserved automatically
          };
          await this.store.set(tokenKey, updatedToken);

          return {
            token: refreshedToken.access_token,
            scopes: tokenData.scopes,
            provider: tokenData.providerData
              ? config?.extractMetadata?.(tokenData.providerData)
              : undefined,
          };
        } catch (error) {
          const logger = createLogger({ priority_twist_id: this.priorityTwistId });
          logger.error("Failed to refresh token", error as Error, {
            authorization_id: authorization.id,
            provider: authorization.provider,
          });
          // Clear expired token
          await this.store.clear(tokenKey);
          return null;
        }
      }

      // No refresh token or refresh failed, clear expired token
      await this.store.clear(tokenKey);
      return null;
    }

    return {
      token: tokenData.access_token,
      scopes: tokenData.scopes,
      provider: tokenData.providerData
        ? config?.extractMetadata?.(tokenData.providerData)
        : undefined,
    };
  }

  static async HandleOauthCallback(
    storage: DurableObjectNamespace<Storage>,
    callbacks: DurableObjectNamespace<CallbacksState>,
    params: Record<string, string>,
    env: Bindings
  ): Promise<Response> {
    try {
      const { state, error, provider, level, scopes, callback } = params;

      if (error) {
        const logger = createLogger();
        logger.error("OAuth error", new Error(error));
        return new Response(
          JSON.stringify({ error: `OAuth error: ${error}` }),
          {
            status: 400,
            headers: { "Content-Type": "application/json" },
          }
        );
      }

      let authState: AuthState;

      // Check if this is a Google Sign-In flow (no state) or standard OAuth (with state)
      if (!state && provider) {
        // Google Sign-In flow: validate direct parameters
        if (!provider) throw new Error("Missing provider parameter");
        if (!level) throw new Error("Missing level parameter");

        const scopeArray = scopes ? scopes.split(",").map((s) => s.trim()) : [];

        authState = {
          provider: provider as AuthProvider,
          level: level as AuthLevel,
          scopes: scopeArray,
          callback: callback as Callback | undefined,
          // No codeVerifier or timestamp for Google Sign-In
        };
      } else if (state) {
        // Standard OAuth flow: retrieve state from global storage
        const storageStub = storage.idFromName("auth");
        const storageObj = storage.get(storageStub);
        const rawAuthState = await storageObj.get(state);
        let retrievedAuthState: AuthState | null = null;
        if (rawAuthState) {
          try {
            retrievedAuthState = superjson.parse<AuthState>(rawAuthState);
          } catch {
            // Fallback to JSON.parse for backward compatibility
            retrievedAuthState = JSON.parse(rawAuthState) as AuthState;
          }
        }

        if (!retrievedAuthState) {
          return new Response(
            JSON.stringify({ error: "Invalid or expired state" }),
            {
              status: 400,
              headers: { "Content-Type": "application/json" },
            }
          );
        }

        authState = retrievedAuthState;

        // Check state timestamp (expire after 1 hour) - only for standard OAuth
        if (authState.timestamp && Date.now() - authState.timestamp > 3600000) {
          await storageObj.clear(state);
          const logger = createLogger();
          logger.error("State expired", {
            timestamp: authState.timestamp,
            age_ms: Date.now() - authState.timestamp,
          });
          return new Response(JSON.stringify({ error: "State expired" }), {
            status: 400,
            headers: { "Content-Type": "application/json" },
          });
        }

        // Cleanup state after successful validation
        await storageObj.clear(state);
      } else {
        // Neither state nor provider provided
        const logger = createLogger();
        logger.error("Missing both state and provider parameters");
        return new Response(
          JSON.stringify({
            error: "Missing required authentication parameters",
          }),
          {
            status: 400,
            headers: { "Content-Type": "application/json" },
          }
        );
      }

      const { code, clientId, redirectUri } = params;
      if (!code) throw new Error("Missing code parameter");
      if (!clientId) throw new Error("Missing clientId parameter");
      if (!redirectUri) throw new Error("Missing redirectUri parameter");

      // Exchange code for tokens using static helper
      // Always include code_verifier if it exists in auth state (PKCE flow)
      const tokenResponse = await Integrations.exchangeCodeForTokens({
        clientId,
        code,
        codeVerifier: authState.codeVerifier,
        provider: authState.provider,
        redirectUri,
        env,
      });

      // Call the wrapped callback (onAuth) with token info
      if (authState.callback) {
        try {
          await CallbacksState.CallCallback(callbacks, authState.callback, {
            // Spread all token response fields (provider-specific fields included)
            ...tokenResponse,
            // Add our metadata
            provider: authState.provider,
            level: authState.level,
            scopes: authState.scopes,
            client_id: clientId,
          });
        } catch (error) {
          const logger = createLogger();
          logger.error("Error executing auth callback", error as Error, {
            provider: authState.provider,
            level: authState.level,
          });
          // Don't fail the auth flow even if callback fails
        }
      }

      return new Response(
        JSON.stringify({
          message: "Authentication successful! You can close this window.",
        }),
        {
          status: 200,
          headers: { "Content-Type": "application/json" },
        }
      );
    } catch (error) {
      const logger = createLogger();
      logger.error("Error handling OAuth callback", error as Error);
      const errorMessage =
        error instanceof Error ? error.message : "Unknown error";
      return new Response(
        JSON.stringify({ error: `Authentication failed: ${errorMessage}` }),
        {
          status: 500,
          headers: { "Content-Type": "application/json" },
        }
      );
    }
  }

  private static GenerateRandomString(length: number): string {
    const charset =
      "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_~";
    const values = crypto.getRandomValues(new Uint8Array(length));
    return Array.from(values)
      .map((x) => charset[x % charset.length])
      .join("");
  }

  private static GenerateCodeVerifier(): string {
    return Integrations.GenerateRandomString(128);
  }

  private static async GenerateCodeChallenge(
    codeVerifier: string
  ): Promise<string> {
    const encoder = new TextEncoder();
    const data = encoder.encode(codeVerifier);
    const digest = await crypto.subtle.digest("SHA-256", data);

    // Convert to base64url
    return btoa(String.fromCharCode(...new Uint8Array(digest)))
      .replace(/\+/g, "-")
      .replace(/\//g, "_")
      .replace(/=/g, "");
  }

  private static async exchangeCodeForTokens({
    code,
    codeVerifier,
    provider,
    redirectUri,
    clientId,
    env,
  }: {
    code: string;
    codeVerifier?: string;
    provider: AuthProvider;
    redirectUri: string;
    clientId: string;
    env: Bindings;
  }): Promise<{
    access_token: string;
    refresh_token?: string;
    expires_in?: number;
    [key: string]: any; // Allow any provider-specific fields
  }> {
    const config = PROVIDER_CONFIGS[provider];
    if (!config) {
      throw new Error(`Token exchange not implemented for ${provider}`);
    }

    const clientSecret = Integrations.SecretFromId(env, provider, clientId);

    const params = new URLSearchParams({
      client_id: clientId,
      ...(clientSecret ? { client_secret: clientSecret } : null),
      code,
      grant_type: "authorization_code",
      redirect_uri: redirectUri,
      ...(codeVerifier ? { code_verifier: codeVerifier } : {}),
    });

    const response = await fetch(config.tokenUrl, {
      method: "POST",
      headers: {
        "Content-Type": "application/x-www-form-urlencoded",
      },
      body: params.toString(),
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`Token exchange failed: ${response.status} ${errorText}`);
    }

    const tokenData = (await response.json()) as any;

    // Return the raw token data - parsing will happen in onAuth via config.parseTokenResponse
    return tokenData;
  }

  private async refreshToken({
    clientId,
    refreshToken,
    provider,
  }: {
    clientId: string;
    refreshToken: string;
    provider: AuthProvider;
  }): Promise<{
    access_token: string;
    refresh_token?: string;
    expires_in?: number;
  }> {
    const config = PROVIDER_CONFIGS[provider];
    if (!config) {
      throw new Error(`Token refresh not implemented for ${provider}`);
    }

    const clientSecret = Integrations.SecretFromId(
      this.env,
      provider,
      clientId
    );

    const params = new URLSearchParams({
      client_id: clientId,
      ...(clientSecret ? { client_secret: clientSecret } : null),
      refresh_token: refreshToken,
      grant_type: "refresh_token",
    });

    const response = await fetch(config.tokenUrl, {
      method: "POST",
      headers: {
        "Content-Type": "application/x-www-form-urlencoded",
      },
      body: params.toString(),
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`Token refresh failed: ${response.status} ${errorText}`);
    }

    const tokenData = (await response.json()) as {
      access_token: string;
      refresh_token?: string;
      expires_in?: number;
    };
    return {
      access_token: tokenData.access_token,
      refresh_token: tokenData.refresh_token,
      expires_in: tokenData.expires_in,
    };
  }

  static async GenerateAuthUrl({
    provider,
    level,
    scopes,
    callback,
    redirectUri,
    platform,
    env,
    storage,
  }: {
    provider: AuthProvider;
    level: AuthLevel;
    scopes: string[];
    callback?: Callback;
    redirectUri: string;
    platform?: "ios" | "android" | "desktop";
    env: Bindings;
    storage: DurableObjectNamespace<Storage>;
  }): Promise<{ url: string; clientId: string; state: string } | null> {
    const config = PROVIDER_CONFIGS[provider];
    if (!config) {
      const logger = createLogger();
      logger.error("Provider not supported", { provider });
      throw new Error(`Provider ${provider} not supported`);
    }

    // Merge email scopes with requested scopes
    const emailScopes = config.emailScopes ?? [];
    const allScopes = Array.from(new Set([...scopes, ...emailScopes]));

    // Generate fresh PKCE parameters for this specific OAuth flow
    const codeVerifier = Integrations.GenerateCodeVerifier();
    const codeChallenge = await Integrations.GenerateCodeChallenge(
      codeVerifier
    );

    // Use global auth storage
    const storageStub = storage.idFromName("auth");
    const storageObj = storage.get(storageStub);

    // Generate unique state and store globally
    const state = crypto.randomUUID();
    const authState: AuthState = {
      provider,
      level,
      scopes: allScopes,
      codeVerifier,
      timestamp: Date.now(),
      callback,
    };
    await storageObj.set(
      state,
      superjson.stringify(authState)
    );

    const platformEnvKey = `${Integrations.EnvPrefix(
      provider,
      platform
    )}_ID` as keyof Bindings;
    const baseEnvKey = `${Integrations.EnvPrefix(
      provider
    )}_ID` as keyof Bindings;

    const clientId = (env[platformEnvKey] ?? env[baseEnvKey]) as string;

    if (!clientId) {
      const logger = createLogger();
      logger.error("No client ID found for provider", {
        provider,
        platform,
        platform_env_key: platformEnvKey,
        base_env_key: baseEnvKey,
        available_auth_keys: Object.keys(env).filter((k) =>
          k.startsWith("AUTH_")
        ),
      });
      return null;
    }

    const params = new URLSearchParams({
      response_type: "code",
      client_id: clientId,
      redirect_uri: redirectUri,
      scope: allScopes.join(" "),
      state,
      code_challenge: codeChallenge,
      code_challenge_method: "S256",
      ...config.additionalParams,
      // Override prompt for twist auth to always show consent
      prompt: "select_account consent",
    });

    const url = `${config.authUrl}?${params.toString()}`;

    return { url, clientId, state };
  }

  private static ALL_PLATFORMS: (undefined | "ios" | "android" | "desktop")[] =
    [undefined, "desktop", "ios", "android"];
  private static EnvPrefix(
    provider: AuthProvider,
    platform?: "ios" | "android" | "desktop"
  ) {
    return `AUTH_${provider.toUpperCase()}${
      platform ? `_${platform.toUpperCase()}` : ""
    }`;
  }

  private static SecretFromId(
    env: Bindings,
    provider: AuthProvider,
    id: string
  ) {
    const prefix = Integrations.ALL_PLATFORMS.map((platform) =>
      Integrations.EnvPrefix(provider, platform)
    ).find((p) => env[`${p}_ID` as keyof Bindings] === id);
    return prefix
      ? (env[`${prefix}_SECRET` as keyof Bindings] as string | undefined)
      : undefined;
  }
}
