name: Deploy App (Web)
on:
  push:
    branches:
      - main
    paths:
      - "apps/plot/**"
      - ".env"
      - ".env.production"
      - ".github/workflows/deploy-app.yml"

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Load secrets and create .env file
        uses: 1password/load-secrets-action@v2
        id: secrets
        with:
          export-env: true
        env:
          CLOUDFLARE_ACCOUNT_ID: op://Production/Cloudflare/username
          CLOUDFLARE_API_TOKEN: op://Production/Cloudflare/credential
          SUPABASE_URL: op://Production/Supabase/API/url
          SUPABASE_ANON_KEY: op://Production/Supabase/API/public key
          SENTRY_AUTH_TOKEN: op://Development/Sentry/credential
          SENTRY_ORG: op://Development/Sentry/org
          SENTRY_DSN: op://Development/Sentry/app/dsn
          GOOGLE_CLIENT_ID: op://Production/Google OAuth/username
          GOOGLE_IOS_CLIENT_ID: op://Production/Google OAuth/iOS/client ID
          GOOGLE_ANDROID_CLIENT_ID: op://Production/Google OAuth/Android/client ID
          MICROSOFT_CLIENT_ID: op://Production/Microsoft OAuth/username

      - name: Write .env file
        run: |
          cat > apps/plot/.env << EOF
          SUPABASE_URL=${{ env.SUPABASE_URL }}
          SUPABASE_ANON_KEY=${{ env.SUPABASE_ANON_KEY }}
          API_ROOT=https://sync-api.plot.day
          SENTRY_PROJECT=app
          SENTRY_AUTH_TOKEN=${{ env.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG=${{ env.SENTRY_ORG }}
          SENTRY_DSN=${{ env.SENTRY_DSN }}
          GOOGLE_CLIENT_ID=${{ env.GOOGLE_CLIENT_ID }}
          GOOGLE_IOS_CLIENT_ID=${{ env.GOOGLE_IOS_CLIENT_ID }}
          GOOGLE_ANDROID_CLIENT_ID=${{ env.GOOGLE_ANDROID_CLIENT_ID }}
          MICROSOFT_CLIENT_ID=${{ env.MICROSOFT_CLIENT_ID }}
          AUTH_CALLBACK_URL=https://app.plot.day/auth.html
          EOF

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version-file: apps/plot/pubspec.yaml
          cache: true

      - name: Install derry
        run: dart pub global activate derry

      - name: Get dependencies
        run: cd apps/plot && flutter pub get

      - name: Build
        run: cd apps/plot && derry build web

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install wrangler
        run: pnpm install -w wrangler

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ env.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ env.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy apps/plot/build/web --project-name=app --commit-hash ${{ env.GITHUB_SHA }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
