name: Deploy App (Web)
on:
  push:
    branches:
      - main
    paths:
      - 'apps/plot/**'
permissions:
  contents: read
  deployments: write
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Load secrets
        uses: 1password/load-secrets-action@v2
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: op://Production/Cloudflare/username
          CLOUDFLARE_API_TOKEN: op://Production/Cloudflare/credential

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version-file: apps/plot/pubspec.yaml
          cache: true

      - name: Install derry
        run: dart pub global activate derry

      - name: Get dependencies
        run: cd apps/plot && flutter pub get

      - name: Build
        run: cd apps/plot && derry build web

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ env.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ env.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy apps/plot/build/web --project-name=app --commit-hash $GITHUB_SHA
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
