name: Deploy App (Web)
on:
  push:
    branches:
      - main
permissions:
  contents: read
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Load secrets
        uses: 1password/load-secrets-action@v2
        with:
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: op://app-cicd/hello-world/secret
          CLOUDFLARE_API_TOKEN: op://app-cicd/hello-world/secret

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version-file: pubspec.yaml
          cache: true

      - name: Install derry
        run: dart pub global activate derry

      - name: Get dependencies
        run: cd apps/plot && flutter pub get

      - name: Build
        run: cd apps/plot && derry build web

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ env.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ env.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy apps/plot/build/web --project-name=app --commit-hash $GITHUB_SHA
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
