name: Lint

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

    steps:
      - name: Generate GitHub App Token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: |
            ${{ github.event.repository.name }}
            font_awesome_flutter

      - name: Configure git for private dependencies
        run: |
          git config --global url."https://x-access-token:${{ steps.app-token.outputs.token }}@github.com/".insteadOf "git@github.com:"

      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: true

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: "pnpm"

      - name: Build Twister and tools
        run: |
          cd public
          pnpm install --frozen-lockfile
          pnpm build

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Perl
        uses: shogo82148/actions-setup-perl@v1

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version-file: .flutter-version
          channel: "stable"
          cache: true

      - name: Fake Flutter .env
        run: echo "FOO=bar" >> apps/plot/.env

      - name: Generate Flutter code
        run: cd apps/plot && flutter pub run build_runner build

      - name: Install pg_format
        run: |
          curl -L -o pg_format.zip https://github.com/darold/pgFormatter/archive/refs/tags/v5.5.zip
          unzip pg_format.zip -d $HOME/pg_format
          mv $HOME/pg_format/pgFormatter*/* $HOME/pg_format/
          chmod +x $HOME/pg_format/pg_format
          echo "$HOME/pg_format" >> "$GITHUB_PATH"

      - name: Start Supabase
        run: cd libs/db && pnpm run start:db

      - name: Lint
        run: pnpm run lint
