name: Tests
on:
  push:
    branches:
      - "*/**"
permissions:
  contents: read
jobs:
  run-linters:
    name: Run tests
    runs-on: ubuntu-latest

    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}

    env:
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_OAUTH_SECRET: ${{ secrets.GOOGLE_OAUTH_SECRET }}
      MICROSOFT_CLIENT_ID: ${{ secrets.MICROSOFT_CLIENT_ID }}
      MICROSOFT_OAUTH_SECRET: ${{ secrets.MICROSOFT_OAUTH_SECRET }}
      TEST_GOOGLE_ACCOUNT_ACCESS_TOKEN: ${{ secrets.TEST_GOOGLE_ACCOUNT_ACCESS_TOKEN }}
      TEST_GOOGLE_ACCOUNT_REFRESH_TOKEN: ${{ secrets.TEST_GOOGLE_ACCOUNT_REFRESH_TOKEN }}
      TEST_OUTLOOK_ACCOUNT_ACCESS_TOKEN: ${{ secrets.TEST_OUTLOOK_ACCOUNT_ACCESS_TOKEN }}
      TEST_OUTLOOK_ACCOUNT_REFRESH_TOKEN: ${{ secrets.TEST_OUTLOOK_ACCOUNT_REFRESH_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test
